[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=1fb76bb0-eb23-4bdd-bcb3-df8d3c717b45
Description=丛林放置猎物 N6 东方
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 720, 609
Delay 1592
LeftClick 1
Delay 644
KeyDown "`", 1
Delay 546
KeyUp "`", 1
Delay 1541
KeyDown "M", 1
Delay 167
KeyUp "M", 1
Delay 33
KeyDown "A", 1
Delay 167
KeyUp "A", 1
Delay 2
KeyDown "K", 1
Delay 98
KeyUp "K", 1
Delay 99
KeyDown "E", 1
Delay 134
KeyUp "E", 1
Delay 201
KeyDown "Tab", 1
Delay 200
KeyUp "Tab", 1
Delay 32
KeyDown "Space", 1
Delay 167
KeyUp "Space", 1
Delay 267
KeyDown "Shift", 1
Delay 200
KeyDown "H", 1
Delay 104
KeyUp "Shift", 1
Delay 62
KeyUp "H", 1
Delay 67
KeyDown "A", 1
Delay 135
KeyDown "Y", 1
Delay 67
KeyUp "A", 1
Delay 67
KeyUp "Y", 1
Delay 166
KeyDown "O", 1
Delay 133
KeyUp "O", 1
Delay 67
KeyDown "O", 1
Delay 168
KeyDown "U", 1
Delay 1
KeyUp "O", 1
Delay 164
KeyUp "U", 1
Delay 2
KeyDown "Shift", 1
Delay 265
KeyDown "2", 1
Delay 66
KeyUp "Shift", 1
Delay 100
KeyUp "2", 1
Delay 834
KeyDown "2", 1
Delay 167
KeyUp "2", 1
Delay 168
KeyDown "9", 1
Delay 132
KeyUp "9", 1
Delay 67
KeyDown "9", 1
Delay 133
KeyUp "9", 1
Delay 399
KeyDown "9", 1
Delay 101
KeyUp "9", 1
Delay 132
KeyDown "9", 1
Delay 135
KeyUp "9", 1
Delay 332
KeyDown "Enter", 1
Delay 100
KeyUp "Enter", 1
Delay 1500
KeyDown "`", 1
Delay 100
KeyUp "`", 1
Delay 867
KeyDown "T", 1
Delay 133
KeyUp "T", 1
Delay 268
KeyDown "O", 1
Delay 133
KeyUp "O", 1
Delay 66
KeyDown "G", 1
Delay 136
KeyUp "G", 1
Delay 98
KeyDown "G", 1
Delay 134
KeyUp "G", 1
Delay 769
KeyDown "Up", 1
Delay 100
KeyUp "Up", 1
Delay 69
KeyDown "Up", 1
Delay 98
KeyUp "Up", 1
Delay 66
KeyDown "Up", 1
Delay 134
KeyUp "Up", 1
Delay 267
KeyDown "Up", 1
Delay 99
KeyUp "Up", 1
Delay 134
KeyDown "Enter", 1
Delay 134
KeyUp "Enter", 1
Delay 2567
KeyDown "Esc", 1
Delay 134
KeyUp "Esc", 1
MoveTo 994, 806
Delay 2568
LeftClick 1
MoveTo 1793, 136
Delay 1392
LeftClick 1
MoveTo 747, 242
Delay 1802
LeftClick 1
MoveTo 747, 280
Delay 1281
LeftClick 1
Delay 984
KeyDown "H", 1
Delay 161
KeyDown "A", 1
Delay 16
KeyUp "H", 1
Delay 53
KeyDown "Y", 1
Delay 76
KeyUp "A", 1
Delay 64
KeyUp "Y", 1
MoveTo 755, 360
Delay 3680
LeftClick 1
MoveTo 770, 414
Delay 3042
KeyDown "M", 1
Delay 140
KeyUp "M", 1
MoveTo 1577, 688
Delay 4205
LeftDown 1
MoveTo 1115, 607
Delay 866
LeftUp 1
MoveTo 1486, 628
Delay 400
MouseWheel 1
MoveTo 1526, 620
Delay 33
MouseWheel 1
MoveTo 1592, 616
Delay 34
MouseWheel 1
MoveTo 1506, 594
Delay 700
LeftDown 1
MoveTo 819, 557
Delay 794
LeftUp 1
MoveTo 1197, 567
Delay 1170
LeftDown 1
MoveTo 1210, 712
Delay 930
LeftUp 1
MoveTo 1402, 846
Delay 4034
KeyDown "Ctrl", 1
Delay 401
RightDown 1
Delay 133
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 29
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 90
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 7
Delay 1
KeyDown "Ctrl", 1
Delay 32
KeyUp "Ctrl", 1
MoveTo 735, 361
Delay 3950
KeyDown "Shift", 1
Delay 500
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 3
KeyDown "Shift", 1
Delay 31
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 35
Delay 31
KeyDown "Shift", 1
Delay 34
MoveTo 735, 365
Delay 35
KeyDown "Shift", 1
MoveTo 736, 382
Delay 32
KeyDown "Shift", 1
MoveTo 737, 394
Delay 34
KeyDown "Shift", 1
MoveTo 738, 395
Delay 32
KeyDown "Shift", 1
MoveTo 738, 396
Delay 34
KeyDown "Shift", 1
MoveTo 738, 401
Delay 35
KeyDown "Shift", 1
MoveTo 738, 404
Delay 41
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 2
KeyDown "Shift", 1
Delay 32
MoveTo 738, 406
Delay 34
KeyDown "Shift", 1
MoveTo 738, 410
Delay 33
KeyDown "Shift", 1
MoveTo 738, 411
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 30
KeyDown "Shift", 1
MoveTo 738, 412
Delay 35
KeyDown "Shift", 1
MoveTo 750, 435
Delay 32
KeyDown "Shift", 1
MoveTo 759, 454
Delay 34
KeyDown "Shift", 1
MoveTo 760, 461
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
MoveTo 761, 466
Delay 35
KeyDown "Shift", 1
MoveTo 761, 474
Delay 39
KeyDown "Shift", 1
MoveTo 762, 485
Delay 3
KeyDown "Shift", 1
MoveTo 765, 493
Delay 35
KeyDown "Shift", 1
MoveTo 766, 500
Delay 31
KeyDown "Shift", 1
MoveTo 766, 501
Delay 33
KeyDown "Shift", 1
MoveTo 766, 502
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
MoveTo 765, 501
Delay 37
KeyDown "Shift", 1
MoveTo 762, 496
Delay 34
KeyDown "Shift", 1
MoveTo 761, 487
Delay 36
KeyDown "Shift", 1
MoveTo 761, 484
Delay 34
KeyDown "Shift", 1
MoveTo 760, 482
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 762, 491
Delay 5
KeyDown "Shift", 1
MoveTo 762, 499
Delay 32
KeyDown "Shift", 1
MoveTo 762, 502
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 2
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
Delay 467
KeyDown "M", 1
Delay 158
KeyUp "M", 1
MoveTo 1208, 593
Delay 536
KeyDown "Ctrl", 1
MoveTo 1539, 535
Delay 532
KeyDown "Ctrl", 1
MoveTo 1574, 533
Delay 32
KeyDown "Ctrl", 1
MoveTo 1635, 527
Delay 33
KeyDown "Ctrl", 1
MoveTo 1637, 526
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 1626, 526
Delay 34
KeyDown "Ctrl", 1
MoveTo 1603, 526
Delay 32
KeyDown "Ctrl", 1
MoveTo 1582, 526
Delay 5
KeyDown "Ctrl", 1
MoveTo 1567, 526
Delay 63
KeyDown "Ctrl", 1
MoveTo 1540, 526
Delay 2
KeyDown "Ctrl", 1
MoveTo 1516, 526
Delay 32
KeyDown "Ctrl", 1
MoveTo 1512, 526
Delay 65
KeyDown "Ctrl", 1
MoveTo 1507, 526
Delay 35
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 1506, 526
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 119
KeyDown "Ctrl", 1
Delay 35
Delay 21
KeyDown "Ctrl", 1
Delay 1
Delay 9
KeyUp "Ctrl", 1
MoveTo 771, 359
Delay 3460
KeyDown "Shift", 1
Delay 432
LeftDown 1
Delay 69
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 770, 365
Delay 37
KeyDown "Shift", 1
MoveTo 770, 376
Delay 36
KeyDown "Shift", 1
MoveTo 770, 386
Delay 34
KeyDown "Shift", 1
MoveTo 770, 395
Delay 34
KeyDown "Shift", 1
MoveTo 769, 407
Delay 32
KeyDown "Shift", 1
MoveTo 769, 416
Delay 34
KeyDown "Shift", 1
MoveTo 769, 421
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
MoveTo 767, 417
Delay 36
KeyDown "Shift", 1
MoveTo 765, 409
Delay 32
KeyDown "Shift", 1
MoveTo 765, 406
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 765, 405
Delay 35
KeyDown "Shift", 1
MoveTo 765, 401
Delay 35
KeyDown "Shift", 1
MoveTo 765, 398
Delay 32
KeyDown "Shift", 1
MoveTo 765, 397
Delay 33
KeyDown "Shift", 1
MoveTo 765, 396
Delay 34
KeyDown "Shift", 1
MoveTo 766, 396
Delay 33
KeyDown "Shift", 1
MoveTo 768, 396
Delay 34
KeyDown "Shift", 1
MoveTo 769, 400
Delay 32
KeyDown "Shift", 1
MoveTo 769, 405
Delay 35
KeyDown "Shift", 1
MoveTo 769, 407
Delay 31
KeyDown "Shift", 1
Delay 35
MoveTo 769, 408
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 9
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 770, 415
Delay 35
KeyDown "Shift", 1
MoveTo 773, 427
Delay 32
KeyDown "Shift", 1
MoveTo 779, 447
Delay 33
KeyDown "Shift", 1
MoveTo 780, 454
Delay 34
KeyDown "Shift", 1
MoveTo 780, 455
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 780, 456
Delay 35
KeyDown "Shift", 1
MoveTo 780, 460
Delay 33
KeyDown "Shift", 1
MoveTo 780, 463
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 780, 465
Delay 32
KeyDown "Shift", 1
MoveTo 780, 468
Delay 34
KeyDown "Shift", 1
MoveTo 780, 471
Delay 33
KeyDown "Shift", 1
MoveTo 779, 476
Delay 34
KeyDown "Shift", 1
MoveTo 779, 479
Delay 35
KeyDown "Shift", 1
MoveTo 778, 482
Delay 33
KeyDown "Shift", 1
MoveTo 777, 484
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 776, 486
Delay 34
KeyDown "Shift", 1
MoveTo 775, 494
Delay 35
KeyDown "Shift", 1
MoveTo 774, 499
Delay 32
KeyDown "Shift", 1
MoveTo 774, 500
Delay 33
KeyDown "Shift", 1
MoveTo 774, 501
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 5
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 773, 502
Delay 34
KeyDown "Shift", 1
MoveTo 775, 493
Delay 34
KeyDown "Shift", 1
MoveTo 788, 478
Delay 33
KeyDown "Shift", 1
MoveTo 799, 463
Delay 33
KeyDown "Shift", 1
MoveTo 810, 452
Delay 36
KeyDown "Shift", 1
MoveTo 820, 445
Delay 30
KeyDown "Shift", 1
MoveTo 828, 442
Delay 1
KeyUp "Shift", 1
MoveTo 960, 437
Delay 1003
KeyDown "M", 1
Delay 159
KeyUp "M", 1
MoveTo 1495, 443
Delay 1137
MouseWheel 1
Delay 30
MouseWheel 2
Delay 34
MouseWheel 1
Delay 33
MouseWheel 1
Delay 34
MouseWheel 1
MoveTo 1543, 481
Delay 366
LeftDown 1
MoveTo 575, 501
Delay 667
LeftUp 1
MoveTo 618, 485
Delay 434
KeyDown "Ctrl", 1
MoveTo 537, 370
Delay 501
KeyDown "Ctrl", 1
MoveTo 515, 367
Delay 33
KeyDown "Ctrl", 1
MoveTo 514, 367
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 33
MoveTo 517, 369
Delay 36
KeyDown "Ctrl", 1
MoveTo 524, 374
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 528, 376
Delay 34
KeyDown "Ctrl", 1
MoveTo 535, 378
Delay 33
KeyDown "Ctrl", 1
MoveTo 546, 380
Delay 33
KeyDown "Ctrl", 1
MoveTo 562, 384
Delay 33
KeyDown "Ctrl", 1
MoveTo 592, 389
Delay 36
KeyDown "Ctrl", 1
MoveTo 626, 397
Delay 31
KeyDown "Ctrl", 1
MoveTo 646, 400
Delay 33
KeyDown "Ctrl", 1
MoveTo 647, 401
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 649, 404
Delay 35
KeyDown "Ctrl", 1
MoveTo 652, 406
Delay 32
KeyDown "Ctrl", 1
Delay 34
MoveTo 656, 405
Delay 35
KeyDown "Ctrl", 1
MoveTo 658, 392
Delay 31
KeyDown "Ctrl", 1
MoveTo 659, 371
Delay 33
KeyDown "Ctrl", 1
MoveTo 659, 360
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 3
KeyDown "Ctrl", 1
Delay 148
Delay 32
KeyDown "Ctrl", 1
Delay 57
Delay 47
KeyDown "Ctrl", 1
Delay 1
Delay 18
KeyDown "Ctrl", 1
Delay 4
KeyUp "Ctrl", 1
Delay 2783
KeyDown "Shift", 1
Delay 179
LeftClick 1
MoveTo 691, 403
Delay 200
KeyDown "Shift", 1
MoveTo 695, 407
Delay 33
KeyDown "Shift", 1
MoveTo 696, 408
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 696, 409
Delay 33
KeyDown "Shift", 1
MoveTo 698, 410
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 699, 412
Delay 32
KeyDown "Shift", 1
MoveTo 700, 412
Delay 35
KeyDown "Shift", 1
MoveTo 700, 413
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 33
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 703, 416
Delay 33
KeyDown "Shift", 1
MoveTo 720, 432
Delay 34
KeyDown "Shift", 1
MoveTo 735, 453
Delay 34
KeyDown "Shift", 1
MoveTo 746, 470
Delay 33
KeyDown "Shift", 1
MoveTo 747, 472
Delay 33
KeyDown "Shift", 1
MoveTo 748, 473
Delay 36
KeyDown "Shift", 1
Delay 33
MoveTo 748, 476
Delay 35
KeyDown "Shift", 1
MoveTo 748, 478
Delay 34
KeyDown "Shift", 1
MoveTo 748, 480
Delay 31
KeyDown "Shift", 1
MoveTo 748, 482
Delay 36
KeyDown "Shift", 1
Delay 33
MoveTo 748, 483
Delay 34
KeyDown "Shift", 1
Delay 46
Delay 1
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 748, 486
Delay 35
KeyDown "Shift", 1
MoveTo 748, 487
Delay 33
KeyDown "Shift", 1
Delay 31
MoveTo 748, 488
Delay 35
KeyDown "Shift", 1
MoveTo 745, 486
Delay 33
KeyDown "Shift", 1
MoveTo 744, 481
Delay 34
KeyDown "Shift", 1
MoveTo 744, 479
Delay 34
KeyDown "Shift", 1
MoveTo 744, 476
Delay 32
KeyDown "Shift", 1
MoveTo 745, 473
Delay 36
KeyDown "Shift", 1
MoveTo 746, 472
Delay 3
KeyUp "Shift", 1
MoveTo 746, 467
Delay 627
KeyDown "M", 1
Delay 157
KeyUp "M", 1
MoveTo 879, 607
Delay 568
KeyDown "Ctrl", 1
MoveTo 1300, 576
Delay 534
KeyDown "Ctrl", 1
Delay 2
Delay 63
KeyDown "Ctrl", 1
MoveTo 1304, 576
Delay 33
KeyDown "Ctrl", 1
MoveTo 1308, 570
Delay 35
KeyDown "Ctrl", 1
MoveTo 1312, 566
Delay 36
KeyDown "Ctrl", 1
MoveTo 1314, 564
Delay 32
KeyDown "Ctrl", 1
MoveTo 1317, 557
Delay 32
KeyDown "Ctrl", 1
MoveTo 1318, 553
Delay 35
KeyDown "Ctrl", 1
MoveTo 1318, 551
Delay 31
KeyDown "Ctrl", 1
MoveTo 1318, 549
Delay 33
KeyDown "Ctrl", 1
MoveTo 1318, 547
Delay 33
KeyDown "Ctrl", 1
MoveTo 1318, 543
Delay 35
KeyDown "Ctrl", 1
MoveTo 1319, 540
Delay 33
KeyDown "Ctrl", 1
MoveTo 1320, 536
Delay 38
KeyDown "Ctrl", 1
MoveTo 1322, 533
Delay 27
KeyDown "Ctrl", 1
MoveTo 1322, 532
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 1322, 531
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
MoveTo 1322, 530
Delay 36
KeyDown "Ctrl", 1
Delay 31
Delay 32
RightClick 1
Delay 2
KeyDown "Ctrl", 1
MoveTo 1323, 530
Delay 33
KeyDown "Ctrl", 1
MoveTo 1327, 530
Delay 34
KeyDown "Ctrl", 1
MoveTo 1328, 545
Delay 92
KeyDown "Ctrl", 1
MoveTo 1326, 561
Delay 34
KeyDown "Ctrl", 1
MoveTo 1325, 566
Delay 33
KeyDown "Ctrl", 1
MoveTo 1323, 569
Delay 32
KeyDown "Ctrl", 1
MoveTo 1321, 572
Delay 34
KeyDown "Ctrl", 1
MoveTo 1320, 573
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 21
Delay 1
KeyDown "Ctrl", 1
MoveTo 1320, 574
Delay 11
KeyDown "Ctrl", 1
Delay 8
KeyUp "Ctrl", 1
MoveTo 794, 397
Delay 2659
KeyDown "Shift", 1
MoveTo 767, 358
Delay 307
LeftClick 1
MoveTo 767, 381
Delay 102
KeyDown "Shift", 1
MoveTo 767, 398
Delay 33
KeyDown "Shift", 1
MoveTo 766, 415
Delay 33
KeyDown "Shift", 1
MoveTo 766, 420
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 2
LeftDown 1
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 62
Delay 5
KeyDown "Shift", 1
Delay 29
Delay 65
KeyDown "Shift", 1
MoveTo 771, 449
Delay 34
KeyDown "Shift", 1
MoveTo 773, 464
Delay 33
KeyDown "Shift", 1
MoveTo 773, 472
Delay 37
KeyDown "Shift", 1
MoveTo 773, 473
Delay 35
KeyDown "Shift", 1
MoveTo 773, 475
Delay 33
KeyDown "Shift", 1
MoveTo 773, 478
Delay 32
KeyDown "Shift", 1
MoveTo 773, 483
Delay 33
KeyDown "Shift", 1
MoveTo 773, 488
Delay 34
KeyDown "Shift", 1
MoveTo 774, 490
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 35
MoveTo 771, 488
Delay 35
KeyDown "Shift", 1
MoveTo 771, 471
Delay 32
KeyDown "Shift", 1
MoveTo 775, 431
Delay 33
KeyDown "Shift", 1
MoveTo 782, 387
Delay 35
KeyDown "Shift", 1
MoveTo 784, 362
Delay 32
KeyDown "Shift", 1
MoveTo 784, 354
Delay 33
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
MoveTo 768, 356
Delay 533
KeyDown "Shift", 1
MoveTo 773, 326
Delay 303
LeftClick 1
MoveTo 774, 331
Delay 101
KeyDown "Shift", 1
MoveTo 784, 357
Delay 33
KeyDown "Shift", 1
MoveTo 803, 384
Delay 34
KeyDown "Shift", 1
MoveTo 814, 402
Delay 2
KeyUp "Shift", 1
MoveTo 900, 538
Delay 1303
KeyDown "M", 1
Delay 123
KeyUp "M", 1
MoveTo 1339, 582
Delay 533
KeyDown "Ctrl", 1
MoveTo 1308, 587
Delay 367
RightDown 1
MoveTo 1306, 585
Delay 132
KeyDown "Ctrl", 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 105
KeyDown "Ctrl", 1
Delay 47
Delay 34
KeyDown "Ctrl", 1
Delay 13
Delay 1
KeyDown "Ctrl", 1
Delay 19
KeyUp "Ctrl", 1
MoveTo 496, 38
Delay 3548
KeyDown "Shift", 1
MoveTo 758, 340
Delay 501
KeyDown "Shift", 1
MoveTo 760, 342
Delay 33
KeyDown "Shift", 1
MoveTo 762, 348
Delay 34
KeyDown "Shift", 1
MoveTo 762, 360
Delay 35
KeyDown "Shift", 1
MoveTo 762, 376
Delay 32
KeyDown "Shift", 1
MoveTo 771, 389
Delay 32
KeyDown "Shift", 1
MoveTo 773, 389
Delay 34
KeyDown "Shift", 1
MoveTo 779, 381
Delay 34
KeyDown "Shift", 1
MoveTo 783, 366
Delay 32
KeyDown "Shift", 1
MoveTo 783, 359
Delay 33
KeyDown "Shift", 1
MoveTo 782, 356
Delay 3
KeyDown "Shift", 1
MoveTo 781, 355
Delay 34
KeyDown "Shift", 1
Delay 64
MoveTo 780, 354
Delay 2
KeyDown "Shift", 1
Delay 31
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 32
Delay 33
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 30
MoveTo 775, 350
Delay 35
KeyDown "Shift", 1
MoveTo 772, 347
Delay 33
KeyDown "Shift", 1
MoveTo 769, 343
Delay 33
KeyDown "Shift", 1
MoveTo 768, 341
Delay 34
KeyDown "Shift", 1
MoveTo 767, 339
Delay 35
KeyDown "Shift", 1
MoveTo 767, 337
Delay 31
KeyDown "Shift", 1
MoveTo 767, 336
Delay 33
KeyDown "Shift", 1
MoveTo 766, 336
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 33
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 34
KeyDown "Shift", 1
MoveTo 766, 340
Delay 33
KeyDown "Shift", 1
MoveTo 766, 364
Delay 34
KeyDown "Shift", 1
MoveTo 766, 380
Delay 32
KeyDown "Shift", 1
MoveTo 766, 386
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 766, 387
Delay 33
KeyDown "Shift", 1
MoveTo 768, 389
Delay 36
KeyDown "Shift", 1
MoveTo 768, 393
Delay 32
KeyDown "Shift", 1
MoveTo 768, 397
Delay 32
KeyDown "Shift", 1
MoveTo 768, 400
Delay 34
KeyDown "Shift", 1
MoveTo 769, 401
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 771, 403
Delay 34
KeyDown "Shift", 1
MoveTo 773, 411
Delay 33
KeyDown "Shift", 1
MoveTo 773, 417
Delay 33
KeyDown "Shift", 1
MoveTo 773, 420
Delay 35
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 33
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 36
KeyDown "Shift", 1
MoveTo 773, 424
Delay 33
KeyDown "Shift", 1
MoveTo 770, 432
Delay 32
KeyDown "Shift", 1
MoveTo 766, 437
Delay 33
KeyDown "Shift", 1
MoveTo 765, 440
Delay 33
KeyDown "Shift", 1
MoveTo 762, 445
Delay 36
KeyDown "Shift", 1
MoveTo 760, 448
Delay 32
KeyDown "Shift", 1
MoveTo 757, 452
Delay 34
KeyDown "Shift", 1
MoveTo 757, 454
Delay 36
KeyDown "Shift", 1
MoveTo 756, 456
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 754, 456
Delay 2
KeyDown "Shift", 1
Delay 65
Delay 2
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 754, 457
Delay 34
KeyDown "Shift", 1
MoveTo 754, 461
Delay 34
KeyDown "Shift", 1
MoveTo 754, 466
Delay 33
KeyDown "Shift", 1
MoveTo 754, 472
Delay 34
KeyDown "Shift", 1
MoveTo 753, 480
Delay 34
KeyDown "Shift", 1
MoveTo 752, 484
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
MoveTo 751, 485
Delay 34
KeyDown "Shift", 1
MoveTo 748, 486
Delay 34
KeyDown "Shift", 1
MoveTo 746, 476
Delay 33
KeyDown "Shift", 1
MoveTo 747, 472
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
MoveTo 748, 471
Delay 3
KeyDown "Shift", 1
Delay 65
MoveTo 753, 472
Delay 34
KeyDown "Shift", 1
MoveTo 760, 477
Delay 34
KeyDown "Shift", 1
MoveTo 767, 482
Delay 33
KeyDown "Shift", 1
MoveTo 768, 483
Delay 33
KeyUp "Shift", 1
MoveTo 768, 482
Delay 571
KeyDown "M", 1
Delay 167
KeyUp "M", 1
MoveTo 1464, 553
Delay 367
KeyDown "Ctrl", 1
MoveTo 1337, 580
Delay 500
KeyDown "Ctrl", 1
Delay 1
RightDown 1
MoveTo 1336, 579
Delay 33
KeyDown "Ctrl", 1
MoveTo 1334, 576
Delay 34
KeyDown "Ctrl", 1
MoveTo 1332, 575
Delay 32
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 33
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 113
KeyDown "Ctrl", 1
Delay 52
Delay 33
KeyDown "Ctrl", 1
Delay 28
Delay 1
KeyDown "Ctrl", 1
Delay 4
Delay 1
KeyUp "Ctrl", 1
MoveTo 790, 394
Delay 2566
KeyDown "Shift", 1
MoveTo 793, 356
Delay 432
LeftClick 1
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
Delay 8
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 793, 347
Delay 33
KeyDown "Shift", 1
MoveTo 793, 344
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 795, 341
Delay 36
KeyDown "Shift", 1
MoveTo 796, 340
Delay 32
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 797, 339
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 32
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
MoveTo 795, 353
Delay 32
KeyDown "Shift", 1
MoveTo 795, 372
Delay 34
KeyDown "Shift", 1
MoveTo 793, 392
Delay 33
KeyDown "Shift", 1
MoveTo 791, 408
Delay 34
KeyDown "Shift", 1
MoveTo 786, 425
Delay 4
KeyDown "Shift", 1
MoveTo 785, 430
Delay 63
KeyDown "Shift", 1
MoveTo 785, 431
Delay 36
KeyDown "Shift", 1
Delay 1
Delay 30
KeyDown "Shift", 1
Delay 67
MoveTo 783, 427
Delay 34
KeyDown "Shift", 1
MoveTo 787, 422
Delay 33
KeyDown "Shift", 1
MoveTo 789, 418
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 32
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 35
KeyDown "Shift", 1
Delay 36
Delay 2
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 34
MoveTo 790, 422
Delay 34
KeyDown "Shift", 1
MoveTo 794, 436
Delay 35
KeyDown "Shift", 1
MoveTo 800, 450
Delay 3
KeyDown "Shift", 1
MoveTo 802, 457
Delay 32
KeyUp "Shift", 1
MoveTo 804, 466
Delay 838
KeyDown "M", 1
Delay 128
KeyUp "M", 1
MoveTo 1282, 583
Delay 432
KeyDown "Ctrl", 1
MoveTo 1387, 566
Delay 466
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 32
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 95
Delay 14
KeyDown "Ctrl", 1
Delay 1
Delay 34
KeyUp "Ctrl", 1
MoveTo 1288, 510
Delay 2696
KeyDown "Shift", 1
MoveTo 794, 344
Delay 486
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 31
KeyDown "Shift", 1
MoveTo 791, 346
Delay 39
KeyDown "Shift", 1
MoveTo 788, 355
Delay 35
KeyDown "Shift", 1
MoveTo 787, 363
Delay 34
KeyDown "Shift", 1
MoveTo 787, 364
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 49
KeyDown "Shift", 1
Delay 51
Delay 51
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 56
KeyDown "Shift", 1
Delay 40
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 38
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 33
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 35
Delay 32
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 784, 377
Delay 33
KeyDown "Shift", 1
MoveTo 782, 396
Delay 33
KeyDown "Shift", 1
MoveTo 781, 406
Delay 34
KeyDown "Shift", 1
MoveTo 780, 408
Delay 33
KeyDown "Shift", 1
MoveTo 779, 409
Delay 34
KeyDown "Shift", 1
MoveTo 779, 411
Delay 35
KeyDown "Shift", 1
Delay 2
Delay 32
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 33
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 29
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 1
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 29
Delay 34
KeyDown "Shift", 1
MoveTo 778, 413
Delay 34
KeyDown "Shift", 1
MoveTo 783, 418
Delay 33
KeyDown "Shift", 1
MoveTo 804, 433
Delay 33
KeyDown "Shift", 1
MoveTo 831, 448
Delay 33
KeyDown "Shift", 1
MoveTo 862, 462
Delay 34
KeyUp "Shift", 1
MoveTo 1008, 499
Delay 766
KeyDown "M", 1
Delay 160
KeyUp "M", 1
MoveTo 1366, 602
Delay 532
KeyDown "Ctrl", 1
MoveTo 1420, 565
Delay 467
RightDown 1
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 104
KeyDown "Ctrl", 1
Delay 50
Delay 33
KeyDown "Ctrl", 1
Delay 6
Delay 2
KeyDown "Ctrl", 1
Delay 25
KeyUp "Ctrl", 1
Delay 2565
KeyDown "Shift", 1
MoveTo 849, 356
Delay 482
KeyDown "Shift", 1
MoveTo 848, 357
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 38
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 38
KeyDown "Shift", 1
Delay 32
MoveTo 848, 359
Delay 34
KeyDown "Shift", 1
MoveTo 847, 370
Delay 34
KeyDown "Shift", 1
MoveTo 841, 383
Delay 33
KeyDown "Shift", 1
MoveTo 837, 393
Delay 33
KeyDown "Shift", 1
MoveTo 837, 396
Delay 34
KeyDown "Shift", 1
MoveTo 836, 398
Delay 36
KeyDown "Shift", 1
MoveTo 835, 402
Delay 34
KeyDown "Shift", 1
MoveTo 835, 404
Delay 36
KeyDown "Shift", 1
MoveTo 835, 406
Delay 31
KeyDown "Shift", 1
MoveTo 835, 407
Delay 37
KeyDown "Shift", 1
Delay 32
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 835, 415
Delay 34
KeyDown "Shift", 1
MoveTo 835, 416
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 39
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 37
KeyDown "Shift", 1
Delay 33
Delay 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 831, 423
Delay 34
KeyDown "Shift", 1
MoveTo 823, 436
Delay 34
KeyDown "Shift", 1
MoveTo 814, 450
Delay 34
KeyDown "Shift", 1
MoveTo 808, 457
Delay 33
KeyDown "Shift", 1
MoveTo 805, 461
Delay 33
KeyDown "Shift", 1
MoveTo 799, 467
Delay 34
KeyDown "Shift", 1
MoveTo 790, 473
Delay 34
KeyDown "Shift", 1
MoveTo 784, 479
Delay 33
KeyDown "Shift", 1
MoveTo 779, 487
Delay 35
KeyDown "Shift", 1
MoveTo 776, 493
Delay 33
KeyDown "Shift", 1
MoveTo 773, 498
Delay 33
KeyDown "Shift", 1
MoveTo 771, 501
Delay 33
KeyDown "Shift", 1
MoveTo 768, 504
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 775, 504
Delay 39
KeyDown "Shift", 1
MoveTo 801, 504
Delay 32
KeyDown "Shift", 1
MoveTo 819, 505
Delay 32
KeyDown "Shift", 1
MoveTo 837, 508
Delay 33
KeyUp "Shift", 1
MoveTo 883, 516
Delay 702
KeyDown "M", 1
MoveTo 917, 516
Delay 159
KeyUp "M", 1
MoveTo 1389, 592
Delay 333
KeyDown "Ctrl", 1
MoveTo 1428, 539
Delay 533
KeyDown "Ctrl", 1
MoveTo 1443, 538
Delay 40
KeyDown "Ctrl", 1
MoveTo 1459, 538
Delay 1
KeyDown "Ctrl", 1
MoveTo 1466, 537
Delay 59
KeyDown "Ctrl", 1
MoveTo 1468, 536
Delay 35
KeyDown "Ctrl", 1
Delay 2
MoveTo 1472, 535
Delay 65
KeyDown "Ctrl", 1
MoveTo 1479, 535
Delay 1
KeyDown "Ctrl", 1
MoveTo 1482, 535
Delay 34
KeyDown "Ctrl", 1
Delay 63
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 69
Delay 1
KeyDown "Ctrl", 1
Delay 41
Delay 1
KeyUp "Ctrl", 1
MoveTo 945, 381
Delay 2681
KeyDown "Shift", 1
MoveTo 753, 356
Delay 513
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 36
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 63
Delay 2
Delay 11
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 753, 359
Delay 34
KeyDown "Shift", 1
MoveTo 758, 370
Delay 33
KeyDown "Shift", 1
MoveTo 766, 380
Delay 34
KeyDown "Shift", 1
MoveTo 768, 385
Delay 32
KeyDown "Shift", 1
MoveTo 768, 389
Delay 35
KeyDown "Shift", 1
MoveTo 768, 393
Delay 31
KeyDown "Shift", 1
MoveTo 768, 396
Delay 36
KeyDown "Shift", 1
MoveTo 768, 398
Delay 32
KeyDown "Shift", 1
MoveTo 768, 399
Delay 33
KeyDown "Shift", 1
MoveTo 767, 401
Delay 33
KeyDown "Shift", 1
MoveTo 766, 404
Delay 35
KeyDown "Shift", 1
MoveTo 765, 408
Delay 32
KeyDown "Shift", 1
MoveTo 764, 410
Delay 33
KeyDown "Shift", 1
MoveTo 762, 414
Delay 34
KeyDown "Shift", 1
MoveTo 762, 415
Delay 5
KeyDown "Shift", 1
Delay 29
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 37
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
MoveTo 762, 416
Delay 34
KeyDown "Shift", 1
MoveTo 765, 423
Delay 33
KeyDown "Shift", 1
MoveTo 768, 430
Delay 33
KeyDown "Shift", 1
MoveTo 773, 442
Delay 35
KeyDown "Shift", 1
MoveTo 777, 456
Delay 34
KeyDown "Shift", 1
MoveTo 779, 478
Delay 31
KeyDown "Shift", 1
MoveTo 780, 492
Delay 33
KeyDown "Shift", 1
MoveTo 781, 495
Delay 33
KeyDown "Shift", 1
MoveTo 782, 496
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 782, 497
Delay 37
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 3
KeyDown "Shift", 1
Delay 32
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 29
MoveTo 782, 496
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 786, 490
Delay 33
KeyDown "Shift", 1
MoveTo 818, 481
Delay 34
KeyDown "Shift", 1
MoveTo 830, 481
Delay 32
KeyUp "Shift", 1
MoveTo 850, 480
Delay 604
KeyDown "M", 1
MoveTo 1054, 478
Delay 128
KeyUp "M", 1
MoveTo 1604, 532
Delay 367
KeyDown "Ctrl", 1
MoveTo 1492, 518
Delay 534
KeyDown "Ctrl", 1
Delay 32
MoveTo 1491, 518
Delay 35
KeyDown "Ctrl", 1
MoveTo 1492, 518
Delay 2
KeyDown "Ctrl", 1
MoveTo 1523, 517
Delay 63
KeyDown "Ctrl", 1
MoveTo 1533, 514
Delay 5
KeyDown "Ctrl", 1
MoveTo 1534, 514
Delay 30
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
MoveTo 1534, 512
Delay 35
KeyDown "Ctrl", 1
MoveTo 1530, 509
Delay 33
KeyDown "Ctrl", 1
MoveTo 1527, 507
Delay 35
KeyDown "Ctrl", 1
MoveTo 1524, 504
Delay 33
KeyDown "Ctrl", 1
MoveTo 1523, 503
Delay 32
KeyDown "Ctrl", 1
Delay 32
MoveTo 1522, 502
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 3
RightDown 1
Delay 30
KeyDown "Ctrl", 1
Delay 34
Delay 36
KeyDown "Ctrl", 1
Delay 31
Delay 33
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
MoveTo 1524, 502
Delay 105
KeyDown "Ctrl", 1
Delay 11
Delay 1
KeyDown "Ctrl", 1
MoveTo 1526, 504
Delay 21
KeyUp "Ctrl", 1
MoveTo 870, 314
Delay 2673
KeyDown "Shift", 1
MoveTo 814, 355
Delay 474
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 39
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 2
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 36
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 28
MoveTo 813, 358
Delay 35
KeyDown "Shift", 1
MoveTo 813, 367
Delay 35
KeyDown "Shift", 1
MoveTo 810, 380
Delay 32
KeyDown "Shift", 1
MoveTo 807, 388
Delay 33
KeyDown "Shift", 1
MoveTo 803, 398
Delay 34
KeyDown "Shift", 1
MoveTo 799, 403
Delay 32
KeyDown "Shift", 1
MoveTo 799, 406
Delay 40
KeyDown "Shift", 1
MoveTo 799, 407
Delay 2
KeyDown "Shift", 1
MoveTo 799, 413
Delay 34
KeyDown "Shift", 1
MoveTo 799, 417
Delay 33
KeyDown "Shift", 1
MoveTo 799, 418
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 799, 428
Delay 34
KeyDown "Shift", 1
MoveTo 797, 450
Delay 34
KeyDown "Shift", 1
MoveTo 794, 464
Delay 34
KeyDown "Shift", 1
MoveTo 791, 472
Delay 32
KeyDown "Shift", 1
MoveTo 788, 480
Delay 38
KeyDown "Shift", 1
MoveTo 785, 490
Delay 30
KeyDown "Shift", 1
MoveTo 785, 495
Delay 33
KeyDown "Shift", 1
MoveTo 785, 496
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 32
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 783, 488
Delay 569
KeyDown "M", 1
MoveTo 828, 483
Delay 161
KeyUp "M", 1
MoveTo 1631, 511
Delay 434
KeyDown "Ctrl", 1
MoveTo 1549, 519
Delay 535
KeyDown "Ctrl", 1
MoveTo 1553, 514
Delay 32
KeyDown "Ctrl", 1
MoveTo 1554, 514
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 35
Delay 1
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
MoveTo 1555, 514
Delay 65
KeyDown "Ctrl", 1
MoveTo 1556, 514
Delay 3
KeyDown "Ctrl", 1
Delay 108
Delay 35
KeyDown "Ctrl", 1
Delay 35
Delay 1
KeyDown "Ctrl", 1
Delay 13
Delay 3
KeyUp "Ctrl", 1
MoveTo 809, 413
Delay 2690
KeyDown "Shift", 1
MoveTo 804, 360
Delay 509
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 32
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 41
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
MoveTo 805, 370
Delay 37
KeyDown "Shift", 1
MoveTo 807, 387
Delay 35
KeyDown "Shift", 1
MoveTo 808, 397
Delay 35
KeyDown "Shift", 1
MoveTo 808, 401
Delay 33
KeyDown "Shift", 1
MoveTo 808, 404
Delay 34
KeyDown "Shift", 1
MoveTo 809, 407
Delay 31
KeyDown "Shift", 1
Delay 33
MoveTo 809, 414
Delay 34
KeyDown "Shift", 1
MoveTo 809, 423
Delay 36
KeyDown "Shift", 1
MoveTo 809, 426
Delay 33
KeyDown "Shift", 1
MoveTo 809, 427
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
MoveTo 809, 428
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 3
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 39
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 811, 428
Delay 34
KeyUp "Shift", 1
MoveTo 822, 427
Delay 602
KeyDown "M", 1
MoveTo 967, 447
Delay 98
KeyUp "M", 1
MoveTo 1511, 539
Delay 367
KeyDown "Ctrl", 1
MoveTo 1610, 543
Delay 466
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 96
Delay 19
KeyDown "Ctrl", 1
Delay 1
Delay 14
KeyUp "Ctrl", 1
MoveTo 1117, 385
Delay 2566
KeyDown "Shift", 1
MoveTo 821, 314
Delay 483
KeyDown "Shift", 1
MoveTo 819, 318
Delay 32
KeyDown "Shift", 1
MoveTo 815, 324
Delay 35
KeyDown "Shift", 1
MoveTo 814, 330
Delay 35
KeyDown "Shift", 1
MoveTo 814, 335
Delay 35
KeyDown "Shift", 1
MoveTo 814, 339
Delay 34
KeyDown "Shift", 1
MoveTo 814, 343
Delay 32
KeyDown "Shift", 1
MoveTo 814, 351
Delay 37
KeyDown "Shift", 1
MoveTo 814, 357
Delay 3
KeyDown "Shift", 1
Delay 64
Delay 1
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 40
Delay 1
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 41
Delay 36
KeyDown "Shift", 1
Delay 2
Delay 36
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 814, 361
Delay 35
KeyDown "Shift", 1
MoveTo 818, 369
Delay 38
KeyDown "Shift", 1
MoveTo 820, 379
Delay 31
KeyDown "Shift", 1
MoveTo 821, 388
Delay 36
KeyDown "Shift", 1
MoveTo 821, 396
Delay 34
KeyDown "Shift", 1
MoveTo 821, 400
Delay 34
KeyDown "Shift", 1
MoveTo 821, 402
Delay 36
KeyDown "Shift", 1
Delay 31
MoveTo 821, 403
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 821, 404
Delay 35
KeyDown "Shift", 1
MoveTo 821, 406
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 45
Delay 36
KeyDown "Shift", 1
Delay 2
Delay 35
KeyDown "Shift", 1
Delay 2
Delay 34
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 821, 407
Delay 36
KeyDown "Shift", 1
MoveTo 834, 409
Delay 34
KeyDown "Shift", 1
MoveTo 883, 426
Delay 33
KeyDown "Shift", 1
MoveTo 947, 453
Delay 35
KeyDown "Shift", 1
MoveTo 1001, 471
Delay 32
KeyDown "Shift", 1
MoveTo 1061, 492
Delay 35
KeyDown "Shift", 1
MoveTo 1111, 507
Delay 36
KeyDown "Shift", 1
MoveTo 1157, 519
Delay 33
KeyDown "Shift", 1
MoveTo 1182, 524
Delay 35
KeyUp "Shift", 1
MoveTo 1185, 524
Delay 541
KeyDown "M", 1
MoveTo 1297, 539
Delay 130
KeyUp "M", 1
MoveTo 1702, 663
Delay 333
KeyDown "Ctrl", 1
MoveTo 1627, 570
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 1627, 569
Delay 35
KeyDown "Ctrl", 1
MoveTo 1627, 567
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 73
KeyDown "Ctrl", 1
Delay 1
Delay 26
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 1458, 545
Delay 2568
KeyDown "Shift", 1
MoveTo 707, 338
Delay 502
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 706, 345
Delay 34
KeyDown "Shift", 1
MoveTo 706, 353
Delay 33
KeyDown "Shift", 1
MoveTo 706, 356
Delay 46
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 32
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 2
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 36
KeyDown "Shift", 1
Delay 1
Delay 2
KeyDown "Shift", 1
Delay 32
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 36
KeyDown "Shift", 1
MoveTo 719, 373
Delay 34
KeyDown "Shift", 1
MoveTo 735, 395
Delay 31
KeyDown "Shift", 1
MoveTo 745, 413
Delay 34
KeyDown "Shift", 1
MoveTo 747, 417
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 37
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 63
Delay 6
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
Delay 49
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
KeyUp "Shift", 1
MoveTo 831, 456
Delay 305
KeyDown "M", 1
MoveTo 1048, 495
Delay 130
KeyUp "M", 1
MoveTo 1626, 520
Delay 334
KeyDown "Ctrl", 1
MoveTo 1644, 481
Delay 499
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 99
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 14
KeyDown "Ctrl", 1
Delay 2
Delay 17
KeyUp "Ctrl", 1
MoveTo 1600, 481
Delay 2794
KeyDown "Shift", 1
MoveTo 909, 356
Delay 503
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 41
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 62
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 33
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 32
KeyDown "Shift", 1
MoveTo 901, 370
Delay 35
KeyDown "Shift", 1
MoveTo 885, 392
Delay 33
KeyDown "Shift", 1
MoveTo 865, 410
Delay 35
KeyDown "Shift", 1
MoveTo 851, 418
Delay 34
KeyDown "Shift", 1
MoveTo 848, 418
Delay 32
KeyDown "Shift", 1
MoveTo 847, 418
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 846, 418
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
MoveTo 848, 417
Delay 34
KeyDown "Shift", 1
MoveTo 850, 417
Delay 32
KeyUp "Shift", 1
MoveTo 869, 421
Delay 567
KeyDown "M", 1
MoveTo 938, 415
Delay 165
KeyUp "M", 1
MoveTo 1446, 404
Delay 300
KeyDown "Ctrl", 1
MoveTo 1645, 491
Delay 499
KeyDown "Ctrl", 1
MoveTo 1644, 489
Delay 32
KeyDown "Ctrl", 1
MoveTo 1642, 486
Delay 35
KeyDown "Ctrl", 1
MoveTo 1637, 483
Delay 34
KeyDown "Ctrl", 1
MoveTo 1633, 480
Delay 35
KeyDown "Ctrl", 1
MoveTo 1632, 479
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 5
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 99
Delay 31
KeyDown "Ctrl", 1
Delay 38
Delay 4
KeyDown "Ctrl", 1
Delay 2
Delay 3
KeyUp "Ctrl", 1
MoveTo 1205, 400
Delay 2451
KeyDown "Shift", 1
MoveTo 953, 359
Delay 432
LeftClick 1
Delay 6
KeyDown "Shift", 1
Delay 28
Delay 34
KeyDown "Shift", 1
Delay 41
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 948, 359
Delay 37
KeyDown "Shift", 1
MoveTo 930, 371
Delay 32
KeyDown "Shift", 1
MoveTo 882, 387
Delay 33
KeyDown "Shift", 1
MoveTo 854, 395
Delay 33
KeyDown "Shift", 1
MoveTo 834, 402
Delay 34
KeyDown "Shift", 1
MoveTo 832, 402
Delay 33
KeyDown "Shift", 1
MoveTo 830, 403
Delay 32
KeyDown "Shift", 1
MoveTo 828, 404
Delay 34
KeyDown "Shift", 1
MoveTo 816, 405
Delay 4
KeyDown "Shift", 1
MoveTo 802, 407
Delay 63
KeyDown "Shift", 1
MoveTo 797, 408
Delay 3
KeyDown "Shift", 1
Delay 29
MoveTo 795, 408
Delay 35
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 35
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 28
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 29
Delay 33
KeyDown "Shift", 1
MoveTo 788, 415
Delay 35
KeyDown "Shift", 1
MoveTo 780, 435
Delay 33
KeyDown "Shift", 1
MoveTo 777, 450
Delay 35
KeyDown "Shift", 1
MoveTo 773, 461
Delay 34
KeyDown "Shift", 1
MoveTo 757, 482
Delay 33
KeyDown "Shift", 1
MoveTo 750, 490
Delay 34
KeyDown "Shift", 1
MoveTo 749, 492
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 37
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 38
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
MoveTo 752, 492
Delay 35
KeyDown "Shift", 1
MoveTo 784, 485
Delay 32
KeyUp "Shift", 1
MoveTo 1047, 475
Delay 465
KeyDown "M", 1
MoveTo 1191, 501
Delay 163
KeyUp "M", 1
MoveTo 1611, 456
Delay 334
KeyDown "Ctrl", 1
MoveTo 1631, 489
Delay 499
KeyDown "Ctrl", 1
Delay 36
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 29
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 35
Delay 87
KeyDown "Ctrl", 1
Delay 36
Delay 31
KeyDown "Ctrl", 1
Delay 4
Delay 2
KeyDown "Ctrl", 1
Delay 28
KeyUp "Ctrl", 1
MoveTo 895, 379
Delay 2841
KeyDown "Shift", 1
MoveTo 814, 359
Delay 268
LeftDoubleClick 1
Delay 81
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 814, 364
Delay 32
KeyDown "Shift", 1
MoveTo 813, 379
Delay 33
KeyDown "Shift", 1
MoveTo 812, 394
Delay 34
KeyDown "Shift", 1
MoveTo 809, 408
Delay 33
KeyDown "Shift", 1
MoveTo 808, 415
Delay 33
KeyDown "Shift", 1
MoveTo 808, 419
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 38
Delay 33
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 32
Delay 36
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
MoveTo 790, 431
Delay 34
KeyDown "Shift", 1
MoveTo 760, 470
Delay 34
KeyDown "Shift", 1
MoveTo 754, 487
Delay 32
KeyDown "Shift", 1
MoveTo 754, 489
Delay 34
KeyDown "Shift", 1
MoveTo 754, 490
Delay 33
KeyDown "Shift", 1
MoveTo 757, 492
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 757, 491
Delay 2
KeyDown "Shift", 1
Delay 67
Delay 1
KeyDown "Shift", 1
Delay 63
Delay 34
KeyDown "Shift", 1
MoveTo 758, 491
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 759, 491
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 760, 491
Delay 34
KeyDown "Shift", 1
MoveTo 761, 491
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 761, 488
Delay 34
KeyDown "Shift", 1
MoveTo 764, 479
Delay 35
KeyDown "Shift", 1
MoveTo 769, 470
Delay 33
KeyDown "Shift", 1
MoveTo 785, 454
Delay 34
KeyDown "Shift", 1
MoveTo 797, 444
Delay 32
KeyDown "Shift", 1
MoveTo 801, 441
Delay 4
KeyUp "Shift", 1
MoveTo 868, 450
Delay 497
KeyDown "M", 1
MoveTo 1037, 459
Delay 129
KeyUp "M", 1
MoveTo 1524, 440
Delay 367
KeyDown "Ctrl", 1
MoveTo 1580, 519
Delay 501
KeyDown "Ctrl", 1
MoveTo 1581, 519
Delay 36
KeyDown "Ctrl", 1
MoveTo 1591, 515
Delay 31
KeyDown "Ctrl", 1
MoveTo 1594, 514
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 104
Delay 25
KeyDown "Ctrl", 1
Delay 6
Delay 2
KeyUp "Ctrl", 1
MoveTo 818, 365
Delay 2850
KeyDown "Shift", 1
Delay 247
LeftDoubleClick 1
Delay 69
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 817, 371
Delay 35
KeyDown "Shift", 1
MoveTo 813, 389
Delay 33
KeyDown "Shift", 1
MoveTo 806, 399
Delay 35
KeyDown "Shift", 1
MoveTo 803, 402
Delay 33
KeyDown "Shift", 1
MoveTo 794, 408
Delay 34
KeyDown "Shift", 1
MoveTo 790, 409
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 32
KeyDown "Shift", 1
MoveTo 790, 411
Delay 35
KeyDown "Shift", 1
MoveTo 790, 424
Delay 33
KeyDown "Shift", 1
MoveTo 789, 439
Delay 33
KeyDown "Shift", 1
MoveTo 782, 450
Delay 33
KeyDown "Shift", 1
MoveTo 773, 462
Delay 33
KeyDown "Shift", 1
MoveTo 769, 467
Delay 37
KeyDown "Shift", 1
MoveTo 767, 468
Delay 41
KeyDown "Shift", 1
MoveTo 765, 474
Delay 33
KeyDown "Shift", 1
MoveTo 761, 481
Delay 35
KeyDown "Shift", 1
MoveTo 758, 484
Delay 3
KeyDown "Shift", 1
Delay 30
Delay 35
KeyDown "Shift", 1
Delay 32
MoveTo 758, 487
Delay 35
KeyDown "Shift", 1
MoveTo 758, 490
Delay 33
KeyDown "Shift", 1
MoveTo 759, 494
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 760, 495
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 33
Delay 31
KeyDown "Shift", 1
MoveTo 760, 494
Delay 34
KeyDown "Shift", 1
MoveTo 768, 488
Delay 34
KeyDown "Shift", 1
MoveTo 777, 483
Delay 1
KeyUp "Shift", 1
MoveTo 785, 481
Delay 467
KeyDown "M", 1
MoveTo 841, 482
Delay 170
KeyUp "M", 1
MoveTo 1454, 446
Delay 334
KeyDown "Ctrl", 1
MoveTo 1539, 550
Delay 501
KeyDown "Ctrl", 1
MoveTo 1538, 549
Delay 32
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 112
Delay 50
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 35
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
KeyDown "Ctrl", 1
MoveTo 819, 340
Delay 2417
KeyDown "Shift", 1
MoveTo 802, 363
Delay 434
LeftDown 1
Delay 80
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 1
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
MoveTo 802, 364
Delay 34
KeyDown "Shift", 1
MoveTo 797, 381
Delay 34
KeyDown "Shift", 1
MoveTo 793, 395
Delay 32
KeyDown "Shift", 1
MoveTo 788, 405
Delay 33
KeyDown "Shift", 1
MoveTo 783, 411
Delay 35
KeyDown "Shift", 1
MoveTo 780, 414
Delay 32
KeyDown "Shift", 1
MoveTo 777, 417
Delay 32
KeyDown "Shift", 1
MoveTo 776, 418
Delay 37
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 36
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 3
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 2
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 775, 423
Delay 30
KeyDown "Shift", 1
MoveTo 775, 434
Delay 34
KeyDown "Shift", 1
MoveTo 775, 446
Delay 33
KeyDown "Shift", 1
MoveTo 775, 448
Delay 33
KeyDown "Shift", 1
MoveTo 775, 451
Delay 35
KeyDown "Shift", 1
MoveTo 775, 455
Delay 32
KeyDown "Shift", 1
MoveTo 775, 458
Delay 34
KeyDown "Shift", 1
MoveTo 775, 464
Delay 33
KeyDown "Shift", 1
MoveTo 772, 476
Delay 33
KeyDown "Shift", 1
MoveTo 770, 486
Delay 34
KeyDown "Shift", 1
MoveTo 768, 494
Delay 35
KeyDown "Shift", 1
MoveTo 767, 497
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 35
KeyUp "Shift", 1
Delay 365
KeyDown "M", 1
MoveTo 830, 497
Delay 163
KeyUp "M", 1
MoveTo 1533, 562
Delay 534
KeyDown "Ctrl", 1
MoveTo 1499, 546
Delay 499
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 100
KeyDown "Ctrl", 1
Delay 34
Delay 49
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 1495, 545
Delay 35
KeyDown "Ctrl", 1
MoveTo 1493, 544
Delay 33
KeyDown "Ctrl", 1
MoveTo 1491, 543
Delay 32
KeyDown "Ctrl", 1
Delay 21
Delay 2
KeyDown "Ctrl", 1
MoveTo 1489, 542
Delay 12
KeyUp "Ctrl", 1
MoveTo 560, 357
Delay 2339
KeyDown "Shift", 1
MoveTo 632, 375
Delay 511
KeyDown "Shift", 1
MoveTo 633, 374
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 636, 371
Delay 34
KeyDown "Shift", 1
MoveTo 639, 367
Delay 34
KeyDown "Shift", 1
MoveTo 640, 365
Delay 33
KeyDown "Shift", 1
MoveTo 641, 364
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 42
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 46
Delay 43
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 39
Delay 2
KeyDown "Shift", 1
Delay 46
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 36
KeyDown "Shift", 1
MoveTo 641, 368
Delay 3
KeyDown "Shift", 1
MoveTo 642, 389
Delay 33
KeyDown "Shift", 1
MoveTo 645, 406
Delay 34
KeyDown "Shift", 1
MoveTo 649, 418
Delay 32
KeyDown "Shift", 1
MoveTo 655, 430
Delay 34
KeyDown "Shift", 1
MoveTo 661, 435
Delay 34
KeyDown "Shift", 1
MoveTo 661, 436
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 664, 434
Delay 35
KeyDown "Shift", 1
MoveTo 668, 428
Delay 37
KeyDown "Shift", 1
MoveTo 671, 423
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 37
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 29
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 40
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 672, 422
Delay 33
KeyDown "Shift", 1
MoveTo 675, 430
Delay 33
KeyDown "Shift", 1
MoveTo 686, 449
Delay 34
KeyDown "Shift", 1
MoveTo 697, 465
Delay 37
KeyDown "Shift", 1
MoveTo 705, 478
Delay 35
KeyDown "Shift", 1
MoveTo 707, 480
Delay 32
KeyDown "Shift", 1
Delay 32
MoveTo 708, 482
Delay 35
KeyDown "Shift", 1
MoveTo 708, 484
Delay 32
KeyDown "Shift", 1
MoveTo 708, 486
Delay 34
KeyDown "Shift", 1
MoveTo 708, 488
Delay 34
KeyDown "Shift", 1
MoveTo 708, 489
Delay 34
KeyDown "Shift", 1
MoveTo 708, 495
Delay 38
KeyDown "Shift", 1
MoveTo 708, 499
Delay 33
KeyDown "Shift", 1
MoveTo 707, 500
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 1
KeyUp "Shift", 1
Delay 430
KeyDown "M", 1
Delay 133
KeyUp "M", 1
MoveTo 1197, 553
Delay 264
KeyDown "Ctrl", 1
MoveTo 1432, 521
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 1434, 522
Delay 39
KeyDown "Ctrl", 1
MoveTo 1437, 529
Delay 29
KeyDown "Ctrl", 1
MoveTo 1440, 532
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 5
RightDown 1
Delay 27
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 106
Delay 4
KeyDown "Ctrl", 1
Delay 1
Delay 29
KeyUp "Ctrl", 1
MoveTo 783, 380
Delay 2657
KeyDown "Shift", 1
MoveTo 763, 361
Delay 366
LeftClick 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 763, 362
Delay 30
KeyDown "Shift", 1
MoveTo 763, 391
Delay 34
KeyDown "Shift", 1
MoveTo 766, 412
Delay 37
KeyDown "Shift", 1
MoveTo 770, 420
Delay 36
KeyDown "Shift", 1
MoveTo 771, 421
Delay 30
KeyDown "Shift", 1
Delay 34
MoveTo 773, 423
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 39
Delay 34
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 32
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 35
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 773, 425
Delay 34
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
Delay 465
KeyDown "M", 1
Delay 164
KeyUp "M", 1
MoveTo 1146, 556
Delay 268
KeyDown "Ctrl", 1
MoveTo 1406, 571
Delay 532
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 2
Delay 31
RightDown 1
Delay 34
KeyDown "Ctrl", 1
Delay 2
Delay 34
KeyDown "Ctrl", 1
Delay 64
Delay 1
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 92
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 9
Delay 1
KeyDown "Ctrl", 1
Delay 22
KeyUp "Ctrl", 1
MoveTo 1149, 569
Delay 2281
KeyDown "Shift", 1
MoveTo 790, 508
Delay 506
KeyDown "Shift", 1
MoveTo 783, 507
Delay 30
KeyDown "Shift", 1
MoveTo 782, 507
Delay 33
KeyDown "Shift", 1
MoveTo 775, 502
Delay 33
KeyDown "Shift", 1
MoveTo 768, 494
Delay 36
KeyDown "Shift", 1
MoveTo 762, 463
Delay 34
KeyDown "Shift", 1
MoveTo 762, 418
Delay 33
KeyDown "Shift", 1
MoveTo 770, 387
Delay 36
KeyDown "Shift", 1
MoveTo 773, 367
Delay 33
KeyDown "Shift", 1
MoveTo 774, 364
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 4
Delay 30
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 40
Delay 3
KeyDown "Shift", 1
Delay 36
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 63
Delay 33
KeyDown "Shift", 1
MoveTo 771, 388
Delay 2
KeyDown "Shift", 1
MoveTo 769, 400
Delay 32
KeyDown "Shift", 1
MoveTo 768, 404
Delay 35
KeyDown "Shift", 1
Delay 64
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 35
Delay 30
Delay 2
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 32
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 1
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 30
Delay 2
KeyUp "Shift", 1
MoveTo 769, 419
Delay 366
KeyDown "M", 1
MoveTo 862, 451
Delay 166
KeyUp "M", 1
MoveTo 1292, 494
Delay 333
KeyDown "Ctrl", 1
MoveTo 1347, 477
Delay 502
KeyDown "Ctrl", 1
Delay 32
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 35
Delay 31
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 106
KeyDown "Ctrl", 1
Delay 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 687, 470
Delay 2548
KeyDown "Shift", 1
MoveTo 730, 366
Delay 504
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 35
KeyDown "Shift", 1
Delay 36
Delay 49
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 3
KeyDown "Shift", 1
MoveTo 731, 369
Delay 33
KeyDown "Shift", 1
MoveTo 731, 396
Delay 33
KeyDown "Shift", 1
MoveTo 733, 410
Delay 32
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 35
KeyDown "Shift", 1
Delay 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 31
Delay 32
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 2
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 31
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 766, 432
Delay 233
KeyDown "M", 1
MoveTo 969, 494
Delay 165
KeyUp "M", 1
MoveTo 1221, 516
Delay 268
KeyDown "Ctrl", 1
MoveTo 1378, 532
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
Delay 9
KeyDown "Ctrl", 1
Delay 26
Delay 33
KeyDown "Ctrl", 1
Delay 92
Delay 32
KeyDown "Ctrl", 1
Delay 58
MoveTo 1379, 532
Delay 2
KeyDown "Ctrl", 1
Delay 59
MoveTo 1380, 532
Delay 4
KeyDown "Ctrl", 1
Delay 29
Delay 60
KeyDown "Ctrl", 1
Delay 34
MoveTo 1376, 533
Delay 4
KeyDown "Ctrl", 1
Delay 10
Delay 2
KeyDown "Ctrl", 1
MoveTo 1372, 533
Delay 19
KeyUp "Ctrl", 1
MoveTo 715, 409
Delay 2424
KeyDown "Shift", 1
MoveTo 783, 361
Delay 389
LeftClick 1
Delay 70
KeyDown "Shift", 1
Delay 48
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 773, 387
Delay 33
KeyDown "Shift", 1
MoveTo 762, 409
Delay 32
KeyDown "Shift", 1
MoveTo 759, 425
Delay 33
KeyDown "Shift", 1
MoveTo 758, 427
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 40
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 32
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 35
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 42
Delay 34
KeyDown "Shift", 1
MoveTo 758, 431
Delay 34
KeyUp "Shift", 1
MoveTo 812, 464
Delay 350
KeyDown "M", 1
MoveTo 998, 522
Delay 164
KeyUp "M", 1
MoveTo 1201, 575
Delay 267
KeyDown "Ctrl", 1
MoveTo 1387, 536
Delay 502
KeyDown "Ctrl", 1
MoveTo 1389, 534
Delay 32
KeyDown "Ctrl", 1
MoveTo 1389, 533
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
MoveTo 1390, 533
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
MoveTo 1394, 534
Delay 32
KeyDown "Ctrl", 1
MoveTo 1399, 538
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 3
Delay 65
KeyDown "Ctrl", 1
Delay 2
Delay 64
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 1400, 538
Delay 35
KeyDown "Ctrl", 1
MoveTo 1400, 539
Delay 32
KeyDown "Ctrl", 1
MoveTo 1401, 540
Delay 35
KeyDown "Ctrl", 1
MoveTo 1402, 541
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
MoveTo 1401, 546
Delay 34
KeyDown "Ctrl", 1
MoveTo 1387, 557
Delay 34
KeyDown "Ctrl", 1
MoveTo 1375, 564
Delay 34
KeyDown "Ctrl", 1
MoveTo 1374, 564
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 1373, 561
Delay 34
KeyDown "Ctrl", 1
MoveTo 1372, 560
Delay 32
KeyDown "Ctrl", 1
MoveTo 1371, 559
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 3
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 62
Delay 34
KeyDown "Ctrl", 1
Delay 90
Delay 34
KeyDown "Ctrl", 1
Delay 16
Delay 1
KeyDown "Ctrl", 1
Delay 17
Delay 2
KeyUp "Ctrl", 1
MoveTo 734, 410
Delay 2480
KeyDown "Shift", 1
MoveTo 756, 425
Delay 500
KeyDown "Shift", 1
Delay 34
MoveTo 756, 424
Delay 34
KeyDown "Shift", 1
Delay 45
Delay 30
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 28
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 1
Delay 33
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 1
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 35
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
Delay 306
KeyDown "M", 1
MoveTo 827, 434
Delay 196
KeyUp "M", 1
MoveTo 1421, 514
Delay 698
KeyDown "Ctrl", 1
MoveTo 1409, 512
Delay 501
KeyDown "Ctrl", 1
MoveTo 1408, 512
Delay 32
KeyDown "Ctrl", 1
MoveTo 1407, 512
Delay 34
KeyDown "Ctrl", 1
MoveTo 1405, 512
Delay 35
KeyDown "Ctrl", 1
MoveTo 1403, 512
Delay 32
KeyDown "Ctrl", 1
MoveTo 1398, 512
Delay 33
KeyDown "Ctrl", 1
MoveTo 1397, 512
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 8
RightDown 1
Delay 6
KeyDown "Ctrl", 1
Delay 55
Delay 5
KeyDown "Ctrl", 1
Delay 59
Delay 33
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 120
Delay 32
KeyDown "Ctrl", 1
Delay 10
Delay 4
KeyDown "Ctrl", 1
Delay 19
KeyUp "Ctrl", 1
MoveTo 746, 393
Delay 2670
KeyDown "Shift", 1
MoveTo 770, 364
Delay 516
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 770, 363
Delay 37
KeyDown "Shift", 1
MoveTo 767, 365
Delay 37
KeyDown "Shift", 1
MoveTo 762, 373
Delay 30
KeyDown "Shift", 1
MoveTo 760, 377
Delay 32
KeyDown "Shift", 1
MoveTo 760, 378
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 762, 377
Delay 35
KeyDown "Shift", 1
MoveTo 766, 370
Delay 32
KeyDown "Shift", 1
MoveTo 767, 366
Delay 34
KeyDown "Shift", 1
MoveTo 767, 365
Delay 2
KeyDown "Shift", 1
Delay 64
Delay 67
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 35
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 32
KeyDown "Shift", 1
Delay 3
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 31
KeyDown "Shift", 1
Delay 33
MoveTo 768, 365
Delay 34
KeyDown "Shift", 1
MoveTo 777, 388
Delay 34
KeyDown "Shift", 1
MoveTo 780, 411
Delay 33
KeyDown "Shift", 1
MoveTo 780, 417
Delay 34
KeyDown "Shift", 1
Delay 36
MoveTo 780, 418
Delay 34
KeyDown "Shift", 1
Delay 34
MoveTo 780, 419
Delay 36
KeyDown "Shift", 1
MoveTo 780, 417
Delay 35
KeyDown "Shift", 1
MoveTo 780, 413
Delay 30
KeyDown "Shift", 1
MoveTo 780, 408
Delay 36
KeyDown "Shift", 1
MoveTo 780, 407
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 32
KeyDown "Shift", 1
Delay 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 39
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 38
MoveTo 780, 406
Delay 39
KeyDown "Shift", 1
MoveTo 783, 406
Delay 4
KeyDown "Shift", 1
MoveTo 791, 408
Delay 30
KeyDown "Shift", 1
MoveTo 803, 411
Delay 33
KeyDown "Shift", 1
MoveTo 850, 423
Delay 35
KeyDown "Shift", 1
MoveTo 908, 437
Delay 33
KeyDown "Shift", 1
MoveTo 938, 443
Delay 33
KeyUp "Shift", 1
MoveTo 988, 485
Delay 2603
KeyDown "M", 1
Delay 165
KeyUp "M", 1
MoveTo 1387, 524
Delay 331
KeyDown "Ctrl", 1
MoveTo 1503, 567
Delay 501
KeyDown "Ctrl", 1
MoveTo 1499, 567
Delay 34
KeyDown "Ctrl", 1
MoveTo 1498, 567
Delay 33
KeyDown "Ctrl", 1
MoveTo 1489, 566
Delay 34
KeyDown "Ctrl", 1
MoveTo 1482, 564
Delay 33
KeyDown "Ctrl", 1
MoveTo 1476, 562
Delay 32
KeyDown "Ctrl", 1
MoveTo 1475, 562
Delay 33
KeyDown "Ctrl", 1
MoveTo 1471, 562
Delay 35
KeyDown "Ctrl", 1
MoveTo 1466, 566
Delay 32
KeyDown "Ctrl", 1
MoveTo 1463, 573
Delay 35
KeyDown "Ctrl", 1
MoveTo 1459, 585
Delay 31
KeyDown "Ctrl", 1
MoveTo 1461, 603
Delay 34
KeyDown "Ctrl", 1
MoveTo 1466, 615
Delay 33
KeyDown "Ctrl", 1
MoveTo 1467, 617
Delay 35
KeyDown "Ctrl", 1
Delay 31
MoveTo 1468, 618
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 1465, 616
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 37
KeyDown "Ctrl", 1
Delay 30
MoveTo 1464, 614
Delay 33
KeyDown "Ctrl", 1
MoveTo 1461, 612
Delay 34
KeyDown "Ctrl", 1
MoveTo 1456, 608
Delay 33
KeyDown "Ctrl", 1
MoveTo 1453, 604
Delay 34
KeyDown "Ctrl", 1
MoveTo 1452, 602
Delay 32
KeyDown "Ctrl", 1
MoveTo 1451, 602
Delay 5
KeyDown "Ctrl", 1
Delay 62
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 67
Delay 1
KeyDown "Ctrl", 1
Delay 62
Delay 1
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 30
Delay 37
KeyDown "Ctrl", 1
Delay 108
Delay 52
KeyDown "Ctrl", 1
Delay 33
Delay 14
KeyDown "Ctrl", 1
Delay 1
Delay 18
KeyUp "Ctrl", 1
MoveTo 921, 446
Delay 2552
KeyDown "Shift", 1
MoveTo 719, 354
Delay 511
KeyDown "Shift", 1
Delay 31
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
MoveTo 720, 356
Delay 34
KeyDown "Shift", 1
MoveTo 729, 369
Delay 34
KeyDown "Shift", 1
MoveTo 740, 387
Delay 34
KeyDown "Shift", 1
MoveTo 748, 405
Delay 33
KeyDown "Shift", 1
MoveTo 750, 414
Delay 34
KeyDown "Shift", 1
MoveTo 750, 415
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
MoveTo 751, 416
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 36
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
MoveTo 751, 417
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
MoveTo 750, 416
Delay 35
KeyDown "Shift", 1
MoveTo 749, 415
Delay 35
KeyDown "Shift", 1
MoveTo 752, 411
Delay 34
KeyDown "Shift", 1
MoveTo 774, 408
Delay 34
KeyDown "Shift", 1
MoveTo 821, 408
Delay 1
KeyUp "Shift", 1
MoveTo 863, 412
Delay 598
KeyDown "M", 1
MoveTo 879, 410
Delay 100
KeyUp "M", 1
MoveTo 1411, 468
Delay 433
KeyDown "Ctrl", 1
MoveTo 1407, 534
Delay 533
KeyDown "Ctrl", 1
Delay 33
MoveTo 1408, 534
Delay 2
RightDown 1
MoveTo 1409, 534
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 34
Delay 30
KeyDown "Ctrl", 1
Delay 83
Delay 33
KeyDown "Ctrl", 1
Delay 44
Delay 5
KeyDown "Ctrl", 1
Delay 1
Delay 29
KeyUp "Ctrl", 1
MoveTo 702, 318
Delay 2562
KeyDown "Shift", 1
MoveTo 705, 338
Delay 300
LeftDoubleClick 1
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 41
Delay 33
KeyDown "Shift", 1
MoveTo 710, 353
Delay 34
KeyDown "Shift", 1
MoveTo 718, 367
Delay 34
KeyDown "Shift", 1
MoveTo 719, 373
Delay 33
KeyDown "Shift", 1
MoveTo 719, 376
Delay 35
KeyDown "Shift", 1
MoveTo 719, 379
Delay 31
KeyDown "Shift", 1
MoveTo 719, 383
Delay 32
KeyDown "Shift", 1
MoveTo 719, 385
Delay 34
KeyDown "Shift", 1
MoveTo 719, 388
Delay 33
KeyDown "Shift", 1
MoveTo 719, 392
Delay 34
KeyDown "Shift", 1
MoveTo 719, 398
Delay 34
KeyDown "Shift", 1
MoveTo 717, 408
Delay 33
KeyDown "Shift", 1
MoveTo 717, 416
Delay 38
KeyDown "Shift", 1
MoveTo 717, 419
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 29
MoveTo 717, 420
Delay 33
KeyDown "Shift", 1
MoveTo 731, 417
Delay 35
KeyDown "Shift", 1
MoveTo 733, 417
Delay 33
KeyDown "Shift", 1
MoveTo 737, 417
Delay 32
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
MoveTo 738, 417
Delay 467
KeyDown "M", 1
MoveTo 838, 430
Delay 132
KeyUp "M", 1
MoveTo 1312, 467
Delay 334
KeyDown "Ctrl", 1
MoveTo 1400, 548
Delay 531
KeyDown "Ctrl", 1
MoveTo 1410, 557
Delay 36
KeyDown "Ctrl", 1
MoveTo 1412, 559
Delay 32
KeyDown "Ctrl", 1
MoveTo 1413, 559
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 1415, 561
Delay 35
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
MoveTo 1416, 568
Delay 32
KeyDown "Ctrl", 1
MoveTo 1416, 573
Delay 34
RightClick 1
MoveTo 1416, 575
Delay 2
KeyDown "Ctrl", 1
MoveTo 1416, 576
Delay 30
KeyDown "Ctrl", 1
MoveTo 1416, 577
Delay 35
KeyDown "Ctrl", 1
Delay 96
MoveTo 1422, 573
Delay 52
KeyDown "Ctrl", 1
MoveTo 1423, 572
Delay 31
KeyDown "Ctrl", 1
MoveTo 1425, 571
Delay 34
KeyDown "Ctrl", 1
MoveTo 1425, 570
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
MoveTo 1425, 569
Delay 34
KeyDown "Ctrl", 1
MoveTo 1424, 568
Delay 3
KeyDown "Ctrl", 1
Delay 40
Delay 2
KeyDown "Ctrl", 1
MoveTo 1423, 567
Delay 21
KeyDown "Ctrl", 1
MoveTo 1422, 567
Delay 2
KeyUp "Ctrl", 1
MoveTo 651, 351
Delay 2118
KeyDown "Shift", 1
MoveTo 651, 356
Delay 532
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 40
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 652, 360
Delay 35
KeyDown "Shift", 1
MoveTo 656, 371
Delay 33
KeyDown "Shift", 1
MoveTo 659, 382
Delay 33
KeyDown "Shift", 1
MoveTo 659, 392
Delay 33
KeyDown "Shift", 1
MoveTo 660, 397
Delay 33
KeyDown "Shift", 1
MoveTo 660, 399
Delay 33
KeyDown "Shift", 1
MoveTo 660, 400
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 664, 400
Delay 34
KeyDown "Shift", 1
MoveTo 670, 391
Delay 33
KeyDown "Shift", 1
MoveTo 675, 383
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
MoveTo 676, 383
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 676, 384
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 680, 382
Delay 35
KeyDown "Shift", 1
MoveTo 687, 367
Delay 32
KeyDown "Shift", 1
MoveTo 690, 360
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 8
KeyDown "Shift", 1
Delay 28
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 696, 372
Delay 36
KeyDown "Shift", 1
MoveTo 706, 398
Delay 33
KeyDown "Shift", 1
MoveTo 717, 432
Delay 34
KeyDown "Shift", 1
MoveTo 717, 443
Delay 32
KeyDown "Shift", 1
MoveTo 717, 444
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
MoveTo 717, 443
Delay 37
KeyDown "Shift", 1
MoveTo 717, 441
Delay 33
KeyDown "Shift", 1
MoveTo 717, 440
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 717, 439
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 718, 437
Delay 34
KeyDown "Shift", 1
MoveTo 720, 430
Delay 2
KeyDown "Shift", 1
MoveTo 723, 424
Delay 33
KeyDown "Shift", 1
MoveTo 723, 423
Delay 33
KeyDown "Shift", 1
Delay 65
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 30
Delay 32
KeyDown "Shift", 1
Delay 2
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 31
KeyDown "Shift", 1
Delay 35
KeyUp "Shift", 1
MoveTo 718, 431
Delay 433
KeyDown "M", 1
MoveTo 729, 439
Delay 164
KeyUp "M", 1
MoveTo 1379, 530
Delay 366
KeyDown "Ctrl", 1
MoveTo 1498, 521
Delay 500
KeyDown "Ctrl", 1
MoveTo 1492, 521
Delay 34
KeyDown "Ctrl", 1
MoveTo 1485, 521
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 3
RightDown 1
Delay 29
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 4
Delay 74
KeyDown "Ctrl", 1
Delay 1
Delay 45
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 1084, 295
Delay 2794
KeyDown "Shift", 1
MoveTo 834, 356
Delay 526
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 38
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 30
Delay 30
KeyDown "Shift", 1
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
MoveTo 834, 357
Delay 35
KeyDown "Shift", 1
MoveTo 834, 353
Delay 32
KeyDown "Shift", 1
MoveTo 833, 352
Delay 33
KeyDown "Shift", 1
MoveTo 833, 351
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 832, 350
Delay 35
KeyDown "Shift", 1
MoveTo 831, 346
Delay 33
KeyDown "Shift", 1
MoveTo 831, 344
Delay 34
KeyDown "Shift", 1
MoveTo 830, 342
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 34
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 40
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 2
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 30
Delay 2
KeyUp "Shift", 1
MoveTo 851, 344
Delay 365
KeyDown "M", 1
MoveTo 954, 361
Delay 129
KeyUp "M", 1
MoveTo 1525, 530
Delay 935
KeyDown "Ctrl", 1
MoveTo 1519, 523
Delay 231
RightDown 1
Delay 133
RightClick 1
Delay 151
KeyDown "Ctrl", 1
Delay 23
Delay 2
KeyDown "Ctrl", 1
Delay 9
Delay 1
KeyUp "Ctrl", 1
MoveTo 688, 353
Delay 2562
KeyDown "Shift", 1
MoveTo 725, 361
Delay 505
KeyDown "Shift", 1
Delay 45
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 1
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 727, 354
Delay 33
KeyDown "Shift", 1
MoveTo 728, 347
Delay 33
KeyDown "Shift", 1
MoveTo 732, 341
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 732, 340
Delay 35
KeyDown "Shift", 1
MoveTo 732, 337
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 733, 336
Delay 35
KeyDown "Shift", 1
MoveTo 735, 359
Delay 33
KeyDown "Shift", 1
MoveTo 736, 386
Delay 34
KeyDown "Shift", 1
MoveTo 736, 406
Delay 33
KeyDown "Shift", 1
MoveTo 736, 413
Delay 33
KeyDown "Shift", 1
MoveTo 737, 415
Delay 34
KeyDown "Shift", 1
MoveTo 737, 418
Delay 33
KeyDown "Shift", 1
MoveTo 738, 419
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 37
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 740, 421
Delay 33
KeyDown "Shift", 1
MoveTo 858, 441
Delay 34
KeyDown "Shift", 1
MoveTo 975, 470
Delay 32
KeyDown "Shift", 1
MoveTo 1033, 488
Delay 33
KeyUp "Shift", 1
MoveTo 1073, 494
Delay 467
KeyDown "M", 1
MoveTo 1118, 495
Delay 159
KeyUp "M", 1
MoveTo 1559, 502
Delay 701
KeyDown "Ctrl", 1
MoveTo 1537, 502
Delay 366
RightDown 1
Delay 99
RightClick 1
Delay 72
KeyDown "Ctrl", 1
Delay 87
Delay 1
KeyDown "Ctrl", 1
Delay 22
Delay 2
KeyUp "Ctrl", 1
MoveTo 1026, 386
Delay 3260
KeyDown "Shift", 1
MoveTo 853, 351
Delay 513
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 35
KeyDown "Shift", 1
MoveTo 849, 353
Delay 34
KeyDown "Shift", 1
MoveTo 839, 366
Delay 33
KeyDown "Shift", 1
MoveTo 824, 377
Delay 33
KeyDown "Shift", 1
MoveTo 802, 392
Delay 36
KeyDown "Shift", 1
MoveTo 774, 403
Delay 33
KeyDown "Shift", 1
MoveTo 765, 411
Delay 34
KeyDown "Shift", 1
MoveTo 761, 416
Delay 35
KeyDown "Shift", 1
MoveTo 760, 417
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 32
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 1
Delay 36
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 765, 421
Delay 66
KeyDown "Shift", 1
MoveTo 773, 449
Delay 35
KeyDown "Shift", 1
MoveTo 771, 463
Delay 34
KeyDown "Shift", 1
MoveTo 770, 469
Delay 31
KeyDown "Shift", 1
MoveTo 770, 470
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 43
Delay 36
KeyDown "Shift", 1
Delay 39
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 779, 475
Delay 37
KeyDown "Shift", 1
MoveTo 789, 484
Delay 37
KeyDown "Shift", 1
MoveTo 792, 488
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 3
KeyUp "Shift", 1
MoveTo 796, 484
Delay 501
KeyDown "M", 1
MoveTo 921, 485
Delay 165
KeyUp "M", 1
MoveTo 1435, 500
Delay 303
KeyDown "Ctrl", 1
MoveTo 1536, 515
Delay 531
KeyDown "Ctrl", 1
MoveTo 1532, 512
Delay 33
KeyDown "Ctrl", 1
MoveTo 1529, 509
Delay 35
KeyDown "Ctrl", 1
MoveTo 1527, 507
Delay 32
KeyDown "Ctrl", 1
MoveTo 1526, 506
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 3
RightDown 1
Delay 4
KeyDown "Ctrl", 1
Delay 63
Delay 1
KeyDown "Ctrl", 1
Delay 64
Delay 1
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 30
MoveTo 1526, 507
Delay 35
KeyDown "Ctrl", 1
Delay 99
Delay 35
KeyDown "Ctrl", 1
Delay 11
Delay 1
KeyDown "Ctrl", 1
Delay 19
KeyUp "Ctrl", 1
MoveTo 1523, 508
Delay 2406
KeyDown "Shift", 1
MoveTo 682, 356
Delay 476
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 38
Delay 46
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
MoveTo 687, 350
Delay 34
KeyDown "Shift", 1
MoveTo 697, 336
Delay 34
KeyDown "Shift", 1
MoveTo 699, 332
Delay 34
KeyDown "Shift", 1
MoveTo 699, 331
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 34
MoveTo 699, 330
Delay 34
KeyDown "Shift", 1
MoveTo 699, 328
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 37
KeyDown "Shift", 1
Delay 4
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
MoveTo 700, 329
Delay 33
KeyDown "Shift", 1
MoveTo 703, 345
Delay 35
KeyDown "Shift", 1
MoveTo 713, 364
Delay 35
KeyDown "Shift", 1
MoveTo 719, 372
Delay 32
KeyDown "Shift", 1
MoveTo 722, 377
Delay 37
KeyDown "Shift", 1
MoveTo 725, 381
Delay 38
KeyDown "Shift", 1
MoveTo 727, 386
Delay 32
KeyDown "Shift", 1
MoveTo 729, 395
Delay 33
KeyDown "Shift", 1
MoveTo 731, 399
Delay 33
KeyDown "Shift", 1
MoveTo 732, 400
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 733, 401
Delay 34
KeyDown "Shift", 1
MoveTo 734, 406
Delay 37
KeyDown "Shift", 1
MoveTo 734, 413
Delay 34
KeyDown "Shift", 1
MoveTo 734, 415
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 4
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 31
KeyDown "Shift", 1
Delay 2
Delay 36
KeyDown "Shift", 1
Delay 35
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 733, 416
Delay 366
KeyDown "M", 1
Delay 131
KeyUp "M", 1
MoveTo 1506, 532
Delay 834
KeyDown "Ctrl", 1
MoveTo 1488, 529
Delay 267
RightDown 1
Delay 132
RightClick 1
Delay 161
KeyDown "Ctrl", 1
Delay 22
KeyDown "Ctrl", 1
Delay 12
Delay 2
KeyUp "Ctrl", 1
MoveTo 797, 321
Delay 2871
KeyDown "Shift", 1
Delay 207
LeftDoubleClick 1
Delay 102
MoveTo 797, 322
Delay 35
KeyDown "Shift", 1
MoveTo 801, 336
Delay 32
KeyDown "Shift", 1
MoveTo 809, 362
Delay 34
KeyDown "Shift", 1
MoveTo 809, 384
Delay 33
KeyDown "Shift", 1
MoveTo 804, 401
Delay 39
KeyDown "Shift", 1
MoveTo 798, 415
Delay 33
KeyDown "Shift", 1
MoveTo 796, 422
Delay 34
KeyDown "Shift", 1
MoveTo 795, 424
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 794, 425
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 1
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 2
Delay 34
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 2
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 793, 425
Delay 32
KeyDown "Shift", 1
MoveTo 793, 423
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 793, 427
Delay 401
KeyDown "M", 1
MoveTo 886, 442
Delay 166
KeyUp "M", 1
MoveTo 1653, 482
Delay 368
KeyDown "Ctrl", 1
MoveTo 1570, 517
Delay 534
KeyDown "Ctrl", 1
MoveTo 1568, 518
Delay 2
KeyDown "Ctrl", 1
MoveTo 1567, 519
Delay 32
KeyDown "Ctrl", 1
MoveTo 1563, 522
Delay 34
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 3
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 96
KeyDown "Ctrl", 1
Delay 29
Delay 55
KeyDown "Ctrl", 1
Delay 8
Delay 51
KeyUp "Ctrl", 1
MoveTo 1275, 441
Delay 2534
KeyDown "Shift", 1
MoveTo 894, 338
Delay 500
KeyDown "Shift", 1
Delay 34
Delay 44
KeyDown "Shift", 1
Delay 32
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
MoveTo 892, 338
Delay 32
KeyDown "Shift", 1
MoveTo 871, 352
Delay 33
KeyDown "Shift", 1
MoveTo 854, 362
Delay 34
KeyDown "Shift", 1
MoveTo 837, 368
Delay 33
KeyDown "Shift", 1
MoveTo 836, 368
Delay 34
KeyDown "Shift", 1
MoveTo 835, 368
Delay 35
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 833, 369
Delay 35
KeyDown "Shift", 1
MoveTo 828, 373
Delay 32
KeyDown "Shift", 1
MoveTo 827, 379
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 824, 385
Delay 34
KeyDown "Shift", 1
MoveTo 822, 394
Delay 33
KeyDown "Shift", 1
MoveTo 822, 397
Delay 33
KeyDown "Shift", 1
MoveTo 821, 407
Delay 4
KeyDown "Shift", 1
MoveTo 821, 412
Delay 33
KeyDown "Shift", 1
MoveTo 821, 413
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 4
LeftUp 1
Delay 55
KeyDown "Shift", 1
Delay 38
Delay 2
KeyDown "Shift", 1
Delay 41
Delay 38
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 822, 417
Delay 373
KeyDown "M", 1
MoveTo 998, 448
Delay 170
KeyUp "M", 1
MoveTo 1633, 516
Delay 333
KeyDown "Ctrl", 1
MoveTo 1545, 532
Delay 535
KeyDown "Ctrl", 1
MoveTo 1540, 533
Delay 32
KeyDown "Ctrl", 1
MoveTo 1537, 533
Delay 33
KeyDown "Ctrl", 1
MoveTo 1531, 535
Delay 38
KeyDown "Ctrl", 1
MoveTo 1530, 535
Delay 2
KeyDown "Ctrl", 1
MoveTo 1529, 536
Delay 60
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 5
KeyDown "Ctrl", 1
Delay 60
Delay 36
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 62
Delay 2
KeyDown "Ctrl", 1
Delay 97
KeyDown "Ctrl", 1
Delay 6
Delay 2
KeyUp "Ctrl", 1
MoveTo 733, 355
Delay 2596
KeyDown "Shift", 1
MoveTo 731, 343
Delay 265
LeftDoubleClick 1
Delay 73
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 36
KeyDown "Shift", 1
MoveTo 734, 356
Delay 35
KeyDown "Shift", 1
MoveTo 734, 357
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 49
Delay 1
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 37
Delay 39
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 2
Delay 38
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
MoveTo 752, 380
Delay 407
KeyDown "M", 1
MoveTo 1009, 430
Delay 171
KeyUp "M", 1
MoveTo 1428, 525
Delay 301
KeyDown "Ctrl", 1
MoveTo 1541, 592
Delay 498
KeyDown "Ctrl", 1
MoveTo 1540, 590
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 38
Delay 29
KeyDown "Ctrl", 1
MoveTo 1540, 589
Delay 34
KeyDown "Ctrl", 1
MoveTo 1539, 589
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 31
KeyDown "Ctrl", 1
Delay 36
Delay 30
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 38
Delay 2
KeyDown "Ctrl", 1
Delay 60
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 1559, 585
Delay 34
KeyDown "Ctrl", 1
MoveTo 1575, 580
Delay 33
KeyDown "Ctrl", 1
MoveTo 1580, 579
Delay 33
KeyDown "Ctrl", 1
MoveTo 1588, 579
Delay 33
KeyDown "Ctrl", 1
MoveTo 1598, 577
Delay 34
KeyDown "Ctrl", 1
MoveTo 1603, 575
Delay 33
KeyDown "Ctrl", 1
MoveTo 1606, 569
Delay 33
KeyDown "Ctrl", 1
MoveTo 1608, 565
Delay 34
KeyDown "Ctrl", 1
MoveTo 1610, 559
Delay 36
KeyDown "Ctrl", 1
MoveTo 1614, 554
Delay 32
KeyDown "Ctrl", 1
MoveTo 1618, 551
Delay 32
KeyDown "Ctrl", 1
MoveTo 1622, 551
Delay 33
KeyDown "Ctrl", 1
MoveTo 1628, 551
Delay 34
KeyDown "Ctrl", 1
MoveTo 1634, 549
Delay 33
KeyDown "Ctrl", 1
MoveTo 1636, 549
Delay 34
KeyDown "Ctrl", 1
Delay 31
MoveTo 1636, 548
Delay 36
KeyDown "Ctrl", 1
MoveTo 1636, 547
Delay 32
KeyDown "Ctrl", 1
MoveTo 1636, 546
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 1640, 542
Delay 35
KeyDown "Ctrl", 1
MoveTo 1648, 538
Delay 35
KeyDown "Ctrl", 1
MoveTo 1653, 534
Delay 30
KeyDown "Ctrl", 1
MoveTo 1654, 533
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 7
Delay 61
KeyDown "Ctrl", 1
MoveTo 1654, 532
Delay 36
KeyDown "Ctrl", 1
Delay 2
MoveTo 1651, 532
Delay 60
KeyDown "Ctrl", 1
MoveTo 1650, 531
Delay 4
KeyDown "Ctrl", 1
MoveTo 1648, 531
Delay 65
KeyDown "Ctrl", 1
MoveTo 1645, 528
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 6
RightClick 1
Delay 28
KeyDown "Ctrl", 1
Delay 34
Delay 107
KeyDown "Ctrl", 1
Delay 57
Delay 60
KeyDown "Ctrl", 1
MoveTo 1645, 529
Delay 3
KeyDown "Ctrl", 1
MoveTo 1645, 530
Delay 31
KeyDown "Ctrl", 1
Delay 9
Delay 1
KeyDown "Ctrl", 1
MoveTo 1645, 532
Delay 24
KeyUp "Ctrl", 1
MoveTo 755, 412
Delay 2309
KeyDown "Shift", 1
MoveTo 747, 369
Delay 514
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 50
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 37
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 2
Delay 35
KeyDown "Shift", 1
Delay 2
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 40
Delay 33
KeyDown "Shift", 1
MoveTo 748, 370
Delay 36
KeyDown "Shift", 1
MoveTo 753, 384
Delay 34
KeyDown "Shift", 1
MoveTo 756, 397
Delay 33
KeyDown "Shift", 1
MoveTo 760, 410
Delay 41
KeyDown "Shift", 1
MoveTo 763, 417
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 2
KeyDown "Shift", 1
Delay 32
MoveTo 766, 417
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 39
Delay 40
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 4
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 38
KeyUp "Shift", 1
MoveTo 778, 430
Delay 369
KeyDown "M", 1
MoveTo 942, 463
Delay 167
KeyUp "M", 1
MoveTo 1466, 540
Delay 333
KeyDown "Ctrl", 1
MoveTo 1596, 512
Delay 502
KeyDown "Ctrl", 1
MoveTo 1598, 512
Delay 32
KeyDown "Ctrl", 1
Delay 36
Delay 33
KeyDown "Ctrl", 1
MoveTo 1599, 511
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 1599, 508
Delay 35
KeyDown "Ctrl", 1
MoveTo 1599, 507
Delay 9
KeyDown "Ctrl", 1
MoveTo 1598, 506
Delay 56
KeyDown "Ctrl", 1
MoveTo 1598, 505
Delay 3
KeyDown "Ctrl", 1
MoveTo 1597, 504
Delay 67
KeyDown "Ctrl", 1
Delay 31
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 66
Delay 4
KeyDown "Ctrl", 1
Delay 63
MoveTo 1597, 503
Delay 1
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 31
KeyDown "Ctrl", 1
Delay 109
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 31
KeyDown "Ctrl", 1
Delay 2
Delay 2
KeyUp "Ctrl", 1
MoveTo 877, 363
Delay 1523
KeyDown "Shift", 1
MoveTo 920, 289
Delay 532
KeyDown "Shift", 1
MoveTo 921, 279
Delay 34
KeyDown "Shift", 1
MoveTo 921, 267
Delay 35
KeyDown "Shift", 1
MoveTo 921, 255
Delay 32
KeyDown "Shift", 1
MoveTo 919, 247
Delay 36
KeyDown "Shift", 1
MoveTo 918, 242
Delay 3
KeyDown "Shift", 1
MoveTo 917, 241
Delay 60
KeyUp "Shift", 1
MoveTo 845, 240
Delay 975
KeyDown "Shift", 1
MoveTo 794, 330
Delay 502
LeftDown 1
Delay 2
KeyDown "Shift", 1
MoveTo 794, 331
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 33
Delay 54
KeyDown "Shift", 1
Delay 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 37
MoveTo 793, 334
Delay 35
KeyDown "Shift", 1
MoveTo 789, 346
Delay 34
KeyDown "Shift", 1
MoveTo 783, 356
Delay 40
KeyDown "Shift", 1
MoveTo 778, 361
Delay 36
KeyDown "Shift", 1
MoveTo 773, 365
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 35
KeyDown "Shift", 1
Delay 37
Delay 35
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 2
LeftUp 1
MoveTo 772, 365
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 36
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 40
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
MoveTo 773, 365
Delay 375
KeyDown "M", 1
MoveTo 949, 391
Delay 167
KeyUp "M", 1
MoveTo 1437, 538
Delay 431
KeyDown "Ctrl", 1
MoveTo 1587, 658
Delay 500
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 1586, 659
Delay 36
KeyDown "Ctrl", 1
MoveTo 1579, 654
Delay 32
KeyDown "Ctrl", 1
MoveTo 1574, 649
Delay 33
KeyDown "Ctrl", 1
MoveTo 1572, 647
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 1570, 647
Delay 35
KeyDown "Ctrl", 1
MoveTo 1569, 646
Delay 32
KeyDown "Ctrl", 1
MoveTo 1568, 646
Delay 33
KeyDown "Ctrl", 1
MoveTo 1567, 645
Delay 34
KeyDown "Ctrl", 1
MoveTo 1566, 645
Delay 33
KeyDown "Ctrl", 1
MoveTo 1565, 644
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 1565, 642
Delay 33
KeyDown "Ctrl", 1
MoveTo 1563, 640
Delay 37
KeyDown "Ctrl", 1
MoveTo 1562, 640
Delay 30
KeyDown "Ctrl", 1
MoveTo 1561, 638
Delay 34
KeyDown "Ctrl", 1
MoveTo 1557, 637
Delay 34
KeyDown "Ctrl", 1
MoveTo 1555, 637
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 3
KeyDown "Ctrl", 1
Delay 63
Delay 33
KeyDown "Ctrl", 1
Delay 2
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 30
Delay 106
KeyDown "Ctrl", 1
Delay 36
Delay 34
KeyDown "Ctrl", 1
Delay 57
Delay 33
KeyDown "Ctrl", 1
Delay 36
Delay 32
KeyDown "Ctrl", 1
Delay 24
Delay 1
KeyDown "Ctrl", 1
Delay 6
KeyUp "Ctrl", 1
MoveTo 952, 402
Delay 2668
KeyDown "Shift", 1
MoveTo 830, 322
Delay 453
LeftDown 1
Delay 72
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 2
Delay 36
KeyDown "Shift", 1
Delay 37
Delay 4
LeftUp 1
Delay 3
KeyDown "Shift", 1
MoveTo 828, 331
Delay 34
KeyDown "Shift", 1
MoveTo 824, 351
Delay 33
KeyDown "Shift", 1
MoveTo 817, 366
Delay 34
KeyDown "Shift", 1
MoveTo 812, 372
Delay 34
KeyDown "Shift", 1
MoveTo 810, 374
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
MoveTo 809, 374
Delay 34
KeyDown "Shift", 1
MoveTo 809, 373
Delay 34
KeyDown "Shift", 1
MoveTo 812, 370
Delay 33
KeyDown "Shift", 1
MoveTo 813, 370
Delay 32
KeyDown "Shift", 1
Delay 36
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 814, 367
Delay 34
KeyDown "Shift", 1
MoveTo 815, 365
Delay 33
KeyDown "Shift", 1
MoveTo 815, 363
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 2
Delay 39
KeyDown "Shift", 1
Delay 36
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 36
MoveTo 809, 381
Delay 32
KeyDown "Shift", 1
MoveTo 806, 398
Delay 33
KeyDown "Shift", 1
MoveTo 804, 411
Delay 34
KeyDown "Shift", 1
MoveTo 801, 416
Delay 32
KeyDown "Shift", 1
MoveTo 800, 419
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 36
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 37
Delay 34
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 41
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 35
KeyUp "Shift", 1
Delay 400
KeyDown "M", 1
MoveTo 803, 420
Delay 170
KeyUp "M", 1
MoveTo 1233, 513
Delay 409
KeyDown "Ctrl", 1
MoveTo 1502, 555
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 37
KeyDown "Ctrl", 1
Delay 37
Delay 30
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 1502, 556
Delay 33
KeyDown "Ctrl", 1
MoveTo 1503, 557
Delay 34
KeyDown "Ctrl", 1
MoveTo 1500, 567
Delay 36
KeyDown "Ctrl", 1
MoveTo 1492, 577
Delay 32
KeyDown "Ctrl", 1
MoveTo 1487, 584
Delay 2
KeyDown "Ctrl", 1
MoveTo 1486, 587
Delay 63
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 1
Delay 65
KeyDown "Ctrl", 1
MoveTo 1485, 587
Delay 4
KeyDown "Ctrl", 1
MoveTo 1485, 585
Delay 32
KeyDown "Ctrl", 1
MoveTo 1485, 584
Delay 31
KeyDown "Ctrl", 1
Delay 35
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 1485, 583
Delay 34
KeyDown "Ctrl", 1
MoveTo 1494, 580
Delay 34
KeyDown "Ctrl", 1
MoveTo 1496, 579
Delay 35
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 36
Delay 104
KeyDown "Ctrl", 1
Delay 34
Delay 1
KeyDown "Ctrl", 1
Delay 64
Delay 3
KeyDown "Ctrl", 1
Delay 48
KeyUp "Ctrl", 1
MoveTo 838, 412
Delay 2569
KeyDown "Shift", 1
MoveTo 763, 361
Delay 511
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 42
Delay 41
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 1
Delay 52
Delay 2
KeyDown "Shift", 1
Delay 43
Delay 37
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 760, 357
Delay 35
KeyDown "Shift", 1
MoveTo 754, 349
Delay 36
KeyDown "Shift", 1
MoveTo 750, 344
Delay 35
KeyDown "Shift", 1
MoveTo 750, 342
Delay 32
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 37
Delay 40
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 2
Delay 37
KeyDown "Shift", 1
Delay 56
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
MoveTo 760, 365
Delay 38
KeyDown "Shift", 1
MoveTo 766, 387
Delay 1
KeyDown "Shift", 1
MoveTo 768, 396
Delay 35
KeyDown "Shift", 1
MoveTo 768, 401
Delay 33
KeyDown "Shift", 1
MoveTo 768, 405
Delay 34
KeyDown "Shift", 1
MoveTo 768, 410
Delay 36
KeyDown "Shift", 1
MoveTo 768, 414
Delay 35
KeyDown "Shift", 1
MoveTo 768, 416
Delay 38
KeyDown "Shift", 1
MoveTo 768, 417
Delay 33
KeyDown "Shift", 1
MoveTo 769, 417
Delay 34
KeyDown "Shift", 1
MoveTo 770, 418
Delay 33
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 2
KeyDown "Shift", 1
MoveTo 771, 419
Delay 38
KeyDown "Shift", 1
Delay 37
Delay 3
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 38
KeyDown "Shift", 1
Delay 37
Delay 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
Delay 568
KeyDown "M", 1
MoveTo 807, 415
Delay 167
KeyUp "M", 1
MoveTo 1420, 436
Delay 268
KeyDown "Ctrl", 1
MoveTo 1525, 431
Delay 500
KeyDown "Ctrl", 1
MoveTo 1520, 432
Delay 33
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
MoveTo 1516, 432
Delay 34
KeyDown "Ctrl", 1
MoveTo 1514, 431
Delay 33
KeyDown "Ctrl", 1
MoveTo 1511, 429
Delay 33
KeyDown "Ctrl", 1
MoveTo 1509, 426
Delay 38
KeyDown "Ctrl", 1
MoveTo 1507, 424
Delay 29
KeyDown "Ctrl", 1
MoveTo 1506, 423
Delay 35
KeyDown "Ctrl", 1
MoveTo 1506, 422
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 40
KeyDown "Ctrl", 1
Delay 27
Delay 32
KeyDown "Ctrl", 1
Delay 34
MoveTo 1508, 423
Delay 34
KeyDown "Ctrl", 1
MoveTo 1511, 426
Delay 34
KeyDown "Ctrl", 1
MoveTo 1513, 429
Delay 34
KeyDown "Ctrl", 1
MoveTo 1513, 431
Delay 34
KeyDown "Ctrl", 1
MoveTo 1514, 435
Delay 31
KeyDown "Ctrl", 1
MoveTo 1514, 438
Delay 35
KeyDown "Ctrl", 1
MoveTo 1515, 440
Delay 32
KeyDown "Ctrl", 1
MoveTo 1516, 443
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 1515, 443
Delay 34
KeyDown "Ctrl", 1
MoveTo 1512, 440
Delay 33
KeyDown "Ctrl", 1
MoveTo 1510, 435
Delay 33
KeyDown "Ctrl", 1
MoveTo 1506, 431
Delay 6
KeyDown "Ctrl", 1
MoveTo 1506, 430
Delay 61
KeyDown "Ctrl", 1
MoveTo 1505, 430
Delay 33
KeyDown "Ctrl", 1
MoveTo 1505, 429
Delay 1
KeyDown "Ctrl", 1
Delay 66
Delay 2
KeyDown "Ctrl", 1
MoveTo 1504, 428
Delay 32
KeyDown "Ctrl", 1
MoveTo 1492, 428
Delay 33
KeyDown "Ctrl", 1
MoveTo 1483, 428
Delay 33
KeyDown "Ctrl", 1
MoveTo 1476, 431
Delay 34
KeyDown "Ctrl", 1
MoveTo 1472, 440
Delay 34
KeyDown "Ctrl", 1
MoveTo 1472, 451
Delay 33
KeyDown "Ctrl", 1
MoveTo 1472, 460
Delay 33
KeyDown "Ctrl", 1
MoveTo 1472, 467
Delay 34
KeyDown "Ctrl", 1
MoveTo 1472, 473
Delay 34
KeyDown "Ctrl", 1
MoveTo 1472, 477
Delay 33
KeyDown "Ctrl", 1
MoveTo 1472, 479
Delay 33
KeyDown "Ctrl", 1
MoveTo 1472, 480
Delay 32
KeyDown "Ctrl", 1
MoveTo 1472, 481
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
MoveTo 1472, 482
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 1473, 483
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 33
MoveTo 1476, 484
Delay 35
KeyDown "Ctrl", 1
MoveTo 1484, 482
Delay 31
KeyDown "Ctrl", 1
MoveTo 1487, 480
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 1484, 481
Delay 35
KeyDown "Ctrl", 1
MoveTo 1474, 487
Delay 32
KeyDown "Ctrl", 1
MoveTo 1471, 490
Delay 36
KeyDown "Ctrl", 1
Delay 34
Delay 29
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 1466, 492
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 36
KeyDown "Ctrl", 1
Delay 33
MoveTo 1465, 492
Delay 31
KeyDown "Ctrl", 1
MoveTo 1464, 492
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
MoveTo 1463, 491
Delay 36
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 29
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 120
KeyDown "Ctrl", 1
Delay 36
Delay 30
KeyDown "Ctrl", 1
Delay 34
Delay 4
KeyDown "Ctrl", 1
Delay 2
Delay 28
KeyUp "Ctrl", 1
MoveTo 1191, 472
Delay 2374
KeyDown "Shift", 1
MoveTo 800, 335
Delay 516
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 53
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
MoveTo 799, 337
Delay 36
KeyDown "Shift", 1
MoveTo 795, 355
Delay 35
KeyDown "Shift", 1
MoveTo 794, 366
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 38
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
MoveTo 794, 367
Delay 34
KeyDown "Shift", 1
MoveTo 798, 376
Delay 34
KeyDown "Shift", 1
MoveTo 805, 398
Delay 34
KeyDown "Shift", 1
MoveTo 806, 412
Delay 33
KeyDown "Shift", 1
MoveTo 806, 416
Delay 5
KeyDown "Shift", 1
Delay 65
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 36
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
Delay 405
KeyDown "M", 1
MoveTo 830, 432
Delay 167
KeyUp "M", 1
MoveTo 1390, 495
Delay 535
KeyDown "Ctrl", 1
Delay 329
Delay 1
KeyDown "Ctrl", 1
MoveTo 1405, 516
Delay 2
KeyUp "Ctrl", 1
MoveTo 1406, 520
Delay 132
KeyDown "Ctrl", 1
MoveTo 1392, 502
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 1395, 498
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 118
Delay 59
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
Delay 4
Delay 87
KeyDown "Ctrl", 1
Delay 13
Delay 1
KeyDown "Ctrl", 1
Delay 19
Delay 1
KeyUp "Ctrl", 1
MoveTo 980, 402
Delay 2489
KeyDown "Shift", 1
MoveTo 907, 362
Delay 510
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
MoveTo 903, 360
Delay 34
KeyDown "Shift", 1
MoveTo 883, 356
Delay 34
KeyDown "Shift", 1
MoveTo 814, 343
Delay 34
KeyDown "Shift", 1
MoveTo 797, 338
Delay 33
KeyDown "Shift", 1
MoveTo 796, 337
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 796, 336
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 30
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 38
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 3
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 36
MoveTo 802, 343
Delay 34
KeyDown "Shift", 1
MoveTo 810, 357
Delay 36
KeyDown "Shift", 1
MoveTo 814, 371
Delay 33
KeyDown "Shift", 1
MoveTo 815, 378
Delay 35
KeyDown "Shift", 1
MoveTo 816, 383
Delay 32
KeyDown "Shift", 1
MoveTo 816, 391
Delay 37
KeyDown "Shift", 1
MoveTo 809, 396
Delay 33
KeyDown "Shift", 1
MoveTo 803, 400
Delay 38
KeyDown "Shift", 1
MoveTo 799, 403
Delay 32
KeyDown "Shift", 1
MoveTo 796, 406
Delay 33
KeyDown "Shift", 1
MoveTo 796, 409
Delay 34
KeyDown "Shift", 1
MoveTo 795, 410
Delay 32
KeyDown "Shift", 1
Delay 4
Delay 64
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 37
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
MoveTo 798, 416
Delay 373
KeyDown "M", 1
MoveTo 883, 441
Delay 145
KeyUp "M", 1
MoveTo 1294, 518
Delay 299
KeyDown "Ctrl", 1
MoveTo 1410, 582
Delay 500
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 1410, 583
Delay 33
KeyDown "Ctrl", 1
MoveTo 1410, 584
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 37
KeyDown "Ctrl", 1
Delay 28
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 1450, 551
Delay 34
KeyDown "Ctrl", 1
MoveTo 1484, 519
Delay 34
KeyDown "Ctrl", 1
MoveTo 1505, 502
Delay 4
KeyDown "Ctrl", 1
MoveTo 1511, 496
Delay 31
KeyDown "Ctrl", 1
MoveTo 1510, 492
Delay 66
KeyDown "Ctrl", 1
MoveTo 1507, 489
Delay 1
KeyDown "Ctrl", 1
MoveTo 1504, 487
Delay 31
KeyDown "Ctrl", 1
MoveTo 1500, 485
Delay 33
KeyDown "Ctrl", 1
MoveTo 1496, 482
Delay 33
KeyDown "Ctrl", 1
MoveTo 1490, 480
Delay 34
KeyDown "Ctrl", 1
MoveTo 1482, 478
Delay 34
KeyDown "Ctrl", 1
MoveTo 1479, 476
Delay 32
KeyDown "Ctrl", 1
MoveTo 1478, 475
Delay 34
KeyDown "Ctrl", 1
MoveTo 1478, 472
Delay 33
KeyDown "Ctrl", 1
MoveTo 1478, 466
Delay 34
KeyDown "Ctrl", 1
MoveTo 1478, 461
Delay 33
KeyDown "Ctrl", 1
MoveTo 1482, 452
Delay 33
KeyDown "Ctrl", 1
MoveTo 1484, 448
Delay 34
KeyDown "Ctrl", 1
MoveTo 1484, 447
Delay 33
KeyDown "Ctrl", 1
MoveTo 1484, 446
Delay 35
KeyDown "Ctrl", 1
MoveTo 1484, 445
Delay 32
KeyDown "Ctrl", 1
MoveTo 1484, 442
Delay 33
KeyDown "Ctrl", 1
MoveTo 1484, 440
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 35
MoveTo 1484, 438
Delay 35
KeyDown "Ctrl", 1
Delay 30
Delay 3
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 96
KeyDown "Ctrl", 1
Delay 49
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 66
KeyDown "Ctrl", 1
Delay 34
Delay 75
KeyDown "Ctrl", 1
Delay 32
KeyDown "Ctrl", 1
Delay 2
Delay 1
KeyUp "Ctrl", 1
MoveTo 806, 358
Delay 2487
KeyDown "Shift", 1
MoveTo 807, 351
Delay 305
LeftDoubleClick 1
Delay 39
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
MoveTo 808, 351
Delay 35
KeyDown "Shift", 1
MoveTo 805, 367
Delay 33
KeyDown "Shift", 1
MoveTo 802, 384
Delay 32
KeyDown "Shift", 1
MoveTo 801, 394
Delay 35
KeyDown "Shift", 1
MoveTo 801, 401
Delay 33
KeyDown "Shift", 1
Delay 38
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 801, 404
Delay 33
KeyDown "Shift", 1
MoveTo 801, 407
Delay 34
KeyDown "Shift", 1
MoveTo 801, 412
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 34
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 1
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
MoveTo 801, 414
Delay 35
KeyUp "Shift", 1
MoveTo 812, 416
Delay 732
KeyDown "M", 1
MoveTo 849, 412
Delay 133
KeyUp "M", 1
MoveTo 1382, 433
Delay 301
KeyDown "Ctrl", 1
MoveTo 1436, 521
Delay 533
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 1438, 521
Delay 33
KeyDown "Ctrl", 1
MoveTo 1446, 521
Delay 34
KeyDown "Ctrl", 1
MoveTo 1449, 521
Delay 6
KeyDown "Ctrl", 1
Delay 60
MoveTo 1450, 521
Delay 3
KeyDown "Ctrl", 1
Delay 65
Delay 1
KeyDown "Ctrl", 1
MoveTo 1451, 521
Delay 33
KeyDown "Ctrl", 1
MoveTo 1452, 522
Delay 33
KeyDown "Ctrl", 1
MoveTo 1455, 525
Delay 34
KeyDown "Ctrl", 1
MoveTo 1457, 526
Delay 34
KeyDown "Ctrl", 1
MoveTo 1457, 527
Delay 31
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 91
KeyDown "Ctrl", 1
Delay 51
Delay 32
KeyDown "Ctrl", 1
Delay 18
Delay 1
KeyDown "Ctrl", 1
Delay 15
KeyUp "Ctrl", 1
MoveTo 1120, 454
Delay 2394
KeyDown "Shift", 1
MoveTo 1011, 373
Delay 500
KeyDown "Shift", 1
MoveTo 1011, 372
Delay 32
KeyDown "Shift", 1
Delay 35
Delay 32
KeyDown "Shift", 1
MoveTo 1011, 371
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 43
Delay 3
KeyDown "Shift", 1
Delay 64
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 32
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 1009, 376
Delay 33
KeyDown "Shift", 1
MoveTo 1003, 390
Delay 35
KeyDown "Shift", 1
MoveTo 999, 402
Delay 32
KeyDown "Shift", 1
MoveTo 993, 407
Delay 34
KeyDown "Shift", 1
MoveTo 989, 410
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 31
MoveTo 994, 410
Delay 36
KeyDown "Shift", 1
MoveTo 1005, 410
Delay 31
KeyDown "Shift", 1
MoveTo 1023, 414
Delay 34
KeyDown "Shift", 1
MoveTo 1048, 417
Delay 33
KeyDown "Shift", 1
MoveTo 1071, 419
Delay 2
KeyUp "Shift", 1
MoveTo 1109, 436
Delay 599
KeyDown "M", 1
MoveTo 1137, 439
Delay 127
KeyUp "M", 1
MoveTo 1655, 584
Delay 501
KeyDown "Ctrl", 1
MoveTo 1550, 609
Delay 531
KeyDown "Ctrl", 1
MoveTo 1533, 607
Delay 4
KeyDown "Ctrl", 1
MoveTo 1518, 602
Delay 31
KeyDown "Ctrl", 1
MoveTo 1510, 598
Delay 34
KeyDown "Ctrl", 1
MoveTo 1507, 596
Delay 32
KeyDown "Ctrl", 1
MoveTo 1501, 593
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 1501, 592
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 37
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 32
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 35
KeyDown "Ctrl", 1
Delay 32
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 34
MoveTo 1503, 592
Delay 32
KeyDown "Ctrl", 1
Delay 101
Delay 56
KeyDown "Ctrl", 1
Delay 1
MoveTo 1508, 592
KeyDown "Ctrl", 1
MoveTo 1511, 593
Delay 2
KeyDown "Ctrl", 1
MoveTo 1512, 594
Delay 1
KeyUp "Ctrl", 1
MoveTo 717, 504
Delay 3301
KeyDown "Shift", 1
Delay 167
LeftDoubleClick 1
Delay 67
MoveTo 717, 495
Delay 71
KeyDown "Shift", 1
MoveTo 717, 479
Delay 34
KeyDown "Shift", 1
MoveTo 717, 460
Delay 33
KeyDown "Shift", 1
MoveTo 722, 446
Delay 33
KeyDown "Shift", 1
MoveTo 725, 439
Delay 33
KeyDown "Shift", 1
MoveTo 730, 431
Delay 33
KeyDown "Shift", 1
MoveTo 733, 425
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 734, 425
Delay 33
KeyDown "Shift", 1
MoveTo 734, 424
Delay 34
KeyDown "Shift", 1
MoveTo 734, 423
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 32
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
KeyUp "Shift", 1
'==========以上是按键精灵录制的内容==========
