[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=57ef0866-13bf-491c-826b-929e975d73f5
Description=放置猎物 雪地
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 972, 615
Delay 1000
LeftClick 1
Delay 867
KeyDown "`", 1
Delay 167
KeyUp "`", 1
Delay 799
KeyDown "Shift", 1
Delay 136
KeyDown "M", 1
Delay 131
KeyUp "Shift", 1
Delay 33
KeyUp "M", 1
Delay 68
KeyDown "A", 1
Delay 166
KeyDown "K", 1
Delay 2
KeyUp "A", 1
Delay 98
KeyUp "K", 1
Delay 233
KeyDown "E", 1
Delay 69
KeyUp "E", 1
Delay 165
KeyDown "Tab", 1
Delay 166
KeyUp "Tab", 1
Delay 600
KeyDown "Space", 1
Delay 167
KeyUp "Space", 1
Delay 66
KeyDown "Shift", 1
Delay 201
KeyDown "H", 1
Delay 133
KeyUp "Shift", 1
Delay 2
KeyUp "H", 1
Delay 98
KeyDown "A", 1
Delay 166
KeyDown "Y", 1
Delay 34
KeyUp "A", 1
Delay 100
KeyUp "Y", 1
Delay 100
KeyDown "O", 1
Delay 100
KeyUp "O", 1
Delay 67
KeyDown "O", 1
Delay 133
KeyUp "O", 1
Delay 1
KeyDown "U", 1
Delay 169
KeyUp "U", 1
Delay 30
KeyDown "Shift", 1
Delay 167
KeyDown "2", 1
Delay 66
KeyUp "Shift", 1
Delay 100
KeyUp "2", 1
Delay 134
KeyDown "2", 1
Delay 166
KeyUp "2", 1
Delay 135
KeyDown "9", 1
Delay 99
KeyUp "9", 1
Delay 66
KeyDown "9", 1
Delay 100
KeyUp "9", 1
Delay 267
KeyDown "9", 1
Delay 100
KeyUp "9", 1
Delay 200
KeyDown "9", 1
Delay 133
KeyUp "9", 1
Delay 203
KeyDown "Enter", 1
Delay 102
KeyUp "Enter", 1
Delay 1195
KeyDown "Esc", 1
Delay 202
KeyUp "Esc", 1
MoveTo 982, 810
Delay 1432
LeftClick 1
MoveTo 1787, 143
Delay 1992
LeftClick 1
MoveTo 727, 247
Delay 2515
LeftClick 1
MoveTo 652, 298
Delay 1530
LeftClick 1
Delay 1590
KeyDown "H", 1
Delay 86
KeyDown "A", 1
Delay 56
KeyUp "H", 1
Delay 88
KeyDown "Y", 1
Delay 39
KeyUp "A", 1
Delay 99
KeyUp "Y", 1
MoveTo 689, 349
Delay 2542
KeyDown "Shift", 1
Delay 206
LeftDoubleClick 1
Delay 67
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 689, 350
Delay 34
KeyDown "Shift", 1
MoveTo 694, 360
Delay 34
KeyDown "Shift", 1
MoveTo 703, 371
Delay 33
KeyDown "Shift", 1
MoveTo 708, 377
Delay 34
KeyDown "Shift", 1
MoveTo 711, 380
Delay 33
KeyDown "Shift", 1
MoveTo 717, 385
Delay 33
KeyDown "Shift", 1
MoveTo 726, 392
Delay 33
KeyDown "Shift", 1
MoveTo 734, 399
Delay 34
KeyDown "Shift", 1
MoveTo 738, 403
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 739, 405
Delay 34
KeyDown "Shift", 1
MoveTo 740, 405
Delay 33
KeyDown "Shift", 1
Delay 38
MoveTo 740, 403
Delay 34
KeyDown "Shift", 1
MoveTo 740, 368
Delay 36
KeyDown "Shift", 1
MoveTo 738, 345
Delay 34
KeyDown "Shift", 1
MoveTo 736, 338
Delay 31
KeyDown "Shift", 1
MoveTo 736, 337
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
MoveTo 736, 348
Delay 35
KeyDown "Shift", 1
MoveTo 739, 362
Delay 32
KeyDown "Shift", 1
MoveTo 742, 374
Delay 34
KeyDown "Shift", 1
MoveTo 745, 388
Delay 34
KeyDown "Shift", 1
MoveTo 745, 398
Delay 33
KeyDown "Shift", 1
MoveTo 745, 402
Delay 33
KeyDown "Shift", 1
Delay 32
MoveTo 745, 403
Delay 34
KeyDown "Shift", 1
MoveTo 745, 405
Delay 33
KeyDown "Shift", 1
MoveTo 745, 406
Delay 34
KeyDown "Shift", 1
MoveTo 746, 408
Delay 33
KeyDown "Shift", 1
MoveTo 746, 410
Delay 34
KeyDown "Shift", 1
MoveTo 747, 411
Delay 31
KeyDown "Shift", 1
MoveTo 747, 414
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 41
KeyDown "Shift", 1
Delay 38
Delay 1
LeftUp 1
Delay 38
KeyDown "Shift", 1
Delay 35
MoveTo 747, 421
Delay 37
KeyDown "Shift", 1
MoveTo 750, 432
Delay 42
KeyDown "Shift", 1
MoveTo 757, 447
Delay 35
KeyDown "Shift", 1
MoveTo 762, 459
Delay 4
KeyDown "Shift", 1
MoveTo 768, 471
Delay 37
KeyDown "Shift", 1
MoveTo 770, 482
Delay 33
KeyDown "Shift", 1
MoveTo 772, 489
Delay 33
KeyDown "Shift", 1
MoveTo 773, 491
Delay 33
KeyDown "Shift", 1
MoveTo 773, 496
Delay 34
KeyDown "Shift", 1
MoveTo 773, 497
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 37
MoveTo 773, 498
Delay 34
KeyUp "Shift", 1
MoveTo 773, 504
Delay 646
KeyDown "M", 1
Delay 162
KeyUp "M", 1
MoveTo 351, 420
Delay 743
KeyDown "Ctrl", 1
MoveTo 201, 444
Delay 532
KeyDown "Ctrl", 1
MoveTo 202, 449
Delay 45
KeyDown "Ctrl", 1
MoveTo 202, 455
Delay 1
KeyDown "Ctrl", 1
MoveTo 202, 458
Delay 54
KeyDown "Ctrl", 1
MoveTo 202, 464
Delay 33
KeyDown "Ctrl", 1
MoveTo 202, 472
Delay 33
KeyDown "Ctrl", 1
MoveTo 202, 482
Delay 34
KeyDown "Ctrl", 1
MoveTo 207, 498
Delay 4
KeyDown "Ctrl", 1
MoveTo 212, 506
Delay 63
KeyDown "Ctrl", 1
MoveTo 217, 513
Delay 33
KeyDown "Ctrl", 1
MoveTo 222, 519
Delay 33
KeyDown "Ctrl", 1
MoveTo 227, 522
Delay 4
KeyDown "Ctrl", 1
MoveTo 232, 522
Delay 63
KeyDown "Ctrl", 1
MoveTo 233, 523
Delay 2
KeyDown "Ctrl", 1
MoveTo 236, 523
Delay 32
KeyDown "Ctrl", 1
Delay 32
MoveTo 237, 523
Delay 36
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 238, 523
Delay 35
KeyDown "Ctrl", 1
MoveTo 237, 521
Delay 32
KeyDown "Ctrl", 1
MoveTo 233, 516
Delay 35
KeyDown "Ctrl", 1
MoveTo 228, 510
Delay 32
KeyDown "Ctrl", 1
MoveTo 216, 498
Delay 33
KeyDown "Ctrl", 1
MoveTo 204, 490
Delay 34
KeyDown "Ctrl", 1
MoveTo 193, 482
Delay 33
KeyDown "Ctrl", 1
MoveTo 189, 478
Delay 33
KeyDown "Ctrl", 1
MoveTo 181, 473
Delay 34
KeyDown "Ctrl", 1
MoveTo 179, 471
Delay 33
KeyDown "Ctrl", 1
MoveTo 178, 470
Delay 35
KeyDown "Ctrl", 1
Delay 32
MoveTo 177, 469
Delay 32
KeyDown "Ctrl", 1
MoveTo 175, 467
Delay 35
KeyDown "Ctrl", 1
MoveTo 174, 466
Delay 33
KeyDown "Ctrl", 1
MoveTo 174, 465
Delay 34
KeyDown "Ctrl", 1
MoveTo 174, 462
Delay 34
KeyDown "Ctrl", 1
MoveTo 174, 460
Delay 35
KeyDown "Ctrl", 1
Delay 29
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 174, 459
Delay 35
KeyDown "Ctrl", 1
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 185
Delay 56
KeyDown "Ctrl", 1
Delay 33
Delay 20
KeyDown "Ctrl", 1
Delay 2
Delay 11
KeyUp "Ctrl", 1
MoveTo 723, 341
Delay 3300
KeyDown "Shift", 1
Delay 168
LeftClick 1
MoveTo 723, 360
Delay 266
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 723, 369
Delay 38
KeyDown "Shift", 1
MoveTo 723, 377
Delay 32
KeyDown "Shift", 1
MoveTo 726, 386
Delay 34
KeyDown "Shift", 1
MoveTo 727, 388
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 727, 390
Delay 34
KeyDown "Shift", 1
MoveTo 729, 396
Delay 38
KeyDown "Shift", 1
MoveTo 730, 401
Delay 2
KeyDown "Shift", 1
MoveTo 730, 410
Delay 33
KeyDown "Shift", 1
MoveTo 731, 414
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 63
Delay 34
KeyDown "Shift", 1
MoveTo 735, 429
Delay 5
KeyDown "Shift", 1
MoveTo 738, 448
Delay 38
KeyDown "Shift", 1
MoveTo 740, 460
Delay 34
KeyDown "Shift", 1
MoveTo 741, 468
Delay 33
KeyDown "Shift", 1
MoveTo 742, 472
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
KeyUp "Shift", 1
MoveTo 742, 474
Delay 465
KeyDown "M", 1
Delay 163
KeyUp "M", 1
MoveTo 266, 528
Delay 536
KeyDown "Ctrl", 1
MoveTo 185, 561
Delay 497
KeyDown "Ctrl", 1
Delay 34
MoveTo 184, 561
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 104
KeyDown "Ctrl", 1
MoveTo 184, 562
Delay 34
KeyDown "Ctrl", 1
MoveTo 184, 568
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 26
KeyDown "Ctrl", 1
Delay 3
Delay 4
KeyDown "Ctrl", 1
Delay 3
KeyUp "Ctrl", 1
MoveTo 376, 377
Delay 2602
KeyDown "Shift", 1
MoveTo 653, 337
Delay 508
KeyDown "Shift", 1
Delay 34
Delay 39
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 656, 344
Delay 33
KeyDown "Shift", 1
MoveTo 659, 355
Delay 33
KeyDown "Shift", 1
MoveTo 662, 363
Delay 33
KeyDown "Shift", 1
MoveTo 663, 364
Delay 34
KeyDown "Shift", 1
MoveTo 664, 365
Delay 34
KeyDown "Shift", 1
MoveTo 666, 367
Delay 34
KeyDown "Shift", 1
Delay 31
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 668, 367
Delay 34
KeyDown "Shift", 1
MoveTo 670, 364
Delay 33
KeyDown "Shift", 1
MoveTo 671, 363
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 43
Delay 2
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 672, 364
Delay 32
KeyDown "Shift", 1
MoveTo 673, 375
Delay 37
KeyDown "Shift", 1
MoveTo 676, 385
Delay 31
KeyDown "Shift", 1
MoveTo 681, 396
Delay 33
KeyDown "Shift", 1
MoveTo 684, 404
Delay 33
KeyDown "Shift", 1
MoveTo 685, 407
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
MoveTo 686, 408
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 29
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 29
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 680, 419
Delay 467
KeyDown "M", 1
MoveTo 673, 423
Delay 166
KeyUp "M", 1
MoveTo 185, 567
Delay 632
KeyDown "Ctrl", 1
MoveTo 215, 580
Delay 500
KeyDown "Ctrl", 1
MoveTo 215, 581
Delay 34
RightDown 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 103
Delay 46
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 26
Delay 2
KeyDown "Ctrl", 1
Delay 5
KeyUp "Ctrl", 1
MoveTo 927, 295
Delay 2537
KeyDown "Shift", 1
MoveTo 757, 334
Delay 514
KeyDown "Shift", 1
MoveTo 757, 336
Delay 43
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 40
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 35
MoveTo 757, 349
Delay 35
KeyDown "Shift", 1
MoveTo 757, 359
Delay 33
KeyDown "Shift", 1
MoveTo 757, 363
Delay 33
KeyDown "Shift", 1
MoveTo 757, 364
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
MoveTo 757, 365
Delay 6
KeyDown "Shift", 1
Delay 35
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
MoveTo 757, 373
Delay 37
KeyDown "Shift", 1
MoveTo 756, 389
Delay 33
KeyDown "Shift", 1
MoveTo 753, 407
Delay 35
KeyDown "Shift", 1
MoveTo 752, 411
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 2
LeftDown 1
Delay 43
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 35
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
KeyUp "Shift", 1
Delay 403
KeyDown "M", 1
MoveTo 742, 423
Delay 167
KeyUp "M", 1
MoveTo 583, 591
Delay 332
KeyDown "Ctrl", 1
MoveTo 222, 576
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
MoveTo 224, 575
Delay 37
RightClick 1
MoveTo 225, 575
Delay 1
KeyDown "Ctrl", 1
Delay 29
Delay 33
KeyDown "Ctrl", 1
Delay 100
Delay 33
KeyDown "Ctrl", 1
Delay 57
MoveTo 226, 575
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 10
KeyDown "Ctrl", 1
Delay 1
Delay 22
KeyUp "Ctrl", 1
MoveTo 550, 316
Delay 2329
KeyDown "Shift", 1
MoveTo 597, 338
Delay 369
LeftClick 1
Delay 35
KeyDown "Shift", 1
Delay 3
MoveTo 599, 341
Delay 33
KeyDown "Shift", 1
MoveTo 614, 351
Delay 36
KeyDown "Shift", 1
MoveTo 627, 358
Delay 42
KeyDown "Shift", 1
MoveTo 629, 359
Delay 32
KeyDown "Shift", 1
Delay 44
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 38
Delay 36
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 31
KeyDown "Shift", 1
MoveTo 639, 372
Delay 35
KeyDown "Shift", 1
MoveTo 645, 385
Delay 33
KeyDown "Shift", 1
MoveTo 650, 395
Delay 34
KeyDown "Shift", 1
MoveTo 652, 398
Delay 34
KeyDown "Shift", 1
MoveTo 652, 400
Delay 34
KeyDown "Shift", 1
MoveTo 655, 404
Delay 32
KeyDown "Shift", 1
MoveTo 656, 408
Delay 36
KeyDown "Shift", 1
MoveTo 657, 410
Delay 36
KeyDown "Shift", 1
MoveTo 658, 412
Delay 32
KeyDown "Shift", 1
MoveTo 659, 412
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 660, 414
Delay 37
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 42
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 3
KeyUp "Shift", 1
MoveTo 658, 423
Delay 364
KeyDown "M", 1
MoveTo 653, 432
Delay 165
KeyUp "M", 1
MoveTo 527, 556
Delay 334
KeyDown "Ctrl", 1
MoveTo 265, 557
Delay 502
KeyDown "Ctrl", 1
Delay 30
MoveTo 268, 554
Delay 36
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 4
KeyDown "Ctrl", 1
Delay 29
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 111
Delay 50
KeyDown "Ctrl", 1
Delay 33
Delay 22
KeyDown "Ctrl", 1
Delay 1
Delay 10
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 743, 330
Delay 2577
KeyDown "Shift", 1
Delay 134
LeftClick 1
MoveTo 745, 358
Delay 275
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 1
Delay 35
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
MoveTo 745, 374
Delay 33
KeyDown "Shift", 1
MoveTo 745, 394
Delay 36
KeyDown "Shift", 1
MoveTo 745, 400
Delay 31
KeyDown "Shift", 1
MoveTo 745, 403
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 745, 405
Delay 34
KeyDown "Shift", 1
MoveTo 745, 410
Delay 36
KeyDown "Shift", 1
MoveTo 745, 412
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 36
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 35
Delay 31
Delay 1
KeyDown "Shift", 1
Delay 46
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyUp "Shift", 1
MoveTo 745, 413
Delay 300
KeyDown "M", 1
MoveTo 741, 416
Delay 165
KeyUp "M", 1
MoveTo 395, 591
Delay 432
KeyDown "Ctrl", 1
MoveTo 309, 563
Delay 467
RightDown 1
Delay 66
KeyDown "Ctrl", 1
Delay 33
MoveTo 310, 562
Delay 34
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 104
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
MoveTo 310, 561
Delay 35
KeyDown "Ctrl", 1
Delay 32
MoveTo 307, 561
Delay 54
KeyDown "Ctrl", 1
MoveTo 306, 561
Delay 32
KeyDown "Ctrl", 1
MoveTo 305, 561
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 20
Delay 1
KeyDown "Ctrl", 1
MoveTo 307, 560
Delay 12
KeyDown "Ctrl", 1
MoveTo 315, 557
Delay 2
KeyUp "Ctrl", 1
MoveTo 660, 333
Delay 2505
KeyDown "Shift", 1
MoveTo 661, 331
Delay 269
LeftClick 1
MoveTo 670, 338
Delay 99
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 42
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 32
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
MoveTo 671, 344
Delay 33
KeyDown "Shift", 1
MoveTo 671, 351
Delay 37
KeyDown "Shift", 1
MoveTo 673, 359
Delay 34
KeyDown "Shift", 1
MoveTo 674, 362
Delay 35
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 674, 363
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 39
KeyDown "Shift", 1
Delay 37
Delay 42
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 680, 378
Delay 33
KeyDown "Shift", 1
MoveTo 689, 398
Delay 35
KeyDown "Shift", 1
MoveTo 691, 406
Delay 33
KeyDown "Shift", 1
MoveTo 691, 408
Delay 32
KeyDown "Shift", 1
Delay 32
MoveTo 691, 409
Delay 35
KeyDown "Shift", 1
MoveTo 691, 412
Delay 35
KeyDown "Shift", 1
MoveTo 691, 416
Delay 41
KeyDown "Shift", 1
MoveTo 691, 419
Delay 35
KeyDown "Shift", 1
MoveTo 691, 422
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 30
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 37
KeyDown "Shift", 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 695, 432
Delay 35
KeyDown "Shift", 1
MoveTo 697, 436
Delay 2
KeyUp "Shift", 1
MoveTo 705, 464
Delay 366
KeyDown "M", 1
MoveTo 701, 476
Delay 161
KeyUp "M", 1
MoveTo 479, 583
Delay 368
KeyDown "Ctrl", 1
MoveTo 327, 563
Delay 498
KeyDown "Ctrl", 1
MoveTo 328, 563
Delay 35
KeyDown "Ctrl", 1
MoveTo 329, 563
Delay 34
KeyDown "Ctrl", 1
MoveTo 330, 564
Delay 31
KeyDown "Ctrl", 1
MoveTo 331, 564
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
MoveTo 332, 565
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 118
KeyDown "Ctrl", 1
Delay 16
Delay 1
KeyDown "Ctrl", 1
Delay 33
KeyUp "Ctrl", 1
MoveTo 693, 334
Delay 2453
KeyDown "Shift", 1
MoveTo 696, 332
Delay 267
LeftClick 1
MoveTo 705, 362
Delay 141
KeyDown "Shift", 1
MoveTo 706, 364
Delay 3
KeyDown "Shift", 1
Delay 64
Delay 1
KeyDown "Shift", 1
Delay 44
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 43
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 3
KeyDown "Shift", 1
MoveTo 706, 365
Delay 64
KeyDown "Shift", 1
MoveTo 710, 388
Delay 32
KeyDown "Shift", 1
MoveTo 719, 416
Delay 34
KeyDown "Shift", 1
MoveTo 721, 424
Delay 4
KeyDown "Shift", 1
MoveTo 722, 424
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyUp "Shift", 1
Delay 372
KeyDown "M", 1
MoveTo 722, 433
Delay 139
KeyUp "M", 1
MoveTo 573, 547
Delay 368
KeyDown "Ctrl", 1
MoveTo 375, 566
Delay 498
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 366, 566
Delay 34
KeyDown "Ctrl", 1
MoveTo 355, 566
Delay 34
KeyDown "Ctrl", 1
MoveTo 349, 566
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 34
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 350, 566
Delay 33
KeyDown "Ctrl", 1
MoveTo 352, 566
Delay 35
KeyDown "Ctrl", 1
Delay 27
Delay 1
KeyDown "Ctrl", 1
Delay 4
MoveTo 353, 566
Delay 2
KeyUp "Ctrl", 1
MoveTo 358, 562
Delay 723
KeyDown "Ctrl", 1
Delay 220
Delay 1
KeyDown "Ctrl", 1
Delay 12
KeyUp "Ctrl", 1
MoveTo 736, 333
Delay 2527
KeyDown "Shift", 1
Delay 305
LeftClick 1
MoveTo 740, 351
Delay 111
KeyDown "Shift", 1
MoveTo 740, 355
Delay 34
KeyDown "Shift", 1
MoveTo 740, 357
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
MoveTo 740, 358
Delay 33
KeyDown "Shift", 1
MoveTo 742, 360
Delay 35
KeyDown "Shift", 1
MoveTo 742, 361
Delay 32
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 40
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 37
MoveTo 745, 374
Delay 34
KeyDown "Shift", 1
MoveTo 750, 396
Delay 34
KeyDown "Shift", 1
MoveTo 751, 412
Delay 4
KeyDown "Shift", 1
MoveTo 751, 418
Delay 67
KeyDown "Shift", 1
MoveTo 751, 421
Delay 39
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 1
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 2
Delay 40
KeyDown "Shift", 1
Delay 37
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 37
Delay 33
KeyUp "Shift", 1
MoveTo 751, 423
Delay 404
KeyDown "M", 1
Delay 133
KeyUp "M", 1
MoveTo 414, 547
Delay 601
KeyDown "Ctrl", 1
MoveTo 396, 545
Delay 533
KeyDown "Ctrl", 1
Delay 32
Delay 3
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 397, 545
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 31
KeyDown "Ctrl", 1
Delay 1
Delay 89
KeyDown "Ctrl", 1
Delay 4
KeyUp "Ctrl", 1
MoveTo 819, 276
Delay 2617
KeyDown "Shift", 1
MoveTo 769, 332
Delay 437
LeftDown 1
Delay 81
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
MoveTo 767, 341
Delay 34
KeyDown "Shift", 1
MoveTo 764, 360
Delay 33
KeyDown "Shift", 1
MoveTo 760, 369
Delay 34
KeyDown "Shift", 1
MoveTo 759, 370
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 757, 370
Delay 34
KeyDown "Shift", 1
MoveTo 757, 367
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 1
Delay 35
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 40
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
MoveTo 757, 372
Delay 34
KeyDown "Shift", 1
MoveTo 756, 387
Delay 39
KeyDown "Shift", 1
MoveTo 756, 395
Delay 1
KeyDown "Shift", 1
MoveTo 756, 396
Delay 31
KeyDown "Shift", 1
MoveTo 756, 398
Delay 34
KeyDown "Shift", 1
MoveTo 756, 401
Delay 34
KeyDown "Shift", 1
MoveTo 756, 402
Delay 33
KeyDown "Shift", 1
MoveTo 756, 403
Delay 32
KeyDown "Shift", 1
MoveTo 756, 406
Delay 35
KeyDown "Shift", 1
MoveTo 756, 413
Delay 34
KeyDown "Shift", 1
MoveTo 756, 416
Delay 32
KeyDown "Shift", 1
MoveTo 755, 419
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 32
Delay 33
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 4
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 34
KeyUp "Shift", 1
Delay 438
KeyDown "M", 1
MoveTo 755, 432
Delay 131
KeyUp "M", 1
MoveTo 699, 554
Delay 300
KeyDown "Ctrl", 1
MoveTo 470, 555
Delay 500
KeyDown "Ctrl", 1
MoveTo 466, 555
Delay 34
KeyDown "Ctrl", 1
MoveTo 463, 556
Delay 34
KeyDown "Ctrl", 1
MoveTo 456, 556
Delay 33
KeyDown "Ctrl", 1
MoveTo 452, 556
Delay 32
KeyDown "Ctrl", 1
Delay 33
MoveTo 452, 554
Delay 34
KeyDown "Ctrl", 1
MoveTo 451, 553
Delay 33
KeyDown "Ctrl", 1
MoveTo 450, 552
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 2
RightDown 1
MoveTo 450, 551
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 79
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 2
KeyUp "Ctrl", 1
MoveTo 641, 422
Delay 2456
KeyDown "Shift", 1
MoveTo 703, 336
Delay 516
KeyDown "Shift", 1
MoveTo 703, 333
Delay 33
KeyDown "Shift", 1
MoveTo 705, 329
Delay 33
KeyDown "Shift", 1
MoveTo 706, 326
Delay 34
KeyDown "Shift", 1
Delay 42
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
MoveTo 706, 337
Delay 35
KeyDown "Shift", 1
MoveTo 700, 359
Delay 36
KeyDown "Shift", 1
MoveTo 699, 362
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 35
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
MoveTo 699, 374
Delay 33
KeyDown "Shift", 1
MoveTo 704, 398
Delay 39
KeyDown "Shift", 1
MoveTo 711, 412
Delay 32
KeyDown "Shift", 1
MoveTo 712, 414
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 2
Delay 42
KeyDown "Shift", 1
Delay 36
Delay 35
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 33
Delay 33
KeyUp "Shift", 1
MoveTo 713, 421
Delay 334
KeyDown "M", 1
MoveTo 713, 423
Delay 164
KeyUp "M", 1
MoveTo 660, 538
Delay 367
KeyDown "Ctrl", 1
MoveTo 500, 545
Delay 534
KeyDown "Ctrl", 1
MoveTo 499, 545
Delay 33
KeyDown "Ctrl", 1
MoveTo 497, 545
Delay 36
KeyDown "Ctrl", 1
MoveTo 496, 544
Delay 30
KeyDown "Ctrl", 1
Delay 2
RightDown 1
MoveTo 495, 544
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 71
Delay 1
KeyDown "Ctrl", 1
Delay 41
MoveTo 500, 543
Delay 2
KeyUp "Ctrl", 1
MoveTo 652, 348
Delay 2678
KeyDown "Shift", 1
MoveTo 666, 331
Delay 266
LeftClick 1
MoveTo 670, 359
Delay 134
KeyDown "Shift", 1
Delay 35
Delay 42
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 41
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 672, 365
Delay 39
KeyDown "Shift", 1
MoveTo 684, 393
Delay 33
KeyDown "Shift", 1
MoveTo 692, 420
Delay 33
KeyDown "Shift", 1
MoveTo 693, 435
Delay 33
KeyDown "Shift", 1
MoveTo 693, 436
Delay 34
KeyDown "Shift", 1
Delay 2
Delay 34
KeyDown "Shift", 1
MoveTo 694, 437
Delay 34
KeyDown "Shift", 1
MoveTo 695, 437
Delay 35
KeyDown "Shift", 1
MoveTo 697, 433
Delay 33
KeyDown "Shift", 1
MoveTo 700, 423
Delay 37
KeyDown "Shift", 1
MoveTo 700, 419
Delay 35
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 42
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 2
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 37
KeyDown "Shift", 1
Delay 36
Delay 2
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 2
KeyUp "Shift", 1
Delay 299
KeyDown "M", 1
Delay 165
KeyUp "M", 1
MoveTo 607, 540
Delay 333
KeyDown "Ctrl", 1
MoveTo 532, 538
Delay 400
RightDown 1
Delay 133
KeyDown "Ctrl", 1
Delay 3
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 99
KeyDown "Ctrl", 1
Delay 13
Delay 1
KeyDown "Ctrl", 1
Delay 19
Delay 2
KeyUp "Ctrl", 1
MoveTo 606, 360
Delay 2589
KeyDown "Shift", 1
MoveTo 635, 336
Delay 376
LeftClick 1
Delay 34
KeyDown "Shift", 1
MoveTo 636, 344
Delay 33
KeyDown "Shift", 1
MoveTo 637, 351
Delay 34
KeyDown "Shift", 1
MoveTo 638, 356
Delay 34
KeyDown "Shift", 1
MoveTo 638, 360
Delay 33
KeyDown "Shift", 1
Delay 47
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
MoveTo 644, 372
Delay 37
KeyDown "Shift", 1
MoveTo 651, 392
Delay 33
KeyDown "Shift", 1
MoveTo 655, 403
Delay 35
KeyDown "Shift", 1
MoveTo 656, 409
Delay 34
KeyDown "Shift", 1
MoveTo 657, 410
Delay 30
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 658, 410
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 35
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 32
KeyUp "Shift", 1
MoveTo 659, 429
Delay 367
KeyDown "M", 1
MoveTo 657, 433
Delay 128
KeyUp "M", 1
MoveTo 549, 449
Delay 468
KeyDown "Ctrl", 1
MoveTo 530, 494
Delay 500
KeyDown "Ctrl", 1
MoveTo 532, 497
Delay 33
KeyDown "Ctrl", 1
MoveTo 533, 497
Delay 34
KeyDown "Ctrl", 1
MoveTo 536, 498
Delay 33
KeyDown "Ctrl", 1
MoveTo 537, 498
Delay 38
KeyDown "Ctrl", 1
Delay 27
Delay 3
RightDown 1
Delay 38
KeyDown "Ctrl", 1
Delay 27
Delay 32
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 129
KeyDown "Ctrl", 1
Delay 9
Delay 1
KeyDown "Ctrl", 1
Delay 50
KeyUp "Ctrl", 1
MoveTo 670, 278
Delay 2580
KeyDown "Shift", 1
MoveTo 680, 332
Delay 505
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 37
Delay 36
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 48
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 681, 338
Delay 2
KeyDown "Shift", 1
MoveTo 681, 343
Delay 36
KeyDown "Shift", 1
MoveTo 682, 346
Delay 33
KeyDown "Shift", 1
MoveTo 683, 346
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 683, 347
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 683, 350
Delay 42
KeyDown "Shift", 1
MoveTo 683, 354
Delay 39
KeyDown "Shift", 1
MoveTo 683, 356
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 683, 361
Delay 35
KeyDown "Shift", 1
MoveTo 688, 373
Delay 33
KeyDown "Shift", 1
MoveTo 699, 389
Delay 39
KeyDown "Shift", 1
MoveTo 706, 403
Delay 32
KeyDown "Shift", 1
MoveTo 710, 412
Delay 35
KeyDown "Shift", 1
MoveTo 711, 417
Delay 33
KeyDown "Shift", 1
MoveTo 711, 418
Delay 36
KeyDown "Shift", 1
Delay 40
MoveTo 711, 420
Delay 2
KeyDown "Shift", 1
MoveTo 711, 421
Delay 33
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 41
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 35
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 3
Delay 35
KeyDown "Shift", 1
Delay 3
Delay 47
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 39
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
MoveTo 710, 426
Delay 332
KeyDown "M", 1
MoveTo 691, 437
Delay 105
KeyUp "M", 1
MoveTo 530, 455
Delay 432
KeyDown "Ctrl", 1
MoveTo 488, 520
Delay 534
KeyDown "Ctrl", 1
Delay 3
RightDown 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 489, 520
Delay 63
KeyDown "Ctrl", 1
MoveTo 490, 521
Delay 2
KeyDown "Ctrl", 1
Delay 64
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 40
KeyDown "Ctrl", 1
Delay 80
MoveTo 490, 520
Delay 2
KeyUp "Ctrl", 1
MoveTo 496, 510
Delay 2662
KeyDown "Shift", 1
MoveTo 768, 338
Delay 522
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 38
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
MoveTo 765, 347
Delay 35
KeyDown "Shift", 1
MoveTo 763, 361
Delay 35
KeyDown "Shift", 1
MoveTo 763, 362
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 41
KeyDown "Shift", 1
Delay 38
Delay 41
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
MoveTo 763, 375
Delay 37
KeyDown "Shift", 1
MoveTo 763, 388
Delay 34
KeyDown "Shift", 1
MoveTo 763, 393
Delay 33
KeyDown "Shift", 1
MoveTo 763, 397
Delay 34
KeyDown "Shift", 1
MoveTo 763, 400
Delay 34
KeyDown "Shift", 1
MoveTo 763, 403
Delay 35
KeyDown "Shift", 1
MoveTo 763, 407
Delay 33
KeyDown "Shift", 1
MoveTo 763, 408
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 4
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 49
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 2
Delay 38
KeyDown "Shift", 1
Delay 36
Delay 39
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 44
MoveTo 762, 415
Delay 36
KeyDown "Shift", 1
MoveTo 762, 425
Delay 34
KeyDown "Shift", 1
MoveTo 771, 445
Delay 32
KeyDown "Shift", 1
MoveTo 779, 455
Delay 34
KeyDown "Shift", 1
MoveTo 783, 462
Delay 3
KeyUp "Shift", 1
MoveTo 772, 484
Delay 604
KeyDown "M", 1
MoveTo 751, 490
Delay 135
KeyUp "M", 1
MoveTo 532, 532
Delay 365
KeyDown "Ctrl", 1
MoveTo 455, 530
Delay 466
RightDown 1
Delay 33
KeyDown "Ctrl", 1
MoveTo 454, 529
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 87
Delay 1
KeyDown "Ctrl", 1
Delay 19
Delay 2
KeyUp "Ctrl", 1
MoveTo 595, 330
Delay 2647
KeyDown "Shift", 1
MoveTo 607, 355
Delay 508
KeyDown "Shift", 1
Delay 33
MoveTo 608, 355
Delay 35
KeyDown "Shift", 1
MoveTo 610, 351
Delay 34
KeyDown "Shift", 1
MoveTo 610, 348
Delay 47
KeyDown "Shift", 1
Delay 64
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 39
Delay 37
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 615, 343
Delay 38
KeyDown "Shift", 1
MoveTo 617, 341
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 38
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 618, 341
Delay 35
KeyDown "Shift", 1
MoveTo 620, 360
Delay 37
KeyDown "Shift", 1
MoveTo 620, 376
Delay 34
KeyDown "Shift", 1
MoveTo 620, 382
Delay 32
KeyDown "Shift", 1
MoveTo 622, 386
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 4
KeyDown "Shift", 1
Delay 63
Delay 33
KeyDown "Shift", 1
Delay 4
MoveTo 622, 387
Delay 32
KeyDown "Shift", 1
MoveTo 623, 387
Delay 34
KeyDown "Shift", 1
Delay 34
MoveTo 626, 389
Delay 34
KeyDown "Shift", 1
MoveTo 627, 396
Delay 35
KeyDown "Shift", 1
MoveTo 628, 402
Delay 33
KeyDown "Shift", 1
MoveTo 629, 406
Delay 35
KeyDown "Shift", 1
MoveTo 629, 411
Delay 36
KeyDown "Shift", 1
MoveTo 629, 412
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 2
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 35
KeyUp "Shift", 1
MoveTo 616, 425
Delay 470
KeyDown "M", 1
MoveTo 615, 426
Delay 165
KeyUp "M", 1
MoveTo 455, 447
Delay 368
KeyDown "Ctrl", 1
MoveTo 417, 503
Delay 499
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
RightDown 1
Delay 5
KeyDown "Ctrl", 1
Delay 28
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 59
Delay 1
KeyDown "Ctrl", 1
Delay 53
Delay 2
KeyUp "Ctrl", 1
MoveTo 449, 457
Delay 2563
KeyDown "Shift", 1
MoveTo 617, 336
Delay 517
KeyDown "Shift", 1
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 31
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 52
Delay 2
LeftUp 1
MoveTo 618, 336
Delay 34
KeyDown "Shift", 1
MoveTo 621, 353
Delay 33
KeyDown "Shift", 1
MoveTo 623, 363
Delay 36
KeyDown "Shift", 1
MoveTo 623, 364
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 6
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 35
MoveTo 623, 368
Delay 35
KeyDown "Shift", 1
MoveTo 623, 388
Delay 4
KeyDown "Shift", 1
MoveTo 624, 395
Delay 33
KeyDown "Shift", 1
MoveTo 624, 398
Delay 34
KeyDown "Shift", 1
MoveTo 625, 399
Delay 33
KeyDown "Shift", 1
MoveTo 625, 400
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 625, 401
Delay 35
KeyDown "Shift", 1
MoveTo 625, 403
Delay 36
KeyDown "Shift", 1
MoveTo 625, 405
Delay 36
KeyDown "Shift", 1
MoveTo 625, 407
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 625, 408
Delay 33
KeyDown "Shift", 1
MoveTo 625, 411
Delay 37
KeyDown "Shift", 1
MoveTo 625, 413
Delay 33
KeyDown "Shift", 1
MoveTo 625, 416
Delay 35
KeyDown "Shift", 1
Delay 33
MoveTo 625, 417
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 36
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 40
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
Delay 399
KeyDown "M", 1
MoveTo 617, 420
Delay 129
KeyUp "M", 1
MoveTo 407, 465
Delay 434
KeyDown "Ctrl", 1
MoveTo 386, 509
Delay 534
KeyDown "Ctrl", 1
MoveTo 386, 506
Delay 3
KeyDown "Ctrl", 1
MoveTo 386, 505
Delay 62
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 4
RightDown 1
KeyDown "Ctrl", 1
Delay 63
Delay 4
KeyDown "Ctrl", 1
Delay 31
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 36
Delay 28
KeyDown "Ctrl", 1
Delay 128
Delay 3
KeyDown "Ctrl", 1
Delay 48
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 3
KeyDown "Ctrl", 1
Delay 31
KeyUp "Ctrl", 1
MoveTo 525, 342
Delay 2242
KeyDown "Shift", 1
MoveTo 674, 330
Delay 366
LeftClick 1
Delay 4
KeyDown "Shift", 1
MoveTo 678, 345
Delay 33
KeyDown "Shift", 1
MoveTo 678, 353
Delay 32
KeyDown "Shift", 1
MoveTo 679, 356
Delay 33
KeyDown "Shift", 1
MoveTo 680, 358
Delay 35
KeyDown "Shift", 1
Delay 32
MoveTo 681, 359
Delay 34
KeyDown "Shift", 1
MoveTo 681, 361
Delay 32
KeyDown "Shift", 1
MoveTo 681, 362
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
MoveTo 682, 363
Delay 2
LeftDown 1
Delay 45
KeyDown "Shift", 1
Delay 1
Delay 34
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 33
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 683, 373
Delay 33
KeyDown "Shift", 1
MoveTo 682, 384
Delay 36
KeyDown "Shift", 1
MoveTo 682, 392
Delay 35
KeyDown "Shift", 1
MoveTo 681, 398
Delay 32
KeyDown "Shift", 1
MoveTo 681, 403
Delay 34
KeyDown "Shift", 1
MoveTo 681, 407
Delay 33
KeyDown "Shift", 1
MoveTo 681, 411
Delay 36
KeyDown "Shift", 1
MoveTo 681, 413
Delay 32
KeyDown "Shift", 1
MoveTo 681, 414
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 681, 415
Delay 35
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 1
KeyDown "Shift", 1
Delay 40
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 34
KeyUp "Shift", 1
MoveTo 681, 417
Delay 400
KeyDown "M", 1
MoveTo 657, 425
Delay 133
KeyUp "M", 1
MoveTo 413, 448
Delay 367
KeyDown "Ctrl", 1
MoveTo 353, 500
Delay 500
KeyDown "Ctrl", 1
MoveTo 355, 500
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 358, 499
Delay 35
KeyDown "Ctrl", 1
Delay 32
MoveTo 361, 497
Delay 37
KeyDown "Ctrl", 1
MoveTo 365, 495
Delay 31
RightDown 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 368, 492
Delay 31
KeyDown "Ctrl", 1
MoveTo 370, 492
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 105
KeyDown "Ctrl", 1
Delay 21
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 2
KeyUp "Ctrl", 1
MoveTo 705, 354
Delay 2480
KeyDown "Shift", 1
MoveTo 721, 338
Delay 269
LeftClick 1
MoveTo 724, 359
Delay 172
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 45
Delay 1
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 35
KeyDown "Shift", 1
Delay 36
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 41
KeyDown "Shift", 1
Delay 36
MoveTo 731, 370
Delay 34
KeyDown "Shift", 1
MoveTo 744, 392
Delay 35
KeyDown "Shift", 1
MoveTo 744, 399
Delay 31
KeyDown "Shift", 1
MoveTo 744, 405
Delay 34
KeyDown "Shift", 1
MoveTo 742, 409
Delay 36
KeyDown "Shift", 1
MoveTo 741, 413
Delay 39
KeyDown "Shift", 1
MoveTo 739, 415
Delay 33
KeyDown "Shift", 1
Delay 38
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 2
Delay 36
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 32
Delay 2
KeyUp "Shift", 1
MoveTo 734, 421
Delay 398
KeyDown "M", 1
MoveTo 704, 425
Delay 138
KeyUp "M", 1
MoveTo 219, 443
Delay 400
KeyDown "Ctrl", 1
MoveTo 311, 514
Delay 499
KeyDown "Ctrl", 1
MoveTo 314, 515
Delay 33
KeyDown "Ctrl", 1
MoveTo 323, 517
Delay 34
KeyDown "Ctrl", 1
MoveTo 330, 520
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 55
KeyDown "Ctrl", 1
Delay 52
MoveTo 331, 520
Delay 3
KeyUp "Ctrl", 1
MoveTo 697, 377
Delay 2771
KeyDown "Shift", 1
MoveTo 709, 331
Delay 416
LeftDown 1
Delay 74
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 36
KeyDown "Shift", 1
MoveTo 709, 340
Delay 35
KeyDown "Shift", 1
MoveTo 709, 346
Delay 46
KeyDown "Shift", 1
MoveTo 709, 357
Delay 34
KeyDown "Shift", 1
MoveTo 709, 358
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 2
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 42
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
MoveTo 709, 372
Delay 35
KeyDown "Shift", 1
MoveTo 711, 392
Delay 35
KeyDown "Shift", 1
MoveTo 713, 409
Delay 34
KeyDown "Shift", 1
MoveTo 715, 417
Delay 36
KeyDown "Shift", 1
MoveTo 715, 418
Delay 31
KeyDown "Shift", 1
Delay 35
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 716, 422
Delay 36
KeyDown "Shift", 1
MoveTo 716, 426
Delay 31
KeyDown "Shift", 1
MoveTo 716, 431
Delay 35
KeyDown "Shift", 1
MoveTo 717, 434
Delay 37
KeyDown "Shift", 1
Delay 66
MoveTo 717, 432
Delay 34
KeyDown "Shift", 1
MoveTo 717, 423
Delay 36
KeyDown "Shift", 1
MoveTo 717, 416
Delay 31
KeyDown "Shift", 1
MoveTo 717, 415
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 39
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 717, 424
Delay 33
KeyDown "Shift", 1
MoveTo 717, 436
Delay 34
KeyDown "Shift", 1
MoveTo 717, 442
Delay 35
KeyDown "Shift", 1
MoveTo 717, 443
Delay 34
KeyDown "Shift", 1
MoveTo 717, 445
Delay 33
KeyDown "Shift", 1
MoveTo 717, 446
Delay 34
KeyDown "Shift", 1
MoveTo 717, 448
Delay 3
KeyDown "Shift", 1
Delay 66
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 35
KeyDown "Shift", 1
MoveTo 717, 457
Delay 34
KeyDown "Shift", 1
MoveTo 721, 472
Delay 38
KeyDown "Shift", 1
MoveTo 722, 481
Delay 34
KeyDown "Shift", 1
MoveTo 723, 485
Delay 34
KeyDown "Shift", 1
MoveTo 723, 487
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 720, 486
Delay 542
KeyDown "M", 1
MoveTo 711, 485
Delay 142
KeyUp "M", 1
MoveTo 478, 491
Delay 333
KeyDown "Ctrl", 1
MoveTo 304, 529
Delay 533
KeyDown "Ctrl", 1
Delay 33
MoveTo 303, 528
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 37
Delay 30
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 93
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 23
KeyDown "Ctrl", 1
Delay 1
Delay 32
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 585, 300
Delay 2503
KeyDown "Shift", 1
MoveTo 585, 331
Delay 344
LeftClick 1
MoveTo 587, 332
Delay 67
KeyDown "Shift", 1
MoveTo 590, 342
Delay 34
KeyDown "Shift", 1
MoveTo 591, 343
Delay 33
KeyDown "Shift", 1
MoveTo 593, 346
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 44
KeyDown "Shift", 1
Delay 1
Delay 32
KeyDown "Shift", 1
MoveTo 593, 348
Delay 34
KeyDown "Shift", 1
MoveTo 594, 352
Delay 33
KeyDown "Shift", 1
MoveTo 595, 358
Delay 45
KeyDown "Shift", 1
MoveTo 602, 374
Delay 34
KeyDown "Shift", 1
MoveTo 608, 388
Delay 34
KeyDown "Shift", 1
MoveTo 609, 389
Delay 33
KeyDown "Shift", 1
MoveTo 612, 394
Delay 34
KeyDown "Shift", 1
MoveTo 615, 400
Delay 32
KeyDown "Shift", 1
MoveTo 618, 403
Delay 35
KeyDown "Shift", 1
MoveTo 621, 411
Delay 40
KeyDown "Shift", 1
MoveTo 623, 417
Delay 35
KeyDown "Shift", 1
MoveTo 625, 421
Delay 2
KeyDown "Shift", 1
MoveTo 626, 422
Delay 62
KeyDown "Shift", 1
Delay 35
Delay 1
KeyDown "Shift", 1
Delay 39
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
Delay 39
KeyDown "Shift", 1
Delay 38
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 64
Delay 1
KeyUp "Shift", 1
Delay 334
KeyDown "M", 1
MoveTo 616, 431
Delay 133
KeyUp "M", 1
MoveTo 415, 511
Delay 300
KeyDown "Ctrl", 1
MoveTo 247, 524
Delay 501
KeyDown "Ctrl", 1
MoveTo 249, 526
Delay 32
KeyDown "Ctrl", 1
MoveTo 250, 529
Delay 34
KeyDown "Ctrl", 1
MoveTo 251, 529
Delay 33
KeyDown "Ctrl", 1
MoveTo 253, 529
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 254, 529
Delay 3
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 112
KeyDown "Ctrl", 1
Delay 60
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
Delay 1
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 501, 393
Delay 2276
KeyDown "Shift", 1
MoveTo 686, 337
Delay 413
LeftDown 1
Delay 108
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 2
MoveTo 686, 339
Delay 76
KeyDown "Shift", 1
MoveTo 692, 357
Delay 33
KeyDown "Shift", 1
Delay 41
Delay 39
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 39
KeyDown "Shift", 1
Delay 36
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 37
LeftUp 1
MoveTo 692, 358
Delay 4
KeyDown "Shift", 1
MoveTo 693, 378
Delay 37
KeyDown "Shift", 1
MoveTo 697, 407
Delay 35
KeyDown "Shift", 1
MoveTo 705, 418
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 707, 419
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 2
Delay 32
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
Delay 551
KeyDown "M", 1
MoveTo 675, 431
Delay 133
KeyUp "M", 1
MoveTo 332, 471
Delay 469
KeyDown "Ctrl", 1
MoveTo 230, 487
Delay 498
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 119
KeyDown "Ctrl", 1
Delay 49
Delay 18
KeyDown "Ctrl", 1
Delay 1
Delay 14
KeyDown "Ctrl", 1
Delay 3
KeyUp "Ctrl", 1
MoveTo 716, 317
Delay 2699
KeyDown "Shift", 1
MoveTo 718, 336
Delay 348
LeftClick 1
MoveTo 718, 353
Delay 85
KeyDown "Shift", 1
MoveTo 718, 364
Delay 4
KeyDown "Shift", 1
MoveTo 719, 367
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 41
KeyDown "Shift", 1
MoveTo 720, 368
Delay 39
KeyDown "Shift", 1
Delay 39
Delay 3
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 35
MoveTo 723, 381
Delay 37
KeyDown "Shift", 1
MoveTo 725, 397
Delay 38
KeyDown "Shift", 1
MoveTo 726, 410
Delay 38
KeyDown "Shift", 1
MoveTo 727, 416
Delay 34
KeyDown "Shift", 1
MoveTo 727, 419
Delay 3
KeyDown "Shift", 1
MoveTo 727, 421
Delay 37
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 36
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 36
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 36
KeyUp "Shift", 1
MoveTo 725, 425
Delay 402
KeyDown ",", 1
MoveTo 709, 429
Delay 143
KeyUp ",", 1
MoveTo 678, 429
Delay 541
KeyDown ",", 1
MoveTo 676, 428
Delay 136
KeyUp ",", 1
MoveTo 657, 429
Delay 1046
KeyDown "M", 1
Delay 131
KeyUp "M", 1
MoveTo 213, 474
Delay 835
KeyDown "Shift", 1
MoveTo 204, 507
Delay 498
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
MoveTo 204, 505
Delay 35
KeyDown "Shift", 1
MoveTo 204, 504
Delay 31
KeyDown "Shift", 1
MoveTo 205, 501
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
RightDown 1
Delay 2
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 35
RightClick 1
Delay 8
KeyDown "Shift", 1
Delay 24
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 215, 501
Delay 3
KeyDown "Shift", 1
MoveTo 217, 501
Delay 32
KeyDown "Shift", 1
MoveTo 219, 500
Delay 65
KeyUp "Shift", 1
MoveTo 1668, 619
Delay 934
LeftClick 1
MoveTo 222, 495
Delay 3167
KeyDown "Esc", 1
Delay 96
KeyUp "Esc", 1
Delay 502
KeyDown "M", 1
Delay 134
KeyUp "M", 1
MoveTo 231, 503
Delay 1634
KeyDown "Ctrl", 1
MoveTo 235, 494
Delay 499
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 36
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 29
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 138
KeyDown "Ctrl", 1
Delay 53
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 61
KeyDown "Ctrl", 1
Delay 34
Delay 51
KeyDown "Ctrl", 1
Delay 34
Delay 10
KeyDown "Ctrl", 1
Delay 9
Delay 17
KeyUp "Ctrl", 1
MoveTo 628, 346
Delay 2269
KeyDown "Shift", 1
MoveTo 651, 333
Delay 246
LeftClick 1
MoveTo 665, 360
Delay 173
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 43
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 669, 374
Delay 36
KeyDown "Shift", 1
MoveTo 684, 409
Delay 33
KeyDown "Shift", 1
MoveTo 692, 421
Delay 33
KeyDown "Shift", 1
MoveTo 693, 423
Delay 33
KeyDown "Shift", 1
MoveTo 693, 424
Delay 4
KeyDown "Shift", 1
Delay 62
Delay 35
KeyDown "Shift", 1
MoveTo 691, 423
Delay 67
KeyDown "Shift", 1
MoveTo 690, 420
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 39
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
KeyUp "Shift", 1
MoveTo 689, 420
Delay 544
KeyDown "M", 1
Delay 196
KeyUp "M", 1
MoveTo 417, 403
Delay 334
KeyDown "Ctrl", 1
MoveTo 225, 477
Delay 499
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 227, 476
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 228, 475
Delay 37
KeyDown "Ctrl", 1
MoveTo 231, 471
Delay 31
KeyDown "Ctrl", 1
MoveTo 232, 470
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 70
KeyDown "Ctrl", 1
Delay 1
Delay 60
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 575, 282
Delay 2494
KeyDown "Shift", 1
MoveTo 598, 336
Delay 467
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 2
LeftUp 1
Delay 35
KeyDown "Shift", 1
MoveTo 601, 343
Delay 33
KeyDown "Shift", 1
MoveTo 608, 360
Delay 37
KeyDown "Shift", 1
MoveTo 612, 367
Delay 32
KeyDown "Shift", 1
MoveTo 613, 370
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 4
KeyDown "Shift", 1
MoveTo 613, 368
Delay 31
KeyDown "Shift", 1
MoveTo 613, 367
Delay 33
KeyDown "Shift", 1
MoveTo 613, 365
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
MoveTo 616, 364
Delay 35
KeyDown "Shift", 1
MoveTo 632, 371
Delay 32
KeyDown "Shift", 1
MoveTo 645, 378
Delay 39
KeyDown "Shift", 1
MoveTo 651, 382
Delay 33
KeyDown "Shift", 1
Delay 31
MoveTo 653, 384
Delay 35
KeyDown "Shift", 1
MoveTo 656, 387
Delay 35
KeyDown "Shift", 1
MoveTo 660, 389
Delay 32
KeyDown "Shift", 1
MoveTo 662, 391
Delay 32
KeyDown "Shift", 1
MoveTo 665, 393
Delay 44
KeyDown "Shift", 1
MoveTo 667, 395
Delay 2
KeyDown "Shift", 1
MoveTo 671, 398
Delay 64
KeyDown "Shift", 1
MoveTo 674, 400
Delay 33
KeyDown "Shift", 1
MoveTo 676, 402
Delay 3
KeyDown "Shift", 1
MoveTo 679, 405
Delay 32
KeyDown "Shift", 1
Delay 32
MoveTo 680, 406
Delay 35
KeyDown "Shift", 1
MoveTo 681, 408
Delay 41
KeyDown "Shift", 1
MoveTo 681, 409
Delay 34
KeyDown "Shift", 1
MoveTo 681, 411
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 43
KeyDown "Shift", 1
Delay 41
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 47
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 64
MoveTo 681, 397
Delay 37
KeyDown "Shift", 1
MoveTo 681, 392
Delay 35
KeyDown "Shift", 1
MoveTo 681, 391
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
MoveTo 681, 390
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 31
KeyDown "Shift", 1
Delay 34
MoveTo 681, 381
Delay 33
KeyDown "Shift", 1
MoveTo 681, 373
Delay 34
KeyDown "Shift", 1
MoveTo 681, 368
Delay 35
KeyDown "Shift", 1
MoveTo 681, 366
Delay 34
KeyDown "Shift", 1
MoveTo 681, 364
Delay 33
KeyDown "Shift", 1
MoveTo 681, 360
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 681, 359
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 37
Delay 36
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
Delay 336
KeyDown "M", 1
Delay 163
KeyUp "M", 1
MoveTo 298, 469
Delay 401
KeyDown "Ctrl", 1
MoveTo 233, 498
Delay 499
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 109
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 19
Delay 1
KeyDown "Ctrl", 1
Delay 13
KeyUp "Ctrl", 1
MoveTo 763, 351
Delay 3330
KeyDown "Shift", 1
MoveTo 765, 337
Delay 518
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 43
Delay 41
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 34
MoveTo 766, 341
Delay 41
KeyDown "Shift", 1
MoveTo 768, 351
Delay 1
KeyDown "Shift", 1
MoveTo 770, 355
Delay 38
KeyDown "Shift", 1
MoveTo 771, 357
Delay 34
KeyDown "Shift", 1
MoveTo 772, 358
Delay 34
KeyDown "Shift", 1
Delay 39
Delay 37
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 40
KeyDown "Shift", 1
Delay 39
Delay 43
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 41
Delay 33
KeyDown "Shift", 1
Delay 5
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 40
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 35
MoveTo 772, 361
Delay 34
KeyDown "Shift", 1
MoveTo 772, 384
Delay 4
KeyDown "Shift", 1
MoveTo 772, 391
Delay 36
KeyDown "Shift", 1
MoveTo 772, 393
Delay 50
KeyDown "Shift", 1
MoveTo 772, 395
Delay 30
KeyDown "Shift", 1
MoveTo 772, 396
Delay 34
KeyDown "Shift", 1
MoveTo 773, 398
Delay 39
KeyDown "Shift", 1
MoveTo 774, 401
Delay 40
KeyDown "Shift", 1
MoveTo 774, 406
Delay 3
KeyDown "Shift", 1
MoveTo 774, 412
Delay 32
KeyDown "Shift", 1
MoveTo 774, 414
Delay 35
KeyDown "Shift", 1
Delay 31
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 41
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 39
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 37
KeyUp "Shift", 1
Delay 451
KeyDown "M", 1
MoveTo 772, 417
Delay 131
KeyUp "M", 1
MoveTo 462, 492
Delay 367
KeyDown "Ctrl", 1
MoveTo 270, 568
Delay 534
KeyDown "Ctrl", 1
MoveTo 254, 569
Delay 32
KeyDown "Ctrl", 1
MoveTo 247, 571
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 33
MoveTo 248, 571
Delay 34
KeyDown "Ctrl", 1
MoveTo 249, 571
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 4
KeyDown "Ctrl", 1
Delay 65
Delay 65
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 4
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 121
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 249, 572
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 249, 573
Delay 34
KeyDown "Ctrl", 1
MoveTo 249, 574
Delay 34
KeyDown "Ctrl", 1
MoveTo 251, 577
Delay 35
KeyDown "Ctrl", 1
MoveTo 253, 579
Delay 31
KeyDown "Ctrl", 1
Delay 24
Delay 1
KeyDown "Ctrl", 1
MoveTo 253, 580
Delay 8
KeyUp "Ctrl", 1
MoveTo 680, 413
Delay 1922
KeyDown "Shift", 1
MoveTo 739, 334
Delay 379
LeftClick 1
Delay 34
KeyDown "Shift", 1
MoveTo 739, 345
Delay 33
KeyDown "Shift", 1
MoveTo 740, 354
Delay 35
KeyDown "Shift", 1
MoveTo 740, 356
Delay 31
KeyDown "Shift", 1
Delay 43
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 35
KeyDown "Shift", 1
Delay 40
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 37
Delay 31
KeyDown "Shift", 1
Delay 35
Delay 1
Delay 35
KeyDown "Shift", 1
Delay 38
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 744, 381
Delay 36
KeyDown "Shift", 1
MoveTo 749, 405
Delay 34
KeyDown "Shift", 1
MoveTo 750, 414
Delay 33
KeyDown "Shift", 1
MoveTo 751, 418
Delay 43
KeyDown "Shift", 1
MoveTo 752, 425
Delay 35
KeyDown "Shift", 1
MoveTo 752, 428
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 2
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 39
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
MoveTo 752, 429
Delay 407
KeyDown "M", 1
MoveTo 731, 449
Delay 139
KeyUp "M", 1
MoveTo 450, 589
Delay 332
KeyDown "Ctrl", 1
MoveTo 282, 578
Delay 499
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 4
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 91
Delay 34
KeyDown "Ctrl", 1
Delay 24
Delay 2
KeyDown "Ctrl", 1
Delay 7
Delay 1
KeyUp "Ctrl", 1
MoveTo 644, 309
Delay 3553
KeyDown "Shift", 1
MoveTo 654, 328
Delay 330
LeftDown 1
MoveTo 655, 329
Delay 116
LeftUp 1
MoveTo 662, 346
Delay 74
KeyDown "Shift", 1
MoveTo 668, 359
Delay 53
KeyDown "Shift", 1
MoveTo 671, 365
Delay 1
KeyDown "Shift", 1
Delay 37
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 36
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 65
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
MoveTo 672, 372
Delay 33
KeyDown "Shift", 1
MoveTo 679, 395
Delay 38
KeyDown "Shift", 1
MoveTo 684, 411
Delay 39
KeyDown "Shift", 1
MoveTo 685, 415
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 3
LeftDown 1
Delay 40
KeyDown "Shift", 1
Delay 36
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 685, 419
Delay 404
KeyDown "M", 1
MoveTo 683, 423
Delay 170
KeyUp "M", 1
MoveTo 488, 574
Delay 331
KeyDown "Ctrl", 1
MoveTo 325, 582
Delay 501
KeyDown "Ctrl", 1
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 81
Delay 1
KeyDown "Ctrl", 1
Delay 35
Delay 1
KeyUp "Ctrl", 1
MoveTo 551, 361
Delay 2606
KeyDown "Shift", 1
MoveTo 589, 361
Delay 505
KeyDown "Shift", 1
Delay 35
Delay 37
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 48
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 42
KeyDown "Shift", 1
MoveTo 598, 374
Delay 36
KeyDown "Shift", 1
MoveTo 612, 390
Delay 33
KeyDown "Shift", 1
MoveTo 623, 399
Delay 38
KeyDown "Shift", 1
MoveTo 627, 403
Delay 34
KeyDown "Shift", 1
MoveTo 628, 404
Delay 34
KeyDown "Shift", 1
Delay 40
Delay 38
KeyDown "Shift", 1
Delay 38
Delay 39
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 41
KeyDown "Shift", 1
Delay 37
Delay 40
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 39
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 642, 422
Delay 499
KeyDown "M", 1
Delay 143
KeyUp "M", 1
MoveTo 523, 509
Delay 335
KeyDown "Ctrl", 1
MoveTo 342, 563
Delay 498
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
MoveTo 341, 563
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 146
Delay 2
KeyDown "Ctrl", 1
Delay 53
MoveTo 342, 562
Delay 50
KeyDown "Ctrl", 1
MoveTo 348, 562
Delay 2
KeyDown "Ctrl", 1
MoveTo 349, 562
Delay 31
KeyDown "Ctrl", 1
MoveTo 351, 562
Delay 45
KeyDown "Ctrl", 1
MoveTo 359, 562
Delay 22
KeyDown "Ctrl", 1
MoveTo 376, 560
Delay 35
KeyDown "Ctrl", 1
MoveTo 404, 547
Delay 33
KeyDown "Ctrl", 1
Delay 24
Delay 3
KeyDown "Ctrl", 1
MoveTo 485, 521
Delay 7
KeyUp "Ctrl", 1
MoveTo 823, 290
Delay 2328
KeyDown "Shift", 1
MoveTo 772, 369
Delay 423
LeftClick 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 772, 373
Delay 35
KeyDown "Shift", 1
MoveTo 772, 380
Delay 48
KeyDown "Shift", 1
MoveTo 772, 384
Delay 32
KeyDown "Shift", 1
MoveTo 772, 386
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 772, 391
Delay 37
KeyDown "Shift", 1
MoveTo 772, 398
Delay 32
KeyDown "Shift", 1
MoveTo 772, 403
Delay 34
KeyDown "Shift", 1
MoveTo 772, 407
Delay 3
KeyDown "Shift", 1
MoveTo 771, 411
Delay 65
KeyDown "Shift", 1
MoveTo 771, 413
Delay 2
KeyDown "Shift", 1
Delay 66
Delay 1
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 45
KeyUp "Shift", 1
MoveTo 766, 418
Delay 371
KeyDown "M", 1
MoveTo 760, 424
Delay 137
KeyUp "M", 1
MoveTo 559, 552
Delay 330
KeyDown "Ctrl", 1
MoveTo 386, 570
Delay 499
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 385, 570
Delay 35
KeyDown "Ctrl", 1
Delay 34
MoveTo 384, 570
Delay 32
KeyDown "Ctrl", 1
MoveTo 381, 570
Delay 35
KeyDown "Ctrl", 1
Delay 31
MoveTo 379, 570
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 378, 570
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 36
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 28
KeyDown "Ctrl", 1
Delay 1
Delay 88
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 787, 335
Delay 2463
KeyDown "Shift", 1
MoveTo 775, 364
Delay 265
LeftClick 1
MoveTo 779, 387
Delay 169
KeyDown "Shift", 1
MoveTo 780, 395
Delay 38
KeyDown "Shift", 1
MoveTo 780, 399
Delay 35
KeyDown "Shift", 1
MoveTo 780, 402
Delay 40
KeyDown "Shift", 1
MoveTo 780, 403
Delay 42
KeyDown "Shift", 1
MoveTo 780, 404
Delay 34
KeyDown "Shift", 1
MoveTo 781, 405
Delay 32
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 39
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
Delay 500
KeyDown "M", 1
MoveTo 781, 407
Delay 169
KeyUp "M", 1
MoveTo 539, 513
Delay 334
KeyDown "Ctrl", 1
MoveTo 426, 558
Delay 499
KeyDown "Ctrl", 1
MoveTo 425, 559
Delay 34
KeyDown "Ctrl", 1
MoveTo 422, 562
Delay 34
KeyDown "Ctrl", 1
MoveTo 421, 562
Delay 33
KeyDown "Ctrl", 1
MoveTo 416, 563
Delay 34
KeyDown "Ctrl", 1
MoveTo 413, 563
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 4
RightClick 1
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 49
Delay 1
KeyDown "Ctrl", 1
Delay 47
Delay 2
KeyUp "Ctrl", 1
MoveTo 749, 332
Delay 2546
KeyDown "Shift", 1
MoveTo 748, 365
Delay 386
LeftClick 1
MoveTo 748, 367
Delay 70
KeyDown "Shift", 1
MoveTo 749, 380
Delay 34
KeyDown "Shift", 1
MoveTo 752, 390
Delay 34
KeyDown "Shift", 1
MoveTo 752, 397
Delay 4
KeyDown "Shift", 1
MoveTo 752, 401
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
MoveTo 752, 403
Delay 35
KeyDown "Shift", 1
MoveTo 753, 405
Delay 51
KeyDown "Shift", 1
MoveTo 754, 409
Delay 36
KeyDown "Shift", 1
MoveTo 754, 411
Delay 4
KeyDown "Shift", 1
MoveTo 755, 415
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 38
KeyDown "Shift", 1
LeftUp 1
MoveTo 755, 416
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 1
KeyUp "Shift", 1
MoveTo 755, 429
Delay 372
KeyDown "M", 1
MoveTo 754, 437
Delay 132
KeyUp "M", 1
MoveTo 638, 563
Delay 366
KeyDown "Ctrl", 1
MoveTo 480, 569
Delay 533
KeyDown "Ctrl", 1
Delay 34
MoveTo 478, 568
Delay 3
KeyDown "Ctrl", 1
Delay 30
MoveTo 476, 566
Delay 35
KeyDown "Ctrl", 1
MoveTo 475, 566
Delay 32
KeyDown "Ctrl", 1
Delay 32
MoveTo 475, 564
Delay 35
KeyDown "Ctrl", 1
MoveTo 474, 563
Delay 32
KeyDown "Ctrl", 1
Delay 34
MoveTo 473, 561
Delay 33
KeyDown "Ctrl", 1
MoveTo 473, 560
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 31
KeyDown "Ctrl", 1
Delay 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 667, 394
Delay 2600
KeyDown "Shift", 1
MoveTo 704, 365
Delay 515
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 46
KeyDown "Shift", 1
MoveTo 705, 367
Delay 33
KeyDown "Shift", 1
MoveTo 709, 383
Delay 32
KeyDown "Shift", 1
MoveTo 713, 394
Delay 34
KeyDown "Shift", 1
MoveTo 714, 401
Delay 34
KeyDown "Shift", 1
MoveTo 714, 403
Delay 32
KeyDown "Shift", 1
MoveTo 715, 404
Delay 33
KeyDown "Shift", 1
Delay 36
MoveTo 717, 407
Delay 33
KeyDown "Shift", 1
MoveTo 718, 409
Delay 33
KeyDown "Shift", 1
MoveTo 718, 411
Delay 33
KeyDown "Shift", 1
MoveTo 718, 415
Delay 33
KeyDown "Shift", 1
MoveTo 718, 416
Delay 32
KeyDown "Shift", 1
MoveTo 718, 417
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 39
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
MoveTo 725, 431
Delay 272
KeyDown "M", 1
MoveTo 728, 446
Delay 136
KeyUp "M", 1
MoveTo 511, 541
Delay 2000
LeftClick 1
Delay 500
RightDown 1
Delay 133
RightClick 1
MoveTo 1675, 604
Delay 1334
LeftClick 1
MoveTo 537, 545
Delay 1201
KeyDown "Esc", 1
MoveTo 528, 545
Delay 143
KeyUp "Esc", 1
Delay 522
KeyDown "M", 1
Delay 101
KeyUp "M", 1
MoveTo 515, 548
Delay 634
KeyDown "Ctrl", 1
MoveTo 514, 553
Delay 267
RightDown 1
Delay 166
RightClick 1
Delay 204
KeyDown "Ctrl", 1
Delay 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 532, 541
Delay 1
KeyDown "Ctrl", 1
MoveTo 538, 539
Delay 2
KeyUp "Ctrl", 1
MoveTo 722, 358
Delay 3607
KeyDown "Shift", 1
Delay 239
LeftClick 1
MoveTo 738, 402
Delay 167
KeyDown "Shift", 1
MoveTo 741, 410
Delay 36
KeyDown "Shift", 1
MoveTo 743, 413
Delay 33
KeyDown "Shift", 1
MoveTo 743, 416
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 42
KeyDown "Shift", 1
Delay 40
LeftUp 1
Delay 9
KeyDown "Shift", 1
Delay 29
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyUp "Shift", 1
Delay 433
KeyDown "M", 1
MoveTo 741, 419
Delay 164
KeyUp "M", 1
MoveTo 532, 509
Delay 367
KeyDown "Ctrl", 1
MoveTo 538, 516
Delay 532
KeyDown "Ctrl", 1
MoveTo 538, 513
Delay 35
KeyDown "Ctrl", 1
MoveTo 539, 510
Delay 32
KeyDown "Ctrl", 1
MoveTo 545, 505
Delay 33
KeyDown "Ctrl", 1
MoveTo 546, 504
Delay 5
KeyDown "Ctrl", 1
Delay 62
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 2
MoveTo 547, 502
Delay 31
KeyDown "Ctrl", 1
MoveTo 547, 500
Delay 34
KeyDown "Ctrl", 1
MoveTo 547, 499
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 35
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 36
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 13
Delay 1
KeyDown "Ctrl", 1
Delay 20
KeyUp "Ctrl", 1
MoveTo 670, 353
Delay 3298
KeyDown "Shift", 1
MoveTo 675, 334
Delay 492
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
MoveTo 677, 334
Delay 33
KeyDown "Shift", 1
MoveTo 684, 351
Delay 34
KeyDown "Shift", 1
MoveTo 689, 366
Delay 33
KeyDown "Shift", 1
MoveTo 692, 379
Delay 34
KeyDown "Shift", 1
MoveTo 694, 390
Delay 33
KeyDown "Shift", 1
MoveTo 694, 399
Delay 33
KeyDown "Shift", 1
MoveTo 696, 406
Delay 34
KeyDown "Shift", 1
MoveTo 696, 411
Delay 33
KeyDown "Shift", 1
MoveTo 697, 414
Delay 34
KeyDown "Shift", 1
MoveTo 697, 419
Delay 33
KeyDown "Shift", 1
MoveTo 697, 420
Delay 34
KeyDown "Shift", 1
MoveTo 697, 421
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 39
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 34
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
Delay 367
KeyDown "M", 1
MoveTo 697, 422
Delay 160
KeyUp "M", 1
MoveTo 578, 470
Delay 268
KeyDown "Ctrl", 1
MoveTo 479, 497
Delay 532
KeyDown "Ctrl", 1
Delay 33
Delay 4
KeyDown "Ctrl", 1
MoveTo 480, 492
Delay 32
KeyDown "Ctrl", 1
MoveTo 485, 489
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 35
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
MoveTo 486, 488
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 117
KeyDown "Ctrl", 1
Delay 45
Delay 1
KeyDown "Ctrl", 1
Delay 9
Delay 1
KeyUp "Ctrl", 1
MoveTo 618, 343
Delay 2414
KeyDown "Shift", 1
MoveTo 662, 343
Delay 343
LeftDown 1
MoveTo 663, 343
Delay 73
LeftUp 1
MoveTo 670, 352
Delay 105
KeyDown "Shift", 1
MoveTo 670, 354
Delay 37
KeyDown "Shift", 1
MoveTo 670, 356
Delay 33
KeyDown "Shift", 1
Delay 48
MoveTo 671, 356
Delay 34
KeyDown "Shift", 1
Delay 34
MoveTo 672, 357
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 32
MoveTo 672, 367
Delay 35
KeyDown "Shift", 1
MoveTo 675, 385
Delay 33
KeyDown "Shift", 1
MoveTo 679, 399
Delay 33
KeyDown "Shift", 1
MoveTo 680, 405
Delay 33
KeyDown "Shift", 1
MoveTo 681, 408
Delay 38
KeyDown "Shift", 1
MoveTo 682, 411
Delay 32
KeyDown "Shift", 1
MoveTo 682, 413
Delay 33
KeyDown "Shift", 1
MoveTo 683, 414
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 684, 414
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 39
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 35
KeyDown "Shift", 1
Delay 4
KeyUp "Shift", 1
MoveTo 684, 417
Delay 342
KeyDown "M", 1
MoveTo 664, 422
Delay 171
KeyUp "M", 1
MoveTo 424, 467
Delay 534
KeyDown "Ctrl", 1
MoveTo 437, 511
Delay 499
RightDown 1
MoveTo 438, 512
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 63
Delay 99
KeyDown "Ctrl", 1
Delay 1
Delay 9
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 657, 333
Delay 2532
KeyDown "Shift", 1
Delay 234
LeftClick 1
MoveTo 678, 356
Delay 203
KeyDown "Shift", 1
Delay 34
Delay 3
LeftDown 1
Delay 48
KeyDown "Shift", 1
Delay 36
Delay 41
LeftUp 1
Delay 3
KeyDown "Shift", 1
MoveTo 678, 362
Delay 35
KeyDown "Shift", 1
MoveTo 687, 388
Delay 36
KeyDown "Shift", 1
MoveTo 699, 412
Delay 38
KeyDown "Shift", 1
MoveTo 702, 417
Delay 33
KeyDown "Shift", 1
MoveTo 703, 418
Delay 33
KeyDown "Shift", 1
MoveTo 704, 418
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 38
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
Delay 365
KeyDown "M", 1
MoveTo 693, 426
Delay 132
KeyUp "M", 1
MoveTo 569, 428
Delay 299
KeyDown "Ctrl", 1
MoveTo 373, 486
Delay 501
KeyDown "Ctrl", 1
MoveTo 375, 489
Delay 34
KeyDown "Ctrl", 1
MoveTo 375, 490
Delay 32
KeyDown "Ctrl", 1
MoveTo 376, 491
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 377, 491
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 378, 492
Delay 2
RightDown 1
MoveTo 378, 493
Delay 32
KeyDown "Ctrl", 1
MoveTo 379, 494
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 71
KeyDown "Ctrl", 1
Delay 1
Delay 33
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 575, 357
Delay 2465
KeyDown "Shift", 1
MoveTo 627, 337
Delay 449
LeftDown 1
Delay 68
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
MoveTo 628, 349
Delay 34
KeyDown "Shift", 1
MoveTo 629, 363
Delay 5
KeyDown "Shift", 1
MoveTo 632, 374
Delay 43
KeyDown "Shift", 1
MoveTo 632, 375
Delay 33
KeyDown "Shift", 1
MoveTo 633, 376
Delay 41
KeyDown "Shift", 1
Delay 46
Delay 40
KeyDown "Shift", 1
MoveTo 636, 371
Delay 35
KeyDown "Shift", 1
MoveTo 637, 366
Delay 38
KeyDown "Shift", 1
MoveTo 637, 365
Delay 41
KeyDown "Shift", 1
Delay 40
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 41
KeyDown "Shift", 1
Delay 37
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 59
Delay 49
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 35
MoveTo 641, 369
Delay 3
KeyDown "Shift", 1
MoveTo 654, 397
Delay 41
KeyDown "Shift", 1
MoveTo 660, 413
Delay 39
KeyDown "Shift", 1
MoveTo 660, 417
Delay 38
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 662, 417
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 2
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
Delay 334
KeyDown "M", 1
Delay 165
KeyUp "M", 1
MoveTo 569, 424
Delay 266
KeyDown "Ctrl", 1
MoveTo 339, 487
Delay 504
KeyDown "Ctrl", 1
Delay 35
Delay 33
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
MoveTo 340, 486
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 3
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 65
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 65
Delay 33
KeyDown "Ctrl", 1
Delay 2
Delay 60
KeyUp "Ctrl", 1
MoveTo 780, 336
Delay 2549
KeyDown "Shift", 1
MoveTo 762, 361
Delay 339
LeftClick 1
MoveTo 762, 364
Delay 102
KeyDown "Shift", 1
MoveTo 764, 377
Delay 34
KeyDown "Shift", 1
MoveTo 766, 387
Delay 3
KeyDown "Shift", 1
MoveTo 766, 394
Delay 64
KeyDown "Shift", 1
MoveTo 766, 396
Delay 2
KeyDown "Shift", 1
MoveTo 766, 397
Delay 35
KeyDown "Shift", 1
MoveTo 767, 400
Delay 34
KeyDown "Shift", 1
MoveTo 768, 401
Delay 33
KeyDown "Shift", 1
MoveTo 768, 403
Delay 43
KeyDown "Shift", 1
MoveTo 768, 405
Delay 35
KeyDown "Shift", 1
MoveTo 769, 407
Delay 35
KeyDown "Shift", 1
MoveTo 769, 408
Delay 39
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 38
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 31
KeyDown "Shift", 1
Delay 35
Delay 33
KeyUp "Shift", 1
MoveTo 767, 413
Delay 366
KeyDown "M", 1
MoveTo 678, 432
Delay 146
KeyUp "M", 1
MoveTo 388, 410
Delay 267
KeyDown "Ctrl", 1
MoveTo 299, 496
Delay 500
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 36
Delay 31
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 4
KeyDown "Ctrl", 1
Delay 1
Delay 62
KeyDown "Ctrl", 1
Delay 34
Delay 3
KeyDown "Ctrl", 1
Delay 86
KeyDown "Ctrl", 1
Delay 28
Delay 2
KeyUp "Ctrl", 1
MoveTo 576, 304
Delay 2463
KeyDown "Shift", 1
MoveTo 592, 359
Delay 403
LeftClick 1
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 594, 363
Delay 35
KeyDown "Shift", 1
MoveTo 606, 380
Delay 31
KeyDown "Shift", 1
MoveTo 625, 397
Delay 45
KeyDown "Shift", 1
MoveTo 634, 409
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 635, 410
Delay 34
KeyDown "Shift", 1
MoveTo 635, 411
Delay 33
KeyDown "Shift", 1
MoveTo 636, 411
Delay 32
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 38
KeyDown "Shift", 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 2
KeyUp "Shift", 1
Delay 367
KeyDown "M", 1
Delay 168
KeyUp "M", 1
MoveTo 368, 424
Delay 301
KeyDown "Ctrl", 1
MoveTo 273, 487
Delay 501
KeyDown "Ctrl", 1
MoveTo 270, 486
Delay 33
KeyDown "Ctrl", 1
MoveTo 269, 482
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 121
KeyDown "Ctrl", 1
Delay 1
Delay 10
KeyDown "Ctrl", 1
Delay 3
KeyUp "Ctrl", 1
MoveTo 687, 311
Delay 2512
KeyDown "Shift", 1
MoveTo 685, 371
Delay 409
LeftClick 1
Delay 5
KeyDown "Shift", 1
MoveTo 687, 382
Delay 36
KeyDown "Shift", 1
MoveTo 699, 407
Delay 45
KeyDown "Shift", 1
MoveTo 710, 423
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 38
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 37
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 33
KeyUp "Shift", 1
Delay 373
KeyDown "M", 1
Delay 133
KeyUp "M", 1
MoveTo 404, 439
Delay 302
KeyDown "Ctrl", 1
MoveTo 250, 468
Delay 531
KeyDown "Ctrl", 1
MoveTo 258, 476
Delay 34
KeyDown "Ctrl", 1
MoveTo 267, 481
Delay 33
KeyDown "Ctrl", 1
MoveTo 268, 483
Delay 34
KeyDown "Ctrl", 1
MoveTo 269, 483
Delay 32
KeyDown "Ctrl", 1
MoveTo 270, 484
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 272, 486
Delay 34
KeyDown "Ctrl", 1
MoveTo 274, 488
Delay 33
KeyDown "Ctrl", 1
MoveTo 279, 493
Delay 33
KeyDown "Ctrl", 1
MoveTo 282, 497
Delay 5
KeyDown "Ctrl", 1
MoveTo 284, 499
Delay 31
KeyDown "Ctrl", 1
MoveTo 285, 500
Delay 64
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 3
Delay 30
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
MoveTo 287, 505
Delay 33
KeyDown "Ctrl", 1
MoveTo 290, 512
Delay 33
KeyDown "Ctrl", 1
MoveTo 296, 525
Delay 34
KeyDown "Ctrl", 1
MoveTo 308, 541
Delay 33
KeyDown "Ctrl", 1
MoveTo 316, 552
Delay 34
KeyDown "Ctrl", 1
MoveTo 318, 554
Delay 34
KeyDown "Ctrl", 1
MoveTo 318, 555
Delay 33
KeyDown "Ctrl", 1
Delay 32
MoveTo 320, 557
Delay 34
KeyDown "Ctrl", 1
MoveTo 322, 558
Delay 33
KeyDown "Ctrl", 1
MoveTo 326, 559
Delay 33
KeyDown "Ctrl", 1
MoveTo 330, 559
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 110
KeyDown "Ctrl", 1
Delay 3
Delay 64
KeyDown "Ctrl", 1
Delay 34
MoveTo 339, 561
Delay 3
KeyDown "Ctrl", 1
MoveTo 348, 568
Delay 30
KeyDown "Ctrl", 1
Delay 11
Delay 2
KeyDown "Ctrl", 1
Delay 20
KeyUp "Ctrl", 1
MoveTo 665, 458
Delay 2417
KeyDown "Shift", 1
MoveTo 714, 365
Delay 500
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 54
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 714, 373
Delay 33
KeyDown "Shift", 1
MoveTo 715, 389
Delay 35
KeyDown "Shift", 1
MoveTo 715, 398
Delay 33
KeyDown "Shift", 1
MoveTo 715, 405
Delay 33
KeyDown "Shift", 1
MoveTo 715, 406
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 716, 409
Delay 435
KeyDown "M", 1
MoveTo 717, 414
Delay 167
KeyUp "M", 1
MoveTo 450, 565
Delay 430
KeyDown "Ctrl", 1
MoveTo 385, 571
Delay 466
RightDown 1
MoveTo 385, 572
Delay 66
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
MoveTo 385, 573
Delay 3
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 29
Delay 32
KeyDown "Ctrl", 1
Delay 112
MoveTo 385, 574
Delay 52
KeyDown "Ctrl", 1
Delay 3
Delay 29
KeyDown "Ctrl", 1
Delay 33
MoveTo 385, 575
Delay 35
KeyDown "Ctrl", 1
MoveTo 385, 577
Delay 32
KeyDown "Ctrl", 1
Delay 29
Delay 2
KeyDown "Ctrl", 1
MoveTo 389, 577
Delay 4
KeyUp "Ctrl", 1
MoveTo 691, 438
Delay 2248
KeyDown "Shift", 1
MoveTo 708, 358
Delay 366
LeftClick 1
Delay 66
KeyDown "Shift", 1
Delay 35
MoveTo 709, 371
Delay 34
KeyDown "Shift", 1
MoveTo 709, 382
Delay 35
KeyDown "Shift", 1
MoveTo 709, 384
Delay 44
KeyDown "Shift", 1
Delay 34
MoveTo 709, 385
Delay 33
KeyDown "Shift", 1
MoveTo 711, 390
Delay 3
KeyDown "Shift", 1
MoveTo 713, 396
Delay 65
KeyDown "Shift", 1
MoveTo 714, 401
Delay 2
KeyDown "Shift", 1
MoveTo 714, 409
Delay 32
KeyDown "Shift", 1
MoveTo 715, 414
Delay 36
KeyDown "Shift", 1
Delay 32
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 37
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
MoveTo 715, 417
Delay 330
KeyDown "M", 1
MoveTo 712, 426
Delay 163
KeyUp "M", 1
MoveTo 438, 586
Delay 800
KeyDown "Ctrl", 1
MoveTo 438, 578
Delay 233
RightDown 1
Delay 133
RightClick 1
MoveTo 443, 580
Delay 152
KeyDown "Ctrl", 1
MoveTo 444, 582
Delay 34
KeyDown "Ctrl", 1
MoveTo 445, 583
Delay 32
KeyDown "Ctrl", 1
MoveTo 445, 584
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 446, 584
Delay 35
KeyDown "Ctrl", 1
Delay 33
MoveTo 448, 586
Delay 32
KeyDown "Ctrl", 1
MoveTo 457, 587
Delay 35
KeyDown "Ctrl", 1
MoveTo 472, 587
Delay 32
KeyDown "Ctrl", 1
MoveTo 490, 584
Delay 33
KeyDown "Ctrl", 1
Delay 3
MoveTo 496, 582
Delay 1
KeyUp "Ctrl", 1
KeyDown "Ctrl", 1
MoveTo 804, 379
Delay 2301
KeyDown "Shift", 1
MoveTo 804, 362
Delay 253
LeftClick 1
MoveTo 798, 419
Delay 178
KeyDown "Shift", 1
MoveTo 797, 420
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 39
KeyDown "Shift", 1
Delay 33
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 35
KeyUp "Shift", 1
Delay 432
KeyDown "M", 1
MoveTo 797, 421
Delay 161
KeyUp "M", 1
MoveTo 586, 543
Delay 334
KeyDown "Ctrl", 1
MoveTo 490, 574
Delay 532
KeyDown "Ctrl", 1
MoveTo 491, 574
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 120
MoveTo 492, 574
Delay 51
KeyDown "Ctrl", 1
Delay 47
Delay 5
KeyDown "Ctrl", 1
Delay 1
Delay 28
KeyUp "Ctrl", 1
MoveTo 779, 321
Delay 2365
KeyDown "Shift", 1
MoveTo 766, 354
Delay 272
LeftDown 1
MoveTo 766, 355
Delay 113
LeftUp 1
MoveTo 770, 386
Delay 119
KeyDown "Shift", 1
MoveTo 770, 397
Delay 33
KeyDown "Shift", 1
MoveTo 770, 405
Delay 34
KeyDown "Shift", 1
MoveTo 770, 406
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
MoveTo 770, 408
Delay 34
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 39
KeyDown "Shift", 1
Delay 31
Delay 2
KeyUp "Shift", 1
MoveTo 770, 409
Delay 499
KeyDown "M", 1
MoveTo 770, 413
Delay 142
KeyUp "M", 1
MoveTo 721, 575
Delay 305
KeyDown "Ctrl", 1
MoveTo 543, 569
Delay 514
KeyDown "Ctrl", 1
MoveTo 543, 567
Delay 33
KeyDown "Ctrl", 1
MoveTo 542, 566
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 45
KeyDown "Ctrl", 1
Delay 65
Delay 3
KeyUp "Ctrl", 1
MoveTo 957, 300
Delay 2350
KeyDown "Shift", 1
MoveTo 833, 351
Delay 514
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 831, 353
Delay 30
KeyDown "Shift", 1
MoveTo 825, 368
Delay 35
KeyDown "Shift", 1
MoveTo 819, 386
Delay 32
KeyDown "Shift", 1
MoveTo 814, 399
Delay 34
KeyDown "Shift", 1
MoveTo 811, 404
Delay 32
KeyDown "Shift", 1
Delay 33
MoveTo 810, 405
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 40
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 63
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
Delay 399
KeyDown "M", 1
Delay 136
KeyUp "M", 1
MoveTo 711, 488
Delay 301
KeyDown "Ctrl", 1
MoveTo 572, 553
Delay 533
KeyDown "Ctrl", 1
MoveTo 571, 553
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 571, 555
Delay 34
KeyDown "Ctrl", 1
MoveTo 571, 556
Delay 33
KeyDown "Ctrl", 1
MoveTo 573, 558
Delay 33
KeyDown "Ctrl", 1
MoveTo 574, 558
Delay 34
KeyDown "Ctrl", 1
MoveTo 574, 559
Delay 10
KeyDown "Ctrl", 1
MoveTo 575, 559
Delay 56
KeyDown "Ctrl", 1
MoveTo 576, 559
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 62
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 1
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 65
KeyDown "Ctrl", 1
Delay 100
Delay 1
KeyDown "Ctrl", 1
Delay 19
Delay 2
KeyUp "Ctrl", 1
MoveTo 699, 306
Delay 2455
KeyDown "Shift", 1
MoveTo 705, 359
Delay 369
LeftClick 1
MoveTo 708, 361
Delay 67
KeyDown "Shift", 1
MoveTo 712, 376
Delay 33
KeyDown "Shift", 1
MoveTo 717, 393
Delay 34
KeyDown "Shift", 1
MoveTo 718, 404
Delay 46
KeyDown "Shift", 1
MoveTo 720, 409
Delay 1
KeyDown "Shift", 1
MoveTo 721, 413
Delay 65
KeyDown "Shift", 1
MoveTo 722, 420
Delay 35
KeyDown "Shift", 1
MoveTo 722, 422
Delay 32
KeyDown "Shift", 1
MoveTo 722, 423
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
Delay 398
KeyDown "M", 1
Delay 160
KeyUp "M", 1
MoveTo 413, 355
Delay 1601
KeyDown "Ctrl", 1
MoveTo 375, 344
Delay 499
KeyDown "Ctrl", 1
Delay 34
MoveTo 376, 344
Delay 34
KeyDown "Ctrl", 1
MoveTo 385, 342
Delay 34
KeyDown "Ctrl", 1
MoveTo 394, 337
Delay 32
KeyDown "Ctrl", 1
MoveTo 397, 336
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 2
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 35
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 30
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 120
Delay 49
KeyDown "Ctrl", 1
Delay 34
MoveTo 398, 336
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 31
Delay 2
KeyDown "Ctrl", 1
MoveTo 399, 336
Delay 33
KeyDown "Ctrl", 1
Delay 69
Delay 1
KeyDown "Ctrl", 1
MoveTo 403, 336
Delay 35
KeyDown "Ctrl", 1
MoveTo 407, 335
Delay 2
KeyUp "Ctrl", 1
MoveTo 713, 334
Delay 3193
KeyDown "Ctrl", 1
Delay 500
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 713, 333
Delay 33
KeyDown "Ctrl", 1
MoveTo 715, 333
Delay 33
KeyDown "Ctrl", 1
MoveTo 718, 334
Delay 33
KeyDown "Ctrl", 1
MoveTo 729, 341
Delay 35
KeyDown "Ctrl", 1
MoveTo 739, 346
Delay 32
KeyDown "Ctrl", 1
MoveTo 745, 351
Delay 33
KeyDown "Ctrl", 1
MoveTo 749, 354
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 68
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 749, 352
Delay 36
KeyDown "Ctrl", 1
MoveTo 748, 348
Delay 32
KeyDown "Ctrl", 1
Delay 16
Delay 1
KeyDown "Ctrl", 1
MoveTo 748, 343
Delay 17
KeyUp "Ctrl", 1
MoveTo 742, 335
Delay 265
KeyDown "Shift", 1
MoveTo 741, 333
Delay 167
RightDown 1
Delay 133
RightClick 1
MoveTo 770, 360
Delay 237
KeyDown "Shift", 1
MoveTo 770, 362
Delay 29
KeyDown "Shift", 1
Delay 34
MoveTo 770, 363
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
RightDown 1
Delay 1
KeyDown "Shift", 1
Delay 31
Delay 35
KeyDown "Shift", 1
Delay 32
RightClick 1
Delay 1
KeyDown "Shift", 1
MoveTo 770, 364
Delay 32
KeyDown "Shift", 1
MoveTo 779, 377
Delay 35
KeyDown "Shift", 1
MoveTo 792, 395
Delay 33
KeyDown "Shift", 1
MoveTo 796, 404
Delay 35
KeyDown "Shift", 1
MoveTo 796, 410
Delay 31
KeyDown "Shift", 1
MoveTo 796, 414
Delay 35
KeyDown "Shift", 1
MoveTo 795, 415
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 37
RightDown 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
RightClick 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 2
KeyUp "Shift", 1
MoveTo 787, 329
Delay 1672
KeyDown "Shift", 1
Delay 100
LeftClick 1
MoveTo 787, 366
Delay 333
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 43
Delay 3
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 787, 382
Delay 34
KeyDown "Shift", 1
MoveTo 787, 395
Delay 33
KeyDown "Shift", 1
MoveTo 786, 403
Delay 33
KeyDown "Shift", 1
MoveTo 786, 407
Delay 34
KeyDown "Shift", 1
MoveTo 785, 411
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 785, 412
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 32
Delay 33
KeyUp "Shift", 1
MoveTo 778, 419
Delay 476
KeyDown "M", 1
Delay 166
KeyUp "M", 1
MoveTo 643, 432
Delay 403
KeyDown "Ctrl", 1
MoveTo 472, 505
Delay 498
KeyDown "Ctrl", 1
MoveTo 467, 507
Delay 34
KeyDown "Ctrl", 1
MoveTo 462, 510
Delay 32
KeyDown "Ctrl", 1
MoveTo 456, 513
Delay 36
KeyDown "Ctrl", 1
MoveTo 451, 514
Delay 31
KeyDown "Ctrl", 1
MoveTo 443, 518
Delay 34
KeyDown "Ctrl", 1
MoveTo 438, 520
Delay 35
KeyDown "Ctrl", 1
MoveTo 435, 520
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
MoveTo 434, 521
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 6
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 30
Delay 102
KeyDown "Ctrl", 1
Delay 1
Delay 18
KeyDown "Ctrl", 1
MoveTo 434, 520
Delay 5
KeyUp "Ctrl", 1
MoveTo 578, 328
Delay 2561
KeyDown "Shift", 1
MoveTo 581, 333
Delay 167
LeftClick 1
MoveTo 614, 357
Delay 267
KeyDown "Shift", 1
MoveTo 615, 357
Delay 40
KeyDown "Shift", 1
MoveTo 617, 358
Delay 33
KeyDown "Shift", 1
MoveTo 620, 361
Delay 32
KeyDown "Shift", 1
MoveTo 621, 363
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 37
Delay 38
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 621, 364
Delay 33
KeyDown "Shift", 1
MoveTo 622, 373
Delay 36
KeyDown "Shift", 1
MoveTo 631, 389
Delay 31
KeyDown "Shift", 1
MoveTo 643, 399
Delay 34
KeyDown "Shift", 1
MoveTo 653, 407
Delay 33
KeyDown "Shift", 1
MoveTo 656, 410
Delay 33
KeyDown "Shift", 1
MoveTo 656, 411
Delay 33
KeyDown "Shift", 1
MoveTo 657, 412
Delay 33
KeyDown "Shift", 1
Delay 38
MoveTo 658, 412
Delay 35
KeyDown "Shift", 1
MoveTo 659, 413
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 37
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
Delay 654
KeyDown "M", 1
Delay 100
KeyUp "M", 1
MoveTo 549, 483
Delay 534
KeyDown "Ctrl", 1
MoveTo 486, 507
Delay 368
RightDown 1
Delay 131
RightClick 1
MoveTo 485, 507
Delay 35
KeyDown "Ctrl", 1
Delay 32
MoveTo 489, 507
Delay 35
KeyDown "Ctrl", 1
Delay 27
Delay 3
KeyDown "Ctrl", 1
MoveTo 498, 506
Delay 79
KeyDown "Ctrl", 1
MoveTo 505, 504
Delay 1
KeyUp "Ctrl", 1
MoveTo 654, 375
Delay 2555
KeyDown "Shift", 1
MoveTo 707, 343
Delay 404
LeftClick 1
Delay 79
KeyDown "Shift", 1
MoveTo 707, 348
Delay 34
KeyDown "Shift", 1
MoveTo 707, 349
Delay 33
KeyDown "Shift", 1
MoveTo 707, 350
Delay 34
KeyDown "Shift", 1
MoveTo 707, 353
Delay 33
KeyDown "Shift", 1
MoveTo 708, 356
Delay 33
KeyDown "Shift", 1
MoveTo 708, 357
Delay 33
KeyDown "Shift", 1
MoveTo 708, 358
Delay 2
LeftDown 1
MoveTo 709, 358
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
MoveTo 707, 374
Delay 33
KeyDown "Shift", 1
MoveTo 703, 390
Delay 35
KeyDown "Shift", 1
MoveTo 701, 400
Delay 33
KeyDown "Shift", 1
MoveTo 701, 405
Delay 33
KeyDown "Shift", 1
MoveTo 701, 410
Delay 34
KeyDown "Shift", 1
MoveTo 701, 413
Delay 31
KeyDown "Shift", 1
MoveTo 701, 416
Delay 34
KeyDown "Shift", 1
MoveTo 701, 417
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 3
Delay 35
KeyDown "Shift", 1
Delay 33
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 31
KeyDown "Shift", 1
MoveTo 701, 420
Delay 34
KeyDown "Shift", 1
MoveTo 735, 434
Delay 35
KeyDown "Shift", 1
MoveTo 757, 441
Delay 33
KeyUp "Shift", 1
MoveTo 767, 445
Delay 598
KeyDown "M", 1
Delay 98
KeyUp "M", 1
MoveTo 521, 512
Delay 1567
KeyDown "Ctrl", 1
Delay 167
RightDown 1
Delay 166
RightClick 1
Delay 157
KeyDown "Ctrl", 1
Delay 1
MoveTo 535, 509
Delay 56
KeyUp "Ctrl", 1
MoveTo 693, 360
Delay 2558
KeyDown "Shift", 1
MoveTo 708, 339
Delay 300
LeftDown 1
MoveTo 708, 338
Delay 75
LeftUp 1
MoveTo 711, 369
Delay 105
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 46
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 35
MoveTo 711, 384
Delay 34
KeyDown "Shift", 1
MoveTo 713, 396
Delay 34
KeyDown "Shift", 1
MoveTo 714, 401
Delay 2
KeyDown "Shift", 1
MoveTo 715, 404
Delay 33
KeyDown "Shift", 1
Delay 65
MoveTo 716, 407
Delay 34
KeyDown "Shift", 1
MoveTo 717, 410
Delay 33
KeyDown "Shift", 1
MoveTo 718, 412
Delay 34
KeyDown "Shift", 1
MoveTo 719, 414
Delay 35
KeyDown "Shift", 1
MoveTo 719, 415
Delay 35
KeyDown "Shift", 1
Delay 31
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 33
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
Delay 369
KeyDown "M", 1
Delay 127
KeyUp "M", 1
MoveTo 691, 399
Delay 468
KeyDown "Ctrl", 1
MoveTo 575, 504
Delay 465
RightDown 1
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 31
Delay 1
KeyDown "Ctrl", 1
Delay 89
Delay 1
KeyUp "Ctrl", 1
MoveTo 685, 360
Delay 2510
KeyDown "Shift", 1
MoveTo 720, 326
Delay 335
LeftClick 1
MoveTo 722, 347
Delay 71
KeyDown "Shift", 1
MoveTo 722, 351
Delay 34
KeyDown "Shift", 1
MoveTo 722, 352
Delay 42
KeyDown "Shift", 1
Delay 32
Delay 40
KeyDown "Shift", 1
MoveTo 722, 355
Delay 47
KeyDown "Shift", 1
MoveTo 723, 360
Delay 35
KeyDown "Shift", 1
MoveTo 724, 362
Delay 41
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 43
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 725, 372
Delay 33
KeyDown "Shift", 1
MoveTo 725, 391
Delay 33
KeyDown "Shift", 1
MoveTo 725, 402
Delay 34
KeyDown "Shift", 1
MoveTo 725, 409
Delay 33
KeyDown "Shift", 1
MoveTo 726, 412
Delay 34
KeyDown "Shift", 1
MoveTo 727, 414
Delay 35
KeyDown "Shift", 1
MoveTo 727, 417
Delay 33
KeyDown "Shift", 1
MoveTo 727, 419
Delay 36
KeyDown "Shift", 1
MoveTo 727, 422
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 1
KeyUp "Shift", 1
Delay 439
KeyDown "M", 1
MoveTo 724, 420
Delay 160
KeyUp "M", 1
MoveTo 675, 400
Delay 368
KeyDown "Ctrl", 1
MoveTo 587, 488
Delay 501
KeyDown "Ctrl", 1
MoveTo 585, 490
Delay 31
KeyDown "Ctrl", 1
MoveTo 585, 492
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 6
RightDown 1
Delay 29
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 24
KeyDown "Ctrl", 1
Delay 1
Delay 96
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 646, 402
Delay 2656
KeyDown "Shift", 1
MoveTo 704, 332
Delay 469
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 37
Delay 2
LeftUp 1
Delay 45
KeyDown "Shift", 1
MoveTo 707, 346
Delay 35
KeyDown "Shift", 1
MoveTo 707, 352
Delay 32
KeyDown "Shift", 1
MoveTo 707, 353
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 3
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 36
Delay 36
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 41
MoveTo 709, 370
Delay 34
KeyDown "Shift", 1
MoveTo 716, 392
Delay 34
KeyDown "Shift", 1
MoveTo 719, 400
Delay 32
KeyDown "Shift", 1
MoveTo 721, 405
Delay 34
KeyDown "Shift", 1
MoveTo 721, 407
Delay 32
KeyDown "Shift", 1
MoveTo 722, 411
Delay 34
KeyDown "Shift", 1
MoveTo 722, 414
Delay 34
KeyDown "Shift", 1
MoveTo 722, 418
Delay 33
KeyDown "Shift", 1
Delay 36
Delay 30
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
MoveTo 719, 423
Delay 404
KeyDown "M", 1
MoveTo 717, 425
Delay 131
KeyUp "M", 1
MoveTo 607, 483
Delay 367
KeyDown "Ctrl", 1
MoveTo 539, 543
Delay 534
KeyDown "Ctrl", 1
Delay 33
RightDown 1
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
MoveTo 540, 543
Delay 33
KeyDown "Ctrl", 1
Delay 55
Delay 1
KeyDown "Ctrl", 1
Delay 64
Delay 2
KeyUp "Ctrl", 1
MoveTo 611, 383
Delay 2457
KeyDown "Shift", 1
MoveTo 653, 340
Delay 506
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 41
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 3
Delay 64
KeyDown "Shift", 1
Delay 66
Delay 34
KeyDown "Shift", 1
Delay 67
Delay 36
KeyDown "Shift", 1
Delay 30
Delay 39
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 39
KeyDown "Shift", 1
Delay 38
Delay 1
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 36
MoveTo 658, 348
Delay 34
KeyDown "Shift", 1
MoveTo 662, 357
Delay 33
KeyDown "Shift", 1
MoveTo 664, 362
Delay 32
KeyDown "Shift", 1
MoveTo 665, 366
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 3
Delay 32
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 32
MoveTo 665, 380
Delay 34
KeyDown "Shift", 1
MoveTo 667, 398
Delay 35
KeyDown "Shift", 1
MoveTo 669, 404
Delay 31
KeyDown "Shift", 1
MoveTo 669, 406
Delay 34
KeyDown "Shift", 1
MoveTo 670, 406
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 670, 408
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 665, 433
Delay 537
KeyDown "M", 1
MoveTo 648, 449
Delay 130
KeyUp "M", 1
MoveTo 524, 560
Delay 366
KeyDown "Ctrl", 1
MoveTo 492, 549
Delay 401
RightDown 1
Delay 98
RightClick 1
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 93
KeyDown "Ctrl", 1
Delay 33
Delay 14
KeyDown "Ctrl", 1
Delay 47
KeyUp "Ctrl", 1
MoveTo 735, 353
Delay 2659
KeyDown "Shift", 1
MoveTo 742, 330
Delay 300
LeftClick 1
MoveTo 742, 350
Delay 134
KeyDown "Shift", 1
Delay 43
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
MoveTo 742, 352
Delay 33
KeyDown "Shift", 1
MoveTo 742, 370
Delay 33
KeyDown "Shift", 1
MoveTo 744, 387
Delay 65
KeyDown "Shift", 1
MoveTo 745, 394
Delay 37
KeyDown "Shift", 1
MoveTo 745, 401
Delay 35
KeyDown "Shift", 1
MoveTo 745, 410
Delay 35
KeyDown "Shift", 1
MoveTo 745, 414
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 38
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 32
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
MoveTo 739, 424
Delay 367
KeyDown "M", 1
MoveTo 727, 426
Delay 129
KeyUp "M", 1
MoveTo 517, 530
Delay 333
KeyDown "Ctrl", 1
MoveTo 469, 541
Delay 402
RightDown 1
MoveTo 469, 540
Delay 100
KeyDown "Ctrl", 1
Delay 31
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 104
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 68
KeyDown "Ctrl", 1
Delay 32
Delay 58
KeyDown "Ctrl", 1
Delay 32
Delay 31
KeyDown "Ctrl", 1
Delay 1
Delay 1
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 660, 398
Delay 2306
KeyDown "Shift", 1
MoveTo 686, 362
Delay 469
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 37
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
MoveTo 686, 366
Delay 35
KeyDown "Shift", 1
MoveTo 686, 381
Delay 33
KeyDown "Shift", 1
MoveTo 686, 395
Delay 35
KeyDown "Shift", 1
MoveTo 686, 401
Delay 33
KeyDown "Shift", 1
MoveTo 686, 407
Delay 42
KeyDown "Shift", 1
MoveTo 686, 409
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 36
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 32
KeyUp "Shift", 1
MoveTo 686, 410
Delay 476
KeyDown "M", 1
MoveTo 651, 434
Delay 170
KeyUp "M", 1
MoveTo 558, 494
Delay 296
KeyDown "Ctrl", 1
MoveTo 431, 547
Delay 538
KeyDown "Ctrl", 1
MoveTo 430, 547
Delay 2
KeyDown "Ctrl", 1
Delay 61
MoveTo 429, 547
Delay 3
KeyDown "Ctrl", 1
MoveTo 428, 547
Delay 34
RightDown 1
MoveTo 427, 547
Delay 2
KeyDown "Ctrl", 1
MoveTo 425, 548
Delay 30
KeyDown "Ctrl", 1
Delay 64
Delay 36
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 108
Delay 48
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 19
Delay 1
KeyDown "Ctrl", 1
Delay 13
Delay 2
KeyUp "Ctrl", 1
MoveTo 480, 473
Delay 2221
KeyDown "Shift", 1
MoveTo 734, 336
Delay 533
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 33
Delay 39
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 36
MoveTo 736, 341
Delay 48
KeyDown "Shift", 1
MoveTo 737, 353
Delay 4
KeyDown "Shift", 1
MoveTo 738, 357
Delay 34
KeyDown "Shift", 1
MoveTo 738, 358
Delay 32
KeyDown "Shift", 1
Delay 64
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 36
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 739, 365
Delay 35
KeyDown "Shift", 1
MoveTo 739, 392
Delay 36
KeyDown "Shift", 1
MoveTo 739, 410
Delay 33
KeyDown "Shift", 1
MoveTo 739, 415
Delay 32
KeyDown "Shift", 1
MoveTo 739, 418
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 38
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 31
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
MoveTo 738, 420
Delay 434
KeyDown "M", 1
MoveTo 684, 448
Delay 143
KeyUp "M", 1
MoveTo 417, 541
Delay 364
KeyDown "Ctrl", 1
MoveTo 398, 556
Delay 467
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 106
KeyDown "Ctrl", 1
Delay 1
Delay 65
KeyDown "Ctrl", 1
Delay 3
Delay 1
KeyDown "Ctrl", 1
Delay 29
KeyUp "Ctrl", 1
MoveTo 598, 322
Delay 2604
KeyDown "Shift", 1
MoveTo 604, 345
Delay 266
LeftClick 1
MoveTo 615, 368
Delay 138
KeyDown "Shift", 1
Delay 66
Delay 34
KeyDown "Shift", 1
MoveTo 618, 369
Delay 34
KeyDown "Shift", 1
MoveTo 622, 357
Delay 58
KeyDown "Shift", 1
MoveTo 627, 340
Delay 35
KeyDown "Shift", 1
MoveTo 629, 338
Delay 39
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 34
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 632, 342
Delay 65
KeyDown "Shift", 1
MoveTo 635, 364
Delay 4
KeyDown "Shift", 1
MoveTo 643, 386
Delay 32
KeyDown "Shift", 1
MoveTo 647, 399
Delay 35
KeyDown "Shift", 1
MoveTo 647, 407
Delay 34
KeyDown "Shift", 1
MoveTo 647, 415
Delay 33
KeyDown "Shift", 1
MoveTo 647, 419
Delay 32
KeyDown "Shift", 1
MoveTo 647, 420
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 39
KeyDown "Shift", 1
Delay 39
Delay 1
LeftUp 1
Delay 42
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
Delay 369
KeyDown "M", 1
MoveTo 624, 433
Delay 138
KeyUp "M", 1
MoveTo 460, 501
Delay 266
KeyDown "Ctrl", 1
MoveTo 352, 548
Delay 503
KeyDown "Ctrl", 1
MoveTo 351, 550
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 3
RightDown 1
MoveTo 351, 551
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 30
RightClick 1
Delay 2
KeyDown "Ctrl", 1
MoveTo 351, 552
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 85
KeyDown "Ctrl", 1
Delay 1
Delay 22
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 684, 354
Delay 2889
KeyDown "Shift", 1
MoveTo 705, 331
Delay 235
LeftClick 1
MoveTo 705, 357
Delay 169
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
Delay 39
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 34
MoveTo 705, 366
Delay 42
KeyDown "Shift", 1
MoveTo 715, 393
Delay 37
KeyDown "Shift", 1
MoveTo 715, 394
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 32
KeyDown "Shift", 1
Delay 34
MoveTo 715, 397
Delay 37
KeyDown "Shift", 1
MoveTo 714, 408
Delay 33
KeyDown "Shift", 1
MoveTo 713, 413
Delay 37
KeyDown "Shift", 1
MoveTo 713, 414
Delay 33
KeyDown "Shift", 1
Delay 37
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 35
KeyUp "Shift", 1
Delay 401
KeyDown "M", 1
MoveTo 711, 415
Delay 141
KeyUp "M", 1
MoveTo 459, 480
Delay 333
KeyDown "Ctrl", 1
MoveTo 317, 495
Delay 532
KeyDown "Ctrl", 1
MoveTo 314, 495
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 313, 495
Delay 34
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 1
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 66
Delay 103
KeyDown "Ctrl", 1
Delay 6
Delay 1
KeyDown "Ctrl", 1
Delay 26
KeyUp "Ctrl", 1
MoveTo 633, 333
Delay 2837
KeyDown "Shift", 1
MoveTo 635, 333
Delay 140
LeftClick 1
MoveTo 661, 375
Delay 282
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 42
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 38
Delay 33
KeyDown "Shift", 1
MoveTo 663, 369
Delay 36
KeyDown "Shift", 1
MoveTo 664, 367
Delay 44
KeyDown "Shift", 1
Delay 32
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 36
Delay 42
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
MoveTo 666, 371
Delay 39
KeyDown "Shift", 1
MoveTo 669, 386
Delay 41
KeyDown "Shift", 1
MoveTo 681, 407
Delay 33
KeyDown "Shift", 1
MoveTo 683, 411
Delay 35
KeyDown "Shift", 1
MoveTo 683, 415
Delay 41
KeyDown "Shift", 1
Delay 35
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
KeyDown "Shift", 1
Delay 38
Delay 42
KeyDown "Shift", 1
Delay 43
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 36
KeyUp "Shift", 1
Delay 444
KeyDown "M", 1
MoveTo 673, 416
Delay 108
KeyUp "M", 1
MoveTo 531, 434
Delay 301
KeyDown "Ctrl", 1
MoveTo 357, 506
Delay 500
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 93
MoveTo 358, 506
Delay 34
KeyDown "Ctrl", 1
Delay 42
Delay 1
KeyDown "Ctrl", 1
MoveTo 362, 503
Delay 9
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 505, 350
Delay 2532
KeyDown "Shift", 1
MoveTo 701, 327
Delay 441
LeftDown 1
Delay 41
KeyDown "Shift", 1
Delay 37
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 702, 329
Delay 37
KeyDown "Shift", 1
MoveTo 711, 344
Delay 38
KeyDown "Shift", 1
MoveTo 720, 358
Delay 46
KeyDown "Shift", 1
MoveTo 722, 360
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 2
LeftDown 1
Delay 39
KeyDown "Shift", 1
Delay 40
Delay 2
LeftUp 1
Delay 38
KeyDown "Shift", 1
Delay 33
MoveTo 728, 378
Delay 35
KeyDown "Shift", 1
MoveTo 740, 397
Delay 37
KeyDown "Shift", 1
MoveTo 743, 403
Delay 36
KeyDown "Shift", 1
Delay 30
Delay 34
KeyDown "Shift", 1
Delay 34
MoveTo 743, 404
Delay 34
KeyDown "Shift", 1
MoveTo 743, 406
Delay 39
KeyDown "Shift", 1
MoveTo 743, 411
Delay 38
KeyDown "Shift", 1
MoveTo 743, 413
Delay 36
KeyDown "Shift", 1
MoveTo 743, 415
Delay 32
KeyDown "Shift", 1
MoveTo 743, 416
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 35
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 66
MoveTo 743, 418
Delay 1
KeyDown "Shift", 1
MoveTo 743, 421
Delay 33
KeyDown "Shift", 1
MoveTo 752, 430
Delay 36
KeyDown "Shift", 1
MoveTo 765, 437
Delay 34
KeyDown "Shift", 1
MoveTo 774, 440
Delay 37
KeyDown "Shift", 1
MoveTo 788, 444
Delay 33
KeyDown "Shift", 1
MoveTo 797, 447
Delay 41
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 796, 445
Delay 714
KeyDown "M", 1
Delay 132
KeyUp "M", 1
MoveTo 621, 445
Delay 301
KeyDown "Ctrl", 1
MoveTo 415, 505
Delay 532
KeyDown "Ctrl", 1
MoveTo 413, 507
Delay 34
KeyDown "Ctrl", 1
MoveTo 408, 511
Delay 34
KeyDown "Ctrl", 1
MoveTo 400, 514
Delay 5
KeyDown "Ctrl", 1
MoveTo 396, 514
Delay 64
KeyDown "Ctrl", 1
MoveTo 394, 514
Delay 2
KeyDown "Ctrl", 1
Delay 61
Delay 34
KeyDown "Ctrl", 1
Delay 3
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 62
Delay 36
KeyDown "Ctrl", 1
Delay 32
RightClick 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 393, 515
Delay 34
KeyDown "Ctrl", 1
MoveTo 394, 516
Delay 33
KeyDown "Ctrl", 1
Delay 49
Delay 1
KeyDown "Ctrl", 1
MoveTo 396, 516
Delay 91
KeyDown "Ctrl", 1
MoveTo 398, 516
Delay 1
KeyUp "Ctrl", 1
MoveTo 572, 412
Delay 2720
KeyDown "Shift", 1
MoveTo 692, 359
Delay 351
LeftClick 1
MoveTo 695, 359
Delay 36
KeyDown "Shift", 1
MoveTo 701, 374
Delay 35
KeyDown "Shift", 1
MoveTo 706, 387
Delay 38
KeyDown "Shift", 1
MoveTo 710, 397
Delay 35
KeyDown "Shift", 1
MoveTo 711, 402
Delay 33
KeyDown "Shift", 1
MoveTo 713, 408
Delay 3
KeyDown "Shift", 1
MoveTo 714, 413
Delay 36
KeyDown "Shift", 1
MoveTo 714, 417
Delay 47
KeyDown "Shift", 1
MoveTo 714, 419
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 36
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 33
MoveTo 715, 419
Delay 35
KeyDown "Shift", 1
Delay 34
MoveTo 716, 420
Delay 2
KeyUp "Shift", 1
MoveTo 719, 420
Delay 436
KeyDown "M", 1
Delay 131
KeyUp "M", 1
MoveTo 687, 433
Delay 268
KeyDown "Ctrl", 1
MoveTo 437, 514
Delay 501
KeyDown "Ctrl", 1
MoveTo 434, 518
Delay 32
KeyDown "Ctrl", 1
MoveTo 433, 518
Delay 33
KeyDown "Ctrl", 1
MoveTo 432, 521
Delay 34
KeyDown "Ctrl", 1
MoveTo 432, 522
Delay 32
KeyDown "Ctrl", 1
MoveTo 432, 523
Delay 34
KeyDown "Ctrl", 1
Delay 36
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 29
Delay 33
KeyDown "Ctrl", 1
MoveTo 433, 524
Delay 33
KeyDown "Ctrl", 1
MoveTo 433, 525
Delay 2
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 47
KeyDown "Ctrl", 1
Delay 1
MoveTo 434, 525
Delay 68
KeyDown "Ctrl", 1
MoveTo 435, 525
Delay 3
KeyUp "Ctrl", 1
MoveTo 701, 418
Delay 2468
KeyDown "Shift", 1
MoveTo 708, 367
Delay 381
LeftClick 1
MoveTo 711, 367
Delay 69
KeyDown "Shift", 1
MoveTo 718, 379
Delay 1
KeyDown "Shift", 1
MoveTo 725, 396
Delay 34
KeyDown "Shift", 1
MoveTo 728, 404
Delay 34
KeyDown "Shift", 1
MoveTo 729, 410
Delay 34
KeyDown "Shift", 1
Delay 32
MoveTo 729, 411
Delay 33
KeyDown "Shift", 1
MoveTo 731, 414
Delay 44
KeyDown "Shift", 1
MoveTo 731, 418
Delay 37
KeyDown "Shift", 1
MoveTo 731, 420
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 1
LeftDown 1
Delay 36
KeyDown "Shift", 1
Delay 40
Delay 40
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 34
KeyUp "Shift", 1
Delay 402
KeyDown "M", 1
Delay 132
KeyUp "M", 1
MoveTo 624, 427
Delay 335
KeyDown "Ctrl", 1
MoveTo 497, 502
Delay 500
KeyDown "Ctrl", 1
MoveTo 490, 504
Delay 33
KeyDown "Ctrl", 1
MoveTo 480, 507
Delay 34
KeyDown "Ctrl", 1
MoveTo 479, 508
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 3
RightDown 1
Delay 31
KeyDown "Ctrl", 1
MoveTo 478, 508
Delay 36
KeyDown "Ctrl", 1
MoveTo 478, 509
Delay 31
KeyDown "Ctrl", 1
MoveTo 478, 510
Delay 35
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 29
MoveTo 480, 510
Delay 35
KeyDown "Ctrl", 1
Delay 15
Delay 2
KeyDown "Ctrl", 1
MoveTo 481, 510
Delay 15
KeyUp "Ctrl", 1
MoveTo 745, 371
Delay 2505
KeyDown "Shift", 1
MoveTo 749, 359
Delay 337
LeftClick 1
Delay 69
KeyDown "Shift", 1
MoveTo 749, 367
Delay 37
KeyDown "Shift", 1
MoveTo 749, 378
Delay 2
KeyDown "Shift", 1
MoveTo 752, 389
Delay 33
KeyDown "Shift", 1
MoveTo 753, 400
Delay 34
KeyDown "Shift", 1
MoveTo 753, 409
Delay 32
KeyDown "Shift", 1
MoveTo 753, 413
Delay 35
KeyDown "Shift", 1
MoveTo 752, 417
Delay 49
KeyDown "Shift", 1
MoveTo 752, 418
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 39
Delay 2
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 36
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
KeyDown "Shift", 1
MoveTo 752, 419
Delay 34
KeyDown "Shift", 1
MoveTo 752, 423
Delay 36
KeyDown "Shift", 1
MoveTo 752, 427
Delay 35
KeyUp "Shift", 1
MoveTo 747, 441
Delay 978
KeyDown "M", 1
MoveTo 740, 441
Delay 132
KeyUp "M", 1
MoveTo 595, 443
Delay 400
KeyDown "Ctrl", 1
MoveTo 462, 501
Delay 536
KeyDown "Ctrl", 1
MoveTo 462, 503
Delay 30
KeyDown "Ctrl", 1
MoveTo 462, 504
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 3
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 463, 505
Delay 3
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 62
MoveTo 465, 506
Delay 3
KeyDown "Ctrl", 1
Delay 25
Delay 1
KeyDown "Ctrl", 1
Delay 5
KeyUp "Ctrl", 1
MoveTo 767, 381
Delay 3592
KeyDown "Shift", 1
MoveTo 778, 368
Delay 502
KeyDown "Shift", 1
MoveTo 780, 366
Delay 34
KeyDown "Shift", 1
MoveTo 780, 365
Delay 33
KeyDown "Shift", 1
MoveTo 781, 364
Delay 49
KeyDown "Shift", 1
MoveTo 783, 362
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 3
Delay 36
KeyDown "Shift", 1
Delay 4
LeftUp 1
Delay 31
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
MoveTo 784, 362
Delay 33
KeyDown "Shift", 1
MoveTo 786, 373
Delay 36
KeyDown "Shift", 1
MoveTo 786, 381
Delay 32
KeyDown "Shift", 1
MoveTo 786, 391
Delay 33
KeyDown "Shift", 1
MoveTo 786, 401
Delay 33
KeyDown "Shift", 1
MoveTo 784, 409
Delay 35
KeyDown "Shift", 1
MoveTo 782, 413
Delay 39
KeyDown "Shift", 1
MoveTo 780, 417
Delay 33
KeyDown "Shift", 1
MoveTo 779, 418
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 38
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 29
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 36
KeyUp "Shift", 1
Delay 364
KeyDown "M", 1
Delay 131
KeyUp "M", 1
MoveTo 718, 496
Delay 302
KeyDown "Ctrl", 1
MoveTo 555, 537
Delay 532
KeyDown "Ctrl", 1
MoveTo 554, 537
Delay 34
KeyDown "Ctrl", 1
MoveTo 549, 536
Delay 34
KeyDown "Ctrl", 1
MoveTo 546, 534
Delay 34
KeyDown "Ctrl", 1
MoveTo 545, 534
Delay 31
KeyDown "Ctrl", 1
Delay 36
Delay 31
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 3
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 35
Delay 110
KeyDown "Ctrl", 1
Delay 1
Delay 16
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 742, 444
Delay 2457
KeyDown "Shift", 1
MoveTo 776, 367
Delay 466
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 777, 367
Delay 32
KeyDown "Shift", 1
MoveTo 777, 380
Delay 34
KeyDown "Shift", 1
MoveTo 777, 398
Delay 34
KeyDown "Shift", 1
MoveTo 776, 413
Delay 42
KeyDown "Shift", 1
MoveTo 775, 417
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 34
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 33
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
MoveTo 775, 423
Delay 34
KeyDown "Shift", 1
MoveTo 777, 431
Delay 32
KeyDown "Shift", 1
MoveTo 778, 436
Delay 34
KeyDown "Shift", 1
MoveTo 778, 439
Delay 35
KeyDown "Shift", 1
MoveTo 779, 443
Delay 2
KeyDown "Shift", 1
MoveTo 779, 449
Delay 63
KeyDown "Shift", 1
MoveTo 779, 456
Delay 4
KeyDown "Shift", 1
MoveTo 779, 459
Delay 33
KeyDown "Shift", 1
MoveTo 779, 463
Delay 31
KeyDown "Shift", 1
MoveTo 779, 464
Delay 35
KeyDown "Shift", 1
MoveTo 779, 465
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 37
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 778, 458
Delay 467
KeyDown "M", 1
MoveTo 774, 458
Delay 130
KeyUp "M", 1
MoveTo 592, 563
Delay 1000
KeyDown "Ctrl", 1
MoveTo 588, 560
Delay 402
RightDown 1
Delay 98
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 122
Delay 48
KeyDown "Ctrl", 1
Delay 33
Delay 53
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 588, 558
Delay 33
KeyDown "Ctrl", 1
MoveTo 591, 555
Delay 35
KeyDown "Ctrl", 1
MoveTo 605, 547
Delay 32
KeyDown "Ctrl", 1
Delay 18
Delay 2
KeyDown "Ctrl", 1
MoveTo 627, 536
Delay 15
KeyUp "Ctrl", 1
MoveTo 923, 280
Delay 2028
KeyDown "Shift", 1
MoveTo 849, 332
Delay 479
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 1
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyUp "Shift", 1
Delay 378
KeyDown "M", 1
MoveTo 843, 338
Delay 135
KeyUp "M", 1
MoveTo 668, 429
Delay 264
KeyDown "Ctrl", 1
MoveTo 582, 499
Delay 499
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
MoveTo 582, 500
Delay 32
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 32
KeyDown "Ctrl", 1
MoveTo 582, 501
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 1
KeyDown "Ctrl", 1
Delay 75
Delay 2
KeyUp "Ctrl", 1
MoveTo 687, 403
Delay 2605
KeyDown "Shift", 1
MoveTo 709, 347
Delay 504
KeyDown "Shift", 1
MoveTo 713, 344
Delay 33
KeyDown "Shift", 1
MoveTo 715, 343
Delay 34
KeyDown "Shift", 1
MoveTo 716, 342
Delay 33
KeyDown "Shift", 1
MoveTo 719, 339
Delay 3
KeyDown "Shift", 1
MoveTo 722, 337
Delay 34
KeyDown "Shift", 1
MoveTo 723, 336
Delay 31
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 725, 345
Delay 31
KeyDown "Shift", 1
MoveTo 725, 353
Delay 34
KeyDown "Shift", 1
MoveTo 725, 356
Delay 34
KeyDown "Shift", 1
MoveTo 725, 359
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 36
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
MoveTo 731, 377
Delay 35
KeyDown "Shift", 1
MoveTo 736, 391
Delay 31
KeyDown "Shift", 1
MoveTo 737, 399
Delay 35
KeyDown "Shift", 1
MoveTo 737, 404
Delay 33
KeyDown "Shift", 1
MoveTo 737, 405
Delay 2
KeyDown "Shift", 1
Delay 66
Delay 34
KeyDown "Shift", 1
Delay 31
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 35
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 32
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyUp "Shift", 1
MoveTo 731, 431
Delay 500
KeyDown "M", 1
MoveTo 730, 434
Delay 109
KeyUp "M", 1
MoveTo 608, 683
Delay 1132
KeyDown "Ctrl", 1
MoveTo 604, 674
Delay 503
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 3
Delay 65
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 109
KeyDown "Ctrl", 1
Delay 53
Delay 2
KeyDown "Ctrl", 1
Delay 77
Delay 2
KeyDown "Ctrl", 1
Delay 21
Delay 2
KeyUp "Ctrl", 1
MoveTo 777, 405
Delay 2903
KeyDown "Shift", 1
MoveTo 797, 357
Delay 305
LeftClick 1
MoveTo 797, 398
Delay 134
KeyDown "Shift", 1
MoveTo 798, 415
Delay 34
KeyDown "Shift", 1
MoveTo 798, 422
Delay 34
KeyDown "Shift", 1
MoveTo 798, 424
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 35
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 40
Delay 31
KeyDown "Shift", 1
MoveTo 798, 401
Delay 35
KeyDown "Shift", 1
MoveTo 801, 383
Delay 34
KeyDown "Shift", 1
MoveTo 803, 365
Delay 33
KeyDown "Shift", 1
MoveTo 804, 349
Delay 34
KeyDown "Shift", 1
MoveTo 804, 338
Delay 34
KeyDown "Shift", 1
MoveTo 804, 335
Delay 34
KeyDown "Shift", 1
MoveTo 805, 334
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 33
KeyUp "Shift", 1
MoveTo 790, 368
Delay 608
KeyDown "M", 1
MoveTo 781, 389
Delay 97
KeyUp "M", 1
MoveTo 611, 625
Delay 399
KeyDown "Ctrl", 1
MoveTo 566, 602
Delay 503
KeyDown "Ctrl", 1
MoveTo 561, 601
Delay 35
KeyDown "Ctrl", 1
MoveTo 558, 592
Delay 31
KeyDown "Ctrl", 1
MoveTo 557, 583
Delay 33
KeyDown "Ctrl", 1
MoveTo 555, 578
Delay 32
KeyDown "Ctrl", 1
Delay 32
MoveTo 554, 576
Delay 37
KeyDown "Ctrl", 1
MoveTo 553, 575
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 552, 575
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 552, 569
Delay 35
KeyDown "Ctrl", 1
MoveTo 552, 564
Delay 33
KeyDown "Ctrl", 1
MoveTo 553, 560
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 4
RightDown 1
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 3
RightClick 1
Delay 30
KeyDown "Ctrl", 1
MoveTo 554, 559
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 116
KeyDown "Ctrl", 1
MoveTo 554, 563
Delay 2
KeyDown "Ctrl", 1
MoveTo 554, 564
Delay 49
KeyDown "Ctrl", 1
MoveTo 554, 565
Delay 34
KeyDown "Ctrl", 1
MoveTo 554, 567
Delay 4
KeyDown "Ctrl", 1
MoveTo 554, 569
Delay 62
KeyDown "Ctrl", 1
MoveTo 554, 570
Delay 34
KeyDown "Ctrl", 1
MoveTo 554, 572
Delay 3
KeyDown "Ctrl", 1
MoveTo 556, 573
Delay 32
KeyDown "Ctrl", 1
MoveTo 560, 574
Delay 33
KeyDown "Ctrl", 1
Delay 18
KeyDown "Ctrl", 1
MoveTo 564, 574
Delay 15
KeyUp "Ctrl", 1
MoveTo 651, 483
Delay 2224
KeyDown "Shift", 1
MoveTo 723, 335
Delay 499
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 49
Delay 1
LeftUp 1
Delay 39
KeyDown "Shift", 1
MoveTo 723, 341
Delay 32
KeyDown "Shift", 1
MoveTo 723, 352
Delay 34
KeyDown "Shift", 1
MoveTo 723, 360
Delay 32
KeyDown "Shift", 1
MoveTo 723, 362
Delay 33
KeyDown "Shift", 1
Delay 35
Delay 1
KeyDown "Shift", 1
Delay 32
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 728, 372
Delay 33
KeyDown "Shift", 1
MoveTo 738, 410
Delay 32
KeyDown "Shift", 1
MoveTo 754, 438
Delay 35
KeyDown "Shift", 1
MoveTo 761, 447
Delay 32
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 35
KeyDown "Shift", 1
MoveTo 761, 443
Delay 33
KeyDown "Shift", 1
MoveTo 761, 431
Delay 33
KeyDown "Shift", 1
MoveTo 763, 421
Delay 33
KeyDown "Shift", 1
MoveTo 763, 420
Delay 33
KeyDown "Shift", 1
MoveTo 763, 419
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 30
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 761, 423
Delay 401
KeyDown "M", 1
MoveTo 751, 436
Delay 163
KeyUp "M", 1
MoveTo 617, 594
Delay 300
KeyDown "Ctrl", 1
MoveTo 517, 575
Delay 501
KeyDown "Ctrl", 1
MoveTo 517, 568
Delay 33
KeyDown "Ctrl", 1
MoveTo 518, 565
Delay 31
KeyDown "Ctrl", 1
MoveTo 519, 564
Delay 34
RightDown 1
Delay 4
KeyDown "Ctrl", 1
Delay 32
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 36
Delay 28
KeyDown "Ctrl", 1
Delay 87
Delay 1
KeyDown "Ctrl", 1
Delay 14
MoveTo 521, 564
Delay 2
KeyUp "Ctrl", 1
MoveTo 887, 310
Delay 2471
KeyDown "Shift", 1
MoveTo 825, 340
Delay 504
KeyDown "Shift", 1
MoveTo 825, 342
Delay 35
KeyDown "Shift", 1
MoveTo 824, 354
Delay 34
KeyDown "Shift", 1
MoveTo 822, 359
Delay 34
KeyDown "Shift", 1
MoveTo 821, 360
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 44
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 2
Delay 35
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
MoveTo 821, 365
Delay 33
KeyDown "Shift", 1
MoveTo 829, 404
Delay 38
KeyDown "Shift", 1
MoveTo 829, 426
Delay 33
KeyDown "Shift", 1
MoveTo 829, 433
Delay 33
KeyDown "Shift", 1
MoveTo 829, 435
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 829, 430
Delay 34
KeyDown "Shift", 1
MoveTo 830, 422
Delay 34
KeyDown "Shift", 1
MoveTo 830, 418
Delay 33
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 36
KeyDown "Shift", 1
MoveTo 831, 417
Delay 50
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 33
Delay 38
KeyDown "Shift", 1
Delay 32
Delay 2
KeyUp "Shift", 1
MoveTo 831, 418
Delay 404
KeyDown "M", 1
MoveTo 815, 432
Delay 133
KeyUp "M", 1
MoveTo 603, 569
Delay 300
KeyDown "Ctrl", 1
MoveTo 479, 571
Delay 433
RightDown 1
Delay 100
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 119
KeyDown "Ctrl", 1
MoveTo 485, 571
Delay 2
KeyDown "Ctrl", 1
Delay 14
Delay 1
KeyDown "Ctrl", 1
MoveTo 488, 571
Delay 35
KeyUp "Ctrl", 1
MoveTo 786, 335
Delay 2444
KeyDown "Shift", 1
MoveTo 782, 342
Delay 343
LeftClick 1
MoveTo 783, 353
Delay 71
KeyDown "Shift", 1
MoveTo 783, 356
Delay 2
KeyDown "Shift", 1
MoveTo 783, 357
Delay 43
KeyDown "Shift", 1
MoveTo 784, 358
Delay 40
KeyDown "Shift", 1
Delay 38
Delay 1
LeftDown 1
Delay 57
KeyDown "Shift", 1
Delay 45
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 785, 362
Delay 39
KeyDown "Shift", 1
MoveTo 791, 374
Delay 39
KeyDown "Shift", 1
MoveTo 806, 398
Delay 45
KeyUp "Shift", 1
MoveTo 811, 447
Delay 531
KeyDown ",", 1
Delay 132
KeyUp ",", 1
MoveTo 806, 452
Delay 602
KeyDown "M", 1
Delay 162
KeyUp "M", 1
MoveTo 647, 611
Delay 369
KeyDown "Ctrl", 1
MoveTo 540, 545
Delay 501
KeyDown "Ctrl", 1
Delay 63
MoveTo 541, 544
Delay 4
KeyDown "Ctrl", 1
Delay 63
MoveTo 540, 542
Delay 3
KeyDown "Ctrl", 1
MoveTo 537, 542
Delay 32
KeyDown "Ctrl", 1
MoveTo 525, 541
Delay 33
KeyDown "Ctrl", 1
MoveTo 517, 541
Delay 33
KeyDown "Ctrl", 1
MoveTo 515, 541
Delay 34
KeyDown "Ctrl", 1
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
RightClick 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 520, 541
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 37
KeyDown "Ctrl", 1
Delay 1
Delay 88
KeyDown "Ctrl", 1
MoveTo 522, 541
Delay 2
KeyUp "Ctrl", 1
MoveTo 745, 513
Delay 2395
KeyDown "Shift", 1
MoveTo 727, 387
Delay 510
KeyDown "Shift", 1
MoveTo 736, 380
Delay 39
KeyDown "Shift", 1
MoveTo 742, 375
Delay 34
KeyDown "Shift", 1
MoveTo 748, 370
Delay 36
KeyDown "Shift", 1
MoveTo 751, 366
Delay 32
KeyDown "Shift", 1
MoveTo 753, 365
Delay 32
KeyDown "Shift", 1
Delay 49
Delay 2
LeftDown 1
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 753, 366
Delay 43
KeyDown "Shift", 1
MoveTo 753, 374
Delay 35
KeyDown "Shift", 1
MoveTo 757, 385
Delay 54
KeyDown "Shift", 1
MoveTo 760, 399
Delay 1
KeyDown "Shift", 1
MoveTo 762, 411
Delay 64
KeyDown "Shift", 1
MoveTo 762, 416
Delay 43
KeyDown "Shift", 1
Delay 35
Delay 43
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 44
KeyDown "Shift", 1
Delay 40
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 1
KeyUp "Shift", 1
MoveTo 760, 429
Delay 367
KeyDown "M", 1
MoveTo 752, 438
Delay 163
KeyUp "M", 1
MoveTo 555, 550
Delay 334
KeyDown "Ctrl", 1
MoveTo 529, 493
Delay 500
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 34
MoveTo 528, 493
Delay 32
RightDown 1
Delay 2
KeyDown "Ctrl", 1
MoveTo 527, 494
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 3
RightClick 1
MoveTo 527, 495
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 123
KeyDown "Ctrl", 1
MoveTo 539, 495
Delay 1
KeyDown "Ctrl", 1
Delay 59
Delay 1
KeyDown "Ctrl", 1
MoveTo 544, 495
Delay 1
KeyDown "Ctrl", 1
MoveTo 547, 494
Delay 1
KeyDown "Ctrl", 1
MoveTo 548, 493
Delay 2
KeyUp "Ctrl", 1
MoveTo 738, 330
Delay 2398
KeyDown "Shift", 1
MoveTo 746, 328
Delay 446
LeftDown 1
Delay 74
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 746, 329
Delay 33
KeyDown "Shift", 1
MoveTo 749, 342
Delay 37
KeyDown "Shift", 1
MoveTo 751, 351
Delay 36
KeyDown "Shift", 1
MoveTo 752, 354
Delay 32
KeyDown "Shift", 1
MoveTo 752, 355
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 2
LeftDown 1
Delay 50
KeyDown "Shift", 1
Delay 37
Delay 1
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 35
MoveTo 752, 360
Delay 34
KeyDown "Shift", 1
MoveTo 758, 373
Delay 35
KeyDown "Shift", 1
MoveTo 764, 387
Delay 33
KeyDown "Shift", 1
MoveTo 771, 400
Delay 32
KeyDown "Shift", 1
MoveTo 774, 406
Delay 35
KeyDown "Shift", 1
MoveTo 775, 408
Delay 33
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
MoveTo 776, 418
Delay 634
KeyDown "M", 1
Delay 130
KeyUp "M", 1
MoveTo 689, 473
Delay 368
KeyDown "Ctrl", 1
MoveTo 568, 505
Delay 499
KeyDown "Ctrl", 1
MoveTo 566, 507
Delay 35
KeyDown "Ctrl", 1
MoveTo 565, 508
Delay 31
KeyDown "Ctrl", 1
Delay 35
Delay 35
KeyDown "Ctrl", 1
MoveTo 566, 510
Delay 31
KeyDown "Ctrl", 1
MoveTo 577, 510
Delay 33
KeyDown "Ctrl", 1
MoveTo 578, 510
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 6
RightClick 1
Delay 28
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 38
Delay 1
KeyDown "Ctrl", 1
Delay 86
Delay 2
KeyUp "Ctrl", 1
MoveTo 840, 352
Delay 2419
KeyDown "Shift", 1
MoveTo 841, 341
Delay 299
LeftClick 1
MoveTo 831, 355
Delay 140
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 48
Delay 36
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 67
KeyUp "Shift", 1
MoveTo 831, 367
Delay 467
KeyDown "M", 1
MoveTo 830, 368
Delay 99
KeyUp "M", 1
MoveTo 724, 434
Delay 300
KeyDown "Ctrl", 1
MoveTo 614, 511
Delay 532
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
MoveTo 613, 512
Delay 37
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 30
KeyDown "Ctrl", 1
Delay 32
Delay 137
KeyDown "Ctrl", 1
Delay 4
Delay 1
KeyDown "Ctrl", 1
Delay 51
KeyUp "Ctrl", 1
MoveTo 696, 418
Delay 2368
KeyDown "Shift", 1
MoveTo 750, 320
Delay 400
LeftClick 1
Delay 36
KeyDown "Shift", 1
Delay 33
MoveTo 750, 322
Delay 34
KeyDown "Shift", 1
MoveTo 750, 333
Delay 33
KeyDown "Shift", 1
MoveTo 750, 346
Delay 35
KeyDown "Shift", 1
MoveTo 750, 350
Delay 47
KeyDown "Shift", 1
Delay 32
Delay 36
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 1
Delay 37
KeyDown "Shift", 1
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
MoveTo 750, 360
Delay 35
KeyDown "Shift", 1
MoveTo 752, 375
Delay 32
KeyDown "Shift", 1
MoveTo 757, 392
Delay 34
KeyDown "Shift", 1
MoveTo 761, 406
Delay 32
KeyDown "Shift", 1
MoveTo 761, 411
Delay 36
KeyDown "Shift", 1
Delay 32
MoveTo 761, 415
Delay 34
KeyDown "Shift", 1
MoveTo 761, 416
Delay 32
KeyDown "Shift", 1
MoveTo 761, 417
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 1
KeyUp "Shift", 1
Delay 432
KeyDown "M", 1
Delay 144
KeyUp "M", 1
MoveTo 731, 455
Delay 303
KeyDown "Ctrl", 1
MoveTo 662, 523
Delay 499
KeyDown "Ctrl", 1
MoveTo 662, 524
Delay 32
KeyDown "Ctrl", 1
MoveTo 662, 525
Delay 34
KeyDown "Ctrl", 1
MoveTo 662, 527
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 33
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 79
KeyDown "Ctrl", 1
Delay 1
Delay 33
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 824, 348
Delay 2498
KeyDown "Shift", 1
MoveTo 826, 327
Delay 300
LeftClick 1
MoveTo 822, 348
Delay 137
KeyDown "Shift", 1
Delay 1
Delay 33
KeyDown "Shift", 1
Delay 67
Delay 1
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 51
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 34
KeyDown "Shift", 1
Delay 35
MoveTo 822, 355
Delay 3
KeyDown "Shift", 1
MoveTo 822, 368
Delay 35
KeyDown "Shift", 1
MoveTo 821, 379
Delay 33
KeyDown "Shift", 1
MoveTo 819, 385
Delay 32
KeyDown "Shift", 1
MoveTo 819, 390
Delay 33
KeyDown "Shift", 1
MoveTo 818, 396
Delay 34
KeyDown "Shift", 1
MoveTo 816, 400
Delay 36
KeyDown "Shift", 1
MoveTo 816, 403
Delay 33
KeyDown "Shift", 1
MoveTo 815, 408
Delay 35
KeyDown "Shift", 1
MoveTo 813, 415
Delay 32
KeyDown "Shift", 1
MoveTo 813, 419
Delay 34
KeyDown "Shift", 1
Delay 31
Delay 34
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 31
Delay 33
KeyUp "Shift", 1
MoveTo 805, 427
Delay 368
KeyDown "M", 1
MoveTo 802, 431
Delay 167
KeyUp "M", 1
MoveTo 733, 521
Delay 334
KeyDown "Ctrl", 1
MoveTo 702, 564
Delay 533
KeyDown "Ctrl", 1
MoveTo 701, 564
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 696, 564
Delay 33
KeyDown "Ctrl", 1
MoveTo 694, 564
Delay 33
KeyDown "Ctrl", 1
MoveTo 693, 564
Delay 34
KeyDown "Ctrl", 1
MoveTo 692, 564
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 110
KeyDown "Ctrl", 1
Delay 33
MoveTo 692, 566
Delay 34
KeyDown "Ctrl", 1
MoveTo 692, 567
Delay 32
KeyDown "Ctrl", 1
MoveTo 691, 568
Delay 35
KeyDown "Ctrl", 1
MoveTo 691, 569
Delay 33
KeyDown "Ctrl", 1
MoveTo 690, 569
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 689, 571
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 7
KeyDown "Ctrl", 1
Delay 1
MoveTo 693, 562
Delay 28
KeyUp "Ctrl", 1
MoveTo 777, 368
Delay 3097
KeyDown "Shift", 1
MoveTo 781, 364
Delay 236
LeftClick 1
MoveTo 780, 420
Delay 201
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 33
Delay 40
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
Delay 470
KeyDown "M", 1
Delay 127
KeyUp "M", 1
MoveTo 724, 538
Delay 434
KeyDown "Ctrl", 1
MoveTo 930, 592
Delay 501
KeyDown "Ctrl", 1
MoveTo 1066, 571
Delay 33
KeyDown "Ctrl", 1
MoveTo 1147, 551
Delay 34
KeyDown "Ctrl", 1
MoveTo 1223, 541
Delay 32
KeyDown "Ctrl", 1
MoveTo 1266, 533
Delay 36
KeyDown "Ctrl", 1
MoveTo 1268, 533
Delay 30
KeyDown "Ctrl", 1
Delay 34
MoveTo 1269, 533
Delay 33
KeyDown "Ctrl", 1
MoveTo 1269, 532
Delay 33
KeyDown "Ctrl", 1
MoveTo 1261, 532
Delay 34
KeyDown "Ctrl", 1
MoveTo 1256, 532
Delay 33
KeyDown "Ctrl", 1
MoveTo 1248, 532
Delay 34
KeyDown "Ctrl", 1
MoveTo 1227, 534
Delay 34
KeyDown "Ctrl", 1
MoveTo 1196, 536
Delay 33
KeyDown "Ctrl", 1
MoveTo 1135, 541
Delay 32
KeyDown "Ctrl", 1
MoveTo 1039, 542
Delay 34
KeyDown "Ctrl", 1
MoveTo 963, 551
Delay 34
KeyDown "Ctrl", 1
MoveTo 908, 562
Delay 33
KeyDown "Ctrl", 1
MoveTo 874, 573
Delay 33
KeyDown "Ctrl", 1
MoveTo 848, 581
Delay 34
KeyDown "Ctrl", 1
MoveTo 820, 586
Delay 32
KeyDown "Ctrl", 1
MoveTo 788, 591
Delay 34
KeyDown "Ctrl", 1
MoveTo 755, 593
Delay 33
KeyDown "Ctrl", 1
MoveTo 744, 594
Delay 35
KeyDown "Ctrl", 1
MoveTo 739, 594
Delay 2
KeyDown "Ctrl", 1
MoveTo 735, 594
Delay 63
KeyDown "Ctrl", 1
MoveTo 729, 594
Delay 2
KeyDown "Ctrl", 1
MoveTo 721, 594
Delay 65
KeyDown "Ctrl", 1
MoveTo 688, 592
Delay 34
KeyDown "Ctrl", 1
MoveTo 670, 590
Delay 34
KeyDown "Ctrl", 1
MoveTo 665, 590
Delay 32
KeyDown "Ctrl", 1
MoveTo 661, 589
Delay 34
KeyDown "Ctrl", 1
MoveTo 656, 589
Delay 33
KeyDown "Ctrl", 1
MoveTo 650, 589
Delay 33
KeyDown "Ctrl", 1
MoveTo 646, 588
Delay 34
KeyDown "Ctrl", 1
MoveTo 636, 588
Delay 33
KeyDown "Ctrl", 1
MoveTo 630, 588
Delay 33
KeyDown "Ctrl", 1
MoveTo 626, 588
Delay 34
KeyDown "Ctrl", 1
MoveTo 621, 588
Delay 33
KeyDown "Ctrl", 1
MoveTo 619, 588
Delay 34
KeyDown "Ctrl", 1
MoveTo 618, 587
Delay 32
KeyDown "Ctrl", 1
MoveTo 617, 586
Delay 34
KeyDown "Ctrl", 1
MoveTo 616, 586
Delay 34
KeyDown "Ctrl", 1
MoveTo 616, 583
Delay 34
KeyDown "Ctrl", 1
MoveTo 616, 582
Delay 31
KeyDown "Ctrl", 1
MoveTo 616, 581
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 616, 578
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
MoveTo 618, 578
Delay 34
KeyDown "Ctrl", 1
MoveTo 620, 578
Delay 127
KeyDown "Ctrl", 1
MoveTo 623, 578
Delay 59
KeyDown "Ctrl", 1
MoveTo 625, 583
Delay 4
KeyDown "Ctrl", 1
MoveTo 618, 592
Delay 29
KeyDown "Ctrl", 1
Delay 33
MoveTo 618, 593
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 6
KeyDown "Ctrl", 1
MoveTo 618, 592
Delay 27
KeyUp "Ctrl", 1
MoveTo 852, 433
Delay 2097
KeyDown "Shift", 1
MoveTo 810, 361
Delay 503
KeyDown "Shift", 1
MoveTo 811, 360
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 47
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 811, 363
Delay 33
KeyDown "Shift", 1
MoveTo 811, 381
Delay 34
KeyDown "Shift", 1
MoveTo 811, 397
Delay 35
KeyDown "Shift", 1
MoveTo 811, 406
Delay 32
KeyDown "Shift", 1
MoveTo 809, 415
Delay 34
KeyDown "Shift", 1
MoveTo 808, 419
Delay 34
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 36
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
Delay 365
KeyDown "M", 1
MoveTo 808, 421
Delay 165
KeyUp "M", 1
MoveTo 705, 599
Delay 466
KeyDown "Ctrl", 1
MoveTo 592, 599
Delay 501
KeyDown "Ctrl", 1
MoveTo 591, 598
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 591, 597
Delay 34
KeyDown "Ctrl", 1
MoveTo 589, 595
Delay 33
KeyDown "Ctrl", 1
MoveTo 586, 593
Delay 35
KeyDown "Ctrl", 1
MoveTo 583, 591
Delay 33
KeyDown "Ctrl", 1
MoveTo 582, 591
Delay 33
KeyDown "Ctrl", 1
MoveTo 581, 590
Delay 32
KeyDown "Ctrl", 1
MoveTo 581, 589
Delay 33
KeyDown "Ctrl", 1
MoveTo 578, 587
Delay 35
KeyDown "Ctrl", 1
MoveTo 576, 584
Delay 33
KeyDown "Ctrl", 1
MoveTo 574, 582
Delay 34
KeyDown "Ctrl", 1
MoveTo 571, 579
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 114
MoveTo 585, 576
Delay 4
KeyDown "Ctrl", 1
Delay 9
Delay 1
KeyDown "Ctrl", 1
Delay 40
KeyUp "Ctrl", 1
MoveTo 900, 337
Delay 2499
KeyDown "Shift", 1
MoveTo 875, 355
Delay 277
LeftClick 1
MoveTo 847, 415
Delay 168
KeyDown "Shift", 1
MoveTo 843, 421
Delay 45
KeyDown "Shift", 1
MoveTo 842, 422
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 35
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 33
Delay 32
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyUp "Shift", 1
MoveTo 841, 431
Delay 502
KeyDown "M", 1
Delay 132
KeyUp "M", 1
MoveTo 667, 579
Delay 333
KeyDown "Ctrl", 1
MoveTo 539, 545
Delay 532
KeyDown "Ctrl", 1
MoveTo 538, 543
Delay 34
KeyDown "Ctrl", 1
MoveTo 537, 540
Delay 33
KeyDown "Ctrl", 1
MoveTo 536, 538
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 42
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 57
KeyDown "Ctrl", 1
Delay 4
Delay 33
KeyDown "Ctrl", 1
Delay 31
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 114
MoveTo 559, 540
Delay 71
KeyDown "Ctrl", 1
MoveTo 570, 540
Delay 2
KeyDown "Ctrl", 1
MoveTo 590, 538
Delay 31
KeyDown "Ctrl", 1
MoveTo 621, 527
Delay 33
KeyDown "Ctrl", 1
MoveTo 640, 515
Delay 34
KeyDown "Ctrl", 1
Delay 21
MoveTo 651, 507
Delay 12
KeyDown "Ctrl", 1
MoveTo 654, 505
Delay 2
KeyUp "Ctrl", 1
MoveTo 798, 395
Delay 2339
KeyDown "Shift", 1
MoveTo 793, 366
Delay 383
LeftClick 1
MoveTo 793, 382
Delay 73
KeyDown "Shift", 1
MoveTo 793, 398
Delay 33
KeyDown "Shift", 1
MoveTo 793, 407
Delay 35
KeyDown "Shift", 1
MoveTo 794, 410
Delay 34
KeyDown "Shift", 1
MoveTo 795, 412
Delay 50
KeyDown "Shift", 1
MoveTo 795, 413
Delay 34
KeyDown "Shift", 1
Delay 32
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 38
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 3
KeyUp "Shift", 1
Delay 432
KeyDown "M", 1
Delay 136
KeyUp "M", 1
MoveTo 832, 450
Delay 401
KeyDown "Ctrl", 1
MoveTo 738, 476
Delay 500
KeyDown "Ctrl", 1
MoveTo 742, 468
Delay 32
KeyDown "Ctrl", 1
MoveTo 744, 467
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 36
Delay 31
KeyDown "Ctrl", 1
Delay 35
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 2
KeyDown "Ctrl", 1
Delay 63
Delay 33
KeyDown "Ctrl", 1
Delay 4
Delay 64
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 36
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 3
KeyDown "Ctrl", 1
Delay 64
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 37
KeyDown "Ctrl", 1
Delay 30
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 3
Delay 64
KeyDown "Ctrl", 1
Delay 4
Delay 29
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 735, 467
Delay 35
KeyDown "Ctrl", 1
MoveTo 724, 470
Delay 33
KeyDown "Ctrl", 1
MoveTo 702, 473
Delay 34
KeyDown "Ctrl", 1
MoveTo 690, 476
Delay 33
KeyDown "Ctrl", 1
MoveTo 676, 481
Delay 34
KeyDown "Ctrl", 1
MoveTo 658, 489
Delay 32
KeyDown "Ctrl", 1
MoveTo 644, 494
Delay 35
KeyDown "Ctrl", 1
MoveTo 640, 498
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightDown 1
MoveTo 639, 498
Delay 35
KeyDown "Ctrl", 1
Delay 30
Delay 35
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 112
Delay 60
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 1
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 795, 420
Delay 2325
KeyDown "Shift", 1
MoveTo 824, 363
Delay 470
LeftDown 1
Delay 42
KeyDown "Shift", 1
Delay 35
Delay 37
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 825, 363
Delay 2
KeyDown "Shift", 1
MoveTo 825, 374
Delay 49
KeyDown "Shift", 1
MoveTo 821, 390
Delay 33
KeyDown "Shift", 1
MoveTo 819, 408
Delay 33
KeyDown "Shift", 1
MoveTo 819, 415
Delay 34
KeyDown "Shift", 1
Delay 32
Delay 33
KeyDown "Shift", 1
MoveTo 819, 416
Delay 34
KeyDown "Shift", 1
Delay 33
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 31
Delay 33
KeyDown "Shift", 1
Delay 33
KeyUp "Shift", 1
MoveTo 816, 421
Delay 410
KeyDown "M", 1
MoveTo 813, 424
Delay 165
KeyUp "M", 1
MoveTo 567, 485
Delay 6268
KeyDown "Ctrl", 1
MoveTo 515, 472
Delay 532
KeyDown "Ctrl", 1
Delay 6
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 60
Delay 4
KeyDown "Ctrl", 1
Delay 29
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 33
Delay 30
KeyDown "Ctrl", 1
Delay 131
Delay 3
KeyDown "Ctrl", 1
Delay 2
Delay 36
KeyDown "Ctrl", 1
Delay 1
Delay 13
KeyDown "Ctrl", 1
MoveTo 516, 472
Delay 3
KeyUp "Ctrl", 1
MoveTo 1014, 440
Delay 2422
KeyDown "Shift", 1
MoveTo 956, 359
Delay 515
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 47
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 35
Delay 34
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 956, 372
Delay 39
KeyDown "Shift", 1
MoveTo 948, 398
Delay 34
KeyDown "Shift", 1
MoveTo 941, 411
Delay 35
KeyDown "Shift", 1
MoveTo 936, 427
Delay 34
KeyDown "Shift", 1
MoveTo 935, 436
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 1
LeftDown 1
Delay 35
KeyDown "Shift", 1
Delay 38
Delay 35
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 935, 437
Delay 33
KeyDown "Shift", 1
MoveTo 935, 432
Delay 38
KeyDown "Shift", 1
MoveTo 935, 426
Delay 40
KeyDown "Shift", 1
MoveTo 935, 425
Delay 44
KeyDown "Shift", 1
Delay 33
Delay 43
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 35
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 32
Delay 34
KeyDown "Shift", 1
Delay 33
MoveTo 938, 422
Delay 35
KeyDown "Shift", 1
MoveTo 970, 418
Delay 35
KeyDown "Shift", 1
MoveTo 1020, 414
Delay 39
KeyUp "Shift", 1
'==========以上是按键精灵录制的内容==========
