[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=553bc737-1a6f-48a0-b8cb-6b2aa1fca718
Description=放置猎物 E9
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 604, 641
Delay 734
LeftClick 1
Delay 800
KeyDown "`", 1
Delay 164
KeyUp "`", 1
Delay 868
KeyDown "M", 1
Delay 98
KeyDown "A", 1
Delay 67
KeyUp "M", 1
Delay 100
KeyUp "A", 1
Delay 2
KeyDown "K", 1
Delay 132
KeyDown "E", 1
Delay 68
KeyUp "K", 1
Delay 65
KeyUp "E", 1
Delay 299
KeyDown "Tab", 1
Delay 169
KeyUp "Tab", 1
Delay 99
KeyDown "Space", 1
Delay 166
KeyUp "Space", 1
Delay 201
KeyDown "Shift", 1
Delay 132
KeyDown "H", 1
Delay 136
KeyUp "Shift", 1
Delay 32
KeyUp "H", 1
Delay 65
KeyDown "A", 1
Delay 169
KeyDown "Y", 1
Delay 32
KeyUp "A", 1
Delay 100
KeyUp "Y", 1
Delay 100
KeyDown "O", 1
Delay 259
KeyUp "O", 1
Delay 2
KeyDown "O", 1
Delay 31
KeyDown "U", 1
Delay 34
KeyUp "O", 1
Delay 109
KeyUp "U", 1
Delay 33
KeyDown "Shift", 1
Delay 101
KeyDown "2", 1
Delay 133
KeyUp "Shift", 1
Delay 100
KeyUp "2", 1
Delay 600
KeyDown "2", 1
Delay 200
KeyUp "2", 1
Delay 338
KeyDown "9", 1
Delay 96
KeyUp "9", 1
Delay 67
KeyDown "9", 1
Delay 99
KeyUp "9", 1
Delay 100
KeyDown "9", 1
Delay 67
KeyUp "9", 1
Delay 134
KeyDown "9", 1
Delay 99
KeyUp "9", 1
Delay 401
KeyDown "Enter", 1
Delay 99
KeyUp "Enter", 1
Delay 1100
KeyDown "Esc", 1
MoveTo 608, 641
Delay 201
KeyUp "Esc", 1
MoveTo 1000, 802
Delay 1266
LeftClick 1
MoveTo 1843, 139
Delay 1443
LeftClick 1
MoveTo 708, 221
Delay 2227
LeftClick 1
MoveTo 702, 285
Delay 935
LeftClick 1
Delay 1357
KeyDown "H", 1
Delay 162
KeyDown "A", 1
Delay 18
KeyUp "H", 1
Delay 6
KeyDown "Y", 1
Delay 19
KeyUp "A", 1
Delay 138
KeyUp "Y", 1
MoveTo 726, 369
Delay 3907
KeyDown "Shift", 1
MoveTo 726, 367
Delay 133
LeftClick 1
Delay 90
KeyUp "Shift", 1
MoveTo 733, 438
Delay 1632
KeyDown "Shift", 1
MoveTo 748, 419
Delay 506
KeyDown "Shift", 1
MoveTo 748, 417
Delay 49
KeyDown "Shift", 1
MoveTo 749, 417
Delay 43
KeyDown "Shift", 1
Delay 43
Delay 44
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 50
KeyDown "Shift", 1
Delay 51
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 43
Delay 41
KeyDown "Shift", 1
Delay 46
Delay 41
KeyUp "Shift", 1
Delay 525
KeyDown "M", 1
MoveTo 749, 416
Delay 143
KeyUp "M", 1
MoveTo 696, 484
Delay 733
KeyDown "Ctrl", 1
MoveTo 736, 516
Delay 500
KeyDown "Ctrl", 1
MoveTo 740, 513
Delay 34
KeyDown "Ctrl", 1
MoveTo 742, 512
Delay 34
KeyDown "Ctrl", 1
MoveTo 743, 511
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 35
MoveTo 745, 510
Delay 32
KeyDown "Ctrl", 1
MoveTo 746, 507
Delay 34
KeyDown "Ctrl", 1
MoveTo 746, 501
Delay 35
KeyDown "Ctrl", 1
MoveTo 744, 495
Delay 32
KeyDown "Ctrl", 1
MoveTo 738, 490
Delay 35
KeyDown "Ctrl", 1
MoveTo 733, 487
Delay 32
KeyDown "Ctrl", 1
MoveTo 728, 482
Delay 33
KeyDown "Ctrl", 1
MoveTo 725, 479
Delay 33
KeyDown "Ctrl", 1
MoveTo 725, 477
Delay 33
KeyDown "Ctrl", 1
MoveTo 722, 477
Delay 33
KeyDown "Ctrl", 1
MoveTo 719, 476
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 61
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 1
Delay 68
KeyDown "Ctrl", 1
Delay 5
Delay 145
KeyDown "Ctrl", 1
Delay 2
Delay 7
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 748, 365
Delay 3647
KeyDown "Shift", 1
Delay 206
LeftClick 1
MoveTo 748, 427
Delay 198
KeyDown "Shift", 1
Delay 44
Delay 55
KeyDown "Shift", 1
MoveTo 749, 425
Delay 50
KeyDown "Shift", 1
Delay 53
Delay 48
KeyDown "Shift", 1
Delay 47
Delay 1
LeftDown 1
Delay 51
KeyDown "Shift", 1
Delay 73
Delay 5
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 53
MoveTo 749, 500
Delay 55
KeyDown "Shift", 1
MoveTo 749, 516
Delay 46
KeyDown "Shift", 1
Delay 40
Delay 56
KeyDown "Shift", 1
MoveTo 749, 511
Delay 54
KeyDown "Shift", 1
MoveTo 749, 502
Delay 53
KeyDown "Shift", 1
MoveTo 749, 501
Delay 60
KeyDown "Shift", 1
MoveTo 749, 500
Delay 59
KeyDown "Shift", 1
Delay 71
Delay 46
KeyDown "Shift", 1
Delay 61
Delay 53
KeyDown "Shift", 1
Delay 65
Delay 46
KeyDown "Shift", 1
Delay 44
Delay 56
KeyDown "Shift", 1
Delay 59
Delay 55
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 62
KeyDown "Shift", 1
Delay 58
Delay 1
LeftUp 1
Delay 74
KeyDown "Shift", 1
Delay 50
MoveTo 748, 498
Delay 4
KeyDown "Shift", 1
Delay 44
KeyUp "Shift", 1
MoveTo 747, 497
Delay 538
KeyDown "M", 1
Delay 162
KeyUp "M", 1
MoveTo 676, 468
Delay 300
KeyDown "Ctrl", 1
MoveTo 605, 533
Delay 533
KeyDown "Ctrl", 1
MoveTo 605, 534
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 607, 535
Delay 4
KeyDown "Ctrl", 1
Delay 62
Delay 2
KeyDown "Ctrl", 1
Delay 43
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 54
Delay 32
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 609, 536
Delay 34
KeyDown "Ctrl", 1
MoveTo 626, 542
Delay 33
KeyDown "Ctrl", 1
MoveTo 634, 547
Delay 35
KeyDown "Ctrl", 1
Delay 34
Delay 2
KeyUp "Ctrl", 1
MoveTo 686, 350
Delay 3218
KeyDown "Shift", 1
Delay 224
LeftClick 1
MoveTo 720, 428
Delay 183
KeyDown "Shift", 1
MoveTo 722, 430
Delay 44
KeyDown "Shift", 1
Delay 40
MoveTo 723, 431
Delay 40
KeyDown "Shift", 1
MoveTo 724, 427
Delay 45
KeyDown "Shift", 1
MoveTo 725, 420
Delay 49
KeyDown "Shift", 1
MoveTo 725, 415
Delay 2
KeyDown "Shift", 1
MoveTo 725, 414
Delay 41
KeyDown "Shift", 1
Delay 40
Delay 52
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 52
Delay 58
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 46
MoveTo 730, 425
Delay 50
KeyDown "Shift", 1
MoveTo 732, 443
Delay 48
KeyDown "Shift", 1
MoveTo 739, 479
Delay 53
KeyDown "Shift", 1
MoveTo 740, 485
Delay 58
KeyDown "Shift", 1
Delay 48
Delay 2
KeyDown "Shift", 1
MoveTo 741, 485
Delay 50
KeyDown "Shift", 1
MoveTo 741, 482
Delay 64
KeyDown "Shift", 1
MoveTo 741, 478
Delay 61
KeyDown "Shift", 1
MoveTo 741, 477
Delay 54
KeyDown "Shift", 1
MoveTo 741, 476
Delay 3
KeyDown "Shift", 1
MoveTo 739, 488
Delay 53
KeyDown "Shift", 1
MoveTo 739, 500
Delay 57
KeyDown "Shift", 1
MoveTo 739, 505
Delay 53
KeyDown "Shift", 1
Delay 45
Delay 3
LeftDown 1
Delay 55
KeyDown "Shift", 1
Delay 50
Delay 2
LeftUp 1
Delay 8
KeyDown "Shift", 1
Delay 54
Delay 62
KeyDown "Shift", 1
Delay 4
KeyUp "Shift", 1
MoveTo 733, 511
Delay 417
KeyDown "M", 1
Delay 134
KeyUp "M", 1
MoveTo 713, 517
Delay 233
KeyDown "Ctrl", 1
MoveTo 557, 584
Delay 533
KeyDown "Ctrl", 1
MoveTo 558, 584
Delay 33
KeyDown "Ctrl", 1
MoveTo 559, 584
Delay 33
KeyDown "Ctrl", 1
MoveTo 565, 586
Delay 34
KeyDown "Ctrl", 1
MoveTo 568, 590
Delay 33
KeyDown "Ctrl", 1
MoveTo 569, 591
Delay 3
KeyDown "Ctrl", 1
Delay 63
MoveTo 572, 591
Delay 9
KeyDown "Ctrl", 1
MoveTo 576, 581
Delay 26
KeyDown "Ctrl", 1
MoveTo 577, 574
Delay 32
KeyDown "Ctrl", 1
MoveTo 578, 570
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 579, 570
Delay 33
RightDown 1
Delay 3
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 6
RightClick 1
Delay 25
KeyDown "Ctrl", 1
Delay 35
Delay 148
KeyDown "Ctrl", 1
Delay 1
Delay 10
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 707, 379
Delay 2836
KeyDown "Shift", 1
MoveTo 709, 369
Delay 290
LeftClick 1
MoveTo 712, 381
Delay 94
KeyDown "Shift", 1
MoveTo 715, 392
Delay 46
KeyDown "Shift", 1
MoveTo 718, 406
Delay 56
KeyDown "Shift", 1
MoveTo 719, 408
Delay 3
KeyDown "Shift", 1
Delay 41
Delay 41
KeyDown "Shift", 1
Delay 43
Delay 46
KeyDown "Shift", 1
Delay 44
Delay 46
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 49
Delay 60
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 49
Delay 43
KeyDown "Shift", 1
Delay 45
Delay 45
KeyDown "Shift", 1
MoveTo 730, 424
Delay 44
KeyDown "Shift", 1
MoveTo 741, 443
Delay 51
KeyDown "Shift", 1
MoveTo 754, 482
Delay 57
KeyDown "Shift", 1
MoveTo 754, 486
Delay 50
KeyDown "Shift", 1
Delay 40
Delay 49
KeyDown "Shift", 1
Delay 42
MoveTo 754, 488
Delay 43
KeyDown "Shift", 1
MoveTo 752, 494
Delay 47
KeyDown "Shift", 1
MoveTo 750, 504
Delay 42
KeyDown "Shift", 1
Delay 39
Delay 44
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 47
Delay 49
KeyDown "Shift", 1
Delay 2
LeftUp 1
MoveTo 750, 505
Delay 7
KeyDown "Shift", 1
Delay 51
Delay 44
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
Delay 351
KeyDown "M", 1
MoveTo 750, 509
Delay 149
KeyUp "M", 1
MoveTo 746, 511
Delay 337
KeyDown "Ctrl", 1
MoveTo 570, 579
Delay 530
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 570, 577
Delay 33
KeyDown "Ctrl", 1
MoveTo 570, 574
Delay 32
KeyDown "Ctrl", 1
MoveTo 570, 573
Delay 34
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 36
KeyDown "Ctrl", 1
Delay 2
MoveTo 570, 572
Delay 28
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 2
Delay 65
KeyDown "Ctrl", 1
Delay 2
Delay 132
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 30
Delay 5
KeyUp "Ctrl", 1
MoveTo 632, 469
Delay 2172
KeyDown "Shift", 1
MoveTo 657, 356
Delay 502
KeyDown "Shift", 1
Delay 54
Delay 59
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 90
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 1
MoveTo 657, 358
Delay 53
KeyDown "Shift", 1
MoveTo 659, 369
Delay 55
KeyDown "Shift", 1
MoveTo 663, 397
Delay 56
KeyDown "Shift", 1
MoveTo 666, 410
Delay 57
KeyDown "Shift", 1
MoveTo 666, 413
Delay 56
KeyDown "Shift", 1
MoveTo 666, 415
Delay 56
KeyDown "Shift", 1
MoveTo 666, 419
Delay 62
KeyDown "Shift", 1
Delay 44
Delay 54
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 65
LeftUp 1
Delay 7
KeyDown "Shift", 1
MoveTo 671, 430
Delay 56
KeyDown "Shift", 1
MoveTo 683, 464
Delay 45
KeyDown "Shift", 1
MoveTo 685, 473
Delay 48
KeyDown "Shift", 1
Delay 45
Delay 47
KeyDown "Shift", 1
Delay 47
MoveTo 685, 474
Delay 52
KeyDown "Shift", 1
Delay 61
Delay 54
KeyDown "Shift", 1
Delay 49
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 2
Delay 51
KeyDown "Shift", 1
Delay 65
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 686, 453
Delay 60
KeyDown "Shift", 1
MoveTo 686, 396
Delay 61
KeyDown "Shift", 1
MoveTo 690, 346
Delay 59
KeyDown "Shift", 1
MoveTo 690, 340
Delay 57
KeyDown "Shift", 1
MoveTo 691, 339
Delay 3
KeyDown "Shift", 1
Delay 48
Delay 51
KeyDown "Shift", 1
Delay 56
Delay 58
KeyDown "Shift", 1
MoveTo 693, 331
Delay 61
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 69
KeyDown "Shift", 1
Delay 57
Delay 2
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 55
Delay 56
KeyUp "Shift", 1
MoveTo 690, 340
Delay 420
KeyDown "M", 1
MoveTo 688, 350
Delay 171
KeyUp "M", 1
MoveTo 682, 459
Delay 198
KeyDown "Ctrl", 1
MoveTo 589, 568
Delay 511
KeyDown "Ctrl", 1
MoveTo 584, 568
Delay 33
KeyDown "Ctrl", 1
MoveTo 581, 569
Delay 36
KeyDown "Ctrl", 1
MoveTo 579, 570
Delay 28
KeyDown "Ctrl", 1
MoveTo 579, 571
Delay 35
KeyDown "Ctrl", 1
MoveTo 578, 574
Delay 33
KeyDown "Ctrl", 1
MoveTo 577, 577
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
MoveTo 577, 578
Delay 32
KeyDown "Ctrl", 1
MoveTo 580, 579
Delay 35
KeyDown "Ctrl", 1
Delay 53
Delay 2
KeyDown "Ctrl", 1
MoveTo 583, 577
Delay 154
KeyDown "Ctrl", 1
MoveTo 591, 570
Delay 2
KeyUp "Ctrl", 1
MoveTo 612, 316
Delay 2696
KeyDown "Shift", 1
MoveTo 624, 368
Delay 540
KeyDown "Shift", 1
MoveTo 625, 365
Delay 92
KeyDown "Shift", 1
Delay 60
LeftDown 1
Delay 5
KeyDown "Shift", 1
Delay 2
Delay 72
KeyDown "Shift", 1
Delay 3
LeftUp 1
MoveTo 625, 364
Delay 7
KeyDown "Shift", 1
MoveTo 631, 352
Delay 70
KeyDown "Shift", 1
MoveTo 633, 344
Delay 52
KeyDown "Shift", 1
MoveTo 636, 337
Delay 53
KeyDown "Shift", 1
MoveTo 637, 335
Delay 4
KeyDown "Shift", 1
Delay 50
MoveTo 638, 334
Delay 50
KeyDown "Shift", 1
Delay 6
LeftDown 1
Delay 54
KeyDown "Shift", 1
Delay 3
Delay 53
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 54
KeyDown "Shift", 1
Delay 62
Delay 9
Delay 4
KeyDown "Shift", 1
Delay 80
Delay 3
LeftUp 1
Delay 12
KeyDown "Shift", 1
Delay 55
MoveTo 647, 349
Delay 5
KeyDown "Shift", 1
MoveTo 662, 386
Delay 61
KeyDown "Shift", 1
MoveTo 670, 423
Delay 62
KeyDown "Shift", 1
MoveTo 671, 431
Delay 4
KeyDown "Shift", 1
MoveTo 671, 440
Delay 64
KeyDown "Shift", 1
MoveTo 671, 452
Delay 60
KeyDown "Shift", 1
MoveTo 671, 454
Delay 3
KeyDown "Shift", 1
Delay 54
Delay 58
KeyDown "Shift", 1
MoveTo 672, 450
Delay 64
KeyDown "Shift", 1
MoveTo 675, 437
Delay 56
KeyDown "Shift", 1
MoveTo 680, 428
Delay 61
KeyDown "Shift", 1
MoveTo 682, 421
Delay 62
KeyDown "Shift", 1
MoveTo 682, 420
Delay 50
KeyDown "Shift", 1
Delay 48
Delay 2
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 58
Delay 61
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 62
Delay 4
KeyDown "Shift", 1
Delay 59
KeyUp "Shift", 1
Delay 441
KeyDown "M", 1
Delay 175
KeyUp "M", 1
MoveTo 688, 518
Delay 234
KeyDown "Ctrl", 1
MoveTo 624, 567
Delay 504
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 32
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 56
Delay 2
KeyDown "Ctrl", 1
Delay 128
Delay 1
KeyUp "Ctrl", 1
MoveTo 663, 316
Delay 2713
KeyDown "Shift", 1
MoveTo 672, 365
Delay 505
KeyDown "Shift", 1
MoveTo 672, 363
Delay 59
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 83
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 74
MoveTo 677, 350
Delay 52
KeyDown "Shift", 1
MoveTo 681, 341
Delay 59
KeyDown "Shift", 1
MoveTo 681, 337
Delay 48
KeyDown "Shift", 1
MoveTo 681, 336
Delay 54
KeyDown "Shift", 1
Delay 53
Delay 51
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 60
Delay 2
LeftUp 1
Delay 62
KeyDown "Shift", 1
Delay 53
Delay 4
KeyDown "Shift", 1
MoveTo 681, 350
Delay 63
KeyDown "Shift", 1
MoveTo 681, 380
Delay 5
KeyDown "Shift", 1
MoveTo 683, 395
Delay 61
KeyDown "Shift", 1
MoveTo 684, 397
Delay 3
KeyDown "Shift", 1
MoveTo 684, 398
Delay 59
KeyDown "Shift", 1
MoveTo 685, 401
Delay 57
KeyDown "Shift", 1
MoveTo 685, 411
Delay 46
KeyDown "Shift", 1
MoveTo 686, 413
Delay 3
KeyDown "Shift", 1
MoveTo 687, 416
Delay 45
KeyDown "Shift", 1
MoveTo 688, 416
Delay 46
KeyDown "Shift", 1
MoveTo 689, 418
Delay 3
KeyDown "Shift", 1
Delay 47
Delay 52
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 57
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 54
Delay 47
Delay 2
KeyDown "Shift", 1
Delay 51
Delay 50
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 46
Delay 47
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 686, 424
Delay 410
KeyDown "M", 1
Delay 146
KeyUp "M", 1
MoveTo 788, 561
Delay 333
KeyDown "Ctrl", 1
MoveTo 665, 560
Delay 499
KeyDown "Ctrl", 1
MoveTo 664, 559
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 665, 558
Delay 37
KeyDown "Ctrl", 1
MoveTo 668, 553
Delay 32
KeyDown "Ctrl", 1
MoveTo 671, 551
Delay 31
KeyDown "Ctrl", 1
MoveTo 673, 549
Delay 35
KeyDown "Ctrl", 1
MoveTo 673, 548
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 38
KeyDown "Ctrl", 1
Delay 29
Delay 34
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
MoveTo 674, 548
Delay 34
KeyDown "Ctrl", 1
Delay 10
Delay 3
KeyDown "Ctrl", 1
MoveTo 677, 548
Delay 20
KeyUp "Ctrl", 1
MoveTo 712, 432
Delay 2989
KeyDown "Shift", 1
MoveTo 729, 330
Delay 446
LeftDown 1
Delay 95
KeyDown "Shift", 1
Delay 45
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 729, 336
Delay 11
KeyDown "Shift", 1
MoveTo 725, 350
Delay 44
KeyDown "Shift", 1
MoveTo 724, 358
Delay 47
KeyDown "Shift", 1
MoveTo 723, 365
Delay 47
KeyDown "Shift", 1
Delay 44
Delay 47
KeyDown "Shift", 1
Delay 2
Delay 50
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 60
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 41
Delay 3
KeyDown "Shift", 1
MoveTo 723, 369
Delay 47
KeyDown "Shift", 1
MoveTo 723, 385
Delay 56
KeyDown "Shift", 1
MoveTo 728, 407
Delay 53
KeyDown "Shift", 1
MoveTo 730, 410
Delay 54
KeyDown "Shift", 1
MoveTo 731, 415
Delay 57
KeyDown "Shift", 1
Delay 51
Delay 41
KeyDown "Shift", 1
MoveTo 732, 416
Delay 52
KeyDown "Shift", 1
Delay 40
Delay 2
LeftDown 1
Delay 51
KeyDown "Shift", 1
Delay 50
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 42
Delay 1
Delay 50
KeyDown "Shift", 1
Delay 70
Delay 5
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 43
MoveTo 733, 416
Delay 45
KeyDown "Shift", 1
Delay 43
KeyUp "Shift", 1
Delay 386
KeyDown "M", 1
Delay 146
KeyUp "M", 1
MoveTo 672, 463
Delay 334
KeyDown "Ctrl", 1
MoveTo 620, 454
Delay 500
KeyDown "Ctrl", 1
MoveTo 619, 456
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 618, 456
Delay 34
KeyDown "Ctrl", 1
Delay 39
Delay 28
KeyDown "Ctrl", 1
MoveTo 617, 457
Delay 33
KeyDown "Ctrl", 1
MoveTo 615, 457
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 613, 457
Delay 33
KeyDown "Ctrl", 1
MoveTo 613, 456
Delay 35
KeyDown "Ctrl", 1
MoveTo 612, 455
Delay 33
KeyDown "Ctrl", 1
MoveTo 611, 455
Delay 32
KeyDown "Ctrl", 1
MoveTo 609, 454
Delay 34
KeyDown "Ctrl", 1
MoveTo 607, 452
Delay 34
KeyDown "Ctrl", 1
MoveTo 606, 452
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 2
RightClick 1
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 3
KeyDown "Ctrl", 1
Delay 1
Delay 146
KeyUp "Ctrl", 1
MoveTo 619, 414
Delay 2766
KeyDown "Shift", 1
MoveTo 674, 345
Delay 537
KeyDown "Shift", 1
Delay 41
MoveTo 675, 343
Delay 65
KeyDown "Shift", 1
MoveTo 675, 341
Delay 43
KeyDown "Shift", 1
MoveTo 675, 340
Delay 45
KeyDown "Shift", 1
Delay 45
Delay 48
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 55
Delay 8
KeyDown "Shift", 1
Delay 49
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 46
MoveTo 675, 365
Delay 59
KeyDown "Shift", 1
MoveTo 675, 367
Delay 3
KeyDown "Shift", 1
Delay 42
Delay 38
KeyDown "Shift", 1
Delay 41
Delay 39
KeyDown "Shift", 1
Delay 6
Delay 47
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 51
KeyDown "Shift", 1
Delay 59
Delay 3
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 59
MoveTo 675, 369
Delay 5
KeyDown "Shift", 1
MoveTo 678, 378
Delay 68
KeyDown "Shift", 1
MoveTo 687, 420
Delay 42
KeyDown "Shift", 1
MoveTo 692, 437
Delay 50
KeyDown "Shift", 1
MoveTo 694, 443
Delay 43
KeyDown "Shift", 1
MoveTo 696, 443
Delay 50
KeyDown "Shift", 1
MoveTo 698, 440
Delay 4
KeyDown "Shift", 1
MoveTo 698, 435
Delay 43
KeyDown "Shift", 1
MoveTo 697, 431
Delay 51
KeyDown "Shift", 1
MoveTo 697, 424
Delay 50
KeyDown "Shift", 1
MoveTo 697, 410
Delay 48
KeyDown "Shift", 1
MoveTo 697, 409
Delay 3
KeyDown "Shift", 1
Delay 45
Delay 3
LeftDown 1
Delay 46
KeyDown "Shift", 1
Delay 49
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 42
Delay 44
KeyDown "Shift", 1
Delay 41
Delay 42
KeyDown "Shift", 1
MoveTo 698, 410
Delay 46
KeyDown "Shift", 1
MoveTo 698, 418
Delay 43
KeyDown "Shift", 1
MoveTo 700, 425
Delay 43
KeyDown "Shift", 1
MoveTo 701, 427
Delay 47
KeyDown "Shift", 1
MoveTo 703, 431
Delay 54
KeyDown "Shift", 1
MoveTo 704, 432
Delay 54
KeyDown "Shift", 1
MoveTo 711, 448
Delay 56
KeyDown "Shift", 1
MoveTo 715, 466
Delay 55
KeyDown "Shift", 1
MoveTo 720, 476
Delay 6
KeyDown "Shift", 1
MoveTo 722, 479
Delay 48
KeyDown "Shift", 1
MoveTo 722, 481
Delay 46
KeyDown "Shift", 1
MoveTo 723, 484
Delay 46
KeyDown "Shift", 1
MoveTo 723, 492
Delay 73
KeyDown "Shift", 1
MoveTo 723, 499
Delay 51
KeyDown "Shift", 1
Delay 52
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 60
Delay 2
LeftUp 1
Delay 48
KeyDown "Shift", 1
Delay 48
Delay 2
KeyDown "Shift", 1
Delay 53
Delay 49
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 44
KeyUp "Shift", 1
Delay 341
KeyDown "M", 1
MoveTo 721, 497
Delay 165
KeyUp "M", 1
MoveTo 704, 494
Delay 269
KeyDown "Ctrl", 1
MoveTo 612, 497
Delay 499
KeyDown "Ctrl", 1
MoveTo 611, 495
Delay 33
KeyDown "Ctrl", 1
MoveTo 610, 495
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 609, 494
Delay 33
KeyDown "Ctrl", 1
MoveTo 607, 492
Delay 34
KeyDown "Ctrl", 1
MoveTo 605, 490
Delay 32
KeyDown "Ctrl", 1
Delay 35
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
MoveTo 605, 489
Delay 2
KeyDown "Ctrl", 1
MoveTo 606, 489
Delay 32
KeyDown "Ctrl", 1
MoveTo 610, 489
Delay 34
KeyDown "Ctrl", 1
Delay 23
Delay 2
KeyDown "Ctrl", 1
MoveTo 612, 488
Delay 9
KeyUp "Ctrl", 1
MoveTo 685, 385
Delay 2751
KeyDown "Shift", 1
MoveTo 704, 361
Delay 477
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 56
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 60
Delay 43
KeyDown "Shift", 1
Delay 44
Delay 2
Delay 58
KeyDown "Shift", 1
Delay 53
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 705, 357
Delay 46
KeyDown "Shift", 1
MoveTo 708, 344
Delay 48
KeyDown "Shift", 1
MoveTo 711, 333
Delay 43
KeyDown "Shift", 1
Delay 42
MoveTo 711, 332
Delay 47
KeyDown "Shift", 1
Delay 41
Delay 5
LeftDown 1
Delay 49
KeyDown "Shift", 1
Delay 54
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 40
Delay 44
KeyDown "Shift", 1
MoveTo 711, 338
Delay 50
KeyDown "Shift", 1
MoveTo 711, 364
Delay 4
KeyDown "Shift", 1
MoveTo 713, 399
Delay 43
KeyDown "Shift", 1
MoveTo 716, 419
Delay 45
KeyDown "Shift", 1
MoveTo 717, 425
Delay 47
KeyDown "Shift", 1
MoveTo 717, 430
Delay 48
KeyDown "Shift", 1
Delay 43
Delay 44
KeyDown "Shift", 1
Delay 46
MoveTo 717, 432
Delay 46
KeyDown "Shift", 1
MoveTo 714, 424
Delay 49
KeyDown "Shift", 1
MoveTo 714, 420
Delay 41
KeyDown "Shift", 1
Delay 5
Delay 39
KeyDown "Shift", 1
Delay 6
LeftDown 1
Delay 49
KeyDown "Shift", 1
Delay 2
Delay 50
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 42
KeyDown "Shift", 1
Delay 3
Delay 45
KeyDown "Shift", 1
Delay 3
Delay 46
KeyDown "Shift", 1
Delay 48
Delay 1
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 39
Delay 41
KeyDown "Shift", 1
Delay 39
KeyUp "Shift", 1
Delay 311
KeyDown "M", 1
MoveTo 712, 419
Delay 169
KeyUp "M", 1
MoveTo 630, 560
Delay 1299
RightDown 1
Delay 133
RightClick 1
MoveTo 642, 553
Delay 3676
KeyDown "Esc", 1
Delay 167
KeyUp "Esc", 1
MoveTo 632, 554
Delay 734
KeyDown "Ctrl", 1
MoveTo 630, 552
Delay 165
RightDown 1
Delay 134
RightClick 1
Delay 161
KeyDown "Ctrl", 1
Delay 1
MoveTo 636, 552
Delay 59
KeyUp "Ctrl", 1
MoveTo 777, 346
Delay 2546
KeyDown "Shift", 1
MoveTo 773, 353
Delay 344
LeftClick 1
Delay 91
KeyDown "Shift", 1
Delay 49
Delay 2
KeyDown "Shift", 1
Delay 51
Delay 1
LeftUp 1
Delay 46
KeyDown "Shift", 1
MoveTo 772, 350
Delay 46
KeyDown "Shift", 1
MoveTo 772, 334
Delay 39
KeyDown "Shift", 1
MoveTo 771, 333
Delay 55
KeyDown "Shift", 1
Delay 3
Delay 39
KeyDown "Shift", 1
Delay 44
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 57
Delay 72
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 54
Delay 2
Delay 1
KeyDown "Shift", 1
Delay 57
Delay 51
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 48
MoveTo 756, 397
Delay 47
KeyDown "Shift", 1
MoveTo 754, 418
Delay 46
KeyDown "Shift", 1
MoveTo 753, 425
Delay 54
KeyDown "Shift", 1
Delay 46
Delay 37
KeyDown "Shift", 1
Delay 52
LeftDown 1
Delay 5
KeyDown "Shift", 1
Delay 1
Delay 63
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 57
Delay 2
KeyDown "Shift", 1
Delay 60
Delay 39
KeyUp "Shift", 1
MoveTo 746, 444
Delay 455
KeyDown "M", 1
MoveTo 745, 447
Delay 148
KeyUp "M", 1
MoveTo 695, 560
Delay 304
KeyDown "Ctrl", 1
MoveTo 647, 568
Delay 485
RightDown 1
Delay 34
KeyDown "Ctrl", 1
MoveTo 648, 567
Delay 67
KeyDown "Ctrl", 1
Delay 65
Delay 1
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 126
Delay 1
KeyDown "Ctrl", 1
Delay 40
Delay 2
KeyUp "Ctrl", 1
MoveTo 716, 343
Delay 2810
KeyDown "Shift", 1
MoveTo 720, 330
Delay 475
LeftDown 1
Delay 48
KeyDown "Shift", 1
Delay 68
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 43
Delay 2
KeyDown "Shift", 1
Delay 51
Delay 2
KeyDown "Shift", 1
Delay 44
Delay 2
KeyDown "Shift", 1
Delay 47
LeftUp 1
Delay 7
KeyDown "Shift", 1
MoveTo 720, 338
Delay 43
KeyDown "Shift", 1
MoveTo 720, 343
Delay 5
KeyDown "Shift", 1
MoveTo 720, 345
Delay 46
KeyDown "Shift", 1
Delay 39
Delay 42
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 48
Delay 49
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 44
MoveTo 720, 349
Delay 42
KeyDown "Shift", 1
MoveTo 720, 353
Delay 45
KeyDown "Shift", 1
Delay 38
Delay 39
KeyDown "Shift", 1
Delay 44
Delay 42
KeyDown "Shift", 1
Delay 41
MoveTo 722, 360
Delay 45
KeyDown "Shift", 1
MoveTo 723, 373
Delay 2
KeyDown "Shift", 1
MoveTo 723, 389
Delay 50
KeyDown "Shift", 1
MoveTo 723, 396
Delay 40
KeyDown "Shift", 1
MoveTo 724, 401
Delay 52
KeyDown "Shift", 1
MoveTo 725, 410
Delay 52
KeyDown "Shift", 1
MoveTo 726, 414
Delay 44
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 46
KeyDown "Shift", 1
Delay 45
Delay 51
LeftUp 1
Delay 7
KeyDown "Shift", 1
MoveTo 726, 415
Delay 3
KeyDown "Shift", 1
Delay 47
Delay 42
Delay 2
KeyDown "Shift", 1
Delay 46
Delay 49
LeftUp 1
MoveTo 726, 417
Delay 7
KeyDown "Shift", 1
MoveTo 724, 427
Delay 2
KeyDown "Shift", 1
MoveTo 718, 441
Delay 46
KeyDown "Shift", 1
MoveTo 714, 452
Delay 45
KeyDown "Shift", 1
MoveTo 712, 457
Delay 42
KeyDown "Shift", 1
MoveTo 712, 458
Delay 43
KeyDown "Shift", 1
Delay 47
Delay 39
KeyDown "Shift", 1
Delay 40
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 44
Delay 46
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 57
MoveTo 712, 460
Delay 40
KeyDown "Shift", 1
MoveTo 712, 467
Delay 56
KeyDown "Shift", 1
MoveTo 713, 476
Delay 3
KeyDown "Shift", 1
MoveTo 715, 483
Delay 41
KeyDown "Shift", 1
MoveTo 717, 486
Delay 46
KeyDown "Shift", 1
MoveTo 718, 487
Delay 61
KeyDown "Shift", 1
MoveTo 719, 493
Delay 47
KeyDown "Shift", 1
MoveTo 720, 498
Delay 57
KeyDown "Shift", 1
MoveTo 720, 500
Delay 49
KeyDown "Shift", 1
MoveTo 720, 502
Delay 3
KeyUp "Shift", 1
MoveTo 715, 501
Delay 569
KeyDown "M", 1
MoveTo 714, 501
Delay 138
KeyUp "M", 1
MoveTo 718, 553
Delay 300
KeyDown "Ctrl", 1
MoveTo 669, 562
Delay 435
RightDown 1
MoveTo 670, 560
Delay 99
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
MoveTo 671, 560
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 166
KeyDown "Ctrl", 1
MoveTo 675, 565
Delay 2
KeyDown "Ctrl", 1
MoveTo 675, 566
Delay 66
KeyDown "Ctrl", 1
Delay 2
Delay 32
KeyDown "Ctrl", 1
Delay 31
Delay 70
KeyDown "Ctrl", 1
Delay 9
Delay 5
KeyUp "Ctrl", 1
MoveTo 570, 304
Delay 2586
KeyDown "Shift", 1
MoveTo 619, 338
Delay 480
KeyDown "Shift", 1
Delay 40
MoveTo 619, 337
Delay 46
KeyDown "Shift", 1
MoveTo 619, 336
Delay 43
KeyDown "Shift", 1
Delay 43
Delay 43
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 62
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 43
Delay 39
Delay 2
KeyDown "Shift", 1
Delay 48
Delay 51
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 8
KeyDown "Shift", 1
Delay 55
MoveTo 624, 357
Delay 53
KeyDown "Shift", 1
MoveTo 626, 370
Delay 65
KeyDown "Shift", 1
Delay 42
MoveTo 628, 375
Delay 54
KeyDown "Shift", 1
MoveTo 632, 386
Delay 44
KeyDown "Shift", 1
MoveTo 641, 412
Delay 57
KeyDown "Shift", 1
MoveTo 644, 422
Delay 56
KeyDown "Shift", 1
MoveTo 644, 425
Delay 47
KeyDown "Shift", 1
Delay 42
Delay 40
KeyDown "Shift", 1
Delay 45
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 46
Delay 67
KeyDown "Shift", 1
Delay 6
LeftUp 1
Delay 10
KeyDown "Shift", 1
Delay 41
Delay 44
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 49
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 45
Delay 43
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 56
Delay 2
LeftUp 1
Delay 48
KeyDown "Shift", 1
MoveTo 644, 426
Delay 8
KeyDown "Shift", 1
Delay 41
Delay 40
KeyUp "Shift", 1
MoveTo 630, 436
Delay 409
KeyDown "M", 1
MoveTo 628, 438
Delay 136
KeyUp "M", 1
MoveTo 691, 503
Delay 233
KeyDown "Ctrl", 1
MoveTo 744, 532
Delay 499
KeyDown "Ctrl", 1
MoveTo 746, 532
Delay 33
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 3
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 54
Delay 18
KeyDown "Ctrl", 1
Delay 64
Delay 2
KeyUp "Ctrl", 1
MoveTo 683, 434
Delay 2671
KeyDown "Shift", 1
MoveTo 711, 329
Delay 519
KeyDown "Shift", 1
Delay 52
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 58
Delay 1
LeftUp 1
Delay 75
KeyDown "Shift", 1
Delay 3
Delay 58
KeyDown "Shift", 1
Delay 2
Delay 82
LeftUp 1
Delay 8
KeyDown "Shift", 1
MoveTo 711, 341
Delay 53
KeyDown "Shift", 1
MoveTo 711, 348
Delay 52
KeyDown "Shift", 1
MoveTo 714, 352
Delay 52
KeyDown "Shift", 1
MoveTo 714, 355
Delay 50
KeyDown "Shift", 1
MoveTo 715, 358
Delay 44
KeyDown "Shift", 1
MoveTo 716, 363
Delay 48
KeyDown "Shift", 1
MoveTo 716, 364
Delay 52
KeyDown "Shift", 1
Delay 50
Delay 55
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 61
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 51
Delay 3
Delay 63
KeyDown "Shift", 1
Delay 51
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 717, 366
Delay 50
KeyDown "Shift", 1
MoveTo 725, 388
Delay 49
KeyDown "Shift", 1
MoveTo 741, 439
Delay 88
KeyDown "Shift", 1
MoveTo 741, 443
Delay 48
KeyDown "Shift", 1
Delay 42
Delay 42
KeyDown "Shift", 1
Delay 54
MoveTo 741, 433
Delay 52
KeyDown "Shift", 1
MoveTo 741, 422
Delay 48
KeyDown "Shift", 1
MoveTo 741, 418
Delay 43
KeyDown "Shift", 1
MoveTo 741, 416
Delay 3
KeyDown "Shift", 1
Delay 47
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 52
Delay 45
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 41
Delay 3
KeyDown "Shift", 1
Delay 41
Delay 1
KeyDown "Shift", 1
Delay 51
Delay 72
KeyDown "Shift", 1
Delay 6
LeftUp 1
Delay 10
KeyDown "Shift", 1
Delay 4
KeyUp "Shift", 1
MoveTo 738, 423
Delay 422
KeyDown "M", 1
MoveTo 738, 435
Delay 172
KeyUp "M", 1
MoveTo 712, 546
Delay 766
KeyDown "Ctrl", 1
MoveTo 721, 553
Delay 500
KeyDown "Ctrl", 1
Delay 36
MoveTo 721, 561
Delay 32
KeyDown "Ctrl", 1
MoveTo 720, 568
Delay 43
KeyDown "Ctrl", 1
MoveTo 719, 569
Delay 8
KeyDown "Ctrl", 1
Delay 64
Delay 2
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 28
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 32
RightClick 1
Delay 5
KeyDown "Ctrl", 1
Delay 30
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 69
KeyDown "Ctrl", 1
Delay 1
Delay 83
KeyDown "Ctrl", 1
MoveTo 719, 570
Delay 2
KeyUp "Ctrl", 1
MoveTo 696, 479
Delay 2614
KeyDown "Shift", 1
MoveTo 732, 330
Delay 425
LeftDown 1
Delay 108
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 9
KeyDown "Shift", 1
Delay 2
Delay 72
KeyDown "Shift", 1
Delay 51
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 732, 339
Delay 48
KeyDown "Shift", 1
MoveTo 731, 350
Delay 4
KeyDown "Shift", 1
MoveTo 731, 352
Delay 48
KeyDown "Shift", 1
Delay 45
Delay 56
KeyDown "Shift", 1
Delay 57
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 54
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 49
Delay 47
KeyDown "Shift", 1
Delay 43
Delay 49
KeyDown "Shift", 1
MoveTo 731, 356
Delay 48
KeyDown "Shift", 1
MoveTo 737, 371
Delay 53
KeyDown "Shift", 1
MoveTo 744, 400
Delay 3
KeyDown "Shift", 1
MoveTo 745, 415
Delay 68
KeyDown "Shift", 1
MoveTo 745, 417
Delay 56
KeyDown "Shift", 1
Delay 50
Delay 60
KeyDown "Shift", 1
Delay 52
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 56
Delay 55
KeyDown "Shift", 1
Delay 4
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 41
Delay 43
Delay 2
KeyDown "Shift", 1
Delay 57
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 43
Delay 51
KeyDown "Shift", 1
MoveTo 745, 424
Delay 66
KeyDown "Shift", 1
MoveTo 746, 427
Delay 2
KeyUp "Shift", 1
MoveTo 747, 449
Delay 422
KeyDown "M", 1
MoveTo 746, 452
Delay 186
KeyUp "M", 1
MoveTo 760, 485
Delay 234
KeyDown "Ctrl", 1
MoveTo 733, 490
Delay 529
KeyDown "Ctrl", 1
MoveTo 729, 490
Delay 35
KeyDown "Ctrl", 1
MoveTo 725, 492
Delay 32
KeyDown "Ctrl", 1
MoveTo 716, 493
Delay 33
KeyDown "Ctrl", 1
MoveTo 710, 495
Delay 34
KeyDown "Ctrl", 1
MoveTo 704, 497
Delay 35
KeyDown "Ctrl", 1
MoveTo 700, 499
Delay 7
KeyDown "Ctrl", 1
Delay 58
MoveTo 698, 500
Delay 4
KeyDown "Ctrl", 1
MoveTo 696, 501
Delay 61
KeyDown "Ctrl", 1
MoveTo 695, 502
Delay 3
KeyDown "Ctrl", 1
Delay 64
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 694, 502
Delay 34
KeyDown "Ctrl", 1
MoveTo 692, 501
Delay 37
KeyDown "Ctrl", 1
MoveTo 691, 496
Delay 30
KeyDown "Ctrl", 1
MoveTo 690, 493
Delay 33
KeyDown "Ctrl", 1
MoveTo 690, 485
Delay 33
KeyDown "Ctrl", 1
MoveTo 690, 470
Delay 34
KeyDown "Ctrl", 1
MoveTo 693, 454
Delay 34
KeyDown "Ctrl", 1
MoveTo 701, 445
Delay 34
KeyDown "Ctrl", 1
MoveTo 707, 440
Delay 36
KeyDown "Ctrl", 1
MoveTo 715, 439
Delay 30
KeyDown "Ctrl", 1
MoveTo 728, 438
Delay 32
KeyDown "Ctrl", 1
MoveTo 736, 438
Delay 33
KeyDown "Ctrl", 1
MoveTo 737, 437
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 739, 436
Delay 38
KeyDown "Ctrl", 1
MoveTo 741, 437
Delay 30
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 738, 430
Delay 33
KeyDown "Ctrl", 1
MoveTo 734, 418
Delay 37
KeyDown "Ctrl", 1
MoveTo 726, 407
Delay 32
KeyDown "Ctrl", 1
MoveTo 720, 398
Delay 32
KeyDown "Ctrl", 1
MoveTo 717, 395
Delay 33
KeyDown "Ctrl", 1
MoveTo 715, 393
Delay 34
KeyDown "Ctrl", 1
MoveTo 715, 388
Delay 33
KeyDown "Ctrl", 1
MoveTo 715, 384
Delay 33
KeyDown "Ctrl", 1
MoveTo 715, 379
Delay 39
KeyDown "Ctrl", 1
MoveTo 712, 376
Delay 27
KeyDown "Ctrl", 1
MoveTo 710, 372
Delay 34
KeyDown "Ctrl", 1
MoveTo 709, 370
Delay 34
KeyDown "Ctrl", 1
MoveTo 707, 368
Delay 33
KeyDown "Ctrl", 1
MoveTo 706, 367
Delay 33
KeyDown "Ctrl", 1
MoveTo 706, 366
Delay 34
KeyDown "Ctrl", 1
MoveTo 706, 364
Delay 33
KeyDown "Ctrl", 1
MoveTo 706, 362
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 706, 360
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 112
KeyDown "Ctrl", 1
Delay 1
Delay 73
KeyDown "Ctrl", 1
MoveTo 706, 364
Delay 1
KeyUp "Ctrl", 1
MoveTo 706, 389
Delay 2911
KeyDown "Shift", 1
MoveTo 743, 325
Delay 416
LeftClick 1
Delay 6
KeyDown "Shift", 1
Delay 55
Delay 2
Delay 47
KeyDown "Shift", 1
Delay 49
Delay 3
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 45
Delay 47
KeyDown "Shift", 1
MoveTo 743, 348
Delay 49
KeyDown "Shift", 1
MoveTo 742, 352
Delay 42
KeyDown "Shift", 1
Delay 43
Delay 44
KeyDown "Shift", 1
Delay 44
Delay 44
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 48
Delay 47
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 55
MoveTo 742, 362
Delay 63
KeyDown "Shift", 1
MoveTo 745, 391
Delay 5
KeyDown "Shift", 1
MoveTo 748, 413
Delay 60
KeyDown "Shift", 1
MoveTo 748, 425
Delay 43
KeyDown "Shift", 1
Delay 46
Delay 47
KeyDown "Shift", 1
MoveTo 746, 422
Delay 46
KeyDown "Shift", 1
MoveTo 746, 421
Delay 47
KeyDown "Shift", 1
Delay 54
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 51
Delay 2
LeftUp 1
Delay 49
KeyDown "Shift", 1
Delay 3
Delay 47
KeyDown "Shift", 1
Delay 2
Delay 55
KeyDown "Shift", 1
Delay 49
Delay 2
LeftUp 1
Delay 48
KeyDown "Shift", 1
Delay 43
Delay 49
KeyUp "Shift", 1
MoveTo 746, 420
Delay 388
KeyDown "M", 1
Delay 160
KeyUp "M", 1
MoveTo 750, 527
Delay 533
KeyDown "Ctrl", 1
MoveTo 687, 571
Delay 434
RightDown 1
MoveTo 686, 572
Delay 99
KeyDown "Ctrl", 1
Delay 33
Delay 1
RightClick 1
Delay 36
KeyDown "Ctrl", 1
Delay 3
Delay 60
KeyDown "Ctrl", 1
Delay 98
Delay 1
KeyDown "Ctrl", 1
Delay 42
Delay 1
KeyUp "Ctrl", 1
MoveTo 690, 426
Delay 2760
KeyDown "Shift", 1
MoveTo 707, 341
Delay 519
KeyDown "Shift", 1
MoveTo 708, 339
Delay 69
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 57
KeyDown "Shift", 1
Delay 51
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 70
Delay 1
Delay 1
KeyDown "Shift", 1
Delay 63
Delay 56
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 710, 346
Delay 55
KeyDown "Shift", 1
MoveTo 711, 351
Delay 50
KeyDown "Shift", 1
Delay 47
Delay 44
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 53
Delay 46
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 63
MoveTo 713, 356
Delay 69
KeyDown "Shift", 1
MoveTo 722, 391
Delay 63
KeyDown "Shift", 1
MoveTo 726, 414
Delay 59
KeyDown "Shift", 1
MoveTo 727, 422
Delay 55
KeyDown "Shift", 1
MoveTo 727, 424
Delay 87
KeyDown "Shift", 1
MoveTo 727, 425
Delay 53
KeyDown "Shift", 1
Delay 49
Delay 81
KeyDown "Shift", 1
MoveTo 724, 422
Delay 76
KeyDown "Shift", 1
MoveTo 724, 418
Delay 63
KeyDown "Shift", 1
MoveTo 723, 417
Delay 60
KeyDown "Shift", 1
Delay 54
Delay 56
KeyDown "Shift", 1
Delay 42
Delay 45
KeyDown "Shift", 1
Delay 43
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 57
Delay 3
LeftUp 1
Delay 47
KeyDown "Shift", 1
Delay 43
Delay 1
KeyDown "Shift", 1
Delay 48
Delay 47
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 45
KeyDown "Shift", 1
Delay 45
Delay 2
KeyUp "Shift", 1
Delay 305
KeyDown "M", 1
MoveTo 723, 422
Delay 143
KeyUp "M", 1
MoveTo 745, 496
Delay 332
KeyDown "Ctrl", 1
MoveTo 713, 573
Delay 499
KeyDown "Ctrl", 1
Delay 35
Delay 32
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 111
KeyDown "Ctrl", 1
Delay 1
Delay 39
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 730, 431
Delay 2706
KeyDown "Shift", 1
MoveTo 743, 337
Delay 495
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 50
KeyDown "Shift", 1
Delay 68
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 47
Delay 52
Delay 1
KeyDown "Shift", 1
Delay 69
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 748, 350
Delay 53
KeyDown "Shift", 1
MoveTo 751, 368
Delay 53
KeyDown "Shift", 1
Delay 43
Delay 42
KeyDown "Shift", 1
Delay 42
Delay 44
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 54
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 46
Delay 41
KeyDown "Shift", 1
Delay 2
Delay 2
KeyDown "Shift", 1
Delay 50
Delay 43
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 61
MoveTo 750, 388
Delay 4
KeyDown "Shift", 1
MoveTo 750, 402
Delay 41
KeyDown "Shift", 1
MoveTo 750, 408
Delay 47
KeyDown "Shift", 1
MoveTo 750, 411
Delay 45
KeyDown "Shift", 1
MoveTo 750, 412
Delay 54
KeyDown "Shift", 1
Delay 43
MoveTo 751, 413
Delay 48
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 50
Delay 67
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 43
Delay 1
Delay 51
KeyDown "Shift", 1
Delay 56
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 43
MoveTo 751, 414
Delay 51
KeyDown "Shift", 1
Delay 3
KeyUp "Shift", 1
MoveTo 748, 434
Delay 446
KeyDown "M", 1
MoveTo 748, 444
Delay 125
KeyUp "M", 1
MoveTo 774, 500
Delay 315
KeyDown "Ctrl", 1
MoveTo 762, 465
Delay 477
KeyDown "Ctrl", 1
MoveTo 762, 464
Delay 64
KeyDown "Ctrl", 1
MoveTo 761, 463
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 156
MoveTo 761, 468
Delay 2
KeyDown "Ctrl", 1
MoveTo 761, 470
Delay 31
KeyDown "Ctrl", 1
MoveTo 761, 473
Delay 87
KeyDown "Ctrl", 1
MoveTo 761, 475
Delay 4
KeyDown "Ctrl", 1
Delay 11
Delay 2
KeyDown "Ctrl", 1
MoveTo 760, 477
Delay 20
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 761, 399
Delay 2232
KeyDown "Shift", 1
MoveTo 759, 323
Delay 500
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 2
Delay 54
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 40
Delay 49
KeyDown "Shift", 1
Delay 2
Delay 53
KeyDown "Shift", 1
Delay 5
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 759, 325
Delay 57
KeyDown "Shift", 1
MoveTo 759, 350
Delay 56
KeyDown "Shift", 1
MoveTo 758, 363
Delay 55
KeyDown "Shift", 1
MoveTo 757, 365
Delay 49
KeyDown "Shift", 1
Delay 43
Delay 49
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 86
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 65
Delay 51
KeyDown "Shift", 1
MoveTo 757, 368
Delay 47
KeyDown "Shift", 1
MoveTo 759, 394
Delay 42
KeyDown "Shift", 1
MoveTo 759, 401
Delay 50
KeyDown "Shift", 1
MoveTo 759, 405
Delay 43
KeyDown "Shift", 1
MoveTo 759, 413
Delay 45
KeyDown "Shift", 1
MoveTo 759, 414
Delay 41
KeyDown "Shift", 1
MoveTo 759, 415
Delay 40
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 49
Delay 48
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 44
Delay 40
KeyDown "Shift", 1
Delay 2
Delay 48
KeyDown "Shift", 1
Delay 46
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 45
MoveTo 759, 417
Delay 42
KeyDown "Shift", 1
MoveTo 760, 437
Delay 44
KeyDown "Shift", 1
MoveTo 762, 457
Delay 2
KeyDown "Shift", 1
MoveTo 763, 473
Delay 50
KeyUp "Shift", 1
MoveTo 753, 504
Delay 425
KeyDown "M", 1
Delay 137
KeyUp "M", 1
MoveTo 750, 536
Delay 334
KeyDown "Ctrl", 1
MoveTo 747, 567
Delay 498
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 36
Delay 29
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 35
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 21
KeyDown "Ctrl", 1
Delay 1
Delay 146
KeyUp "Ctrl", 1
MoveTo 744, 340
Delay 3010
KeyDown "Shift", 1
MoveTo 743, 336
Delay 295
LeftDown 1
MoveTo 743, 335
Delay 77
LeftUp 1
Delay 116
Delay 2
KeyDown "Shift", 1
Delay 70
Delay 2
LeftUp 1
Delay 68
KeyDown "Shift", 1
MoveTo 743, 362
Delay 72
KeyDown "Shift", 1
MoveTo 745, 385
Delay 94
KeyDown "Shift", 1
MoveTo 746, 403
Delay 50
KeyDown "Shift", 1
MoveTo 746, 410
Delay 3
KeyDown "Shift", 1
MoveTo 746, 413
Delay 58
KeyDown "Shift", 1
Delay 60
Delay 54
KeyDown "Shift", 1
Delay 74
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 61
LeftUp 1
Delay 10
KeyDown "Shift", 1
Delay 54
Delay 2
Delay 2
KeyDown "Shift", 1
Delay 62
Delay 52
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 51
MoveTo 746, 415
Delay 60
KeyDown "Shift", 1
MoveTo 747, 419
Delay 4
KeyUp "Shift", 1
MoveTo 748, 431
Delay 328
KeyDown "M", 1
MoveTo 748, 437
Delay 179
KeyUp "M", 1
MoveTo 762, 567
Delay 297
KeyDown "Ctrl", 1
MoveTo 747, 570
Delay 400
RightDown 1
Delay 133
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
MoveTo 749, 571
Delay 195
KeyDown "Ctrl", 1
Delay 34
Delay 5
KeyDown "Ctrl", 1
Delay 59
Delay 83
KeyDown "Ctrl", 1
Delay 2
Delay 9
KeyDown "Ctrl", 1
Delay 3
KeyUp "Ctrl", 1
MoveTo 754, 387
Delay 2412
KeyDown "Shift", 1
MoveTo 757, 323
Delay 531
KeyDown "Shift", 1
Delay 45
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 58
Delay 55
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 74
Delay 48
KeyDown "Shift", 1
MoveTo 757, 325
Delay 4
KeyDown "Shift", 1
MoveTo 756, 343
Delay 48
KeyDown "Shift", 1
MoveTo 755, 361
Delay 52
KeyDown "Shift", 1
MoveTo 755, 391
Delay 44
KeyDown "Shift", 1
MoveTo 755, 399
Delay 45
KeyDown "Shift", 1
MoveTo 754, 407
Delay 41
KeyDown "Shift", 1
MoveTo 753, 409
Delay 69
KeyDown "Shift", 1
MoveTo 753, 414
Delay 10
KeyDown "Shift", 1
MoveTo 753, 417
Delay 54
KeyDown "Shift", 1
Delay 47
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 50
Delay 50
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 42
Delay 3
Delay 51
KeyDown "Shift", 1
Delay 45
Delay 45
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 48
MoveTo 753, 427
Delay 58
KeyDown "Shift", 1
MoveTo 754, 431
Delay 6
KeyUp "Shift", 1
MoveTo 754, 451
Delay 347
KeyDown "M", 1
MoveTo 754, 452
Delay 164
KeyUp "M", 1
MoveTo 787, 575
Delay 336
KeyDown "Ctrl", 1
MoveTo 753, 572
Delay 497
KeyDown "Ctrl", 1
MoveTo 753, 571
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 2
RightDown 1
Delay 37
KeyDown "Ctrl", 1
Delay 28
Delay 32
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 6
KeyDown "Ctrl", 1
Delay 29
Delay 32
KeyDown "Ctrl", 1
MoveTo 753, 570
Delay 172
KeyDown "Ctrl", 1
Delay 88
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 94
KeyDown "Ctrl", 1
Delay 4
KeyUp "Ctrl", 1
Delay 2
KeyDown "Ctrl", 1
MoveTo 758, 438
Delay 2143
KeyDown "Shift", 1
MoveTo 762, 331
Delay 511
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 59
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 55
Delay 54
Delay 2
KeyDown "Shift", 1
Delay 103
Delay 3
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 757, 341
Delay 60
KeyDown "Shift", 1
MoveTo 756, 352
Delay 60
KeyDown "Shift", 1
Delay 75
Delay 65
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 14
KeyDown "Shift", 1
Delay 5
Delay 85
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 54
Delay 2
KeyDown "Shift", 1
Delay 69
Delay 10
LeftUp 1
Delay 8
KeyDown "Shift", 1
Delay 57
MoveTo 754, 394
Delay 75
KeyDown "Shift", 1
MoveTo 754, 411
Delay 60
KeyDown "Shift", 1
MoveTo 754, 412
Delay 55
KeyDown "Shift", 1
MoveTo 753, 417
Delay 5
KeyDown "Shift", 1
MoveTo 753, 421
Delay 72
KeyDown "Shift", 1
Delay 57
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 75
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 54
Delay 2
Delay 67
KeyDown "Shift", 1
Delay 75
Delay 2
LeftUp 1
Delay 8
KeyDown "Shift", 1
MoveTo 753, 437
Delay 79
KeyDown "Shift", 1
MoveTo 754, 471
Delay 66
KeyDown "Shift", 1
MoveTo 755, 479
Delay 14
KeyUp "Shift", 1
MoveTo 753, 528
Delay 757
KeyDown "M", 1
MoveTo 751, 531
Delay 214
KeyUp "M", 1
MoveTo 780, 590
Delay 249
KeyDown "Ctrl", 1
MoveTo 734, 581
Delay 496
KeyDown "Ctrl", 1
MoveTo 733, 580
Delay 36
KeyDown "Ctrl", 1
MoveTo 733, 577
Delay 39
KeyDown "Ctrl", 1
MoveTo 733, 575
Delay 36
KeyDown "Ctrl", 1
Delay 38
Delay 45
KeyDown "Ctrl", 1
Delay 11
RightDown 1
Delay 4
KeyDown "Ctrl", 1
Delay 23
Delay 64
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 3
KeyDown "Ctrl", 1
Delay 30
Delay 40
KeyDown "Ctrl", 1
Delay 96
Delay 2
KeyDown "Ctrl", 1
Delay 86
MoveTo 734, 574
Delay 3
KeyUp "Ctrl", 1
MoveTo 724, 336
Delay 2494
KeyDown "Shift", 1
MoveTo 718, 351
Delay 556
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 113
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 61
MoveTo 718, 363
Delay 56
KeyDown "Shift", 1
MoveTo 723, 390
Delay 57
KeyDown "Shift", 1
MoveTo 723, 396
Delay 63
KeyDown "Shift", 1
MoveTo 724, 410
Delay 63
KeyDown "Shift", 1
MoveTo 725, 417
Delay 77
KeyDown "Shift", 1
MoveTo 726, 421
Delay 3
KeyDown "Shift", 1
Delay 65
Delay 10
KeyDown "Shift", 1
Delay 9
LeftDown 1
Delay 75
KeyDown "Shift", 1
Delay 7
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 68
Delay 3
Delay 75
KeyDown "Shift", 1
Delay 75
Delay 9
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 56
MoveTo 726, 425
Delay 77
KeyDown "Shift", 1
MoveTo 726, 429
Delay 3
KeyUp "Shift", 1
MoveTo 726, 435
Delay 326
KeyDown "M", 1
MoveTo 727, 439
Delay 167
KeyUp "M", 1
MoveTo 766, 554
Delay 337
KeyDown "Ctrl", 1
MoveTo 754, 553
Delay 500
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 34
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 32
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 182
MoveTo 776, 550
Delay 4
KeyDown "Ctrl", 1
MoveTo 805, 540
Delay 39
KeyDown "Ctrl", 1
Delay 12
Delay 4
KeyDown "Ctrl", 1
MoveTo 826, 528
Delay 17
KeyUp "Ctrl", 1
MoveTo 774, 357
Delay 2988
KeyDown "Shift", 1
MoveTo 774, 351
Delay 317
LeftDoubleClick 1
Delay 72
KeyDown "Shift", 1
Delay 4
Delay 1
LeftUp 1
Delay 63
KeyDown "Shift", 1
Delay 58
MoveTo 775, 344
Delay 7
KeyDown "Shift", 1
MoveTo 776, 337
Delay 64
KeyDown "Shift", 1
MoveTo 778, 329
Delay 60
KeyDown "Shift", 1
MoveTo 778, 326
Delay 5
KeyDown "Shift", 1
Delay 53
Delay 56
KeyDown "Shift", 1
Delay 58
MoveTo 778, 325
Delay 7
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 79
Delay 4
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 56
MoveTo 778, 333
Delay 5
KeyDown "Shift", 1
MoveTo 777, 358
Delay 59
KeyDown "Shift", 1
MoveTo 777, 387
Delay 6
KeyDown "Shift", 1
MoveTo 776, 403
Delay 57
KeyDown "Shift", 1
MoveTo 774, 411
Delay 6
KeyDown "Shift", 1
MoveTo 774, 414
Delay 54
KeyDown "Shift", 1
Delay 57
Delay 52
KeyDown "Shift", 1
Delay 54
Delay 49
KeyDown "Shift", 1
Delay 4
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 63
Delay 2
LeftUp 1
Delay 60
KeyDown "Shift", 1
Delay 52
Delay 48
KeyDown "Shift", 1
Delay 56
MoveTo 774, 417
Delay 9
KeyDown "Shift", 1
MoveTo 774, 421
Delay 51
KeyDown "Shift", 1
MoveTo 779, 430
Delay 49
KeyDown "Shift", 1
MoveTo 780, 435
Delay 59
KeyDown "Shift", 1
MoveTo 780, 439
Delay 58
KeyDown "Shift", 1
MoveTo 780, 440
Delay 54
KeyUp "Shift", 1
MoveTo 815, 567
Delay 2665
KeyDown "M", 1
MoveTo 814, 567
Delay 172
KeyUp "M", 1
MoveTo 883, 562
Delay 969
LeftClick 1
MoveTo 857, 560
Delay 912
KeyDown "M", 1
MoveTo 856, 560
Delay 166
KeyUp "M", 1
MoveTo 810, 559
Delay 1075
KeyDown "Shift", 1
MoveTo 807, 556
Delay 495
KeyDown "Shift", 1
Delay 37
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 36
KeyDown "Shift", 1
Delay 30
Delay 35
KeyDown "Shift", 1
Delay 32
Delay 2
RightDown 1
Delay 32
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 5
RightClick 1
Delay 14
KeyDown "Shift", 1
Delay 33
Delay 29
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyUp "Shift", 1
MoveTo 987, 564
Delay 1569
KeyDown "Esc", 1
MoveTo 944, 568
Delay 167
KeyUp "Esc", 1
MoveTo 800, 560
Delay 634
KeyDown "Ctrl", 1
MoveTo 800, 558
Delay 299
RightDown 1
Delay 100
RightClick 1
Delay 129
KeyDown "Ctrl", 1
Delay 62
Delay 2
KeyDown "Ctrl", 1
MoveTo 804, 556
Delay 97
KeyDown "Ctrl", 1
MoveTo 809, 555
Delay 4
KeyDown "Ctrl", 1
MoveTo 810, 554
Delay 3
KeyUp "Ctrl", 1
MoveTo 782, 372
Delay 2569
KeyDown "Shift", 1
MoveTo 771, 333
Delay 435
LeftDown 1
Delay 44
KeyDown "Shift", 1
Delay 57
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 42
Delay 40
KeyDown "Shift", 1
Delay 7
Delay 61
KeyDown "Shift", 1
Delay 46
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 771, 339
Delay 49
KeyDown "Shift", 1
MoveTo 767, 358
Delay 44
KeyDown "Shift", 1
MoveTo 766, 366
Delay 42
KeyDown "Shift", 1
Delay 40
MoveTo 765, 367
Delay 47
KeyDown "Shift", 1
Delay 44
Delay 45
KeyDown "Shift", 1
Delay 45
Delay 3
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 51
Delay 60
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 54
MoveTo 766, 370
Delay 55
KeyDown "Shift", 1
MoveTo 773, 395
Delay 44
KeyDown "Shift", 1
MoveTo 775, 404
Delay 51
KeyDown "Shift", 1
MoveTo 775, 415
Delay 45
KeyDown "Shift", 1
Delay 38
Delay 39
KeyDown "Shift", 1
Delay 41
Delay 50
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 52
Delay 2
LeftUp 1
Delay 49
KeyDown "Shift", 1
Delay 41
Delay 2
Delay 2
KeyDown "Shift", 1
Delay 43
Delay 44
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 42
Delay 38
KeyDown "Shift", 1
Delay 41
KeyUp "Shift", 1
MoveTo 775, 420
Delay 487
KeyDown "M", 1
MoveTo 775, 422
Delay 154
KeyUp "M", 1
MoveTo 776, 486
Delay 368
KeyDown "Ctrl", 1
MoveTo 803, 474
Delay 536
KeyDown "Ctrl", 1
MoveTo 806, 477
Delay 2
KeyDown "Ctrl", 1
MoveTo 808, 479
Delay 68
KeyDown "Ctrl", 1
MoveTo 811, 480
Delay 5
KeyDown "Ctrl", 1
MoveTo 812, 480
Delay 57
KeyDown "Ctrl", 1
MoveTo 816, 480
Delay 3
KeyDown "Ctrl", 1
MoveTo 821, 476
Delay 30
KeyDown "Ctrl", 1
MoveTo 824, 473
Delay 34
KeyDown "Ctrl", 1
MoveTo 829, 472
Delay 37
KeyDown "Ctrl", 1
MoveTo 835, 470
Delay 29
KeyDown "Ctrl", 1
MoveTo 838, 470
Delay 32
KeyDown "Ctrl", 1
Delay 33
MoveTo 840, 470
Delay 34
KeyDown "Ctrl", 1
MoveTo 844, 470
Delay 34
KeyDown "Ctrl", 1
MoveTo 846, 472
Delay 33
KeyDown "Ctrl", 1
MoveTo 848, 477
Delay 33
KeyDown "Ctrl", 1
MoveTo 848, 483
Delay 36
KeyDown "Ctrl", 1
MoveTo 847, 489
Delay 31
KeyDown "Ctrl", 1
MoveTo 846, 496
Delay 34
KeyDown "Ctrl", 1
MoveTo 845, 498
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
MoveTo 845, 499
Delay 32
KeyDown "Ctrl", 1
MoveTo 847, 499
Delay 34
KeyDown "Ctrl", 1
MoveTo 849, 499
Delay 33
KeyDown "Ctrl", 1
MoveTo 850, 498
Delay 141
KeyDown "Ctrl", 1
Delay 22
Delay 3
KeyDown "Ctrl", 1
MoveTo 852, 490
Delay 10
KeyDown "Ctrl", 1
MoveTo 852, 489
Delay 1
KeyUp "Ctrl", 1
MoveTo 776, 276
Delay 2536
KeyDown "Shift", 1
MoveTo 768, 341
Delay 474
LeftDown 1
Delay 49
KeyDown "Shift", 1
Delay 52
Delay 1
LeftUp 1
Delay 50
KeyDown "Shift", 1
Delay 2
Delay 46
KeyDown "Shift", 1
Delay 2
Delay 61
KeyDown "Shift", 1
Delay 45
Delay 1
LeftUp 1
Delay 40
KeyDown "Shift", 1
MoveTo 769, 346
Delay 4
KeyDown "Shift", 1
MoveTo 770, 359
Delay 37
KeyDown "Shift", 1
MoveTo 774, 377
Delay 41
KeyDown "Shift", 1
MoveTo 776, 392
Delay 41
KeyDown "Shift", 1
MoveTo 776, 400
Delay 39
KeyDown "Shift", 1
MoveTo 776, 402
Delay 38
KeyDown "Shift", 1
MoveTo 776, 404
Delay 40
KeyDown "Shift", 1
MoveTo 776, 407
Delay 36
KeyDown "Shift", 1
MoveTo 776, 410
Delay 68
KeyDown "Shift", 1
Delay 39
MoveTo 777, 412
Delay 41
KeyDown "Shift", 1
MoveTo 778, 412
Delay 46
KeyDown "Shift", 1
Delay 43
LeftDown 1
MoveTo 778, 413
Delay 9
KeyDown "Shift", 1
Delay 51
Delay 2
LeftUp 1
Delay 55
KeyDown "Shift", 1
Delay 40
Delay 2
KeyDown "Shift", 1
Delay 43
Delay 40
KeyDown "Shift", 1
Delay 1
Delay 43
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 42
Delay 2
LeftDown 1
Delay 47
KeyDown "Shift", 1
Delay 48
Delay 2
LeftUp 1
Delay 40
KeyDown "Shift", 1
Delay 3
Delay 33
KeyDown "Shift", 1
Delay 47
Delay 41
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
Delay 353
KeyDown "M", 1
Delay 193
KeyUp "M", 1
MoveTo 800, 453
Delay 233
KeyDown "Ctrl", 1
MoveTo 834, 475
Delay 533
RightDown 1
Delay 2
KeyDown "Ctrl", 1
MoveTo 835, 475
Delay 34
KeyDown "Ctrl", 1
MoveTo 836, 476
Delay 31
KeyDown "Ctrl", 1
Delay 32
Delay 36
KeyDown "Ctrl", 1
Delay 1
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 63
Delay 35
KeyDown "Ctrl", 1
Delay 2
Delay 30
KeyDown "Ctrl", 1
Delay 67
Delay 29
KeyDown "Ctrl", 1
Delay 3
KeyUp "Ctrl", 1
MoveTo 814, 361
Delay 2948
KeyDown "Shift", 1
MoveTo 807, 335
Delay 457
LeftDown 1
Delay 50
KeyDown "Shift", 1
Delay 50
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 64
Delay 43
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 1
LeftUp 1
Delay 45
KeyDown "Shift", 1
MoveTo 807, 339
Delay 4
KeyDown "Shift", 1
MoveTo 806, 352
Delay 43
KeyDown "Shift", 1
MoveTo 805, 356
Delay 52
KeyDown "Shift", 1
MoveTo 804, 359
Delay 3
KeyDown "Shift", 1
Delay 42
Delay 43
KeyDown "Shift", 1
Delay 45
Delay 2
KeyDown "Shift", 1
MoveTo 804, 358
Delay 44
KeyDown "Shift", 1
Delay 40
Delay 2
LeftDown 1
Delay 52
KeyDown "Shift", 1
Delay 48
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 805, 358
Delay 44
KeyDown "Shift", 1
Delay 45
MoveTo 806, 374
Delay 49
KeyDown "Shift", 1
MoveTo 807, 418
Delay 45
KeyDown "Shift", 1
MoveTo 807, 424
Delay 45
KeyDown "Shift", 1
MoveTo 807, 427
Delay 4
KeyDown "Shift", 1
Delay 41
Delay 41
KeyDown "Shift", 1
Delay 42
MoveTo 806, 428
Delay 45
KeyDown "Shift", 1
Delay 43
LeftDown 1
Delay 4
KeyDown "Shift", 1
Delay 46
Delay 50
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 51
Delay 5
Delay 2
KeyDown "Shift", 1
Delay 59
Delay 49
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 47
MoveTo 806, 434
Delay 66
KeyUp "Shift", 1
MoveTo 809, 449
Delay 432
KeyDown "M", 1
Delay 142
KeyUp "M", 1
MoveTo 756, 454
Delay 369
KeyDown "Ctrl", 1
MoveTo 757, 519
Delay 530
KeyDown "Ctrl", 1
MoveTo 764, 520
Delay 35
KeyDown "Ctrl", 1
Delay 32
MoveTo 766, 520
Delay 34
KeyDown "Ctrl", 1
MoveTo 766, 521
Delay 34
KeyDown "Ctrl", 1
MoveTo 767, 522
Delay 33
KeyDown "Ctrl", 1
MoveTo 768, 522
Delay 33
KeyDown "Ctrl", 1
MoveTo 769, 523
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 770, 523
Delay 34
KeyDown "Ctrl", 1
MoveTo 774, 525
Delay 45
KeyDown "Ctrl", 1
MoveTo 779, 526
Delay 31
KeyDown "Ctrl", 1
MoveTo 780, 526
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightDown 1
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 185
KeyDown "Ctrl", 1
Delay 9
Delay 2
KeyDown "Ctrl", 1
MoveTo 788, 535
Delay 21
KeyUp "Ctrl", 1
MoveTo 773, 383
Delay 2579
KeyDown "Shift", 1
MoveTo 770, 339
Delay 496
LeftDown 1
Delay 7
KeyDown "Shift", 1
Delay 50
Delay 48
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 62
Delay 1
Delay 52
KeyDown "Shift", 1
Delay 59
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 771, 355
Delay 52
KeyDown "Shift", 1
MoveTo 772, 371
Delay 45
KeyDown "Shift", 1
MoveTo 772, 402
Delay 72
KeyDown "Shift", 1
MoveTo 773, 417
Delay 43
KeyDown "Shift", 1
MoveTo 773, 420
Delay 46
KeyDown "Shift", 1
MoveTo 774, 421
Delay 3
KeyDown "Shift", 1
Delay 45
Delay 42
KeyDown "Shift", 1
Delay 45
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 52
Delay 1
LeftUp 1
Delay 10
KeyDown "Shift", 1
Delay 67
Delay 2
Delay 57
KeyDown "Shift", 1
Delay 2
Delay 52
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 47
KeyDown "Shift", 1
MoveTo 776, 424
Delay 45
KeyDown "Shift", 1
MoveTo 783, 430
Delay 50
KeyDown "Shift", 1
MoveTo 788, 435
Delay 7
KeyDown "Shift", 1
MoveTo 788, 437
Delay 49
KeyDown "Shift", 1
Delay 3
KeyUp "Shift", 1
MoveTo 785, 436
Delay 414
KeyDown "M", 1
MoveTo 786, 435
Delay 144
KeyUp "M", 1
MoveTo 818, 393
Delay 298
KeyDown "Ctrl", 1
MoveTo 800, 473
Delay 500
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 156
KeyDown "Ctrl", 1
Delay 91
Delay 89
KeyDown "Ctrl", 1
Delay 34
Delay 1
KeyDown "Ctrl", 1
Delay 41
Delay 67
KeyDown "Ctrl", 1
Delay 2
MoveTo 802, 474
Delay 39
KeyDown "Ctrl", 1
MoveTo 806, 476
Delay 4
KeyDown "Ctrl", 1
MoveTo 807, 477
Delay 1
KeyUp "Ctrl", 1
MoveTo 801, 331
Delay 2070
KeyDown "Shift", 1
MoveTo 790, 355
Delay 556
KeyDown "Shift", 1
MoveTo 790, 345
Delay 60
KeyDown "Shift", 1
MoveTo 790, 343
Delay 62
KeyDown "Shift", 1
Delay 70
Delay 50
KeyDown "Shift", 1
Delay 56
Delay 3
LeftDown 1
Delay 6
KeyDown "Shift", 1
Delay 63
Delay 64
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 48
Delay 2
Delay 55
KeyDown "Shift", 1
Delay 57
Delay 4
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 84
MoveTo 786, 356
Delay 3
KeyDown "Shift", 1
MoveTo 786, 361
Delay 63
KeyDown "Shift", 1
MoveTo 785, 363
Delay 1
KeyDown "Shift", 1
Delay 53
Delay 61
KeyDown "Shift", 1
Delay 49
Delay 57
KeyDown "Shift", 1
MoveTo 785, 369
Delay 52
KeyDown "Shift", 1
MoveTo 785, 392
Delay 54
KeyDown "Shift", 1
MoveTo 786, 410
Delay 50
KeyDown "Shift", 1
Delay 51
Delay 48
KeyDown "Shift", 1
Delay 50
Delay 58
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 140
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 1
Delay 53
KeyDown "Shift", 1
Delay 46
Delay 2
LeftUp 1
Delay 42
KeyDown "Shift", 1
Delay 3
MoveTo 787, 414
Delay 45
KeyDown "Shift", 1
MoveTo 789, 416
Delay 43
KeyUp "Shift", 1
MoveTo 792, 417
Delay 342
KeyDown "M", 1
MoveTo 796, 417
Delay 252
KeyUp "M", 1
MoveTo 834, 453
Delay 208
KeyDown "Ctrl", 1
MoveTo 831, 516
Delay 501
KeyDown "Ctrl", 1
MoveTo 834, 526
Delay 39
KeyDown "Ctrl", 1
MoveTo 836, 536
Delay 29
KeyDown "Ctrl", 1
MoveTo 839, 546
Delay 34
KeyDown "Ctrl", 1
MoveTo 841, 549
Delay 32
KeyDown "Ctrl", 1
MoveTo 841, 550
Delay 34
KeyDown "Ctrl", 1
MoveTo 841, 551
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 6
RightDown 1
Delay 28
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 131
Delay 3
KeyDown "Ctrl", 1
Delay 53
Delay 1
KeyUp "Ctrl", 1
MoveTo 820, 401
Delay 2420
KeyDown "Shift", 1
MoveTo 813, 339
Delay 522
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 50
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 86
Delay 2
Delay 2
KeyDown "Shift", 1
Delay 68
Delay 4
LeftUp 1
Delay 7
KeyDown "Shift", 1
Delay 52
MoveTo 805, 381
Delay 45
KeyDown "Shift", 1
MoveTo 800, 404
Delay 59
KeyDown "Shift", 1
MoveTo 799, 416
Delay 46
KeyDown "Shift", 1
MoveTo 799, 417
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 37
KeyDown "Shift", 1
Delay 39
Delay 39
KeyDown "Shift", 1
Delay 56
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 51
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 42
Delay 34
KeyDown "Shift", 1
Delay 1
Delay 41
KeyDown "Shift", 1
Delay 44
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 41
Delay 42
KeyDown "Shift", 1
Delay 9
Delay 47
KeyDown "Shift", 1
MoveTo 799, 422
Delay 43
KeyDown "Shift", 1
MoveTo 800, 438
Delay 35
KeyDown "Shift", 1
MoveTo 802, 451
Delay 3
KeyDown "Shift", 1
MoveTo 802, 457
Delay 41
KeyDown "Shift", 1
MoveTo 802, 458
Delay 48
KeyDown "Shift", 1
Delay 37
Delay 2
KeyDown "Shift", 1
Delay 39
Delay 42
KeyDown "Shift", 1
MoveTo 802, 454
Delay 40
KeyDown "Shift", 1
MoveTo 802, 448
Delay 52
KeyDown "Shift", 1
MoveTo 802, 444
Delay 2
KeyUp "Shift", 1
MoveTo 802, 436
Delay 526
KeyDown "M", 1
Delay 155
KeyUp "M", 1
MoveTo 884, 502
Delay 367
KeyDown "Ctrl", 1
MoveTo 863, 494
Delay 400
RightDown 1
Delay 103
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 31
Delay 32
KeyDown "Ctrl", 1
MoveTo 863, 496
Delay 161
KeyDown "Ctrl", 1
MoveTo 865, 510
Delay 3
KeyDown "Ctrl", 1
MoveTo 866, 512
Delay 35
KeyDown "Ctrl", 1
MoveTo 867, 515
Delay 31
KeyDown "Ctrl", 1
Delay 31
Delay 63
KeyDown "Ctrl", 1
Delay 2
MoveTo 868, 516
Delay 23
KeyDown "Ctrl", 1
MoveTo 868, 517
Delay 3
KeyUp "Ctrl", 1
MoveTo 867, 490
Delay 2245
KeyDown "Shift", 1
MoveTo 867, 380
Delay 533
KeyDown "Shift", 1
MoveTo 865, 374
Delay 39
KeyDown "Shift", 1
MoveTo 861, 364
Delay 40
KeyDown "Shift", 1
MoveTo 855, 359
Delay 44
KeyDown "Shift", 1
MoveTo 854, 356
Delay 50
KeyDown "Shift", 1
MoveTo 850, 348
Delay 41
KeyDown "Shift", 1
MoveTo 849, 344
Delay 39
KeyDown "Shift", 1
MoveTo 849, 342
Delay 44
KeyDown "Shift", 1
MoveTo 847, 341
Delay 2
KeyDown "Shift", 1
Delay 42
Delay 37
KeyDown "Shift", 1
Delay 41
Delay 39
KeyDown "Shift", 1
Delay 35
Delay 44
KeyDown "Shift", 1
Delay 48
Delay 2
LeftDown 1
Delay 47
KeyDown "Shift", 1
Delay 46
Delay 1
LeftUp 1
Delay 60
KeyDown "Shift", 1
Delay 47
MoveTo 847, 350
Delay 3
KeyDown "Shift", 1
MoveTo 848, 371
Delay 47
KeyDown "Shift", 1
MoveTo 848, 387
Delay 48
KeyDown "Shift", 1
MoveTo 848, 401
Delay 40
KeyDown "Shift", 1
MoveTo 846, 417
Delay 44
KeyDown "Shift", 1
MoveTo 846, 418
Delay 39
KeyDown "Shift", 1
Delay 48
Delay 35
KeyDown "Shift", 1
Delay 42
Delay 1
LeftDown 1
Delay 43
KeyDown "Shift", 1
Delay 46
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 40
Delay 39
KeyDown "Shift", 1
Delay 2
Delay 48
KeyDown "Shift", 1
Delay 40
Delay 42
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 846, 419
Delay 3
KeyDown "Shift", 1
MoveTo 846, 424
Delay 40
KeyDown "Shift", 1
MoveTo 847, 438
Delay 39
KeyDown "Shift", 1
MoveTo 851, 456
Delay 48
KeyDown "Shift", 1
MoveTo 852, 468
Delay 34
KeyDown "Shift", 1
MoveTo 852, 476
Delay 2
KeyDown "Shift", 1
MoveTo 852, 478
Delay 38
KeyDown "Shift", 1
MoveTo 852, 480
Delay 41
KeyDown "Shift", 1
MoveTo 852, 481
Delay 43
KeyDown "Shift", 1
MoveTo 852, 484
Delay 39
KeyDown "Shift", 1
MoveTo 852, 487
Delay 3
KeyDown "Shift", 1
MoveTo 852, 489
Delay 43
KeyUp "Shift", 1
MoveTo 842, 492
Delay 605
KeyDown "M", 1
MoveTo 841, 492
Delay 145
KeyUp "M", 1
MoveTo 875, 602
Delay 1301
KeyDown "Ctrl", 1
Delay 100
RightDown 1
Delay 100
RightClick 1
Delay 199
KeyDown "Ctrl", 1
MoveTo 881, 606
Delay 11
KeyUp "Ctrl", 1
MoveTo 813, 341
Delay 3259
KeyDown "Shift", 1
MoveTo 812, 336
Delay 480
KeyDown "Shift", 1
Delay 35
Delay 37
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 35
Delay 38
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 41
Delay 39
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 39
KeyDown "Shift", 1
Delay 2
Delay 39
KeyDown "Shift", 1
MoveTo 812, 351
Delay 46
KeyDown "Shift", 1
MoveTo 812, 370
Delay 40
KeyDown "Shift", 1
MoveTo 812, 380
Delay 2
KeyDown "Shift", 1
MoveTo 811, 389
Delay 48
KeyDown "Shift", 1
MoveTo 808, 399
Delay 39
KeyDown "Shift", 1
MoveTo 807, 405
Delay 37
KeyDown "Shift", 1
MoveTo 805, 409
Delay 38
KeyDown "Shift", 1
MoveTo 805, 412
Delay 7
KeyDown "Shift", 1
MoveTo 805, 416
Delay 45
KeyDown "Shift", 1
MoveTo 805, 417
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 37
KeyDown "Shift", 1
Delay 41
MoveTo 805, 422
Delay 39
KeyDown "Shift", 1
Delay 35
Delay 45
KeyDown "Shift", 1
Delay 41
LeftDown 1
Delay 5
KeyDown "Shift", 1
Delay 45
Delay 2
LeftUp 1
Delay 39
KeyDown "Shift", 1
Delay 35
Delay 39
KeyDown "Shift", 1
Delay 1
Delay 1
KeyDown "Shift", 1
Delay 39
Delay 42
KeyDown "Shift", 1
Delay 3
LeftUp 1
Delay 43
KeyDown "Shift", 1
Delay 4
Delay 38
KeyDown "Shift", 1
MoveTo 805, 423
Delay 37
KeyDown "Shift", 1
Delay 35
KeyUp "Shift", 1
MoveTo 802, 425
Delay 509
KeyDown "M", 1
Delay 118
KeyUp "M", 1
MoveTo 828, 566
Delay 395
KeyDown "Ctrl", 1
MoveTo 886, 591
Delay 501
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 30
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 35
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 32
KeyDown "Ctrl", 1
Delay 145
MoveTo 886, 593
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 18
Delay 15
KeyUp "Ctrl", 1
MoveTo 840, 376
Delay 2621
KeyDown "Shift", 1
MoveTo 804, 335
Delay 516
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 42
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 39
MoveTo 802, 345
Delay 44
KeyDown "Shift", 1
MoveTo 802, 366
Delay 44
KeyDown "Shift", 1
MoveTo 802, 383
Delay 35
KeyDown "Shift", 1
MoveTo 802, 397
Delay 4
KeyDown "Shift", 1
MoveTo 802, 405
Delay 38
KeyDown "Shift", 1
MoveTo 802, 412
Delay 38
KeyDown "Shift", 1
MoveTo 801, 416
Delay 35
KeyDown "Shift", 1
MoveTo 801, 418
Delay 38
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 38
Delay 3
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 43
Delay 41
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 37
Delay 35
KeyDown "Shift", 1
Delay 5
Delay 1
KeyDown "Shift", 1
Delay 40
Delay 45
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 3
MoveTo 801, 420
Delay 38
KeyDown "Shift", 1
MoveTo 801, 427
Delay 40
KeyDown "Shift", 1
MoveTo 805, 440
Delay 38
KeyDown "Shift", 1
MoveTo 812, 458
Delay 40
KeyUp "Shift", 1
MoveTo 813, 466
Delay 439
KeyDown "M", 1
MoveTo 813, 469
Delay 144
KeyUp "M", 1
MoveTo 833, 594
Delay 333
KeyDown "Ctrl", 1
MoveTo 865, 589
Delay 535
KeyDown "Ctrl", 1
Delay 31
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 37
KeyDown "Ctrl", 1
Delay 123
Delay 34
KeyDown "Ctrl", 1
Delay 64
Delay 1
KeyDown "Ctrl", 1
Delay 8
Delay 4
KeyUp "Ctrl", 1
MoveTo 837, 523
Delay 2462
KeyDown "Shift", 1
MoveTo 789, 337
Delay 485
LeftDown 1
Delay 51
KeyDown "Shift", 1
Delay 52
Delay 1
LeftUp 1
Delay 47
KeyDown "Shift", 1
Delay 44
MoveTo 789, 338
Delay 46
KeyDown "Shift", 1
MoveTo 789, 356
Delay 55
KeyDown "Shift", 1
MoveTo 793, 398
Delay 58
KeyDown "Shift", 1
MoveTo 800, 429
Delay 48
KeyDown "Shift", 1
MoveTo 800, 437
Delay 36
KeyDown "Shift", 1
MoveTo 800, 441
Delay 58
KeyDown "Shift", 1
MoveTo 800, 451
Delay 45
KeyDown "Shift", 1
MoveTo 799, 457
Delay 47
KeyDown "Shift", 1
Delay 45
Delay 48
KeyDown "Shift", 1
Delay 45
Delay 39
KeyDown "Shift", 1
Delay 40
MoveTo 799, 450
Delay 38
KeyDown "Shift", 1
MoveTo 799, 441
Delay 42
KeyDown "Shift", 1
MoveTo 799, 434
Delay 42
KeyDown "Shift", 1
MoveTo 799, 428
Delay 42
KeyDown "Shift", 1
MoveTo 799, 423
Delay 39
KeyDown "Shift", 1
Delay 37
Delay 35
KeyDown "Shift", 1
Delay 42
Delay 2
LeftDown 1
Delay 43
KeyDown "Shift", 1
Delay 40
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 37
Delay 39
KeyDown "Shift", 1
Delay 2
Delay 51
KeyDown "Shift", 1
Delay 43
Delay 1
LeftUp 1
Delay 42
KeyDown "Shift", 1
Delay 35
Delay 38
KeyDown "Shift", 1
Delay 38
Delay 40
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
Delay 466
KeyDown "M", 1
MoveTo 799, 426
Delay 178
KeyUp "M", 1
MoveTo 829, 496
Delay 268
KeyDown "Ctrl", 1
MoveTo 906, 514
Delay 534
KeyDown "Ctrl", 1
Delay 64
Delay 34
KeyDown "Ctrl", 1
MoveTo 907, 514
Delay 34
KeyDown "Ctrl", 1
MoveTo 906, 512
Delay 39
KeyDown "Ctrl", 1
MoveTo 905, 509
Delay 29
KeyDown "Ctrl", 1
MoveTo 904, 508
Delay 33
KeyDown "Ctrl", 1
Delay 32
MoveTo 903, 507
Delay 33
KeyDown "Ctrl", 1
MoveTo 903, 506
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 70
Delay 1
KeyDown "Ctrl", 1
Delay 71
Delay 1
KeyUp "Ctrl", 1
MoveTo 905, 436
Delay 2509
KeyDown "Shift", 1
MoveTo 828, 332
Delay 482
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 44
Delay 41
KeyDown "Shift", 1
Delay 54
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 825, 346
Delay 38
KeyDown "Shift", 1
MoveTo 825, 361
Delay 38
KeyDown "Shift", 1
MoveTo 825, 369
Delay 7
KeyDown "Shift", 1
MoveTo 825, 373
Delay 37
KeyDown "Shift", 1
MoveTo 825, 374
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 41
KeyDown "Shift", 1
Delay 36
MoveTo 825, 373
Delay 49
KeyDown "Shift", 1
MoveTo 825, 370
Delay 39
KeyDown "Shift", 1
Delay 40
Delay 2
LeftDown 1
Delay 42
KeyDown "Shift", 1
Delay 45
Delay 1
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 39
Delay 34
KeyDown "Shift", 1
Delay 36
Delay 36
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 1
MoveTo 825, 367
Delay 39
KeyDown "Shift", 1
MoveTo 823, 363
Delay 41
KeyDown "Shift", 1
MoveTo 823, 361
Delay 36
KeyDown "Shift", 1
MoveTo 823, 360
Delay 38
KeyDown "Shift", 1
Delay 40
Delay 39
KeyDown "Shift", 1
Delay 37
Delay 34
KeyDown "Shift", 1
Delay 40
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 43
Delay 40
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 37
Delay 37
KeyDown "Shift", 1
Delay 3
Delay 41
KeyDown "Shift", 1
Delay 47
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 48
MoveTo 823, 362
Delay 39
KeyDown "Shift", 1
MoveTo 826, 378
Delay 37
KeyDown "Shift", 1
MoveTo 827, 400
Delay 41
KeyDown "Shift", 1
MoveTo 827, 412
Delay 40
KeyDown "Shift", 1
MoveTo 827, 418
Delay 43
KeyDown "Shift", 1
MoveTo 827, 423
Delay 43
KeyDown "Shift", 1
Delay 42
Delay 37
KeyDown "Shift", 1
Delay 43
Delay 3
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 40
Delay 41
KeyDown "Shift", 1
Delay 5
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 35
Delay 39
Delay 1
KeyDown "Shift", 1
Delay 44
Delay 41
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 39
Delay 40
KeyDown "Shift", 1
MoveTo 827, 426
Delay 3
KeyUp "Shift", 1
MoveTo 837, 463
Delay 349
KeyDown "M", 1
MoveTo 853, 482
Delay 195
KeyUp "M", 1
MoveTo 1042, 640
Delay 362
KeyDown "Ctrl", 1
MoveTo 976, 555
Delay 366
RightDown 1
Delay 100
RightClick 1
Delay 34
KeyDown "Ctrl", 1
MoveTo 976, 557
Delay 33
KeyDown "Ctrl", 1
MoveTo 976, 562
Delay 33
KeyDown "Ctrl", 1
MoveTo 976, 567
Delay 34
KeyDown "Ctrl", 1
MoveTo 976, 571
Delay 36
KeyDown "Ctrl", 1
MoveTo 978, 574
Delay 33
KeyDown "Ctrl", 1
Delay 32
MoveTo 979, 577
Delay 1
KeyDown "Ctrl", 1
Delay 1
MoveTo 979, 578
Delay 2
KeyUp "Ctrl", 1
MoveTo 967, 564
Delay 961
KeyDown "Ctrl", 1
MoveTo 966, 558
Delay 133
RightDown 1
Delay 131
RightClick 1
Delay 229
KeyDown "Ctrl", 1
Delay 1
Delay 13
KeyUp "Ctrl", 1
MoveTo 813, 331
Delay 2596
KeyDown "Shift", 1
MoveTo 813, 329
Delay 142
LeftClick 1
MoveTo 809, 344
Delay 293
KeyDown "Shift", 1
Delay 34
Delay 46
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 41
Delay 38
KeyDown "Shift", 1
Delay 5
LeftUp 1
Delay 35
KeyDown "Shift", 1
Delay 34
Delay 2
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 41
MoveTo 808, 345
Delay 42
KeyDown "Shift", 1
MoveTo 808, 351
Delay 40
KeyDown "Shift", 1
MoveTo 808, 358
Delay 44
KeyDown "Shift", 1
MoveTo 808, 362
Delay 35
KeyDown "Shift", 1
Delay 38
Delay 35
KeyDown "Shift", 1
Delay 36
MoveTo 808, 372
Delay 38
KeyDown "Shift", 1
MoveTo 812, 391
Delay 44
KeyDown "Shift", 1
MoveTo 812, 400
Delay 34
KeyDown "Shift", 1
MoveTo 812, 402
Delay 35
KeyDown "Shift", 1
MoveTo 812, 404
Delay 38
KeyDown "Shift", 1
MoveTo 811, 407
Delay 38
KeyDown "Shift", 1
MoveTo 811, 411
Delay 35
KeyDown "Shift", 1
Delay 36
Delay 34
KeyDown "Shift", 1
Delay 37
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 3
Delay 39
KeyDown "Shift", 1
Delay 45
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 39
Delay 2
KeyDown "Shift", 1
Delay 35
Delay 1
KeyDown "Shift", 1
Delay 36
Delay 40
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 39
KeyDown "Shift", 1
MoveTo 810, 402
Delay 40
KeyDown "Shift", 1
MoveTo 809, 386
Delay 43
KeyDown "Shift", 1
MoveTo 813, 364
Delay 37
KeyDown "Shift", 1
MoveTo 816, 360
Delay 33
KeyDown "Shift", 1
MoveTo 817, 359
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 40
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 2
Delay 43
KeyDown "Shift", 1
Delay 41
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 35
Delay 36
KeyDown "Shift", 1
Delay 36
Delay 36
KeyUp "Shift", 1
Delay 391
KeyDown "M", 1
MoveTo 830, 377
Delay 171
KeyUp "M", 1
MoveTo 878, 534
Delay 265
KeyDown "Ctrl", 1
MoveTo 968, 568
Delay 500
KeyDown "Ctrl", 1
MoveTo 969, 565
Delay 33
KeyDown "Ctrl", 1
MoveTo 969, 563
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 136
KeyDown "Ctrl", 1
MoveTo 967, 567
Delay 76
KeyDown "Ctrl", 1
Delay 3
MoveTo 966, 568
Delay 1
KeyDown "Ctrl", 1
Delay 29
Delay 1
KeyUp "Ctrl", 1
Delay 1
KeyDown "Ctrl", 1
MoveTo 836, 419
Delay 2355
KeyDown "Shift", 1
MoveTo 831, 333
Delay 496
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 42
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 55
Delay 40
KeyDown "Shift", 1
MoveTo 818, 353
Delay 45
KeyDown "Shift", 1
MoveTo 815, 359
Delay 39
KeyDown "Shift", 1
MoveTo 815, 361
Delay 36
KeyDown "Shift", 1
Delay 42
Delay 43
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 39
Delay 44
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 39
Delay 34
KeyDown "Shift", 1
Delay 1
Delay 41
KeyDown "Shift", 1
Delay 40
Delay 42
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 34
MoveTo 812, 367
Delay 41
KeyDown "Shift", 1
MoveTo 809, 384
Delay 39
KeyDown "Shift", 1
MoveTo 807, 395
Delay 41
KeyDown "Shift", 1
MoveTo 806, 401
Delay 41
KeyDown "Shift", 1
Delay 40
Delay 42
KeyDown "Shift", 1
Delay 39
MoveTo 806, 406
Delay 42
KeyDown "Shift", 1
MoveTo 806, 409
Delay 41
KeyDown "Shift", 1
Delay 34
Delay 41
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 43
Delay 41
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 39
KeyDown "Shift", 1
Delay 40
Delay 2
Delay 1
KeyDown "Shift", 1
Delay 39
Delay 40
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 46
KeyDown "Shift", 1
Delay 2
Delay 39
KeyUp "Shift", 1
MoveTo 818, 522
Delay 307
KeyDown "M", 1
MoveTo 839, 595
Delay 183
KeyUp "M", 1
MoveTo 832, 644
Delay 298
KeyDown "Ctrl", 1
MoveTo 920, 567
Delay 502
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
RightDown 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 36
KeyDown "Ctrl", 1
Delay 31
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 134
KeyDown "Ctrl", 1
Delay 24
Delay 1
KeyDown "Ctrl", 1
Delay 9
KeyUp "Ctrl", 1
MoveTo 747, 323
Delay 2797
KeyDown "Shift", 1
MoveTo 747, 342
Delay 450
LeftDown 1
Delay 55
KeyDown "Shift", 1
Delay 45
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 747, 343
Delay 40
KeyDown "Shift", 1
MoveTo 750, 357
Delay 45
KeyDown "Shift", 1
MoveTo 758, 373
Delay 40
KeyDown "Shift", 1
Delay 36
Delay 41
KeyDown "Shift", 1
MoveTo 758, 374
Delay 40
KeyDown "Shift", 1
MoveTo 760, 374
Delay 38
KeyDown "Shift", 1
MoveTo 762, 368
Delay 41
KeyDown "Shift", 1
MoveTo 762, 367
Delay 38
KeyDown "Shift", 1
Delay 38
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 55
Delay 2
LeftUp 1
Delay 48
KeyDown "Shift", 1
Delay 5
Delay 43
KeyDown "Shift", 1
MoveTo 762, 369
Delay 56
KeyDown "Shift", 1
MoveTo 763, 398
Delay 47
KeyDown "Shift", 1
MoveTo 764, 410
Delay 58
KeyDown "Shift", 1
MoveTo 764, 413
Delay 47
KeyDown "Shift", 1
Delay 56
Delay 46
KeyDown "Shift", 1
Delay 43
Delay 38
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 41
Delay 51
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 40
Delay 42
KeyDown "Shift", 1
Delay 5
Delay 1
KeyDown "Shift", 1
Delay 41
Delay 50
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 36
Delay 40
KeyDown "Shift", 1
MoveTo 767, 418
Delay 46
KeyDown "Shift", 1
MoveTo 772, 423
Delay 2
KeyUp "Shift", 1
MoveTo 777, 446
Delay 492
KeyDown "M", 1
MoveTo 776, 452
Delay 143
KeyUp "M", 1
MoveTo 781, 532
Delay 300
KeyDown "Ctrl", 1
MoveTo 892, 510
Delay 501
KeyDown "Ctrl", 1
Delay 33
MoveTo 894, 513
Delay 32
KeyDown "Ctrl", 1
MoveTo 899, 513
Delay 34
KeyDown "Ctrl", 1
MoveTo 900, 513
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 901, 513
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 31
KeyDown "Ctrl", 1
MoveTo 903, 513
Delay 35
KeyDown "Ctrl", 1
MoveTo 909, 511
Delay 33
KeyDown "Ctrl", 1
MoveTo 910, 510
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 32
MoveTo 911, 509
Delay 35
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 136
Delay 33
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 36
Delay 31
KeyDown "Ctrl", 1
Delay 34
Delay 21
KeyDown "Ctrl", 1
Delay 1
Delay 11
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 839, 407
Delay 2296
KeyDown "Shift", 1
MoveTo 825, 360
Delay 366
LeftClick 1
Delay 43
KeyDown "Shift", 1
Delay 35
Delay 3
Delay 54
KeyDown "Shift", 1
Delay 40
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 44
MoveTo 822, 352
Delay 47
KeyDown "Shift", 1
MoveTo 820, 346
Delay 40
KeyDown "Shift", 1
MoveTo 819, 343
Delay 37
KeyDown "Shift", 1
MoveTo 819, 342
Delay 38
KeyDown "Shift", 1
Delay 2
Delay 38
KeyDown "Shift", 1
Delay 33
Delay 38
KeyDown "Shift", 1
Delay 40
Delay 3
LeftDown 1
Delay 42
KeyDown "Shift", 1
Delay 3
Delay 42
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 39
Delay 43
KeyDown "Shift", 1
Delay 1
Delay 49
KeyUp "Shift", 1
Delay 455
KeyDown "M", 1
Delay 152
KeyUp "M", 1
MoveTo 837, 470
Delay 301
KeyDown "Ctrl", 1
MoveTo 915, 509
Delay 535
KeyDown "Ctrl", 1
Delay 1
Delay 63
KeyDown "Ctrl", 1
Delay 2
RightDown 1
KeyDown "Ctrl", 1
Delay 65
Delay 33
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 34
Delay 173
KeyDown "Ctrl", 1
Delay 15
Delay 4
KeyDown "Ctrl", 1
Delay 73
KeyUp "Ctrl", 1
MoveTo 840, 439
Delay 2378
KeyDown "Shift", 1
MoveTo 809, 353
Delay 394
LeftDown 1
Delay 92
KeyDown "Shift", 1
Delay 44
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 35
Delay 2
Delay 41
KeyDown "Shift", 1
Delay 56
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 808, 351
Delay 5
KeyDown "Shift", 1
MoveTo 805, 345
Delay 39
KeyDown "Shift", 1
MoveTo 802, 339
Delay 40
KeyDown "Shift", 1
MoveTo 800, 336
Delay 38
KeyDown "Shift", 1
MoveTo 800, 335
Delay 39
KeyDown "Shift", 1
Delay 34
Delay 37
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 49
Delay 43
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 44
Delay 37
Delay 2
KeyDown "Shift", 1
Delay 50
Delay 46
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 39
Delay 41
KeyDown "Shift", 1
MoveTo 800, 377
Delay 40
KeyDown "Shift", 1
MoveTo 800, 396
Delay 50
KeyDown "Shift", 1
MoveTo 802, 413
Delay 5
KeyDown "Shift", 1
MoveTo 803, 418
Delay 44
KeyDown "Shift", 1
MoveTo 803, 419
Delay 50
KeyDown "Shift", 1
Delay 36
Delay 41
KeyDown "Shift", 1
Delay 40
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 41
Delay 43
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 2
Delay 43
KeyDown "Shift", 1
Delay 4
Delay 50
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 49
KeyDown "Shift", 1
Delay 36
Delay 37
KeyUp "Shift", 1
Delay 267
KeyDown "M", 1
Delay 143
KeyUp "M", 1
MoveTo 865, 508
Delay 371
KeyDown "Ctrl", 1
MoveTo 900, 541
Delay 496
KeyDown "Ctrl", 1
MoveTo 904, 541
Delay 34
KeyDown "Ctrl", 1
MoveTo 909, 537
Delay 34
KeyDown "Ctrl", 1
MoveTo 912, 534
Delay 33
KeyDown "Ctrl", 1
MoveTo 913, 532
Delay 34
KeyDown "Ctrl", 1
MoveTo 912, 529
Delay 33
KeyDown "Ctrl", 1
MoveTo 911, 527
Delay 32
KeyDown "Ctrl", 1
MoveTo 910, 526
Delay 33
KeyDown "Ctrl", 1
MoveTo 904, 526
Delay 35
KeyDown "Ctrl", 1
MoveTo 892, 526
Delay 33
KeyDown "Ctrl", 1
MoveTo 882, 529
Delay 33
KeyDown "Ctrl", 1
MoveTo 868, 539
Delay 33
KeyDown "Ctrl", 1
MoveTo 862, 544
Delay 34
KeyDown "Ctrl", 1
MoveTo 861, 546
Delay 33
KeyDown "Ctrl", 1
MoveTo 861, 547
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 861, 549
Delay 35
KeyDown "Ctrl", 1
MoveTo 866, 549
Delay 32
KeyDown "Ctrl", 1
MoveTo 869, 548
Delay 34
KeyDown "Ctrl", 1
MoveTo 871, 545
Delay 32
KeyDown "Ctrl", 1
MoveTo 871, 543
Delay 34
KeyDown "Ctrl", 1
MoveTo 871, 542
Delay 35
KeyDown "Ctrl", 1
MoveTo 871, 541
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 871, 540
Delay 33
KeyDown "Ctrl", 1
MoveTo 871, 538
Delay 34
KeyDown "Ctrl", 1
MoveTo 871, 536
Delay 33
KeyDown "Ctrl", 1
MoveTo 871, 535
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 32
KeyDown "Ctrl", 1
MoveTo 872, 534
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 98
KeyDown "Ctrl", 1
Delay 1
Delay 37
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 799, 371
Delay 2608
KeyDown "Shift", 1
MoveTo 799, 327
Delay 266
LeftClick 1
MoveTo 793, 351
Delay 127
KeyDown "Shift", 1
MoveTo 791, 364
Delay 44
KeyDown "Shift", 1
MoveTo 790, 369
Delay 41
KeyDown "Shift", 1
Delay 55
Delay 52
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 60
Delay 61
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 43
Delay 51
KeyDown "Shift", 1
MoveTo 790, 370
Delay 56
KeyDown "Shift", 1
Delay 52
Delay 48
KeyDown "Shift", 1
MoveTo 791, 385
Delay 44
KeyDown "Shift", 1
MoveTo 794, 402
Delay 49
KeyDown "Shift", 1
MoveTo 796, 414
Delay 46
KeyDown "Shift", 1
MoveTo 796, 425
Delay 42
KeyDown "Shift", 1
MoveTo 796, 427
Delay 47
KeyDown "Shift", 1
MoveTo 796, 428
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 41
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 45
KeyDown "Shift", 1
Delay 58
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 52
Delay 40
KeyDown "Shift", 1
Delay 1
Delay 4
KeyDown "Shift", 1
Delay 48
Delay 48
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 45
Delay 45
KeyUp "Shift", 1
MoveTo 797, 437
Delay 402
KeyDown "M", 1
MoveTo 796, 439
Delay 155
KeyUp "M", 1
MoveTo 799, 497
Delay 300
KeyDown "Ctrl", 1
MoveTo 829, 481
Delay 504
KeyDown "Ctrl", 1
MoveTo 834, 481
Delay 30
KeyDown "Ctrl", 1
MoveTo 837, 481
Delay 33
KeyDown "Ctrl", 1
MoveTo 840, 481
Delay 34
KeyDown "Ctrl", 1
MoveTo 844, 481
Delay 32
KeyDown "Ctrl", 1
MoveTo 845, 481
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
MoveTo 847, 480
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
MoveTo 849, 480
Delay 34
KeyDown "Ctrl", 1
MoveTo 852, 481
Delay 34
KeyDown "Ctrl", 1
MoveTo 852, 490
Delay 33
KeyDown "Ctrl", 1
MoveTo 849, 496
Delay 35
KeyDown "Ctrl", 1
MoveTo 847, 500
Delay 32
KeyDown "Ctrl", 1
MoveTo 844, 503
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 844, 504
Delay 37
KeyDown "Ctrl", 1
MoveTo 842, 504
Delay 30
KeyDown "Ctrl", 1
MoveTo 842, 501
Delay 34
KeyDown "Ctrl", 1
MoveTo 842, 498
Delay 34
KeyDown "Ctrl", 1
MoveTo 842, 497
Delay 33
KeyDown "Ctrl", 1
MoveTo 846, 494
Delay 34
KeyDown "Ctrl", 1
MoveTo 848, 493
Delay 32
KeyDown "Ctrl", 1
MoveTo 850, 491
Delay 36
KeyDown "Ctrl", 1
MoveTo 852, 489
Delay 30
KeyDown "Ctrl", 1
MoveTo 855, 487
Delay 34
KeyDown "Ctrl", 1
MoveTo 856, 486
Delay 33
KeyDown "Ctrl", 1
MoveTo 857, 484
Delay 34
KeyDown "Ctrl", 1
MoveTo 858, 483
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 2
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 144
Delay 22
KeyDown "Ctrl", 1
Delay 2
Delay 91
KeyUp "Ctrl", 1
MoveTo 839, 370
Delay 2342
KeyDown "Shift", 1
MoveTo 795, 326
Delay 376
LeftClick 1
Delay 5
KeyDown "Shift", 1
Delay 38
Delay 41
KeyDown "Shift", 1
Delay 41
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 5
KeyDown "Shift", 1
MoveTo 795, 328
Delay 56
KeyDown "Shift", 1
MoveTo 795, 337
Delay 45
KeyDown "Shift", 1
MoveTo 794, 348
Delay 42
KeyDown "Shift", 1
MoveTo 793, 353
Delay 50
KeyDown "Shift", 1
MoveTo 793, 355
Delay 43
KeyDown "Shift", 1
Delay 36
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 47
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 35
Delay 38
KeyDown "Shift", 1
Delay 42
MoveTo 793, 376
Delay 44
KeyDown "Shift", 1
MoveTo 793, 387
Delay 43
KeyDown "Shift", 1
MoveTo 793, 392
Delay 46
KeyDown "Shift", 1
MoveTo 793, 399
Delay 38
KeyDown "Shift", 1
MoveTo 793, 403
Delay 44
KeyDown "Shift", 1
MoveTo 793, 404
Delay 40
KeyDown "Shift", 1
Delay 37
Delay 38
KeyDown "Shift", 1
Delay 34
Delay 42
KeyDown "Shift", 1
Delay 37
Delay 40
KeyDown "Shift", 1
Delay 38
Delay 38
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 44
Delay 47
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 46
Delay 2
Delay 51
KeyDown "Shift", 1
Delay 42
Delay 1
LeftUp 1
Delay 43
KeyDown "Shift", 1
Delay 40
Delay 2
KeyDown "Shift", 1
Delay 38
KeyUp "Shift", 1
MoveTo 797, 405
Delay 268
KeyDown "M", 1
MoveTo 807, 412
Delay 153
KeyUp "M", 1
MoveTo 869, 489
Delay 365
KeyDown "Ctrl", 1
MoveTo 886, 541
Delay 500
KeyDown "Ctrl", 1
MoveTo 888, 542
Delay 32
KeyDown "Ctrl", 1
MoveTo 888, 543
Delay 37
KeyDown "Ctrl", 1
MoveTo 889, 545
Delay 31
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 2
KeyDown "Ctrl", 1
Delay 158
Delay 2
KeyUp "Ctrl", 1
MoveTo 807, 417
Delay 2735
KeyDown "Shift", 1
MoveTo 809, 415
Delay 357
LeftClick 1
Delay 47
KeyDown "Shift", 1
Delay 45
Delay 2
Delay 1
KeyDown "Shift", 1
Delay 66
LeftUp 1
Delay 8
KeyDown "Shift", 1
MoveTo 809, 412
Delay 48
KeyDown "Shift", 1
MoveTo 806, 390
Delay 44
KeyDown "Shift", 1
MoveTo 806, 383
Delay 37
KeyDown "Shift", 1
MoveTo 806, 379
Delay 41
KeyDown "Shift", 1
MoveTo 807, 372
Delay 41
KeyDown "Shift", 1
MoveTo 808, 361
Delay 42
KeyDown "Shift", 1
MoveTo 810, 356
Delay 43
KeyDown "Shift", 1
MoveTo 811, 348
Delay 47
KeyDown "Shift", 1
MoveTo 813, 341
Delay 3
KeyDown "Shift", 1
MoveTo 813, 339
Delay 43
KeyDown "Shift", 1
Delay 44
Delay 53
KeyDown "Shift", 1
Delay 38
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 51
Delay 41
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 43
Delay 39
KeyDown "Shift", 1
Delay 37
Delay 38
KeyUp "Shift", 1
MoveTo 803, 382
Delay 770
KeyDown "M", 1
MoveTo 798, 382
Delay 158
KeyUp "M", 1
MoveTo 752, 436
Delay 402
KeyDown "Ctrl", 1
MoveTo 781, 513
Delay 499
KeyDown "Ctrl", 1
MoveTo 781, 514
Delay 32
KeyDown "Ctrl", 1
MoveTo 781, 515
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 781, 517
Delay 34
KeyDown "Ctrl", 1
MoveTo 781, 518
Delay 34
KeyDown "Ctrl", 1
MoveTo 781, 519
Delay 32
KeyDown "Ctrl", 1
MoveTo 781, 520
Delay 33
KeyDown "Ctrl", 1
MoveTo 781, 522
Delay 34
KeyDown "Ctrl", 1
MoveTo 781, 523
Delay 33
KeyDown "Ctrl", 1
MoveTo 783, 525
Delay 34
KeyDown "Ctrl", 1
MoveTo 784, 525
Delay 33
KeyDown "Ctrl", 1
MoveTo 785, 528
Delay 34
KeyDown "Ctrl", 1
MoveTo 786, 528
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 786, 529
Delay 34
KeyDown "Ctrl", 1
Delay 34
MoveTo 786, 530
Delay 32
KeyDown "Ctrl", 1
MoveTo 786, 531
Delay 35
KeyDown "Ctrl", 1
Delay 35
Delay 32
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 32
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 4
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 30
Delay 32
KeyDown "Ctrl", 1
Delay 62
Delay 1
KeyDown "Ctrl", 1
Delay 70
Delay 2
KeyUp "Ctrl", 1
MoveTo 783, 378
Delay 2578
KeyDown "Shift", 1
MoveTo 786, 342
Delay 551
KeyDown "Shift", 1
MoveTo 786, 354
Delay 47
KeyDown "Shift", 1
Delay 36
MoveTo 787, 356
Delay 43
KeyDown "Shift", 1
MoveTo 787, 357
Delay 40
KeyDown "Shift", 1
Delay 40
Delay 1
LeftDown 1
Delay 43
KeyDown "Shift", 1
Delay 42
Delay 1
LeftUp 1
Delay 52
KeyDown "Shift", 1
Delay 40
Delay 46
KeyDown "Shift", 1
MoveTo 787, 351
Delay 5
KeyDown "Shift", 1
MoveTo 787, 341
Delay 37
KeyDown "Shift", 1
MoveTo 787, 340
Delay 38
KeyDown "Shift", 1
Delay 45
Delay 42
KeyDown "Shift", 1
Delay 54
Delay 6
LeftDown 1
Delay 47
KeyDown "Shift", 1
Delay 62
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 787, 341
Delay 42
KeyDown "Shift", 1
MoveTo 787, 374
Delay 54
KeyDown "Shift", 1
MoveTo 787, 419
Delay 48
KeyDown "Shift", 1
MoveTo 787, 427
Delay 53
KeyDown "Shift", 1
MoveTo 786, 429
Delay 40
KeyDown "Shift", 1
MoveTo 786, 430
Delay 46
KeyDown "Shift", 1
Delay 40
Delay 39
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 49
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 785, 431
Delay 41
KeyDown "Shift", 1
Delay 41
Delay 39
KeyDown "Shift", 1
Delay 3
MoveTo 784, 430
Delay 36
KeyDown "Shift", 1
MoveTo 784, 427
Delay 43
KeyDown "Shift", 1
MoveTo 784, 419
Delay 45
KeyDown "Shift", 1
MoveTo 784, 414
Delay 42
KeyDown "Shift", 1
MoveTo 784, 412
Delay 42
KeyDown "Shift", 1
Delay 39
Delay 37
KeyDown "Shift", 1
Delay 46
Delay 2
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 46
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 39
Delay 43
Delay 2
KeyDown "Shift", 1
Delay 43
Delay 45
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 47
KeyDown "Shift", 1
Delay 3
Delay 47
KeyDown "Shift", 1
MoveTo 786, 411
Delay 46
KeyDown "Shift", 1
MoveTo 788, 415
Delay 1
KeyUp "Shift", 1
MoveTo 792, 424
Delay 408
KeyDown "M", 1
MoveTo 792, 430
Delay 179
KeyUp "M", 1
MoveTo 824, 451
Delay 266
KeyDown "Ctrl", 1
MoveTo 828, 420
Delay 531
KeyDown "Ctrl", 1
MoveTo 825, 420
Delay 2
KeyDown "Ctrl", 1
MoveTo 823, 419
Delay 64
KeyDown "Ctrl", 1
MoveTo 813, 417
Delay 34
KeyDown "Ctrl", 1
MoveTo 806, 417
Delay 35
KeyDown "Ctrl", 1
MoveTo 798, 422
Delay 33
KeyDown "Ctrl", 1
MoveTo 792, 429
Delay 40
KeyDown "Ctrl", 1
MoveTo 792, 437
Delay 30
KeyDown "Ctrl", 1
MoveTo 792, 444
Delay 31
KeyDown "Ctrl", 1
MoveTo 793, 452
Delay 33
KeyDown "Ctrl", 1
MoveTo 794, 454
Delay 33
KeyDown "Ctrl", 1
MoveTo 796, 458
Delay 34
KeyDown "Ctrl", 1
MoveTo 798, 461
Delay 33
KeyDown "Ctrl", 1
MoveTo 800, 464
Delay 33
KeyDown "Ctrl", 1
MoveTo 802, 466
Delay 33
KeyDown "Ctrl", 1
MoveTo 807, 468
Delay 34
KeyDown "Ctrl", 1
MoveTo 808, 468
Delay 69
KeyDown "Ctrl", 1
MoveTo 810, 468
Delay 34
KeyDown "Ctrl", 1
MoveTo 811, 468
Delay 33
KeyDown "Ctrl", 1
MoveTo 812, 468
Delay 38
KeyDown "Ctrl", 1
MoveTo 812, 466
Delay 29
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
MoveTo 810, 465
Delay 34
KeyDown "Ctrl", 1
MoveTo 793, 466
Delay 35
KeyDown "Ctrl", 1
MoveTo 780, 466
Delay 33
KeyDown "Ctrl", 1
MoveTo 776, 465
Delay 34
KeyDown "Ctrl", 1
MoveTo 775, 464
Delay 31
KeyDown "Ctrl", 1
MoveTo 773, 462
Delay 34
KeyDown "Ctrl", 1
MoveTo 773, 461
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 31
KeyDown "Ctrl", 1
MoveTo 772, 468
Delay 35
KeyDown "Ctrl", 1
MoveTo 763, 477
Delay 32
KeyDown "Ctrl", 1
MoveTo 753, 485
Delay 34
KeyDown "Ctrl", 1
MoveTo 743, 493
Delay 34
KeyDown "Ctrl", 1
MoveTo 740, 495
Delay 33
KeyDown "Ctrl", 1
MoveTo 739, 496
Delay 35
KeyDown "Ctrl", 1
Delay 35
MoveTo 738, 496
Delay 3
KeyDown "Ctrl", 1
Delay 60
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 3
RightDown 1
Delay 2
KeyDown "Ctrl", 1
Delay 62
Delay 35
KeyDown "Ctrl", 1
Delay 2
RightClick 1
Delay 1
KeyDown "Ctrl", 1
Delay 62
Delay 141
KeyDown "Ctrl", 1
Delay 34
Delay 1
KeyDown "Ctrl", 1
MoveTo 740, 496
Delay 55
KeyDown "Ctrl", 1
MoveTo 741, 496
Delay 2
KeyUp "Ctrl", 1
MoveTo 787, 379
Delay 2685
KeyDown "Shift", 1
MoveTo 791, 368
Delay 245
LeftClick 1
MoveTo 796, 392
Delay 227
KeyDown "Shift", 1
Delay 2
MoveTo 798, 398
Delay 42
KeyDown "Shift", 1
MoveTo 798, 404
Delay 44
KeyDown "Shift", 1
MoveTo 799, 410
Delay 6
KeyDown "Shift", 1
MoveTo 799, 412
Delay 37
KeyDown "Shift", 1
MoveTo 799, 414
Delay 40
KeyDown "Shift", 1
MoveTo 800, 416
Delay 41
KeyDown "Shift", 1
MoveTo 800, 417
Delay 39
KeyDown "Shift", 1
Delay 36
Delay 3
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 49
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 41
Delay 1
Delay 40
KeyDown "Shift", 1
Delay 44
Delay 44
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 40
Delay 38
KeyDown "Shift", 1
MoveTo 800, 418
Delay 2
KeyUp "Shift", 1
MoveTo 808, 434
Delay 346
KeyDown "M", 1
MoveTo 815, 445
Delay 150
KeyUp "M", 1
MoveTo 860, 463
Delay 369
KeyDown "Ctrl", 1
MoveTo 783, 486
Delay 497
RightDown 1
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 9
Delay 3
KeyDown "Ctrl", 1
Delay 136
KeyUp "Ctrl", 1
MoveTo 751, 373
Delay 2394
KeyDown "Shift", 1
MoveTo 755, 360
Delay 336
LeftDoubleClick 1
Delay 45
KeyDown "Shift", 1
Delay 43
Delay 41
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 755, 368
Delay 39
KeyDown "Shift", 1
MoveTo 755, 387
Delay 36
KeyDown "Shift", 1
MoveTo 755, 394
Delay 58
KeyDown "Shift", 1
MoveTo 755, 397
Delay 40
KeyDown "Shift", 1
MoveTo 757, 399
Delay 37
KeyDown "Shift", 1
MoveTo 757, 400
Delay 40
KeyDown "Shift", 1
MoveTo 758, 401
Delay 39
KeyDown "Shift", 1
MoveTo 760, 406
Delay 40
KeyDown "Shift", 1
MoveTo 760, 408
Delay 3
KeyDown "Shift", 1
Delay 36
Delay 39
KeyDown "Shift", 1
Delay 3
LeftDown 1
Delay 37
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 43
KeyDown "Shift", 1
Delay 2
Delay 40
KeyDown "Shift", 1
Delay 41
Delay 41
KeyDown "Shift", 1
Delay 34
Delay 41
KeyDown "Shift", 1
Delay 3
KeyUp "Shift", 1
MoveTo 762, 426
Delay 392
KeyDown "M", 1
Delay 131
KeyUp "M", 1
MoveTo 764, 508
Delay 432
KeyDown "Ctrl", 1
MoveTo 758, 544
Delay 533
KeyDown "Ctrl", 1
Delay 34
MoveTo 758, 545
Delay 4
KeyDown "Ctrl", 1
Delay 64
Delay 1
KeyDown "Ctrl", 1
Delay 65
MoveTo 758, 546
Delay 3
KeyDown "Ctrl", 1
MoveTo 764, 546
Delay 33
KeyDown "Ctrl", 1
MoveTo 795, 546
Delay 31
KeyDown "Ctrl", 1
MoveTo 832, 547
Delay 33
KeyDown "Ctrl", 1
MoveTo 839, 549
Delay 34
KeyDown "Ctrl", 1
MoveTo 841, 550
Delay 37
KeyDown "Ctrl", 1
Delay 61
MoveTo 842, 550
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 843, 550
Delay 37
KeyDown "Ctrl", 1
Delay 29
MoveTo 845, 551
Delay 34
KeyDown "Ctrl", 1
MoveTo 846, 551
Delay 34
KeyDown "Ctrl", 1
Delay 32
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 32
MoveTo 850, 550
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 851, 549
Delay 34
KeyDown "Ctrl", 1
Delay 34
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 848, 549
Delay 34
KeyDown "Ctrl", 1
MoveTo 844, 549
Delay 34
KeyDown "Ctrl", 1
MoveTo 840, 550
Delay 34
KeyDown "Ctrl", 1
MoveTo 839, 550
Delay 32
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
RightClick 1
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 93
Delay 1
KeyDown "Ctrl", 1
Delay 45
Delay 2
KeyUp "Ctrl", 1
MoveTo 801, 167
Delay 2835
KeyDown "Shift", 1
MoveTo 797, 348
Delay 518
KeyDown "Shift", 1
Delay 44
MoveTo 797, 349
Delay 2
KeyDown "Shift", 1
MoveTo 797, 351
Delay 39
KeyDown "Shift", 1
MoveTo 797, 353
Delay 46
KeyDown "Shift", 1
Delay 62
Delay 1
LeftDown 1
Delay 54
KeyDown "Shift", 1
Delay 52
LeftUp 1
Delay 6
KeyDown "Shift", 1
Delay 47
Delay 1
Delay 47
KeyDown "Shift", 1
Delay 46
Delay 47
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 45
MoveTo 800, 384
Delay 48
KeyDown "Shift", 1
MoveTo 802, 395
Delay 39
KeyDown "Shift", 1
MoveTo 803, 396
Delay 4
KeyDown "Shift", 1
MoveTo 804, 398
Delay 44
KeyDown "Shift", 1
Delay 37
MoveTo 805, 399
Delay 48
KeyDown "Shift", 1
MoveTo 807, 401
Delay 2
KeyDown "Shift", 1
MoveTo 809, 404
Delay 47
KeyDown "Shift", 1
MoveTo 809, 407
Delay 40
KeyDown "Shift", 1
MoveTo 809, 408
Delay 44
KeyDown "Shift", 1
Delay 42
Delay 41
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 46
KeyDown "Shift", 1
Delay 45
LeftUp 1
Delay 4
KeyDown "Shift", 1
MoveTo 809, 409
Delay 46
KeyDown "Shift", 1
Delay 40
Delay 5
Delay 1
KeyDown "Shift", 1
Delay 49
Delay 48
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 6
KeyDown "Shift", 1
MoveTo 809, 410
Delay 43
KeyDown "Shift", 1
MoveTo 809, 419
Delay 5
KeyDown "Shift", 1
MoveTo 809, 438
Delay 51
KeyDown "Shift", 1
MoveTo 809, 454
Delay 45
KeyDown "Shift", 1
MoveTo 809, 464
Delay 3
KeyDown "Shift", 1
MoveTo 809, 470
Delay 40
KeyDown "Shift", 1
MoveTo 809, 474
Delay 43
KeyDown "Shift", 1
MoveTo 808, 480
Delay 43
KeyDown "Shift", 1
MoveTo 807, 486
Delay 2
KeyDown "Shift", 1
MoveTo 806, 494
Delay 44
KeyDown "Shift", 1
MoveTo 806, 499
Delay 57
KeyDown "Shift", 1
Delay 2
Delay 45
KeyDown "Shift", 1
Delay 44
Delay 40
KeyDown "Shift", 1
Delay 41
MoveTo 806, 500
Delay 40
LeftDown 1
Delay 1
KeyDown "Shift", 1
Delay 41
Delay 45
KeyDown "Shift", 1
Delay 2
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 42
Delay 39
KeyDown "Shift", 1
Delay 44
KeyUp "Shift", 1
MoveTo 805, 500
Delay 332
KeyDown "M", 1
MoveTo 804, 501
Delay 152
KeyUp "M", 1
MoveTo 737, 462
Delay 1801
KeyDown "Shift", 1
MoveTo 745, 476
Delay 533
KeyDown "Shift", 1
Delay 2
Delay 31
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
MoveTo 745, 475
Delay 34
KeyDown "Shift", 1
MoveTo 740, 475
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 33
Delay 33
KeyDown "Shift", 1
Delay 33
Delay 34
KeyDown "Shift", 1
Delay 34
KeyUp "Shift", 1
Delay 233
KeyDown "Ctrl", 1
MoveTo 742, 480
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 742, 481
Delay 33
KeyDown "Ctrl", 1
MoveTo 744, 481
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 740, 482
Delay 37
KeyDown "Ctrl", 1
MoveTo 726, 488
Delay 30
KeyDown "Ctrl", 1
MoveTo 714, 494
Delay 33
KeyDown "Ctrl", 1
MoveTo 711, 495
Delay 34
KeyDown "Ctrl", 1
Delay 33
MoveTo 710, 496
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
MoveTo 711, 494
Delay 33
KeyDown "Ctrl", 1
MoveTo 714, 492
Delay 33
KeyDown "Ctrl", 1
Delay 1
RightDown 1
Delay 32
KeyDown "Ctrl", 1
MoveTo 715, 491
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 35
KeyDown "Ctrl", 1
Delay 4
Delay 1
RightClick 1
Delay 61
KeyDown "Ctrl", 1
Delay 159
Delay 62
KeyDown "Ctrl", 1
Delay 2
Delay 27
KeyDown "Ctrl", 1
Delay 2
KeyUp "Ctrl", 1
MoveTo 791, 336
Delay 2406
KeyDown "Shift", 1
MoveTo 780, 362
Delay 424
LeftClick 1
Delay 77
KeyDown "Shift", 1
Delay 43
Delay 1
KeyDown "Shift", 1
Delay 46
Delay 3
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 52
MoveTo 780, 363
Delay 43
KeyDown "Shift", 1
MoveTo 780, 377
Delay 4
KeyDown "Shift", 1
MoveTo 782, 390
Delay 77
KeyDown "Shift", 1
MoveTo 783, 400
Delay 72
KeyDown "Shift", 1
MoveTo 783, 403
Delay 66
KeyDown "Shift", 1
MoveTo 783, 406
Delay 70
KeyDown "Shift", 1
MoveTo 783, 410
Delay 49
KeyDown "Shift", 1
Delay 40
Delay 43
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 57
Delay 2
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 48
Delay 41
Delay 1
KeyDown "Shift", 1
Delay 48
Delay 51
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 51
MoveTo 783, 438
Delay 51
KeyDown "Shift", 1
MoveTo 782, 455
Delay 6
KeyDown "Shift", 1
MoveTo 781, 460
Delay 51
KeyDown "Shift", 1
MoveTo 781, 463
Delay 46
KeyDown "Shift", 1
MoveTo 781, 470
Delay 51
KeyDown "Shift", 1
MoveTo 780, 476
Delay 60
KeyDown "Shift", 1
MoveTo 779, 486
Delay 56
KeyDown "Shift", 1
MoveTo 779, 494
Delay 55
KeyDown "Shift", 1
MoveTo 779, 495
Delay 44
KeyDown "Shift", 1
Delay 46
KeyUp "Shift", 1
MoveTo 779, 499
Delay 485
KeyDown "M", 1
MoveTo 779, 502
Delay 152
KeyUp "M", 1
MoveTo 681, 557
Delay 430
KeyDown "Ctrl", 1
MoveTo 674, 563
Delay 500
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
MoveTo 674, 561
Delay 32
KeyDown "Ctrl", 1
MoveTo 674, 558
Delay 34
KeyDown "Ctrl", 1
MoveTo 674, 557
Delay 33
KeyDown "Ctrl", 1
MoveTo 674, 556
Delay 33
KeyDown "Ctrl", 1
MoveTo 674, 553
Delay 34
KeyDown "Ctrl", 1
MoveTo 674, 551
Delay 33
KeyDown "Ctrl", 1
MoveTo 674, 549
Delay 34
KeyDown "Ctrl", 1
Delay 3
RightDown 1
Delay 30
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 1
RightClick 1
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 4
Delay 144
KeyDown "Ctrl", 1
Delay 17
Delay 2
KeyUp "Ctrl", 1
MoveTo 736, 272
Delay 2729
KeyDown "Shift", 1
MoveTo 726, 356
Delay 540
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 3
KeyDown "Shift", 1
Delay 76
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 55
Delay 55
KeyDown "Shift", 1
Delay 2
KeyDown "Shift", 1
Delay 70
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 64
MoveTo 732, 369
Delay 53
KeyDown "Shift", 1
MoveTo 737, 394
Delay 42
KeyDown "Shift", 1
MoveTo 739, 401
Delay 45
KeyDown "Shift", 1
MoveTo 739, 405
Delay 3
KeyDown "Shift", 1
MoveTo 740, 411
Delay 50
KeyDown "Shift", 1
MoveTo 740, 412
Delay 51
KeyDown "Shift", 1
MoveTo 740, 415
Delay 54
KeyDown "Shift", 1
Delay 50
Delay 2
LeftDown 1
Delay 45
KeyDown "Shift", 1
Delay 45
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 740, 416
Delay 43
KeyDown "Shift", 1
MoveTo 741, 424
Delay 44
KeyDown "Shift", 1
MoveTo 747, 437
Delay 43
KeyDown "Shift", 1
MoveTo 756, 462
Delay 43
KeyDown "Shift", 1
MoveTo 757, 468
Delay 45
KeyDown "Shift", 1
MoveTo 758, 472
Delay 8
KeyDown "Shift", 1
MoveTo 759, 475
Delay 45
KeyDown "Shift", 1
MoveTo 759, 477
Delay 47
KeyDown "Shift", 1
MoveTo 760, 480
Delay 1
KeyDown "Shift", 1
MoveTo 760, 483
Delay 40
KeyDown "Shift", 1
MoveTo 761, 485
Delay 40
KeyDown "Shift", 1
MoveTo 761, 486
Delay 46
KeyDown "Shift", 1
MoveTo 761, 488
Delay 39
KeyDown "Shift", 1
MoveTo 761, 490
Delay 48
KeyDown "Shift", 1
MoveTo 761, 492
Delay 53
KeyDown "Shift", 1
MoveTo 761, 498
Delay 47
KeyDown "Shift", 1
MoveTo 761, 499
Delay 39
KeyDown "Shift", 1
MoveTo 761, 501
Delay 45
KeyDown "Shift", 1
MoveTo 762, 502
Delay 45
KeyDown "Shift", 1
Delay 41
MoveTo 762, 503
Delay 46
KeyDown "Shift", 1
Delay 40
MoveTo 762, 502
Delay 41
KeyDown "Shift", 1
MoveTo 762, 501
Delay 45
KeyDown "Shift", 1
MoveTo 762, 499
Delay 3
KeyDown "Shift", 1
MoveTo 761, 498
Delay 39
KeyDown "Shift", 1
Delay 43
Delay 41
KeyDown "Shift", 1
MoveTo 760, 497
Delay 39
KeyDown "Shift", 1
Delay 40
Delay 42
KeyDown "Shift", 1
Delay 2
LeftDown 1
Delay 43
KeyDown "Shift", 1
Delay 52
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 36
Delay 45
KeyDown "Shift", 1
Delay 1
KeyUp "Shift", 1
MoveTo 761, 495
Delay 447
KeyDown "M", 1
MoveTo 761, 496
Delay 187
KeyUp "M", 1
MoveTo 749, 502
Delay 300
KeyDown "Ctrl", 1
MoveTo 654, 578
Delay 499
KeyDown "Ctrl", 1
MoveTo 653, 576
Delay 34
KeyDown "Ctrl", 1
MoveTo 652, 576
Delay 33
KeyDown "Ctrl", 1
MoveTo 650, 574
Delay 35
KeyDown "Ctrl", 1
MoveTo 650, 573
Delay 33
KeyDown "Ctrl", 1
MoveTo 649, 571
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 35
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 38
Delay 1
KeyDown "Ctrl", 1
MoveTo 648, 571
Delay 41
KeyDown "Ctrl", 1
MoveTo 647, 571
Delay 33
KeyDown "Ctrl", 1
MoveTo 646, 571
Delay 32
KeyDown "Ctrl", 1
Delay 47
MoveTo 644, 571
Delay 23
KeyDown "Ctrl", 1
MoveTo 640, 571
Delay 34
KeyDown "Ctrl", 1
MoveTo 635, 570
Delay 33
KeyDown "Ctrl", 1
MoveTo 634, 570
Delay 34
KeyDown "Ctrl", 1
Delay 36
MoveTo 633, 571
Delay 29
KeyDown "Ctrl", 1
Delay 33
MoveTo 631, 571
Delay 58
KeyDown "Ctrl", 1
MoveTo 628, 563
Delay 5
KeyDown "Ctrl", 1
MoveTo 620, 547
Delay 18
KeyDown "Ctrl", 1
MoveTo 613, 531
Delay 65
KeyDown "Ctrl", 1
MoveTo 611, 522
Delay 3
KeyDown "Ctrl", 1
MoveTo 610, 513
Delay 30
KeyDown "Ctrl", 1
MoveTo 610, 505
Delay 37
KeyDown "Ctrl", 1
MoveTo 610, 498
Delay 32
KeyDown "Ctrl", 1
MoveTo 610, 495
Delay 33
KeyDown "Ctrl", 1
MoveTo 610, 493
Delay 31
KeyDown "Ctrl", 1
MoveTo 610, 490
Delay 34
KeyDown "Ctrl", 1
MoveTo 610, 482
Delay 33
KeyDown "Ctrl", 1
MoveTo 610, 476
Delay 35
KeyDown "Ctrl", 1
MoveTo 610, 472
Delay 32
KeyDown "Ctrl", 1
MoveTo 610, 469
Delay 35
KeyDown "Ctrl", 1
MoveTo 612, 467
Delay 35
KeyDown "Ctrl", 1
MoveTo 613, 463
Delay 30
KeyDown "Ctrl", 1
MoveTo 614, 462
Delay 32
KeyDown "Ctrl", 1
MoveTo 614, 461
Delay 35
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 38
KeyDown "Ctrl", 1
MoveTo 613, 460
Delay 32
KeyDown "Ctrl", 1
MoveTo 610, 460
Delay 32
KeyDown "Ctrl", 1
MoveTo 606, 460
Delay 33
KeyDown "Ctrl", 1
MoveTo 597, 460
Delay 34
KeyDown "Ctrl", 1
MoveTo 588, 460
Delay 34
KeyDown "Ctrl", 1
MoveTo 582, 461
Delay 32
KeyDown "Ctrl", 1
MoveTo 579, 461
Delay 34
KeyDown "Ctrl", 1
Delay 31
Delay 34
KeyDown "Ctrl", 1
Delay 2
RightDown 1
Delay 33
KeyDown "Ctrl", 1
Delay 32
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 2
RightClick 1
Delay 32
KeyDown "Ctrl", 1
Delay 36
Delay 32
KeyDown "Ctrl", 1
Delay 81
Delay 1
KeyDown "Ctrl", 1
Delay 44
Delay 1
KeyUp "Ctrl", 1
MoveTo 730, 328
Delay 2585
KeyDown "Shift", 1
MoveTo 727, 358
Delay 350
LeftClick 1
Delay 72
KeyDown "Shift", 1
Delay 35
Delay 5
KeyDown "Shift", 1
Delay 40
Delay 43
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 727, 363
Delay 34
KeyDown "Shift", 1
MoveTo 727, 377
Delay 62
KeyDown "Shift", 1
MoveTo 727, 387
Delay 37
KeyDown "Shift", 1
Delay 35
MoveTo 727, 390
Delay 40
KeyDown "Shift", 1
MoveTo 726, 393
Delay 35
KeyDown "Shift", 1
MoveTo 726, 397
Delay 36
KeyDown "Shift", 1
MoveTo 726, 399
Delay 39
KeyDown "Shift", 1
MoveTo 726, 401
Delay 4
KeyDown "Shift", 1
MoveTo 726, 402
Delay 37
KeyDown "Shift", 1
Delay 37
Delay 32
KeyDown "Shift", 1
Delay 35
MoveTo 726, 403
Delay 39
KeyDown "Shift", 1
MoveTo 726, 404
Delay 35
KeyDown "Shift", 1
MoveTo 726, 406
Delay 33
KeyDown "Shift", 1
MoveTo 726, 407
Delay 39
KeyDown "Shift", 1
Delay 36
Delay 1
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 42
Delay 38
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 39
KeyDown "Shift", 1
Delay 34
Delay 34
Delay 2
KeyDown "Shift", 1
Delay 47
Delay 39
KeyDown "Shift", 1
Delay 1
LeftUp 1
Delay 37
KeyDown "Shift", 1
Delay 39
Delay 47
KeyDown "Shift", 1
Delay 2
KeyUp "Shift", 1
MoveTo 726, 432
Delay 484
KeyDown "M", 1
Delay 171
KeyUp "M", 1
MoveTo 784, 481
Delay 365
KeyDown "Ctrl", 1
MoveTo 762, 497
Delay 532
KeyDown "Ctrl", 1
MoveTo 762, 498
Delay 5
KeyDown "Ctrl", 1
Delay 64
Delay 2
KeyDown "Ctrl", 1
Delay 31
Delay 33
KeyDown "Ctrl", 1
MoveTo 760, 500
Delay 33
KeyDown "Ctrl", 1
MoveTo 759, 501
Delay 33
KeyDown "Ctrl", 1
MoveTo 757, 504
Delay 34
KeyDown "Ctrl", 1
MoveTo 757, 509
Delay 33
KeyDown "Ctrl", 1
MoveTo 756, 510
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 36
KeyDown "Ctrl", 1
Delay 31
MoveTo 755, 511
Delay 35
KeyDown "Ctrl", 1
MoveTo 751, 511
Delay 37
KeyDown "Ctrl", 1
MoveTo 743, 508
Delay 29
KeyDown "Ctrl", 1
MoveTo 737, 503
Delay 32
KeyDown "Ctrl", 1
MoveTo 728, 500
Delay 34
KeyDown "Ctrl", 1
MoveTo 725, 499
Delay 36
KeyDown "Ctrl", 1
Delay 33
Delay 31
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 38
Delay 29
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 34
KeyDown "Ctrl", 1
Delay 35
Delay 30
KeyDown "Ctrl", 1
Delay 34
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 34
KeyDown "Ctrl", 1
Delay 32
MoveTo 729, 505
Delay 36
KeyDown "Ctrl", 1
MoveTo 753, 519
Delay 33
KeyDown "Ctrl", 1
MoveTo 769, 533
Delay 32
KeyDown "Ctrl", 1
MoveTo 777, 544
Delay 34
KeyDown "Ctrl", 1
MoveTo 785, 553
Delay 35
KeyDown "Ctrl", 1
MoveTo 787, 555
Delay 31
KeyDown "Ctrl", 1
MoveTo 789, 561
Delay 35
KeyDown "Ctrl", 1
MoveTo 790, 564
Delay 6
KeyDown "Ctrl", 1
MoveTo 791, 565
Delay 59
KeyDown "Ctrl", 1
MoveTo 791, 566
Delay 33
KeyDown "Ctrl", 1
MoveTo 793, 567
Delay 34
KeyDown "Ctrl", 1
MoveTo 794, 568
Delay 33
KeyDown "Ctrl", 1
Delay 34
MoveTo 796, 568
Delay 33
KeyDown "Ctrl", 1
MoveTo 802, 568
Delay 9
KeyDown "Ctrl", 1
MoveTo 808, 567
Delay 59
KeyDown "Ctrl", 1
MoveTo 810, 565
Delay 2
KeyDown "Ctrl", 1
Delay 64
MoveTo 814, 564
Delay 1
KeyDown "Ctrl", 1
MoveTo 820, 562
Delay 65
KeyDown "Ctrl", 1
MoveTo 823, 562
Delay 2
KeyDown "Ctrl", 1
MoveTo 827, 559
Delay 31
KeyDown "Ctrl", 1
MoveTo 829, 557
Delay 33
KeyDown "Ctrl", 1
MoveTo 829, 556
Delay 34
KeyDown "Ctrl", 1
MoveTo 820, 553
Delay 36
KeyDown "Ctrl", 1
MoveTo 771, 547
Delay 30
KeyDown "Ctrl", 1
MoveTo 700, 533
Delay 34
KeyDown "Ctrl", 1
MoveTo 640, 526
Delay 34
KeyDown "Ctrl", 1
MoveTo 592, 521
Delay 33
KeyDown "Ctrl", 1
MoveTo 582, 521
Delay 33
KeyDown "Ctrl", 1
MoveTo 580, 520
Delay 35
KeyDown "Ctrl", 1
MoveTo 576, 519
Delay 36
KeyDown "Ctrl", 1
MoveTo 566, 517
Delay 30
KeyDown "Ctrl", 1
MoveTo 552, 513
Delay 32
KeyDown "Ctrl", 1
MoveTo 546, 510
Delay 34
KeyDown "Ctrl", 1
MoveTo 545, 510
Delay 35
KeyDown "Ctrl", 1
Delay 33
Delay 31
KeyDown "Ctrl", 1
Delay 37
Delay 30
KeyDown "Ctrl", 1
MoveTo 544, 510
Delay 34
KeyDown "Ctrl", 1
Delay 33
Delay 33
KeyDown "Ctrl", 1
Delay 34
Delay 33
RightDown 1
Delay 3
KeyDown "Ctrl", 1
Delay 30
MoveTo 544, 509
Delay 35
RightClick 1
Delay 4
KeyDown "Ctrl", 1
Delay 28
Delay 32
KeyDown "Ctrl", 1
Delay 34
Delay 142
KeyDown "Ctrl", 1
MoveTo 544, 511
Delay 83
KeyDown "Ctrl", 1
MoveTo 545, 513
Delay 3
KeyDown "Ctrl", 1
MoveTo 546, 515
Delay 2
KeyDown "Ctrl", 1
MoveTo 546, 516
Delay 29
KeyDown "Ctrl", 1
MoveTo 547, 517
Delay 35
KeyDown "Ctrl", 1
MoveTo 547, 518
Delay 31
KeyDown "Ctrl", 1
MoveTo 547, 519
Delay 34
KeyDown "Ctrl", 1
MoveTo 548, 521
Delay 33
KeyDown "Ctrl", 1
MoveTo 548, 522
Delay 34
KeyDown "Ctrl", 1
Delay 29
Delay 1
KeyDown "Ctrl", 1
MoveTo 550, 524
Delay 3
KeyDown "Ctrl", 1
Delay 1
KeyUp "Ctrl", 1
MoveTo 698, 402
Delay 2116
KeyDown "Shift", 1
MoveTo 692, 364
Delay 496
LeftDown 1
Delay 38
KeyDown "Shift", 1
Delay 42
Delay 1
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 34
Delay 36
KeyDown "Shift", 1
Delay 45
Delay 2
Delay 38
KeyDown "Shift", 1
Delay 2
Delay 35
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 31
Delay 34
KeyDown "Shift", 1
MoveTo 694, 368
Delay 38
KeyDown "Shift", 1
MoveTo 703, 386
Delay 34
KeyDown "Shift", 1
MoveTo 707, 398
Delay 43
KeyDown "Shift", 1
MoveTo 708, 402
Delay 10
KeyDown "Shift", 1
MoveTo 708, 403
Delay 38
KeyDown "Shift", 1
Delay 35
Delay 34
KeyDown "Shift", 1
Delay 34
Delay 33
KeyDown "Shift", 1
Delay 34
Delay 34
KeyDown "Shift", 1
MoveTo 708, 409
Delay 34
KeyDown "Shift", 1
MoveTo 708, 411
Delay 41
KeyDown "Shift", 1
Delay 33
Delay 42
LeftDown 1
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 42
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 30
Delay 41
KeyDown "Shift", 1
Delay 35
Delay 3
Delay 2
KeyDown "Shift", 1
Delay 38
Delay 38
LeftUp 1
Delay 5
KeyDown "Shift", 1
MoveTo 708, 412
Delay 35
KeyDown "Shift", 1
Delay 31
MoveTo 713, 418
Delay 36
KeyDown "Shift", 1
MoveTo 726, 427
Delay 40
KeyDown "Shift", 1
MoveTo 744, 442
Delay 36
KeyDown "Shift", 1
MoveTo 758, 456
Delay 34
KeyDown "Shift", 1
MoveTo 762, 461
Delay 3
KeyUp "Shift", 1
MoveTo 767, 469
Delay 511
KeyDown "M", 1
Delay 137
KeyUp "M", 1
MoveTo 541, 593
Delay 1033
KeyDown "Ctrl", 1
MoveTo 531, 577
Delay 300
RightDown 1
Delay 126
RightClick 1
Delay 65
KeyDown "Ctrl", 1
Delay 137
MoveTo 533, 576
Delay 1
KeyDown "Ctrl", 1
MoveTo 535, 577
Delay 86
KeyDown "Ctrl", 1
MoveTo 536, 578
Delay 3
KeyDown "Ctrl", 1
MoveTo 537, 578
Delay 2
KeyDown "Ctrl", 1
MoveTo 538, 579
Delay 60
KeyDown "Ctrl", 1
MoveTo 541, 580
Delay 33
KeyDown "Ctrl", 1
MoveTo 543, 583
Delay 3
KeyDown "Ctrl", 1
MoveTo 550, 585
Delay 64
KeyDown "Ctrl", 1
MoveTo 556, 586
Delay 3
KeyDown "Ctrl", 1
Delay 18
Delay 2
KeyDown "Ctrl", 1
MoveTo 561, 586
Delay 11
KeyUp "Ctrl", 1
MoveTo 676, 361
Delay 2521
KeyDown "Shift", 1
Delay 304
LeftDoubleClick 1
Delay 40
KeyDown "Shift", 1
Delay 35
Delay 38
LeftUp 1
Delay 5
KeyDown "Shift", 1
Delay 33
MoveTo 682, 367
Delay 35
KeyDown "Shift", 1
MoveTo 689, 389
Delay 3
KeyDown "Shift", 1
MoveTo 693, 402
Delay 39
KeyDown "Shift", 1
MoveTo 693, 407
Delay 37
KeyDown "Shift", 1
MoveTo 693, 410
Delay 34
KeyDown "Shift", 1
MoveTo 694, 413
Delay 37
KeyDown "Shift", 1
MoveTo 695, 414
Delay 34
KeyDown "Shift", 1
MoveTo 696, 416
Delay 34
KeyDown "Shift", 1
MoveTo 697, 417
Delay 35
KeyDown "Shift", 1
Delay 33
Delay 37
KeyDown "Shift", 1
Delay 1
LeftDown 1
Delay 45
KeyDown "Shift", 1
Delay 38
LeftUp 1
Delay 4
KeyDown "Shift", 1
Delay 38
Delay 33
KeyDown "Shift", 1
Delay 2
Delay 37
KeyDown "Shift", 1
Delay 40
Delay 3
KeyDown "Shift", 1
Delay 39
LeftUp 1
Delay 3
KeyDown "Shift", 1
Delay 32
MoveTo 700, 423
Delay 46
KeyUp "Shift", 1
'==========以上是按键精灵录制的内容==========
